from .dsl import code, course, fill, lesson, mcq, order, run, t, unit
from .c_adv import ADVANCED, INTERMEDIATE
from .c_expert import EXPERT
from .c_expert2 import EXPERT2
from .c_start import START

STARTER = "#include <stdio.h>\n\nint main(void) {\n    \n    return 0;\n}\n"


def prog(body: str, includes: str = "#include <stdio.h>\n", before: str = "") -> str:
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"{includes}\n{before}int main(void) {{\n{inner}\n    return 0;\n}}\n"


COURSE = course(
    "c", "C", "🔧", "The classic systems language behind operating systems and embedded devices.",
    START,
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · First programs",
        lesson(
            "Hello, C",
            "Every C program starts in main. #include <stdio.h> gives you printf:\n\n#include <stdio.h>\n\nint main(void) {\n    printf(\"Hello!\\n\");\n    return 0;\n}\n\n\\n moves to a new line - printf doesn't add one for you.",
            fill("Print formatted text in C.", '___("Hello\\n");', "printf"),
            mcq("Which header declares printf?", ["<stdio.h>", "<iostream>", "<stdlib.h>", "<string.h>"], 0),
            mcq("What does \\n do?", ["Starts a new line", "Prints n", "Ends the program", "Prints a tab"], 0),
            order("Order a minimal C program.", ["#include <stdio.h>", "int main(void) {", '    printf("Hi\\n");', "    return 0;", "}"]),
            run("Print exactly: Hello, C!", "c", [t("Run")], ["Hello, C!"], prog('printf("Hello, C!\\n");'), starter=STARTER,
                fallback=[r'printf\(\s*"Hello, C!(\\n)?"\s*\)']),
        ),
        lesson(
            "Escapes & comments",
            "Escape sequences inside strings:\n\n\\n  new line     \\t  tab\n\\\"  double quote  \\\\  backslash\n%%  a percent sign (inside printf)\n\nComments: // one line   /* several\n                          lines */",
            mcq("How do you print a literal % with printf?", ["%%", "\\%", "%", "'%'"], 0),
            fill("Insert a tab between the words.", 'printf("Name___Age\\n");', "\\t"),
            mcq("Which is a valid C comment?", ["/* note */", "# note", "<!-- note -->", "-- note"], 0),
            mcq("What is printed?", ['Say "hi"', "Say hi", 'Say \\"hi\\"', "An error"], 0, code='printf("Say \\"hi\\"\\n");'),
            run("Print this exact line: 100% of \"C\" coders use \\n", "c", [t("Run")], ['100% of "C" coders use \\n'],
                prog('printf("100%% of \\"C\\" coders use \\\\n\\n");'), starter=STARTER, fallback=[r"%%", r'\\"C\\"', r"\\\\n"]),
        ),
        lesson(
            "Arithmetic",
            "C does integer maths unless a value is floating-point:\n\n7 / 2     // 3\n7.0 / 2   // 3.5\n7 % 2     // 1\n\nprintf placeholders: %d for int, %f for double (%.2f = 2 decimals).\n\nprintf(\"%d %.1f\\n\", 7 / 2, 7.0 / 2);   // 3 3.5",
            mcq("What is 9 / 4 with ints?", ["2", "2.25", "3", "2.0"], 0),
            mcq("What does printf(\"%.2f\", 3.14159) print?", ["3.14", "3.1", "3.14159", "3"], 0),
            fill("Print an int with printf.", 'printf("___\\n", total);', "%d"),
            mcq("What is 17 % 5?", ["2", "3", "3.4", "5"], 0),
            run("Convert 98.6 °F to Celsius with (F - 32) * 5 / 9 and print it with 1 decimal place.", "c", [t("Run")], ["37.0"],
                prog("double f = 98.6;\ndouble c = (f - 32) * 5 / 9;\nprintf(\"%.1f\\n\", c);"), starter=STARTER, require=[r"%\.1f"],
                forbid=[r"37\.0"], fallback=[r"-\s*32", r"\*\s*5\s*/\s*9|/\s*9\.?0?\s*\*\s*5", r"%\.1f"]),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Variables & types",
        lesson(
            "Types",
            "C variables have fixed types:\n\nint count = 3;        // whole number\ndouble price = 9.99;  // decimal\nchar letter = 'A';    // one character\nlong big = 3000000000L;\n\nC has no built-in bool in old code; include <stdbool.h> for bool, true, false.",
            mcq("Which type holds decimals?", ["double", "int", "char", "long"], 0),
            fill("Declare a character variable.", "___ grade = 'B';", "char"),
            mcq("Which header gives you bool, true and false?", ["<stdbool.h>", "<bool.h>", "<stdlib.h>", "Built in"], 0),
            mcq("What does printf(\"%c\", 'A' + 1) print?", ["B", "A1", "66", "An error"], 0, "chars are small numbers: 'A' + 1 is 'B'."),
            run("Declare int width = 7 and int height = 3. Print: Area: 21, Perimeter: 20 (calculated).", "c", [t("Run")], ["Area: 21, Perimeter: 20"],
                prog('int width = 7;\nint height = 3;\nprintf("Area: %d, Perimeter: %d\\n", width * height, 2 * (width + height));'),
                starter=STARTER, require=[r"int\s+width\s*=\s*7"], forbid=[r"Area: 21"], fallback=[r"width\s*\*\s*height", r"%d"]),
        ),
        lesson(
            "Format specifiers",
            "printf placeholders:\n\n%d   int          %ld  long\n%f   double       %.2f with 2 decimals\n%c   char         %s   string\n%5d  width 5 (right-aligned)\n%-5d left-aligned\n\nprintf(\"%-6s|%4d\\n\", \"Ada\", 36);   // \"Ada   |  36\"",
            mcq("Which specifier prints a string?", ["%s", "%d", "%c", "%f"], 0),
            fill("Print a single character.", 'printf("___", letter);', "%c"),
            mcq("What does printf(\"%03d\", 7) print?", ["007", "7", "  7", "700"], 0, "0 pads with zeros to width 3."),
            mcq("What does printf(\"%d\", 3.7) do?", ["Undefined behaviour - wrong specifier", "Prints 3", "Prints 4", "Prints 3.7"], 0),
            run("Print a small table: two rows, name left-aligned in 6 characters, then a | and the score right-aligned in 3.\nAda   | 95\nBo    |  7", "c",
                [t("Run")], ["Ada   | 95\nBo    |  7"], prog('printf("%-6s|%3d\\n", "Ada", 95);\nprintf("%-6s|%3d\\n", "Bo", 7);'), starter=STARTER,
                require=[r"%-6s"], fallback=[r"%-6s", r"%3d"]),
        ),
        lesson(
            "Constants & casting",
            "#define or const make constants:\n\n#define MAX_USERS 100\nconst double PI = 3.14159;\n\nCast to change a value's type:\n\nint a = 7, b = 2;\ndouble avg = (double) a / b;   // 3.5\nint whole = (int) 9.9;         // 9",
            mcq("What is (int) 9.9?", ["9", "10", "9.9", "An error"], 0),
            mcq("What is (double) 7 / 2?", ["3.5", "3", "4", "3.0"], 0),
            fill("Define a constant called SIZE.", "___ SIZE 10", "#define"),
            mcq("Is there a semicolon at the end of a #define line?", ["No", "Yes", "Only for numbers", "Optional and required for strings"], 0),
            run("Read two ints (a and b) and print a / b as a decimal with 2 places.", "c",
                [t("7 2", stdin="7 2"), t("1 3", stdin="1 3"), t("10 4", stdin="10 4")], ["3.50", "0.33", "2.50"],
                prog('int a, b;\nscanf("%d %d", &a, &b);\nprintf("%.2f\\n", (double) a / b);'), starter=STARTER,
                require=[r"\(double\)|1\.0\s*\*|\*\s*1\.0"], fallback=[r"scanf\(", r"\(double\)|1\.0\s*\*", r"%\.2f"]),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Input & decisions",
        lesson(
            "Reading input with scanf",
            "scanf reads formatted input. Pass the ADDRESS of each variable with &:\n\nint age;\nscanf(\"%d\", &age);\n\ndouble price;\nscanf(\"%lf\", &price);   // %lf for double in scanf\n\nchar name[50];\nscanf(\"%49s\", name);     // arrays don't need &",
            fill("Read an int into n.", 'scanf("%d", ___n);', "&"),
            mcq("Which specifier reads a double with scanf?", ["%lf", "%f", "%d", "%ld"], 0, "printf uses %f for double, but scanf needs %lf."),
            mcq("Why does scanf need &x?", ["It must know where x is stored to write into it", "It's a typo", "To print x", "To make x a pointer type"], 0),
            order("Order the program that doubles a number.", ["int n;", 'scanf("%d", &n);', 'printf("%d\\n", n * 2);']),
            run("Read two ints and print their sum, difference and product, each on its own line.", "c",
                [t("7 3", stdin="7 3"), t("-2 5", stdin="-2 5")], ["10\n4\n21", "3\n-7\n-10"],
                prog('int a, b;\nscanf("%d %d", &a, &b);\nprintf("%d\\n%d\\n%d\\n", a + b, a - b, a * b);'), starter=STARTER,
                fallback=[r"scanf\(\s*\"%d\s*%d\"\s*,\s*&\w+\s*,\s*&\w+\s*\)", r"\+", r"\*"]),
        ),
        lesson(
            "if / else",
            "if (condition) { ... } else if (...) { ... } else { ... }\n\nIn C, 0 means false and any other number means true.\n\nif (n % 2 == 0) {\n    printf(\"even\\n\");\n} else {\n    printf(\"odd\\n\");\n}\n\nLogical operators: && || !",
            mcq("In C, which value counts as false?", ["0", "1", "-1", "Any negative"], 0),
            mcq("What is printed?", ["yes", "no", "yesno", "nothing"], 0, "5 is non-zero, so it's true.", code='if (5) printf("yes");\nelse printf("no");'),
            fill("Check that n is between 1 and 10.", "if (n >= 1 ___ n <= 10)", "&&"),
            mcq("What's the bug?", ["= assigns instead of comparing (use ==)", "Missing semicolon", "Nothing", "Wrong type"], 0, code="if (x = 5) { ... }"),
            run("Read a score (0-100) and print its grade: A (90+), B (80+), C (70+), D (60+) or F.", "c",
                [t("95", stdin="95"), t("80", stdin="80"), t("61", stdin="61"), t("12", stdin="12")], ["A", "B", "D", "F"],
                prog('int s;\nscanf("%d", &s);\nif (s >= 90) printf("A\\n");\nelse if (s >= 80) printf("B\\n");\nelse if (s >= 70) printf("C\\n");\nelse if (s >= 60) printf("D\\n");\nelse printf("F\\n");'),
                starter=STARTER, require=[r"\bif\s*\("], fallback=[r"\bif\s*\(", r"else\s+if", r">=\s*90"]),
        ),
        lesson(
            "switch",
            "switch jumps to a matching case. Don't forget break!\n\nswitch (choice) {\n    case 1:\n        printf(\"Start\\n\");\n        break;\n    case 2:\n        printf(\"Stop\\n\");\n        break;\n    default:\n        printf(\"Unknown\\n\");\n}",
            mcq("What happens if you leave out break?", ["Execution falls through into the next case", "Compile error", "The program ends", "Nothing"], 0),
            fill("The branch for anything else.", "___:\n    printf(\"?\\n\");", "default"),
            mcq("Can a C switch use strings as cases?", ["No - only integer values (ints, chars, enums)", "Yes", "Only with strcmp", "Only in C11"], 0),
            mcq("What is printed for x = 1?", ["AB", "A", "B", "Nothing"], 0, "No break after case 1, so it falls through.",
                code="switch (x) {\n    case 1: printf(\"A\");\n    case 2: printf(\"B\"); break;\n}"),
            run("Read a char (+ - * /) between two ints like 6 * 7 and print the result using a switch (integer maths). For division by zero print Error.", "c",
                [t("6 * 7", stdin="6 * 7"), t("9 - 12", stdin="9 - 12"), t("9 / 2", stdin="9 / 2"), t("1 / 0", stdin="1 / 0")], ["42", "-3", "4", "Error"],
                prog('int a, b;\nchar op;\nscanf("%d %c %d", &a, &op, &b);\nswitch (op) {\n    case \'+\': printf("%d\\n", a + b); break;\n    case \'-\': printf("%d\\n", a - b); break;\n    case \'*\': printf("%d\\n", a * b); break;\n    case \'/\':\n        if (b == 0) printf("Error\\n");\n        else printf("%d\\n", a / b);\n        break;\n}'),
                starter=STARTER, require=[r"\bswitch\b"], fallback=[r"\bswitch\s*\(", r"case\s*'\+'", r"%c"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Loops",
        lesson(
            "while & do-while",
            "while (condition) { ... } checks first. do { ... } while (condition); runs at least once.\n\nint n = 3;\nwhile (n > 0) {\n    printf(\"%d \", n);\n    n--;\n}   // 3 2 1",
            mcq("How many times does a do-while body run at least?", ["1", "0", "2", "Depends"], 0),
            fill("Subtract one from n.", "n___;", "--"),
            mcq("What is printed?", ["0 1 2", "1 2 3", "0 1 2 3", "Nothing"], 0, code='int i = 0;\nwhile (i < 3) {\n    printf("%d ", i);\n    i++;\n}'),
            order("Order the do-while.", ["int x = 0;", "do {", "    x++;", "} while (x < 5);"]),
            run("Read a positive int and print its digits in reverse (e.g. 1234 → 4321) using % 10 and / 10.", "c",
                [t("1234", stdin="1234"), t("7", stdin="7"), t("1200", stdin="1200")], ["4321", "7", "0021"],
                prog('int n;\nscanf("%d", &n);\ndo {\n    printf("%d", n % 10);\n    n /= 10;\n} while (n > 0);\nprintf("\\n");'),
                starter=STARTER, require=[r"%\s*10"], fallback=[r"\bwhile\s*\(", r"%\s*10", r"/=?\s*10"]),
        ),
        lesson(
            "for loops",
            "for (int i = 0; i < n; i++) { ... }\n\n- start:     int i = 0\n- condition: i < n\n- step:      i++\n\nfor (int i = 10; i > 0; i -= 2) counts 10, 8, 6, 4, 2.",
            mcq("What is printed?", ["10 8 6 4 2", "10 9 8", "2 4 6 8 10", "10 8 6 4 2 0"], 0, code='for (int i = 10; i > 0; i -= 2) printf("%d ", i);'),
            fill("Loop from 1 to 100 inclusive.", "for (int i = 1; i ___ 100; i++)", "<="),
            mcq("How many times does the body run?", ["3", "4", "2", "0"], 0, code="for (int i = 0; i < 6; i += 2) { }"),
            code("Write the for loop header counting i from 0 to 4.", [r"for\s*\(\s*int\s+i\s*=\s*0\s*;\s*i\s*(<\s*5|<=\s*4)\s*;\s*(i\+\+|\+\+i|i\s*\+=\s*1)\s*\)"], "for (int i = 0; i < 5; i++)"),
            run("Read n and print the first n Fibonacci numbers (0 1 1 2 3 …) separated by spaces.", "c",
                [t("7", stdin="7"), t("1", stdin="1"), t("10", stdin="10")], ["0 1 1 2 3 5 8", "0", "0 1 1 2 3 5 8 13 21 34"],
                prog('int n;\nscanf("%d", &n);\nlong a = 0, b = 1;\nfor (int i = 0; i < n; i++) {\n    printf(i ? " %ld" : "%ld", a);\n    long next = a + b;\n    a = b;\n    b = next;\n}\nprintf("\\n");'),
                starter=STARTER, require=[r"\bfor\b|\bwhile\b"], fallback=[r"\bfor\s*\(|\bwhile\s*\(", r"\+"]),
        ),
        lesson(
            "break, continue & nesting",
            "break leaves the innermost loop; continue jumps to its next round.\n\nfor (int r = 1; r <= 3; r++) {\n    for (int c = 1; c <= 3; c++) {\n        printf(\"%d \", r * c);\n    }\n    printf(\"\\n\");\n}",
            mcq("What is printed?", ["1 2", "1 2 3", "3", "1 2 4"], 0, code='for (int i = 1; i < 5; i++) {\n    if (i == 3) break;\n    printf("%d ", i);\n}'),
            mcq("What is printed?", ["1 2 4", "1 2", "3", "1 2 3 4"], 0, code='for (int i = 1; i < 5; i++) {\n    if (i == 3) continue;\n    printf("%d ", i);\n}'),
            fill("Skip to the next iteration.", "if (x < 0) ___;", "continue"),
            mcq("How many lines does the multiplication grid above print?", ["3", "9", "1", "6"], 0),
            run("Read n and print an n × n multiplication table; each number right-aligned in width 4 (%4d).", "c",
                [t("3", stdin="3"), t("1", stdin="1")], ["   1   2   3\n   2   4   6\n   3   6   9", "   1"],
                prog('int n;\nscanf("%d", &n);\nfor (int r = 1; r <= n; r++) {\n    for (int c = 1; c <= n; c++) {\n        printf("%4d", r * c);\n    }\n    printf("\\n");\n}'),
                starter=STARTER, require=[r"%4d"], fallback=[r"for\s*\([\s\S]*for\s*\(", r"%4d"]),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Functions",
        lesson(
            "Defining functions",
            "Functions have a return type, name and parameters:\n\nint square(int n) {\n    return n * n;\n}\n\nint main(void) {\n    printf(\"%d\\n\", square(5));\n    return 0;\n}\n\nvoid means 'returns nothing'.",
            mcq("What does add(2, 3) return?", ["5", "23", "void", "An error"], 0, code="int add(int a, int b) {\n    return a + b;\n}"),
            fill("A function that returns nothing.", "___ hello(void) {\n    printf(\"hi\\n\");\n}", "void"),
            mcq("What does (void) in int main(void) mean?", ["It takes no parameters", "It returns nothing", "It's empty", "It's an error"], 0),
            mcq("What happens to a local variable when its function returns?", ["It's destroyed", "It keeps its value for next time", "It becomes global", "It's printed"], 0),
            run("Write int isPrime(int n) returning 1 if n is prime, else 0. main reads n and prints prime or not prime.", "c",
                [t("7", stdin="7"), t("1", stdin="1"), t("21", stdin="21"), t("2", stdin="2")], ["prime", "not prime", "not prime", "prime"],
                prog('int n;\nscanf("%d", &n);\nprintf(isPrime(n) ? "prime\\n" : "not prime\\n");',
                     before="int isPrime(int n) {\n    if (n < 2) return 0;\n    for (int d = 2; d * d <= n; d++) {\n        if (n % d == 0) return 0;\n    }\n    return 1;\n}\n\n"),
                starter=STARTER, require=[r"int\s+isPrime\s*\("], fallback=[r"int\s+isPrime\s*\(\s*int\s+\w+\s*\)", r"%", r"\breturn\b"]),
        ),
        lesson(
            "Prototypes & scope",
            "C reads top to bottom, so declare a function before use. A prototype does that:\n\nint cube(int n);   // prototype\n\nint main(void) { printf(\"%d\", cube(3)); }\n\nint cube(int n) { return n * n * n; }\n\nVariables inside a function are local. static inside a function keeps its value between calls.",
            mcq("What is a prototype?", ["A declaration of a function before its full definition", "A test function", "A macro", "A global variable"], 0),
            fill("Keep the counter's value between calls.", "___ int calls = 0;", "static"),
            mcq("What is printed by calling tick() three times?", ["1 2 3", "1 1 1", "0 1 2", "3 3 3"], 0,
                code='void tick(void) {\n    static int n = 0;\n    n++;\n    printf("%d ", n);\n}'),
            mcq("Where can a local variable be used?", ["Only inside its block/function", "Anywhere", "In other files", "Only in main"], 0),
            run("Write a prototype for double average(int a, int b) ABOVE main, define it BELOW main, and print average of two input ints with 1 decimal.", "c",
                [t("3 4", stdin="3 4"), t("10 11", stdin="10 11")], ["3.5", "10.5"],
                '#include <stdio.h>\n\ndouble average(int a, int b);\n\nint main(void) {\n    int a, b;\n    scanf("%d %d", &a, &b);\n    printf("%.1f\\n", average(a, b));\n    return 0;\n}\n\ndouble average(int a, int b) {\n    return (a + b) / 2.0;\n}\n',
                starter=STARTER, require=[r"double\s+average\s*\([^)]*\)\s*;"], fallback=[r"double\s+average\s*\([^)]*\)\s*;", r"2\.0|\(double\)"]),
        ),
        lesson(
            "Recursion",
            "A recursive function calls itself on a smaller problem, with a base case to stop:\n\nint factorial(int n) {\n    if (n <= 1) return 1;          // base case\n    return n * factorial(n - 1);   // recursive case\n}\n\nfactorial(4) = 4 * 3 * 2 * 1 = 24.",
            mcq("What stops a recursive function from running forever?", ["A base case", "A loop", "break", "return type"], 0),
            mcq("What is sum(3)?", ["6", "3", "0", "Infinite"], 0, code="int sum(int n) {\n    if (n == 0) return 0;\n    return n + sum(n - 1);\n}"),
            fill("The recursive call.", "return n * factorial(n ___ 1);", "-"),
            mcq("What happens without a base case?", ["Stack overflow (crash)", "Returns 0", "Compile error", "Nothing"], 0),
            run("Write a recursive int power(int base, int exp) (no loops). main reads base and exp and prints the result.", "c",
                [t("2 10", stdin="2 10"), t("5 0", stdin="5 0"), t("3 4", stdin="3 4")], ["1024", "1", "81"],
                prog('int b, e;\nscanf("%d %d", &b, &e);\nprintf("%d\\n", power(b, e));',
                     before="int power(int base, int exp) {\n    if (exp == 0) return 1;\n    return base * power(base, exp - 1);\n}\n\n"),
                starter=STARTER, require=[r"power\s*\([^)]*\)[\s\S]*power\s*\("], forbid=[r"\bfor\b|\bwhile\b|pow\("],
                fallback=[r"int\s+power\s*\(\s*int\s+\w+\s*,\s*int\s+\w+\s*\)[\s\S]*power\s*\("]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Arrays & strings",
        lesson(
            "Arrays",
            "An array is a fixed-size block of values:\n\nint nums[5] = {4, 8, 15, 16, 23};\nnums[0]   // 4\nnums[4]   // 23 - the last valid index is size - 1\n\nC does NOT check bounds - nums[5] is undefined behaviour. Loop with the size:\n\nfor (int i = 0; i < 5; i++) printf(\"%d \", nums[i]);",
            mcq("What is the last valid index of int a[10]?", ["9", "10", "11", "0"], 0),
            mcq("What does C do if you read a[10] from int a[10]?", ["Undefined behaviour - no error is guaranteed", "Throws an exception", "Returns 0", "Won't compile"], 0),
            fill("Number of elements in a (a common trick).", "int n = sizeof(a) / ___(a[0]);", "sizeof"),
            mcq("What is in int z[3] = {0};?", ["0 0 0", "0 and garbage", "Garbage", "An error"], 0, "Missing initialisers are zeroed."),
            run("Read n (≤ 100), then n ints. Print the minimum, the maximum and the sum on one line separated by spaces.", "c",
                [t("5 numbers", stdin="5\n3 9 -2 7 4"), t("one", stdin="1\n42")], ["-2 9 21", "42 42 42"],
                prog('int n, a[100];\nscanf("%d", &n);\nfor (int i = 0; i < n; i++) scanf("%d", &a[i]);\nint mn = a[0], mx = a[0], sum = 0;\nfor (int i = 0; i < n; i++) {\n    if (a[i] < mn) mn = a[i];\n    if (a[i] > mx) mx = a[i];\n    sum += a[i];\n}\nprintf("%d %d %d\\n", mn, mx, sum);'),
                starter=STARTER, require=[r"\[\s*\d+\s*\]"], fallback=[r"\bint\b[^;]*\w+\s*\[\s*\d+\s*\]", r"\bfor\s*\("]),
        ),
        lesson(
            "Strings are char arrays",
            "A C string is an array of chars ending with '\\0' (the null terminator):\n\nchar name[] = \"Ada\";   // {'A', 'd', 'a', '\\0'} - 4 bytes\nprintf(\"%s\\n\", name);\nname[0] = 'E';           // \"Eda\"\n\nLoop until the terminator:\nfor (int i = 0; name[i] != '\\0'; i++) { ... }",
            mcq("How many bytes does char s[] = \"cat\"; use?", ["4", "3", "5", "8"], 0, "3 letters + the '\\0' terminator."),
            mcq("What marks the end of a C string?", ["'\\0'", "'\\n'", "EOF", "Nothing - the length is stored"], 0),
            fill("Print a string.", 'printf("___\\n", name);', "%s"),
            mcq("What is printed?", ["Hat", "Cat", "H", "An error"], 0, code='char s[] = "Cat";\ns[0] = \'H\';\nprintf("%s", s);'),
            run("Read a word (up to 99 chars) and print it with its letters swapped in case (a→A, A→a) using <ctype.h>.", "c",
                [t("Hello", stdin="Hello"), t("cODE", stdin="cODE")], ["hELLO", "Code"],
                prog('char w[100];\nscanf("%99s", w);\nfor (int i = 0; w[i] != \'\\0\'; i++) {\n    if (islower(w[i])) w[i] = toupper(w[i]);\n    else if (isupper(w[i])) w[i] = tolower(w[i]);\n}\nprintf("%s\\n", w);',
                     "#include <ctype.h>\n#include <stdio.h>\n"),
                starter=STARTER, require=[r"ctype\.h"], fallback=[r"toupper|tolower", r"\\0|strlen"]),
        ),
        lesson(
            "string.h",
            "#include <string.h> for string functions:\n\nstrlen(s)         // length (not counting '\\0')\nstrcpy(dst, src)  // copy (dst must be big enough!)\nstrcat(dst, src)  // append\nstrcmp(a, b)      // 0 if equal, <0 or >0 otherwise\n\nNever compare strings with == in C - that compares addresses.",
            mcq("What does strcmp(\"abc\", \"abc\") return?", ["0", "1", "true", "-1"], 0),
            mcq("What is strlen(\"hello\")?", ["5", "6", "4", "An error"], 0),
            fill("Append src to the end of dst.", "str___(dst, src);", "cat"),
            mcq("Why is if (a == b) wrong for comparing C strings?", ["It compares addresses, not text", "It's a syntax error", "It's too slow", "It always works"], 0),
            run("Read two words and print them in alphabetical order (smaller first) separated by a space, using strcmp.", "c",
                [t("pear apple", stdin="pear apple"), t("ant bee", stdin="ant bee"), t("same same", stdin="same same")], ["apple pear", "ant bee", "same same"],
                prog('char a[100], b[100];\nscanf("%99s %99s", a, b);\nif (strcmp(a, b) <= 0) printf("%s %s\\n", a, b);\nelse printf("%s %s\\n", b, a);', "#include <stdio.h>\n#include <string.h>\n"),
                starter=STARTER, require=[r"strcmp\("], fallback=[r"strcmp\(", r"string\.h"]),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Pointers",
        lesson(
            "Addresses & pointers",
            "Every variable lives at a memory address. A pointer stores an address:\n\nint x = 10;\nint *p = &x;     // p holds the address of x\nprintf(\"%d\\n\", *p);   // 10  (*p = the value at that address)\n*p = 25;          // x is now 25\n\nNULL means the pointer points nowhere.",
            mcq("What does & do in &x?", ["Gives the address of x", "Multiplies", "Logical and", "Dereferences"], 0),
            mcq("What is x afterwards?", ["25", "10", "An address", "An error"], 0, code="int x = 10;\nint *p = &x;\n*p = 25;"),
            fill("Declare a pointer to an int.", "int ___p;", "*"),
            mcq("What happens if you dereference NULL?", ["Undefined behaviour (usually a crash)", "Returns 0", "Prints NULL", "Compile error"], 0),
            run("Read two ints, store pointers to them, and print the sum by using only the pointers (*p + *q).", "c",
                [t("3 4", stdin="3 4"), t("-1 1", stdin="-1 1")], ["7", "0"],
                prog('int a, b;\nscanf("%d %d", &a, &b);\nint *p = &a;\nint *q = &b;\nprintf("%d\\n", *p + *q);'), starter=STARTER,
                require=[r"\*\s*\w+\s*=\s*&", r"\*\s*\w+\s*\+\s*\*\s*\w+"], fallback=[r"int\s*\*\s*\w+\s*=\s*&", r"\*\s*\w+\s*\+\s*\*\s*\w+"]),
        ),
        lesson(
            "Pointers & functions",
            "C passes arguments by value (copies). To let a function change the caller's variables, pass pointers:\n\nvoid swap(int *a, int *b) {\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\n\nswap(&x, &y);\n\nThat's exactly why scanf needs &.",
            mcq("Why does swap need pointers?", ["C copies arguments, so it must know where the originals are", "It doesn't", "Pointers are faster", "To return two values as a string"], 0),
            fill("Call swap on x and y.", "swap(___x, &y);", "&"),
            mcq("What is n afterwards?", ["5", "6", "An error", "0"], 0, "The function changed its own copy.", code="void inc(int v) { v++; }\nint n = 5;\ninc(n);"),
            mcq("What is n afterwards?", ["6", "5", "An error", "0"], 0, code="void inc(int *v) { (*v)++; }\nint n = 5;\ninc(&n);"),
            run("Write void minmax(int a, int b, int c, int *mn, int *mx) that stores the smallest and largest of three numbers through the pointers. main reads 3 ints and prints min and max.", "c",
                [t("4 1 9", stdin="4 1 9"), t("5 5 5", stdin="5 5 5"), t("-3 8 0", stdin="-3 8 0")], ["1 9", "5 5", "-3 8"],
                prog('int a, b, c, lo, hi;\nscanf("%d %d %d", &a, &b, &c);\nminmax(a, b, c, &lo, &hi);\nprintf("%d %d\\n", lo, hi);',
                     before="void minmax(int a, int b, int c, int *mn, int *mx) {\n    *mn = a;\n    *mx = a;\n    if (b < *mn) *mn = b;\n    if (c < *mn) *mn = c;\n    if (b > *mx) *mx = b;\n    if (c > *mx) *mx = c;\n}\n\n"),
                starter=STARTER, require=[r"int\s*\*\s*mn"], fallback=[r"void\s+minmax\s*\([^)]*int\s*\*\s*\w+[^)]*int\s*\*\s*\w+\s*\)", r"&\w+\s*,\s*&\w+"]),
        ),
        lesson(
            "Pointers & arrays",
            "An array's name acts like a pointer to its first element:\n\nint a[3] = {10, 20, 30};\nint *p = a;          // same as &a[0]\n*(p + 1)             // 20 - same as a[1]\n\nPassing an array to a function passes a pointer, so also pass the length:\n\nint sum(const int *a, int n);",
            mcq("What is *(a + 2) for int a[] = {10, 20, 30}?", ["30", "20", "12", "An address"], 0),
            mcq("When you pass an array to a function, what is actually passed?", ["A pointer to its first element", "A full copy", "Its length", "Nothing"], 0),
            fill("The same as a[1].", "*(a ___ 1)", "+"),
            mcq("Why pass the length along with an array?", ["The function can't find out the array's size from the pointer", "It's a style rule", "For speed", "It's not needed"], 0),
            run("Write void reverse(int *a, int n) that reverses an array in place using two pointers/indices. main reads n and n ints, reverses, and prints them.", "c",
                [t("5", stdin="5\n1 2 3 4 5"), t("2", stdin="2\n7 8")], ["5 4 3 2 1", "8 7"],
                prog('int n, a[100];\nscanf("%d", &n);\nfor (int i = 0; i < n; i++) scanf("%d", &a[i]);\nreverse(a, n);\nfor (int i = 0; i < n; i++) printf(i ? " %d" : "%d", a[i]);\nprintf("\\n");',
                     before="void reverse(int *a, int n) {\n    for (int i = 0, j = n - 1; i < j; i++, j--) {\n        int tmp = a[i];\n        a[i] = a[j];\n        a[j] = tmp;\n    }\n}\n\n"),
                starter=STARTER, require=[r"void\s+reverse\s*\(\s*int\s*\*"], fallback=[r"void\s+reverse\s*\(\s*int\s*\*\s*\w+\s*,\s*int\s+\w+\s*\)", r"reverse\(\s*a\s*,\s*n\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Structs & memory",
        lesson(
            "Structs",
            "A struct groups related values into one type:\n\nstruct Point {\n    int x;\n    int y;\n};\n\nstruct Point p = {3, 4};\nprintf(\"%d\\n\", p.x);   // 3\n\ntypedef gives a shorter name:\ntypedef struct { char name[20]; int age; } Person;\nPerson ada = {\"Ada\", 36};",
            mcq("How do you access field x of struct variable p?", ["p.x", "p->x", "p[x]", "x(p)"], 0),
            fill("Give the struct type a short name.", "___ struct { int w, h; } Size;", "typedef"),
            mcq("How do you access a field through a POINTER to a struct?", ["ptr->field", "ptr.field", "*ptr.field", "ptr[field]"], 0),
            mcq("What's easy to forget after a struct definition?", ["The semicolon", "return", "#include", "main"], 0),
            run("Define typedef struct { char name[32]; int score; } Player;. Read 3 players (name score) and print the name of the one with the highest score.", "c",
                [t("3 players", stdin="ada 90\nbo 95\ncy 80"), t("first wins", stdin="x 5\ny 4\nz 3")], ["bo", "x"],
                '#include <stdio.h>\n\ntypedef struct {\n    char name[32];\n    int score;\n} Player;\n\nint main(void) {\n    Player p[3];\n    for (int i = 0; i < 3; i++) scanf("%31s %d", p[i].name, &p[i].score);\n    int best = 0;\n    for (int i = 1; i < 3; i++) {\n        if (p[i].score > p[best].score) best = i;\n    }\n    printf("%s\\n", p[best].name);\n    return 0;\n}\n',
                starter=STARTER, require=[r"typedef\s+struct"], fallback=[r"typedef\s+struct", r"\.score", r"Player"]),
        ),
        lesson(
            "malloc & free",
            "Stack arrays have a fixed size. For a size known only at run time, allocate on the heap:\n\n#include <stdlib.h>\nint *a = malloc(n * sizeof(int));\nif (a == NULL) { /* out of memory */ }\n...\nfree(a);   // always give it back!\n\nForgetting free leaks memory; using memory after free is a serious bug.",
            mcq("Which header declares malloc and free?", ["<stdlib.h>", "<stdio.h>", "<memory.h>", "<string.h>"], 0),
            fill("Release the memory.", "___(a);", "free"),
            mcq("What does malloc return when it fails?", ["NULL", "0 bytes", "-1", "It throws"], 0),
            mcq("What is a memory leak?", ["Allocated memory that's never freed", "Reading past an array", "A NULL pointer", "Using too many variables"], 0),
            run("Read n, allocate an int array of n elements with malloc, read n ints into it, print them doubled, then free it.", "c",
                [t("3", stdin="3\n1 2 3"), t("1", stdin="1\n-5")], ["2 4 6", "-10"],
                prog('int n;\nscanf("%d", &n);\nint *a = malloc(n * sizeof(int));\nif (a == NULL) return 1;\nfor (int i = 0; i < n; i++) scanf("%d", &a[i]);\nfor (int i = 0; i < n; i++) printf(i ? " %d" : "%d", a[i] * 2);\nprintf("\\n");\nfree(a);',
                     "#include <stdio.h>\n#include <stdlib.h>\n"),
                starter=STARTER, require=[r"malloc\(", r"free\("], fallback=[r"malloc\(", r"sizeof", r"free\("]),
        ),
        lesson(
            "Putting it together",
            "Real C programs combine structs, arrays, pointers and functions:\n\ntypedef struct { char item[32]; double price; int qty; } Line;\n\ndouble total(const Line *lines, int n) {\n    double t = 0;\n    for (int i = 0; i < n; i++) t += lines[i].price * lines[i].qty;\n    return t;\n}\n\nconst promises the function won't modify the data.",
            mcq("What does const in const Line *lines promise?", ["The function won't modify the lines", "lines never changes address", "Nothing", "The lines are global"], 0),
            fill("Access a field of the i-th struct in an array.", "lines[i]___price", "."),
            mcq("With Line *p = &lines[0];, how do you read the price?", ["p->price", "p.price", "*p.price", "p[price]"], 0),
            order("Order the function.", ["double total(const Line *lines, int n) {", "    double t = 0;", "    for (int i = 0; i < n; i++) t += lines[i].price * lines[i].qty;", "    return t;", "}"]),
            run("Read n, then n lines of: item price qty. Print the total bill with 2 decimals, e.g. Total: 12.50 (use a struct array and a total() function).", "c",
                [t("receipt", stdin="3\ntea 2.50 2\ncake 3.25 1\nmilk 1.00 3"), t("single", stdin="1\npen 0.99 10")], ["Total: 11.25", "Total: 9.90"],
                '#include <stdio.h>\n\ntypedef struct {\n    char item[32];\n    double price;\n    int qty;\n} Line;\n\ndouble total(const Line *lines, int n) {\n    double t = 0;\n    for (int i = 0; i < n; i++) t += lines[i].price * lines[i].qty;\n    return t;\n}\n\nint main(void) {\n    int n;\n    Line lines[50];\n    scanf("%d", &n);\n    for (int i = 0; i < n; i++) scanf("%31s %lf %d", lines[i].item, &lines[i].price, &lines[i].qty);\n    printf("Total: %.2f\\n", total(lines, n));\n    return 0;\n}\n',
                starter=STARTER, require=[r"struct", r"total\s*\("], fallback=[r"typedef\s+struct|struct\s+\w+\s*\{", r"double\s+total\s*\(", r"%lf"]),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
    EXPERT,
    EXPERT2,
)
