"""C - Intermediate and Advanced sections (units 9-16). Runnable code targets C11."""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit

STARTER = "#include <stdio.h>\n\nint main(void) {\n    \n    return 0;\n}\n"


def prog(body: str, includes: str = "#include <stdio.h>\n", before: str = "") -> str:
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"{includes}\n{before}int main(void) {{\n{inner}\n    return 0;\n}}\n"


INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · Safer strings",
        lesson(
            "fgets & bounded copies",
            "Never use gets() - it can't know your buffer size. Read lines with fgets:\n\nchar line[100];\nif (fgets(line, sizeof line, stdin)) {\n    line[strcspn(line, \"\\n\")] = '\\0';   // strip the newline\n}\n\nFor copies use snprintf(dst, sizeof dst, \"%s\", src) - it never writes past the buffer and always terminates the string. strcpy/strcat have no bounds and cause buffer overflows.",
            mcq("Why is gets() banned?", ["It can't limit input to the buffer size", "It's slow", "It needs a file", "It strips spaces"], 0),
            mcq("What does fgets keep at the end of the line?", ["The newline character (if it fits)", "Nothing", "A space", "EOF"], 0),
            fill("Find the newline position to strip it.", "line[___(line, \"\\n\")] = '\\0';", "strcspn"),
            mcq("Which copy is bounded and always NUL-terminates?", ["snprintf", "strcpy", "strcat", "gets"], 0),
            run("Read a full line with fgets (buffer of 64), strip the newline, and print it surrounded by brackets plus its length, e.g. [hello world] 11.", "c",
                [t("spaces", stdin="hello world"), t("empty", stdin="")], ["[hello world] 11", "[] 0"],
                prog("char line[64] = \"\";\nif (!fgets(line, sizeof line, stdin)) line[0] = '\\0';\nline[strcspn(line, \"\\n\")] = '\\0';\nprintf(\"[%s] %zu\\n\", line, strlen(line));",
                     includes="#include <stdio.h>\n#include <string.h>\n"),
                starter=STARTER, require=[r"fgets"], forbid=[r"\bgets\s*\("], fallback=[r"fgets\s*\(", r"strcspn|strchr|strlen"]),
        ),
        lesson(
            "Parsing with sscanf & strtol",
            "sscanf parses from a string and returns how many fields matched:\n\nint d, m, y;\nif (sscanf(\"02/10/2026\", \"%d/%d/%d\", &d, &m, &y) == 3) { ... }\n\nstrtol is stricter - it reports where parsing stopped:\nchar *end;\nlong v = strtol(s, &end, 10);\nif (end == s || *end != '\\0') { /* not a whole number */ }\n\natoi gives no error reporting at all.",
            mcq("What does sscanf return?", ["The number of fields successfully parsed", "The parsed value", "0 on success", "A pointer"], 0),
            mcq("Why prefer strtol over atoi?", ["It can report invalid input", "It's shorter", "It returns int", "No reason"], 0),
            fill("Parse a base-10 number and get the end pointer.", "long v = strtol(s, &end, ___);", "10"),
            mcq("strtol(\"42abc\", &end, 10) leaves end pointing at…", ["\"abc\"", "\"42abc\"", "NULL", "The end of the string"], 0),
            run("Read tokens (max 31 chars each) until end of input. Using strtol, print the sum of the tokens that are whole integers and the number of invalid tokens as sum=… invalid=…", "c",
                [t("mixed", stdin="10 abc 5 7x -3"), t("all ok", stdin="1 2 3")], ["sum=12 invalid=2", "sum=6 invalid=0"],
                prog("char tok[32];\nlong sum = 0;\nint invalid = 0;\nwhile (scanf(\"%31s\", tok) == 1) {\n    char *end;\n    long v = strtol(tok, &end, 10);\n    if (end == tok || *end != '\\0') invalid++;\n    else sum += v;\n}\nprintf(\"sum=%ld invalid=%d\\n\", sum, invalid);",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n"),
                starter=STARTER, require=[r"strtol"], fallback=[r"strtol\s*\(", r"\*\s*end"]),
        ),
        lesson(
            "Tokenizing & character tests",
            "strtok splits a string in place (it modifies it and isn't reentrant):\n\nchar s[] = \"a,b,,c\";\nfor (char *p = strtok(s, \",\"); p; p = strtok(NULL, \",\")) puts(p);   // a b c\n\n<ctype.h>: isalpha, isdigit, isspace, toupper, tolower - pass (unsigned char)c to be safe.",
            mcq("What do you pass as the first argument on later strtok calls?", ["NULL", "The same string", "The delimiter", "0"], 0),
            mcq("Does strtok modify its input?", ["Yes - it writes '\\0' over delimiters", "No", "Only with const", "Only the first time"], 0),
            fill("Convert c to upper case.", "c = ___((unsigned char)c);", "toupper"),
            mcq("Why cast to unsigned char before isalpha?", ["Negative char values are undefined behaviour", "Speed", "It's required by printf", "No reason"], 0),
            run("Read a line (up to 200 chars) and print it in Title Case: the first letter of each space-separated word upper-cased, the rest lower-cased, words joined by single spaces (use strtok).", "c",
                [t("mixed", stdin="hELLO   big WORLD"), t("one", stdin="c")], ["Hello Big World", "C"],
                prog("char line[201] = \"\";\nif (!fgets(line, sizeof line, stdin)) return 0;\nline[strcspn(line, \"\\n\")] = '\\0';\nint first = 1;\nfor (char *w = strtok(line, \" \"); w; w = strtok(NULL, \" \")) {\n    for (int i = 0; w[i]; i++) w[i] = (char)(i == 0 ? toupper((unsigned char)w[i]) : tolower((unsigned char)w[i]));\n    printf(first ? \"%s\" : \" %s\", w);\n    first = 0;\n}\nputchar('\\n');",
                     includes="#include <ctype.h>\n#include <stdio.h>\n#include <string.h>\n"),
                starter=STARTER, require=[r"strtok"], fallback=[r"strtok\s*\(", r"toupper"]),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · Pointers in depth",
        lesson(
            "Pointer arithmetic",
            "Adding to a pointer moves it by whole ELEMENTS, not bytes:\n\nint a[] = {10, 20, 30};\nint *p = a;          // same as &a[0]\n*(p + 2)             // 30 - same as a[2] and p[2]\np++;                 // now points at a[1]\nptrdiff_t n = &a[2] - p;   // 1\n\nOnly move within an array (or one past its end).",
            mcq("If int *p = a; what is *(p + 1)?", ["a[1]", "a[0] + 1", "The address + 1 byte", "Undefined"], 0),
            mcq("How far does p + 1 move for an int pointer?", ["sizeof(int) bytes", "1 byte", "8 bytes always", "It depends on the value"], 0),
            fill("a[i] is the same as…", "*(a ___ i)", "+"),
            mcq("Is reading a[5] in a 3-element array safe?", ["No - it's undefined behaviour", "Yes, it's 0", "Yes, it wraps", "Only for chars"], 0),
            run("Write int sum_range(const int *begin, const int *end) that sums using only pointer arithmetic (no [] indexing in that function). main reads n numbers and prints the sum of all and of the middle part skipping the first and last.", "c",
                [t("5", stdin="5\n1 2 3 4 5"), t("2", stdin="2\n4 6")], ["15 9", "10 0"],
                prog("int n, a[100];\nscanf(\"%d\", &n);\nfor (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\nprintf(\"%d %d\\n\", sum_range(a, a + n), sum_range(a + 1, a + n - 1));",
                     before="int sum_range(const int *begin, const int *end) {\n    int s = 0;\n    for (const int *p = begin; p < end; p++) s += *p;\n    return s;\n}\n\n"),
                starter=STARTER, require=[r"sum_range"], fallback=[r"int\s+sum_range\s*\(\s*const\s+int\s*\*", r"\*\s*\w+\s*\+\+|\w+\+\+"]),
        ),
        lesson(
            "Pointers to pointers",
            "A pointer to a pointer lets a function change the CALLER's pointer:\n\nvoid make_buffer(char **out, size_t n) {\n    *out = malloc(n);\n}\nchar *buf = NULL;\nmake_buffer(&buf, 64);\n\nchar *argv[] is an array of strings - main(int argc, char **argv). Arrays of strings: const char *names[] = {\"ada\", \"bo\"};",
            mcq("Why pass char ** to make_buffer?", ["So it can set the caller's pointer", "To copy the string", "It's faster", "To free it"], 0),
            mcq("What is the type of argv?", ["char ** (array of strings)", "char *", "int *", "string[]"], 0),
            fill("Set the caller's pointer through out.", "___out = malloc(n);", "*"),
            mcq("What does names[1][0] give for {\"ada\", \"bo\"}?", ["'b'", "'a'", "\"bo\"", "'o'"], 0),
            run("Write void swap_str(const char **a, const char **b) swapping two string pointers. main reads two words into buffers, points p and q at them, swaps, and prints p then q.", "c",
                [t("words", stdin="left right")], ["right left"],
                prog("char x[32], y[32];\nscanf(\"%31s %31s\", x, y);\nconst char *p = x, *q = y;\nswap_str(&p, &q);\nprintf(\"%s %s\\n\", p, q);",
                     before="void swap_str(const char **a, const char **b) {\n    const char *t = *a;\n    *a = *b;\n    *b = t;\n}\n\n"),
                starter=STARTER, require=[r"\*\s*\*"], fallback=[r"char\s*\*\s*\*\s*a", r"swap_str\s*\(\s*&"]),
        ),
        lesson(
            "Function pointers",
            "Functions have addresses too - pass behaviour as data:\n\nint add(int a, int b) { return a + b; }\nint (*op)(int, int) = add;\nop(2, 3);   // 5\n\nA typedef makes them readable:\ntypedef int (*BinOp)(int, int);\nBinOp table[] = {add, sub, mul};\n\nqsort's comparator is a function pointer.",
            mcq("How do you declare a pointer to a function taking two ints and returning int?", ["int (*f)(int, int);", "int *f(int, int);", "int f*(int, int);", "func<int> f;"], 0),
            fill("Name the function-pointer type.", "___ int (*BinOp)(int, int);", "typedef"),
            mcq("Why the parentheses in int (*f)(int)?", ["Without them it declares a function returning int*", "Style", "For speed", "They're optional"], 0),
            mcq("Where does the C standard library use function pointers?", ["qsort and bsearch comparators", "printf", "malloc", "strlen"], 0),
            run("Build a calculator with an array of function pointers indexed by operator (+ - * /). Read lines 'a op b' until end of input and print each result (integer division; print 'div by zero' for / 0).", "c",
                [t("ops", stdin="6 + 2\n6 - 2\n6 * 2\n7 / 2\n1 / 0")], ["8\n4\n12\n3\ndiv by zero"],
                prog("int a, b;\nchar op;\nwhile (scanf(\"%d %c %d\", &a, &op, &b) == 3) {\n    BinOp f = NULL;\n    for (int i = 0; i < 4; i++) if (SYMBOLS[i] == op) f = OPS[i];\n    if (!f) continue;\n    if (op == '/' && b == 0) puts(\"div by zero\");\n    else printf(\"%d\\n\", f(a, b));\n}",
                     before="typedef int (*BinOp)(int, int);\n\nstatic int add(int a, int b) { return a + b; }\nstatic int sub(int a, int b) { return a - b; }\nstatic int mul(int a, int b) { return a * b; }\nstatic int dvd(int a, int b) { return a / b; }\n\nstatic const char SYMBOLS[] = \"+-*/\";\nstatic const BinOp OPS[] = {add, sub, mul, dvd};\n\n"),
                starter=STARTER, require=[r"\(\s*\*\s*\w+\s*\)\s*\("], fallback=[r"\(\s*\*\s*\w+\s*\)\s*\(\s*int\s*,\s*int\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Dynamic memory in depth",
        lesson(
            "calloc & realloc",
            "calloc(n, size) allocates zeroed memory. realloc grows (or shrinks) a block - possibly moving it:\n\nint *tmp = realloc(arr, new_cap * sizeof *arr);\nif (!tmp) { free(arr); return 1; }   // keep the old pointer on failure!\narr = tmp;\n\nA growable array doubles its capacity when full, giving amortized O(1) appends.",
            mcq("Why assign realloc's result to a temporary first?", ["On failure it returns NULL and the old block would leak", "Style", "It's faster", "It frees the old block"], 0),
            mcq("How does calloc differ from malloc?", ["It zeroes the memory", "It's on the stack", "It never fails", "It frees automatically"], 0),
            fill("Size of the element the pointer points to, robust to type changes.", "malloc(n * sizeof ___arr);", "*"),
            mcq("Why double the capacity instead of +1?", ["Appends become amortized O(1)", "Less memory", "It's required", "Alignment"], 0),
            run("Read integers until end of input into a growable array (start capacity 2, double with realloc). Print the count, the final capacity, and the numbers in reverse.", "c",
                [t("five", stdin="1 2 3 4 5"), t("one", stdin="9")], ["5 8\n5 4 3 2 1", "1 2\n9"],
                prog("size_t cap = 2, n = 0;\nint *a = malloc(cap * sizeof *a);\nif (!a) return 1;\nint x;\nwhile (scanf(\"%d\", &x) == 1) {\n    if (n == cap) {\n        int *tmp = realloc(a, cap * 2 * sizeof *a);\n        if (!tmp) {\n            free(a);\n            return 1;\n        }\n        a = tmp;\n        cap *= 2;\n    }\n    a[n++] = x;\n}\nprintf(\"%zu %zu\\n\", n, cap);\nfor (size_t i = n; i-- > 0;) printf(i ? \"%d \" : \"%d\\n\", a[i]);\nfree(a);",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n"),
                starter=STARTER, require=[r"realloc", r"free\s*\("], fallback=[r"realloc\s*\(", r"free\s*\("]),
        ),
        lesson(
            "memcpy, memmove & memset",
            "<string.h> has raw byte operations:\n\nmemset(buf, 0, sizeof buf);          // fill with a byte\nmemcpy(dst, src, n * sizeof *src);   // copy - regions must NOT overlap\nmemmove(a + 1, a, 4 * sizeof *a);    // safe when they overlap\nmemcmp(a, b, n)                      // compare bytes\n\nmemset only works for 'byte-pattern' values: 0 is fine for ints, 1 is not (it sets every byte to 1).",
            mcq("When must you use memmove instead of memcpy?", ["When source and destination overlap", "For strings", "For large blocks", "Never"], 0),
            mcq("What does memset(arr, 1, sizeof arr) set each int to?", ["16843009 (every byte = 1)", "1", "0", "-1"], 0),
            fill("Zero out a struct.", "memset(&s, ___, sizeof s);", "0"),
            mcq("What does memcmp return when the blocks are equal?", ["0", "1", "true", "The length"], 0),
            run("Read n and n ints, then an index k and value v. Insert v at index k by shifting the tail right with memmove (array capacity 100), then print the array.", "c",
                [t("middle", stdin="4\n1 2 4 5\n2 3"), t("front", stdin="2\n8 9\n0 7")], ["1 2 3 4 5", "7 8 9"],
                prog("int a[100], n, k, v;\nscanf(\"%d\", &n);\nfor (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\nscanf(\"%d %d\", &k, &v);\nmemmove(a + k + 1, a + k, (size_t)(n - k) * sizeof a[0]);\na[k] = v;\nn++;\nfor (int i = 0; i < n; i++) printf(i ? \" %d\" : \"%d\", a[i]);\nputchar('\\n');",
                     includes="#include <stdio.h>\n#include <string.h>\n"),
                starter=STARTER, require=[r"memmove"], fallback=[r"memmove\s*\("]),
        ),
        lesson(
            "Memory bugs",
            "The classic C memory bugs:\n- leak: malloc without free\n- use-after-free: using memory after free (set the pointer to NULL after freeing)\n- double free: freeing twice\n- buffer overflow: writing past the end\n- uninitialized reads\n\nTools catch them: gcc -fsanitize=address,undefined -g and valgrind. Always compile with -Wall -Wextra.",
            mcq("Which bug is this? free(p); printf(\"%d\", *p);", ["Use-after-free", "Leak", "Double free", "Overflow"], 0),
            mcq("Which flag enables AddressSanitizer?", ["-fsanitize=address", "-O2", "-Wall", "-g only"], 0),
            fill("Defensive habit after freeing.", "free(p);\np = ___;", "NULL"),
            mcq("Is free(NULL) safe?", ["Yes - it does nothing", "No, it crashes", "Only once", "Undefined"], 0),
            order("Order a safe allocate-use-release sequence.", ["int *p = malloc(n * sizeof *p);", "if (!p) return 1;", "p[0] = 42;", "free(p);", "p = NULL;"]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Types & sorting",
        lesson(
            "qsort",
            "qsort sorts any array given a comparator:\n\nint cmp_int(const void *a, const void *b) {\n    int x = *(const int *)a, y = *(const int *)b;\n    return (x > y) - (x < y);   // avoids overflow of x - y\n}\nqsort(arr, n, sizeof arr[0], cmp_int);\n\nComparators receive POINTERS to the elements.",
            mcq("What does the comparator receive?", ["Pointers to two elements", "The two values", "Indexes", "The whole array"], 0),
            mcq("Why (x > y) - (x < y) instead of x - y?", ["x - y can overflow", "It's shorter", "It sorts descending", "No reason"], 0),
            fill("Element size argument.", "qsort(a, n, ___ a[0], cmp);", "sizeof"),
            mcq("Which header declares qsort?", ["<stdlib.h>", "<string.h>", "<stdio.h>", "<sort.h>"], 0),
            run("Read words (max 31 chars, up to 100) until end of input. Sort them by length, then alphabetically, using qsort on an array of char[32], and print one per line.", "c",
                [t("words", stdin="pear fig apple kiwi date")], ["fig\ndate\nkiwi\npear\napple"],
                prog("char words[100][32];\nint n = 0;\nwhile (n < 100 && scanf(\"%31s\", words[n]) == 1) n++;\nqsort(words, (size_t)n, sizeof words[0], cmp_word);\nfor (int i = 0; i < n; i++) puts(words[i]);",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n",
                     before="static int cmp_word(const void *a, const void *b) {\n    const char *x = a, *y = b;\n    size_t lx = strlen(x), ly = strlen(y);\n    if (lx != ly) return (lx > ly) - (lx < ly);\n    return strcmp(x, y);\n}\n\n"),
                starter=STARTER, require=[r"qsort"], fallback=[r"qsort\s*\(", r"const\s+void\s*\*"]),
        ),
        lesson(
            "enum & typedef",
            "enum gives names to integer constants; typedef creates an alias:\n\ntypedef enum { RED, GREEN, BLUE, COLOR_COUNT } Color;   // 0, 1, 2, 3\nstatic const char *COLOR_NAMES[] = {\"red\", \"green\", \"blue\"};\n\ntypedef struct { double x, y; } Point;\nPoint p = {.x = 1, .y = 2};   // designated initializers\n\nswitch statements over enums are a common C pattern.",
            mcq("What is GREEN's value in enum { RED, GREEN, BLUE }?", ["1", "0", "2", "\"GREEN\""], 0),
            fill("Alias a struct type.", "___ struct { int w, h; } Size;", "typedef"),
            mcq("What does {.x = 1, .y = 2} use?", ["Designated initializers", "Constructors", "Pointers", "Macros"], 0),
            mcq("Why add COLOR_COUNT as the last enum member?", ["It equals the number of colors - handy for arrays and loops", "It's required", "It's a color", "To end the enum"], 0),
            run("Define typedef enum { LOW, MEDIUM, HIGH } Level. Read scores until end of input; map <40 to LOW, <75 to MEDIUM, else HIGH with a function Level classify(int). Print how many of each as low=… medium=… high=…", "c",
                [t("mix", stdin="10 50 80 39 75 74")], ["low=2 medium=2 high=2"],
                prog("int counts[LEVEL_COUNT] = {0}, s;\nwhile (scanf(\"%d\", &s) == 1) counts[classify(s)]++;\nprintf(\"low=%d medium=%d high=%d\\n\", counts[LOW], counts[MEDIUM], counts[HIGH]);",
                     before="typedef enum { LOW, MEDIUM, HIGH, LEVEL_COUNT } Level;\n\nLevel classify(int score) {\n    if (score < 40) return LOW;\n    if (score < 75) return MEDIUM;\n    return HIGH;\n}\n\n"),
                starter=STARTER, require=[r"\benum\b"], fallback=[r"typedef\s+enum", r"Level\s+classify"]),
        ),
        lesson(
            "Unions & fixed-width types",
            "<stdint.h> gives exact sizes: int8_t, uint16_t, int32_t, uint64_t, plus size_t for sizes. Print uint64_t with PRIu64 from <inttypes.h>.\n\nA union stores ONE of several members in the same memory - its size is the largest member's:\n\ntypedef struct {\n    enum { INT, FLOAT } kind;\n    union { int i; float f; } as;\n} Value;           // a 'tagged union'",
            mcq("How big is union { int i; double d; }?", ["At least sizeof(double)", "sizeof(int) + sizeof(double)", "sizeof(int)", "1 byte"], 0),
            mcq("Which type is guaranteed to be exactly 32 bits?", ["int32_t", "int", "long", "short"], 0),
            fill("Format macro to print a uint64_t.", "printf(\"%\" ___ \"\\n\", big);", "PRIu64"),
            mcq("Why keep a 'kind' tag next to a union?", ["To know which member is currently valid", "For speed", "It's required by C", "To save memory"], 0),
            run("Compute 2^n for n from input (0..63) as a uint64_t using shifts, and print it with PRIu64. Also print whether it fits in an int32_t (yes/no).", "c",
                [t("small", stdin="10"), t("big", stdin="63"), t("edge", stdin="31")], ["1024 yes", "9223372036854775808 no", "2147483648 no"],
                prog("int n;\nscanf(\"%d\", &n);\nuint64_t v = (uint64_t)1 << n;\nprintf(\"%\" PRIu64 \" %s\\n\", v, v <= INT32_MAX ? \"yes\" : \"no\");",
                     includes="#include <inttypes.h>\n#include <stdint.h>\n#include <stdio.h>\n"),
                starter=STARTER, require=[r"uint64_t", r"PRIu64"], fallback=[r"uint64_t", r"PRIu64", r"<<"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Linked data structures",
        lesson(
            "Singly linked lists",
            "Each node points to the next:\n\ntypedef struct Node { int value; struct Node *next; } Node;\n\nNode *push_front(Node *head, int v) {\n    Node *n = malloc(sizeof *n);\n    n->value = v; n->next = head;\n    return n;\n}\n\nTraverse: for (Node *p = head; p; p = p->next)\nFree every node when done.",
            mcq("Why does the struct say struct Node *next and not Node *next?", ["The typedef name isn't defined yet inside the struct", "Style", "Speed", "It doesn't matter"], 0),
            fill("Access a member through a pointer.", "p___value", "->"),
            mcq("What's the cost of inserting at the front?", ["O(1)", "O(n)", "O(log n)", "O(n²)"], 0),
            mcq("What happens if you free a node before reading its next pointer?", ["Use-after-free", "Nothing", "The list reverses", "A leak only"], 0),
            run("Build a linked list from input numbers (append at the tail), reverse it in place, print it as a -> b -> c, and free all nodes.", "c",
                [t("four", stdin="1 2 3 4"), t("one", stdin="7")], ["4 -> 3 -> 2 -> 1", "7"],
                prog("Node *head = NULL, *tail = NULL;\nint v;\nwhile (scanf(\"%d\", &v) == 1) {\n    Node *n = malloc(sizeof *n);\n    if (!n) return 1;\n    n->value = v;\n    n->next = NULL;\n    if (tail) tail->next = n;\n    else head = n;\n    tail = n;\n}\nNode *prev = NULL;\nwhile (head) {\n    Node *next = head->next;\n    head->next = prev;\n    prev = head;\n    head = next;\n}\nhead = prev;\nfor (Node *p = head; p; p = p->next) printf(p->next ? \"%d -> \" : \"%d\\n\", p->value);\nwhile (head) {\n    Node *next = head->next;\n    free(head);\n    head = next;\n}",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n",
                     before="typedef struct Node {\n    int value;\n    struct Node *next;\n} Node;\n\n"),
                starter=STARTER, require=[r"struct\s+Node\s*\*", r"free\s*\("], fallback=[r"struct\s+Node\s*\*\s*next", r"->\s*next", r"free\s*\("]),
        ),
        lesson(
            "Stacks & queues in C",
            "Build a stack on an array with a top index, or a queue with a circular buffer:\n\n#define CAP 8\nint buf[CAP]; int head = 0, count = 0;\nvoid enqueue(int v) { buf[(head + count) % CAP] = v; count++; }\nint dequeue(void) { int v = buf[head]; head = (head + 1) % CAP; count--; return v; }\n\nThe % CAP makes indexes wrap around.",
            mcq("Why % CAP in a circular buffer?", ["Indexes wrap around to the start", "To sort", "To round", "To free memory"], 0),
            mcq("A stack is…", ["Last in, first out", "First in, first out", "Sorted", "Random access only"], 0),
            fill("Advance the head with wrap-around.", "head = (head + 1) ___ CAP;", "%"),
            mcq("What must enqueue check first?", ["That the buffer isn't full", "That it's sorted", "Nothing", "That head is 0"], 0),
            run("Implement a circular queue of capacity 4. Process commands until end of input: 'push x' (print 'full' if full), 'pop' (print the value or 'empty').", "c",
                [t("wrap", stdin="push 1\npush 2\npop\npush 3\npush 4\npush 5\npush 6\npop\npop\npop\npop\npop")], ["1\nfull\n2\n3\n4\n5\nempty"],
                prog("char cmd[8];\nint x;\nwhile (scanf(\"%7s\", cmd) == 1) {\n    if (strcmp(cmd, \"push\") == 0) {\n        scanf(\"%d\", &x);\n        if (count == CAP) puts(\"full\");\n        else {\n            buf[(head + count) % CAP] = x;\n            count++;\n        }\n    } else {\n        if (count == 0) puts(\"empty\");\n        else {\n            printf(\"%d\\n\", buf[head]);\n            head = (head + 1) % CAP;\n            count--;\n        }\n    }\n}",
                     includes="#include <stdio.h>\n#include <string.h>\n",
                     before="#define CAP 4\n\nstatic int buf[CAP];\nstatic int head = 0, count = 0;\n\n"),
                starter=STARTER, require=[r"%\s*CAP|%\s*4"], fallback=[r"%\s*(CAP|4)"]),
        ),
        lesson(
            "Binary search trees",
            "A BST keeps smaller keys on the left and larger on the right:\n\nTree *insert(Tree *t, int k) {\n    if (!t) { t = calloc(1, sizeof *t); t->key = k; return t; }\n    if (k < t->key) t->left = insert(t->left, k);\n    else if (k > t->key) t->right = insert(t->right, k);\n    return t;\n}\n\nAn in-order traversal (left, node, right) visits keys in sorted order.",
            mcq("Which traversal prints a BST in sorted order?", ["In-order", "Pre-order", "Post-order", "Level-order"], 0),
            mcq("What's the worst-case height of an unbalanced BST with n keys?", ["n (a chain)", "log n", "1", "n²"], 0),
            fill("Free children before the node in a…", "___-order traversal", "post"),
            mcq("Average search cost in a balanced BST?", ["O(log n)", "O(n)", "O(1)", "O(n log n)"], 0),
            run("Insert input numbers into a BST (ignore duplicates). Print the in-order traversal on one line and the tree height on the next (empty tree = 0, single node = 1). Free the tree.", "c",
                [t("tree", stdin="5 3 8 1 4 9 3"), t("chain", stdin="1 2 3")], ["1 3 4 5 8 9\n3", "1 2 3\n3"],
                prog("Tree *root = NULL;\nint k;\nwhile (scanf(\"%d\", &k) == 1) root = insert(root, k);\nint first = 1;\ninorder(root, &first);\nprintf(\"\\n%d\\n\", height(root));\nfree_tree(root);",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n",
                     before="typedef struct Tree {\n    int key;\n    struct Tree *left, *right;\n} Tree;\n\nTree *insert(Tree *t, int k) {\n    if (!t) {\n        t = calloc(1, sizeof *t);\n        if (!t) exit(1);\n        t->key = k;\n        return t;\n    }\n    if (k < t->key) t->left = insert(t->left, k);\n    else if (k > t->key) t->right = insert(t->right, k);\n    return t;\n}\n\nvoid inorder(const Tree *t, int *first) {\n    if (!t) return;\n    inorder(t->left, first);\n    printf(*first ? \"%d\" : \" %d\", t->key);\n    *first = 0;\n    inorder(t->right, first);\n}\n\nint height(const Tree *t) {\n    if (!t) return 0;\n    int l = height(t->left), r = height(t->right);\n    return 1 + (l > r ? l : r);\n}\n\nvoid free_tree(Tree *t) {\n    if (!t) return;\n    free_tree(t->left);\n    free_tree(t->right);\n    free(t);\n}\n\n"),
                starter=STARTER, require=[r"->\s*left", r"free\s*\("], fallback=[r"->\s*left", r"->\s*right", r"free\s*\("]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Bits & bytes",
        lesson(
            "Bitwise operators",
            "Work with individual bits:\n\n&  AND    |  OR    ^  XOR    ~  NOT    <<  shift left    >>  shift right\n\nflags |= (1u << 3);      // set bit 3\nflags &= ~(1u << 3);     // clear bit 3\nflags ^= (1u << 3);      // toggle bit 3\nif (flags & (1u << 3))   // test bit 3\n\nUse unsigned types for bit manipulation.",
            mcq("What is 6 & 3?", ["2", "7", "5", "1"], 0, "110 & 011 = 010."),
            mcq("What is 6 ^ 3?", ["5", "7", "2", "1"], 0),
            fill("Clear bit k.", "x &= ___(1u << k);", "~"),
            mcq("Why prefer unsigned types for bit work?", ["Shifting signed negatives is implementation-defined/undefined", "They're faster", "They're bigger", "No reason"], 0),
            run("Read an unsigned int n. Print its 8 lowest bits as binary (most significant first), its popcount (number of 1 bits in all of n), and whether it is a power of two (yes/no, using n & (n - 1)).", "c",
                [t("5", stdin="5"), t("64", stdin="64"), t("255", stdin="255")], ["00000101 2 no", "01000000 1 yes", "11111111 8 no"],
                prog("unsigned n;\nscanf(\"%u\", &n);\nfor (int i = 7; i >= 0; i--) putchar((n >> i) & 1u ? '1' : '0');\nint pop = 0;\nfor (unsigned m = n; m; m &= m - 1) pop++;\nprintf(\" %d %s\\n\", pop, n && !(n & (n - 1)) ? \"yes\" : \"no\");"),
                starter=STARTER, require=[r">>|<<", r"&"], forbid=[r"__builtin"], fallback=[r">>", r"&\s*\(\s*n\s*-\s*1\s*\)"]),
        ),
        lesson(
            "Bit flags",
            "Pack many booleans into one integer:\n\nenum { PERM_READ = 1 << 0, PERM_WRITE = 1 << 1, PERM_EXEC = 1 << 2 };\nunsigned perms = PERM_READ | PERM_WRITE;\nif (perms & PERM_WRITE) ...\n\nThis is how Unix file permissions (rwx = 4 2 1) and many APIs' option flags work.",
            mcq("What is PERM_READ | PERM_EXEC with READ=1, EXEC=4?", ["5", "4", "1", "3"], 0),
            mcq("Unix permission 6 means…", ["read + write", "read + exec", "write only", "all"], 0),
            fill("Add the exec flag.", "perms ___ PERM_EXEC;", "|="),
            mcq("How do you test whether ALL of flags A and B are set?", ["(x & (A | B)) == (A | B)", "x & A | B", "x == A", "x | A"], 0),
            run("Read an octal-style permission digit (0-7) per line until end of input and print it as rwx text, e.g. 5 → r-x, 6 → rw-, 0 → ---.", "c",
                [t("digits", stdin="7\n5\n6\n0\n4")], ["rwx\nr-x\nrw-\n---\nr--"],
                prog("int p;\nwhile (scanf(\"%d\", &p) == 1) {\n    printf(\"%c%c%c\\n\", p & PERM_READ ? 'r' : '-', p & PERM_WRITE ? 'w' : '-', p & PERM_EXEC ? 'x' : '-');\n}",
                     before="enum { PERM_EXEC = 1 << 0, PERM_WRITE = 1 << 1, PERM_READ = 1 << 2 };\n\n"),
                starter=STARTER, require=[r"&"], fallback=[r"&\s*(4|PERM_READ|1\s*<<\s*2)", r"&\s*(1|PERM_EXEC)"]),
        ),
        lesson(
            "Endianness & bytes",
            "Multi-byte numbers are stored in memory with an ENDIANNESS: little-endian (x86, ARM usually) puts the lowest byte first.\n\nTo serialize portably, build bytes with shifts instead of copying raw memory:\nbytes[0] = (v >> 24) & 0xFF;   // big-endian (network order)\n\nRead back: v = (uint32_t)b[0] << 24 | b[1] << 16 | b[2] << 8 | b[3];",
            mcq("Which byte comes first in little-endian?", ["The least significant byte", "The most significant byte", "The sign byte", "It varies by value"], 0),
            mcq("What is 'network byte order'?", ["Big-endian", "Little-endian", "Random", "Middle-endian"], 0),
            fill("Mask the lowest byte.", "uint8_t low = v & ___;", "0xFF"),
            mcq("Why serialize with shifts instead of memcpy of an int?", ["It's portable regardless of the machine's endianness", "It's shorter", "memcpy can't copy ints", "Speed"], 0),
            run("Read a uint32 value. Print its 4 big-endian bytes in hex (two digits each, space-separated, upper case), then rebuild the value from those bytes and print it.", "c",
                [t("value", stdin="305419896"), t("small", stdin="255")], ["12 34 56 78\n305419896", "00 00 00 FF\n255"],
                prog("uint32_t v;\nscanf(\"%\" SCNu32, &v);\nuint8_t b[4];\nfor (int i = 0; i < 4; i++) b[i] = (uint8_t)((v >> (24 - 8 * i)) & 0xFF);\nprintf(\"%02X %02X %02X %02X\\n\", b[0], b[1], b[2], b[3]);\nuint32_t back = (uint32_t)b[0] << 24 | (uint32_t)b[1] << 16 | (uint32_t)b[2] << 8 | b[3];\nprintf(\"%\" PRIu32 \"\\n\", back);",
                     includes="#include <inttypes.h>\n#include <stdint.h>\n#include <stdio.h>\n"),
                starter=STARTER, require=[r">>", r"<<"], fallback=[r">>\s*\(?\s*(24|16|8)", r"<<\s*(24|16|8)"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · Preprocessor & program structure",
        lesson(
            "Macros",
            "The preprocessor runs before compilation and does TEXT substitution:\n\n#define MAX(a, b) ((a) > (b) ? (a) : (b))\n#define ARRAY_LEN(a) (sizeof(a) / sizeof((a)[0]))\n\nAlways parenthesize parameters and the whole body. Arguments may be evaluated twice: MAX(i++, j) is a bug. Prefer static inline functions when you can.",
            mcq("Why parenthesize macro parameters?", ["Operator precedence after substitution", "Style", "Speed", "They're required"], 0),
            mcq("What's wrong with MAX(i++, j)?", ["i++ may run twice", "Nothing", "It doesn't compile", "It returns j"], 0),
            fill("Define a constant with the preprocessor.", "___ BUFFER_SIZE 256", "#define"),
            mcq("What does ARRAY_LEN fail on?", ["A pointer (it gives the wrong answer)", "int arrays", "char arrays", "Nothing"], 0),
            run("Define macros SQUARE(x) (correctly parenthesized) and ARRAY_LEN(a). Print SQUARE(1 + 2), then the length and sum of the array {4, 8, 15, 16, 23, 42} using ARRAY_LEN.", "c",
                [t("Run")], ["9\n6 108"],
                prog("int a[] = {4, 8, 15, 16, 23, 42};\nint sum = 0;\nfor (size_t i = 0; i < ARRAY_LEN(a); i++) sum += a[i];\nprintf(\"%d\\n%zu %d\\n\", SQUARE(1 + 2), ARRAY_LEN(a), sum);",
                     before="#define SQUARE(x) ((x) * (x))\n#define ARRAY_LEN(a) (sizeof(a) / sizeof((a)[0]))\n\n"),
                starter=STARTER, require=[r"#define\s+SQUARE\s*\(\s*x\s*\)\s*\(\s*\(\s*x\s*\)"], fallback=[r"#define\s+SQUARE\s*\(\s*x\s*\)\s*\(\s*\(\s*x\s*\)", r"#define\s+ARRAY_LEN"]),
        ),
        lesson(
            "Headers & include guards",
            "Split programs into .h (declarations) and .c (definitions):\n\n/* stack.h */\n#ifndef STACK_H\n#define STACK_H\nvoid push(int v);\nint pop(void);\n#endif\n\nThe guard stops double inclusion. static at file scope makes a function/variable private to its .c file. extern declares a variable defined elsewhere.",
            mcq("What does an include guard prevent?", ["The header's contents being included twice", "Linking errors always", "Macros", "Recursion"], 0),
            mcq("What does static on a file-scope function do?", ["Makes it visible only in that .c file", "Keeps its value between calls", "Makes it faster", "Makes it a constant"], 0),
            fill("Close an include guard.", "___", "#endif"),
            mcq("Where do function DEFINITIONS usually go?", [".c files", ".h files", "Both", "Makefiles"], 0),
            order("Order a header file with an include guard.", ["#ifndef MATHX_H", "#define MATHX_H", "int clamp(int v, int lo, int hi);", "#endif"]),
        ),
        lesson(
            "Conditional compilation & assert",
            "#ifdef / #if let you compile code only in some builds:\n\n#ifdef DEBUG\n#define LOG(...) fprintf(stderr, __VA_ARGS__)\n#else\n#define LOG(...) ((void)0)\n#endif\n\nassert(expr) from <assert.h> aborts with a message if expr is false; it's removed when NDEBUG is defined. Predefined macros: __FILE__, __LINE__, __func__.",
            mcq("What happens to assert() when NDEBUG is defined?", ["It's compiled out", "It always aborts", "It prints only", "Nothing changes"], 0),
            mcq("What does __VA_ARGS__ represent?", ["The variable arguments passed to a variadic macro", "The argument count", "A va_list", "The file name"], 0),
            fill("Compile a block only if DEBUG is defined.", "___ DEBUG\n...\n#endif", "#ifdef"),
            mcq("Should assert check user input?", ["No - it's for programmer errors and may be compiled out", "Yes", "Only in release", "Only for strings"], 0),
            run("Define VERBOSE as 1 at the top. Write a variadic macro LOG(...) that prints '[log] ' followed by its printf-style arguments when VERBOSE is 1 (use #if). Log 'start', compute the sum of 1..n for input n, log 'n=<n>', and print the sum.", "c",
                [t("10", stdin="10")], ["[log] start\n[log] n=10\n55"],
                prog("LOG(\"start\\n\");\nint n;\nscanf(\"%d\", &n);\nLOG(\"n=%d\\n\", n);\nprintf(\"%d\\n\", n * (n + 1) / 2);",
                     before="#define VERBOSE 1\n\n#if VERBOSE\n#define LOG(...) (printf(\"[log] \"), printf(__VA_ARGS__))\n#else\n#define LOG(...) ((void)0)\n#endif\n\n"),
                starter=STARTER, require=[r"__VA_ARGS__", r"#if"], fallback=[r"#define\s+LOG\s*\(\s*\.\.\.\s*\)", r"__VA_ARGS__", r"#if"]),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Algorithms in C",
        lesson(
            "Recursion & backtracking",
            "Backtracking explores choices recursively and UNDOES them:\n\nvoid permute(char *s, int k, int n) {\n    if (k == n) { puts(s); return; }\n    for (int i = k; i < n; i++) {\n        swap(&s[k], &s[i]);\n        permute(s, k + 1, n);\n        swap(&s[k], &s[i]);   // undo\n    }\n}\n\nUsed for permutations, subsets, sudoku, N-queens.",
            mcq("What does the 'undo' step do in backtracking?", ["Restores state before trying the next choice", "Frees memory", "Sorts", "Ends recursion"], 0),
            mcq("How many permutations does \"abcd\" have?", ["24", "16", "12", "4"], 0),
            fill("Base case: all positions are fixed.", "if (k ___ n) { puts(s); return; }", "=="),
            mcq("How many subsets does a 5-element set have?", ["32", "25", "10", "120"], 0),
            run("Read n (1-10) and count the solutions to the n-queens problem with backtracking.", "c",
                [t("4", stdin="4"), t("6", stdin="6"), t("8", stdin="8")], ["2", "4", "92"],
                prog("int n;\nscanf(\"%d\", &n);\nprintf(\"%d\\n\", solve(0, n));",
                     before="static int col[10];\n\nstatic int safe(int r, int c) {\n    for (int i = 0; i < r; i++) {\n        if (col[i] == c || abs(col[i] - c) == r - i) return 0;\n    }\n    return 1;\n}\n\nstatic int solve(int r, int n) {\n    if (r == n) return 1;\n    int count = 0;\n    for (int c = 0; c < n; c++) {\n        if (safe(r, c)) {\n            col[r] = c;\n            count += solve(r + 1, n);\n        }\n    }\n    return count;\n}\n\n",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n"),
                starter=STARTER, require=[r"\w+\s*\([^;]*\+\s*1"], forbid=[r"92"], fallback=[r"solve\s*\(|place\s*\(|queens?\s*\(", r"\+\s*1"]),
        ),
        lesson(
            "Merge sort",
            "Merge sort splits the array in half, sorts each half, then merges - O(n log n) always, and stable:\n\nvoid merge_sort(int *a, int *tmp, int lo, int hi) {   // [lo, hi)\n    if (hi - lo < 2) return;\n    int mid = lo + (hi - lo) / 2;\n    merge_sort(a, tmp, lo, mid);\n    merge_sort(a, tmp, mid, hi);\n    /* merge a[lo..mid) and a[mid..hi) via tmp */\n}",
            mcq("What's merge sort's worst-case complexity?", ["O(n log n)", "O(n²)", "O(n)", "O(log n)"], 0),
            mcq("What extra memory does array merge sort need?", ["O(n) temporary buffer", "None", "O(1)", "O(n²)"], 0),
            fill("Find the middle without overflow.", "int mid = lo + (hi - lo) ___ 2;", "/"),
            mcq("Is merge sort stable?", ["Yes", "No", "Only for ints", "Only in-place"], 0),
            run("Implement merge sort (no qsort). Read n and n ints, sort ascending and print space-separated.", "c",
                [t("7", stdin="7\n5 -1 3 3 0 9 2"), t("1", stdin="1\n4")], ["-1 0 2 3 3 5 9", "4"],
                prog("int n;\nscanf(\"%d\", &n);\nint *a = malloc((size_t)n * sizeof *a), *tmp = malloc((size_t)n * sizeof *tmp);\nif (!a || !tmp) return 1;\nfor (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\nmerge_sort(a, tmp, 0, n);\nfor (int i = 0; i < n; i++) printf(i ? \" %d\" : \"%d\", a[i]);\nputchar('\\n');\nfree(a);\nfree(tmp);",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n",
                     before="static void merge_sort(int *a, int *tmp, int lo, int hi) {\n    if (hi - lo < 2) return;\n    int mid = lo + (hi - lo) / 2;\n    merge_sort(a, tmp, lo, mid);\n    merge_sort(a, tmp, mid, hi);\n    int i = lo, j = mid, k = lo;\n    while (i < mid && j < hi) tmp[k++] = a[i] <= a[j] ? a[i++] : a[j++];\n    while (i < mid) tmp[k++] = a[i++];\n    while (j < hi) tmp[k++] = a[j++];\n    for (k = lo; k < hi; k++) a[k] = tmp[k];\n}\n\n"),
                starter=STARTER, require=[r"merge"], forbid=[r"qsort"], fallback=[r"merge\w*\s*\(", r"mid"]),
        ),
        lesson(
            "Hash tables",
            "A hash table maps keys to buckets with a hash function; collisions go in a per-bucket linked list (chaining):\n\nunsigned long hash(const char *s) {     // djb2\n    unsigned long h = 5381;\n    for (; *s; s++) h = h * 33 + (unsigned char)*s;\n    return h;\n}\nsize_t bucket = hash(key) % NBUCKETS;\n\nAverage O(1) lookups when the load factor stays low.",
            mcq("What is a collision?", ["Two keys hashing to the same bucket", "A crash", "A duplicate key", "A full table"], 0),
            mcq("What does chaining do?", ["Keeps colliding entries in a list per bucket", "Rehashes forever", "Drops entries", "Sorts keys"], 0),
            fill("Pick a bucket.", "size_t b = hash(key) ___ NBUCKETS;", "%"),
            mcq("Average lookup time with a good hash and low load?", ["O(1)", "O(n)", "O(log n)", "O(n²)"], 0),
            run("Implement a chained hash table (16 buckets, djb2) counting word frequencies. Read words until end of input, then for each query word after a line '---' print word count.", "c",
                [t("counts", stdin="red blue red green red blue\n---\nred blue pink")], ["red 3\nblue 2\npink 0"],
                prog("char w[32];\nint querying = 0;\nwhile (scanf(\"%31s\", w) == 1) {\n    if (strcmp(w, \"---\") == 0) querying = 1;\n    else if (querying) printf(\"%s %d\\n\", w, lookup(w));\n    else add(w);\n}\nfor (int i = 0; i < NBUCKETS; i++) {\n    while (table[i]) {\n        Entry *next = table[i]->next;\n        free(table[i]);\n        table[i] = next;\n    }\n}",
                     includes="#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n",
                     before="#define NBUCKETS 16\n\ntypedef struct Entry {\n    char key[32];\n    int count;\n    struct Entry *next;\n} Entry;\n\nstatic Entry *table[NBUCKETS];\n\nstatic unsigned long hash(const char *s) {\n    unsigned long h = 5381;\n    for (; *s; s++) h = h * 33 + (unsigned char)*s;\n    return h;\n}\n\nstatic void add(const char *key) {\n    size_t b = hash(key) % NBUCKETS;\n    for (Entry *e = table[b]; e; e = e->next) {\n        if (strcmp(e->key, key) == 0) {\n            e->count++;\n            return;\n        }\n    }\n    Entry *e = calloc(1, sizeof *e);\n    if (!e) exit(1);\n    snprintf(e->key, sizeof e->key, \"%s\", key);\n    e->count = 1;\n    e->next = table[b];\n    table[b] = e;\n}\n\nstatic int lookup(const char *key) {\n    for (Entry *e = table[hash(key) % NBUCKETS]; e; e = e->next) {\n        if (strcmp(e->key, key) == 0) return e->count;\n    }\n    return 0;\n}\n\n"),
                starter=STARTER, require=[r"%\s*\w+", r"->\s*next"], fallback=[r"hash\s*\(", r"%\s*(NBUCKETS|16|\w+)", r"->\s*next"]),
        ),
    ),
)
