from .dsl import course, fill, lesson, mcq, order, run, t, unit, code
from .cpp_adv import ADVANCED, INTERMEDIATE
from .cpp_expert import EXPERT
from .cpp_expert2 import EXPERT2

STARTER = "#include <iostream>\n\nint main() {\n    \n    return 0;\n}\n"


def prog(body: str, includes: str = "#include <iostream>\n", before: str = "") -> str:
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"{includes}\n{before}int main() {{\n{inner}\n    return 0;\n}}\n"


COURSE = course(
    "cpp", "C++", "⚙️", "Fast and close to the metal - games, engines and competitive programming.",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · First programs",
        lesson(
            "Output with cout",
            "A C++ program starts in main(). #include <iostream> gives you std::cout for output:\n\n#include <iostream>\n\nint main() {\n    std::cout << \"Hello!\" << std::endl;\n    return 0;\n}\n\n<< sends values to the output. std::endl (or \"\\n\") ends the line. return 0 means success.",
            fill("Complete the output statement.", 'std::cout ___ "Hello";', "<<"),
            mcq("Which header gives you std::cout?", ["<iostream>", "<stdio.h>", "<string>", "<cmath>"], 0),
            order("Order a minimal program.", ["#include <iostream>", "int main() {", '    std::cout << "Hi";', "    return 0;", "}"]),
            mcq("What does main return on success by convention?", ["0", "1", "-1", "true"], 0),
            run("Print exactly: Hello, C++!", "cpp", [t("Run")], ["Hello, C++!"], prog('std::cout << "Hello, C++!" << std::endl;'), starter=STARTER,
                fallback=[r'cout\s*<<\s*"Hello, C\+\+!"']),
        ),
        lesson(
            "Chaining output & comments",
            "You can chain many values with <<:\n\nint age = 20;\nstd::cout << \"Age: \" << age << \"\\n\";\n\nComments: // one line   /* several lines */\n\nWriting using namespace std; lets you type cout instead of std::cout - handy in small programs.",
            mcq("What is printed?", ["Age: 20", "Age:20", "Age: age", "An error"], 0, code='int age = 20;\nstd::cout << "Age: " << age;'),
            mcq("Which is a C++ comment?", ["// note", "# note", "<!-- note -->", "-- note"], 0),
            fill("Allow cout without the std:: prefix.", "using namespace ___;", "std"),
            mcq("What does \"\\n\" do?", ["Starts a new line", "Prints n", "Ends the program", "Prints a tab"], 0),
            run("Print the numbers 1, 2 and 3 on ONE line separated by \" < \" (like 1 < 2 < 3) using a single chained cout statement.", "cpp",
                [t("Run")], ["1 < 2 < 3"], prog('std::cout << 1 << " < " << 2 << " < " << 3 << "\\n";'), starter=STARTER,
                fallback=[r"cout[\s\S]*<<[\s\S]*<<[\s\S]*<<"]),
        ),
        lesson(
            "Arithmetic",
            "Maths works like in most languages:\n\n7 + 3   // 10\n7 / 2   // 3    (int / int -> int!)\n7.0 / 2 // 3.5\n7 % 2   // 1    (remainder, ints only)\n\n#include <cmath> gives std::sqrt, std::pow, std::abs.",
            mcq("What is 7 / 2 with ints?", ["3", "3.5", "4", "An error"], 0),
            mcq("What is 7.0 / 2?", ["3.5", "3", "4", "3.0"], 0),
            fill("Square root of 49.", "double r = std::___(49);", "sqrt"),
            mcq("What is 20 % 6?", ["2", "3", "3.33", "6"], 0),
            run("A trip is 250 km and the car uses 6 litres per 100 km. Calculate and print the litres needed (a decimal).", "cpp",
                [t("Run")], ["15"], prog("double litres = 250.0 / 100 * 6;\nstd::cout << litres << \"\\n\";"), starter=STARTER,
                require=[r"/", r"\*"], forbid=[r"<<\s*15\b"], fallback=[r"250", r"/\s*100", r"\*\s*6"]),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Variables & types",
        lesson(
            "Basic types",
            "C++ variables have types:\n\nint age = 20;        // whole number\ndouble price = 9.99; // decimal\nchar grade = 'A';    // single character\nbool ok = true;      // true / false\n\nauto lets the compiler work out the type: auto x = 3.5;  // double",
            mcq("Which type holds true/false?", ["bool", "int", "char", "boolean"], 0),
            mcq("What type does auto give x in auto x = 42;?", ["int", "double", "auto", "long"], 0),
            fill("Declare a character variable.", "___ letter = 'z';", "char"),
            mcq("What does std::cout << true; print?", ["1", "true", "True", "0"], 0, "cout prints bools as 1/0 by default (use std::boolalpha for true/false)."),
            run("Read an int (hours) and print how many minutes and seconds that is, as: 2 hours = 120 minutes = 7200 seconds", "cpp",
                [t("2", stdin="2"), t("1", stdin="1")], ["2 hours = 120 minutes = 7200 seconds", "1 hours = 60 minutes = 3600 seconds"],
                prog('int h;\nstd::cin >> h;\nstd::cout << h << " hours = " << h * 60 << " minutes = " << h * 3600 << " seconds\\n";'),
                starter=STARTER, fallback=[r"cin\s*>>", r"\*\s*60"]),
        ),
        lesson(
            "std::string",
            "#include <string> for text:\n\nstd::string name = \"Ada\";\nname.length()       // 3\nname + \" Lovelace\"  // join\nname[0]             // 'A'\nname.substr(1, 2)   // \"da\"\n\nRead a whole line with std::getline(std::cin, name);",
            mcq("What is std::string(\"code\").length()?", ["4", "3", "5", "An error"], 0),
            mcq("What is s.substr(0, 3) for s = \"Python\"?", ['"Pyt"', '"Py"', '"Pyth"', '"yth"'], 0),
            fill("Read a whole line into s.", "std::___(std::cin, s);", "getline"),
            mcq("How do you compare two std::strings for equal text?", ["a == b", "a.equals(b)", "strcmp(a, b)", "a = b"], 0, "std::string supports == directly."),
            run("Read a full line (a name) and print: Hello, <name>! (<length> letters)", "cpp",
                [t("Ada", stdin="Ada"), t("Grace Hopper", stdin="Grace Hopper")], ["Hello, Ada! (3 letters)", "Hello, Grace Hopper! (12 letters)"],
                prog('std::string name;\nstd::getline(std::cin, name);\nstd::cout << "Hello, " << name << "! (" << name.length() << " letters)\\n";',
                     "#include <iostream>\n#include <string>\n"),
                starter=STARTER, fallback=[r"getline\s*\(", r"\.length\(\)|\.size\(\)"]),
        ),
        lesson(
            "Casting & constants",
            "Convert types with static_cast:\n\nint total = 7, count = 2;\ndouble avg = static_cast<double>(total) / count;   // 3.5\nint whole = static_cast<int>(9.9);                 // 9\n\nconst makes a value that can't change: const double PI = 3.14159;",
            mcq("What is static_cast<int>(9.9)?", ["9", "10", "9.9", "An error"], 0),
            mcq("What is static_cast<double>(7) / 2?", ["3.5", "3", "4", "An error"], 0),
            fill("Make RATE unchangeable.", "___ double RATE = 0.2;", "const"),
            mcq("What happens?", ["Compile error", "PI becomes 3", "Nothing", "A warning only"], 0, code="const double PI = 3.14;\nPI = 3;"),
            run("Read two ints (total and count) and print their average with exactly 2 decimals (use std::fixed and std::setprecision(2) from <iomanip>).", "cpp",
                [t("7 2", stdin="7 2"), t("10 3", stdin="10 3")], ["3.50", "3.33"],
                prog("int total, count;\nstd::cin >> total >> count;\nstd::cout << std::fixed << std::setprecision(2) << static_cast<double>(total) / count << \"\\n\";",
                     "#include <iomanip>\n#include <iostream>\n"),
                starter=STARTER, require=[r"setprecision"], fallback=[r"setprecision\(\s*2\s*\)", r"static_cast<double>|\(double\)|1\.0\s*\*"]),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Input & decisions",
        lesson(
            "Reading input with cin",
            ">> reads a value from the keyboard (or stdin) into a variable:\n\nint a, b;\nstd::cin >> a >> b;   // reads two numbers separated by spaces/newlines\nstd::cout << a + b;\n\ncin >> stops at whitespace, so it reads one word at a time for strings.",
            fill("Read an int into n.", "std::cin ___ n;", ">>"),
            mcq("Input is \"Ada Lovelace\". What does cin >> name read into a string?", ['"Ada"', '"Ada Lovelace"', '"Lovelace"', "Nothing"], 0),
            mcq("Which reads a whole line including spaces?", ["std::getline(std::cin, s)", "std::cin >> s", "std::cin.get(s)", "scanf(s)"], 0),
            order("Order the program that adds two numbers.", ["int a, b;", "std::cin >> a >> b;", "std::cout << a + b;"]),
            run("Read three whole numbers and print their sum and their product on separate lines.", "cpp",
                [t("1 2 3", stdin="1 2 3"), t("4 5 -1", stdin="4 5 -1")], ["6\n6", "8\n-20"],
                prog("int a, b, c;\nstd::cin >> a >> b >> c;\nstd::cout << a + b + c << \"\\n\" << a * b * c << \"\\n\";"), starter=STARTER,
                fallback=[r"cin\s*>>\s*\w+\s*>>\s*\w+\s*>>\s*\w+", r"\*"]),
        ),
        lesson(
            "if / else",
            "if (condition) { ... } else if (...) { ... } else { ... }\n\nint n = 7;\nif (n % 2 == 0) {\n    std::cout << \"even\";\n} else {\n    std::cout << \"odd\";\n}\n\nCombine with && (and), || (or), ! (not).",
            mcq("What is printed?", ["small", "big", "bigsmall", "nothing"], 0, code='int x = 2;\nif (x > 3) std::cout << "big";\nelse std::cout << "small";'),
            fill("Conditions go inside…", "if ___x > 0) { }", "("),
            mcq("Which operator checks equality?", ["==", "=", "===", ":="], 0),
            mcq("What is (5 > 3 && 2 > 4)?", ["false", "true", "An error", "5"], 0),
            run("Read three side lengths and print Equilateral, Isosceles or Scalene.", "cpp",
                [t("3 3 3", stdin="3 3 3"), t("3 4 3", stdin="3 4 3"), t("3 4 5", stdin="3 4 5")], ["Equilateral", "Isosceles", "Scalene"],
                prog('int a, b, c;\nstd::cin >> a >> b >> c;\nif (a == b && b == c) {\n    std::cout << "Equilateral\\n";\n} else if (a == b || b == c || a == c) {\n    std::cout << "Isosceles\\n";\n} else {\n    std::cout << "Scalene\\n";\n}'),
                starter=STARTER, require=[r"\bif\s*\("], fallback=[r"\bif\s*\(", r"&&", r"\|\|"]),
        ),
        lesson(
            "switch & ternary",
            "switch chooses by value (ints/chars):\n\nswitch (op) {\n    case '+': std::cout << a + b; break;\n    case '-': std::cout << a - b; break;\n    default:  std::cout << \"?\";\n}\n\nThe ternary picks between two values: std::string s = n > 0 ? \"pos\" : \"not pos\";",
            mcq("What happens without break in a case?", ["Execution falls through into the next case", "Compile error", "The switch restarts", "Nothing"], 0),
            fill("Finish the ternary.", 'std::string r = ok ___ "yes" : "no";', "?"),
            mcq("Can a C++ switch work on std::string values?", ["No - only integers, chars and enums", "Yes", "Only with case strings", "Only in C++20"], 0),
            mcq("What is x?", ["10", "5", "An error", "0"], 0, code="int a = 10, b = 5;\nint x = a > b ? a : b;"),
            run("Read a number, an operator (+ - * /) and another number, e.g. 6 * 7, and print the result using a switch. For division by zero print Error.", "cpp",
                [t("6 * 7", stdin="6 * 7"), t("9 - 12", stdin="9 - 12"), t("8 / 2", stdin="8 / 2"), t("1 / 0", stdin="1 / 0")],
                ["42", "-3", "4", "Error"],
                prog('int a, b;\nchar op;\nstd::cin >> a >> op >> b;\nswitch (op) {\n    case \'+\': std::cout << a + b << "\\n"; break;\n    case \'-\': std::cout << a - b << "\\n"; break;\n    case \'*\': std::cout << a * b << "\\n"; break;\n    case \'/\':\n        if (b == 0) std::cout << "Error\\n";\n        else std::cout << a / b << "\\n";\n        break;\n}'),
                starter=STARTER, require=[r"\bswitch\b"], fallback=[r"\bswitch\s*\(", r"case\s*'\+'", r"case\s*'/'"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Loops",
        lesson(
            "while & do-while",
            "while checks the condition first; do-while runs the body at least once:\n\nint n = 3;\nwhile (n > 0) {\n    std::cout << n-- << \" \";\n}\n\ndo {\n    std::cin >> x;\n} while (x < 0);   // keep asking until x >= 0",
            mcq("How many times does a do-while body run at minimum?", ["1", "0", "2", "It depends"], 0),
            mcq("What is printed?", ["3 2 1", "2 1 0", "3 2 1 0", "1 2 3"], 0, code='int n = 3;\nwhile (n > 0) {\n    std::cout << n << " ";\n    n--;\n}'),
            fill("End a do-while loop.", "do {\n    x++;\n} ___ (x < 10);", "while"),
            order("Order the loop.", ["int i = 0;", "while (i < 3) {", "    std::cout << i;", "    i++;", "}"]),
            run("Read a positive number and print how many times you can halve it (integer division by 2) before it reaches 0.", "cpp",
                [t("8", stdin="8"), t("1", stdin="1"), t("100", stdin="100")], ["4", "1", "7"],
                prog("int n;\nstd::cin >> n;\nint steps = 0;\nwhile (n > 0) {\n    n /= 2;\n    steps++;\n}\nstd::cout << steps << \"\\n\";"),
                starter=STARTER, require=[r"\bwhile\b|\bfor\b"], fallback=[r"\bwhile\s*\(|\bfor\s*\(", r"/=?\s*2"]),
        ),
        lesson(
            "for loops",
            "for (start; condition; step) { body }\n\nfor (int i = 1; i <= 5; i++) {\n    std::cout << i << \" \";\n}\n\nCount down with i--, step by 2 with i += 2.",
            mcq("What is printed?", ["0 2 4", "0 1 2 3 4", "2 4", "0 2 4 6"], 0, code='for (int i = 0; i < 5; i += 2) std::cout << i << " ";'),
            fill("Loop i from 10 down to 1.", "for (int i = 10; i >= 1; i___)", "--"),
            mcq("How many times does the body run?", ["5", "4", "6", "0"], 0, code="for (int i = 1; i <= 5; i++) { }"),
            code("Write a for loop header that goes i = 0, 1, …, 9.", [r"for\s*\(\s*int\s+i\s*=\s*0\s*;\s*i\s*(<\s*10|<=\s*9)\s*;\s*(i\+\+|\+\+i|i\s*\+=\s*1)\s*\)"],
                 "for (int i = 0; i < 10; i++)"),
            run("Read n and print n! (n factorial, 1 × 2 × … × n). Use long long - it grows fast!", "cpp",
                [t("5", stdin="5"), t("0", stdin="0"), t("20", stdin="20")], ["120", "1", "2432902008176640000"],
                prog("int n;\nstd::cin >> n;\nlong long f = 1;\nfor (int i = 2; i <= n; i++) {\n    f *= i;\n}\nstd::cout << f << \"\\n\";"),
                starter=STARTER, require=[r"long\s+long", r"\bfor\b|\bwhile\b"], fallback=[r"long\s+long", r"\bfor\s*\(|\bwhile\s*\(", r"\*=?"]),
        ),
        lesson(
            "break, continue & nested loops",
            "break exits the innermost loop; continue skips to its next round.\n\nNested loops draw grids:\n\nfor (int r = 0; r < 3; r++) {\n    for (int c = 0; c < 4; c++) {\n        std::cout << '#';\n    }\n    std::cout << '\\n';\n}",
            mcq("How many # are printed?", ["12", "7", "3", "4"], 0, code="for (int r = 0; r < 3; r++)\n    for (int c = 0; c < 4; c++)\n        std::cout << '#';"),
            mcq("What is printed?", ["1 3", "1 2 3", "2", "1 3 5"], 0, code='for (int i = 1; i <= 4; i++) {\n    if (i % 2 == 0) continue;\n    std::cout << i << " ";\n}'),
            fill("Leave the loop immediately.", "if (found) ___;", "break"),
            mcq("Which loop does break exit in nested loops?", ["The innermost one", "All of them", "The outer one", "None"], 0),
            run("Read n and print all prime numbers up to n, separated by spaces.", "cpp",
                [t("10", stdin="10"), t("2", stdin="2"), t("30", stdin="30")], ["2 3 5 7", "2", "2 3 5 7 11 13 17 19 23 29"],
                prog('int n;\nstd::cin >> n;\nbool first = true;\nfor (int x = 2; x <= n; x++) {\n    bool prime = true;\n    for (int d = 2; d * d <= x; d++) {\n        if (x % d == 0) {\n            prime = false;\n            break;\n        }\n    }\n    if (prime) {\n        if (!first) std::cout << " ";\n        std::cout << x;\n        first = false;\n    }\n}\nstd::cout << "\\n";'),
                starter=STARTER, require=[r"for[\s\S]*for|while[\s\S]*while|for[\s\S]*while|while[\s\S]*for"], fallback=[r"for\s*\([\s\S]*for\s*\(", r"%"]),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Functions",
        lesson(
            "Defining functions",
            "A function has a return type, a name, parameters and a body. Define it before main (or declare a prototype):\n\nint square(int n) {\n    return n * n;\n}\n\nint main() {\n    std::cout << square(5);   // 25\n}\n\nvoid functions return nothing.",
            mcq("What does square(4) return?", ["16", "8", "4", "void"], 0, code="int square(int n) {\n    return n * n;\n}"),
            fill("This function returns nothing.", "___ greet() {\n    std::cout << \"Hi\";\n}", "void"),
            mcq("Where must a function be declared if called in main?", ["Before main (or via a prototype)", "Anywhere", "Inside main", "After main only"], 0),
            order("Order the program: the function must be defined before main uses it.", ["#include <iostream>", "int twice(int x) { return 2 * x; }", "int main() {", "    std::cout << twice(4);", "}"]),
            run("Write int gcd(int a, int b) using Euclid's algorithm (while b != 0: a, b = b, a % b). main reads two numbers and prints gcd.", "cpp",
                [t("12 18", stdin="12 18"), t("17 5", stdin="17 5"), t("100 75", stdin="100 75")], ["6", "1", "25"],
                prog("int a, b;\nstd::cin >> a >> b;\nstd::cout << gcd(a, b) << \"\\n\";",
                     before="int gcd(int a, int b) {\n    while (b != 0) {\n        int r = a % b;\n        a = b;\n        b = r;\n    }\n    return a;\n}\n\n"),
                starter=STARTER, require=[r"int\s+gcd\s*\("], fallback=[r"int\s+gcd\s*\(\s*int\s+\w+\s*,\s*int\s+\w+\s*\)", r"%", r"\breturn\b"]),
        ),
        lesson(
            "Pass by reference",
            "Normally arguments are copied. Add & to pass by reference so the function can change the caller's variable:\n\nvoid addOne(int& x) {\n    x++;\n}\n\nint n = 5;\naddOne(n);   // n is now 6\n\nconst std::string& s passes big objects without copying and without allowing changes.",
            mcq("What is n afterwards?", ["6", "5", "An error", "0"], 0, code="void addOne(int& x) { x++; }\nint n = 5;\naddOne(n);"),
            mcq("What is n afterwards?", ["5", "6", "An error", "0"], 0, "Without &, the function changes a copy.", code="void addOne(int x) { x++; }\nint n = 5;\naddOne(n);"),
            fill("Make x a reference parameter.", "void reset(int___ x) {\n    x = 0;\n}", "&"),
            mcq("Why pass const std::string& instead of std::string?", ["Avoids copying while preventing changes", "It's required", "It makes it faster to type", "It allows changes"], 0),
            run("Write void swapValues(int& a, int& b) that swaps two ints. main reads two numbers, calls it, and prints them (swapped) separated by a space.", "cpp",
                [t("1 2", stdin="1 2"), t("7 -3", stdin="7 -3")], ["2 1", "-3 7"],
                prog('int a, b;\nstd::cin >> a >> b;\nswapValues(a, b);\nstd::cout << a << " " << b << "\\n";',
                     before="void swapValues(int& a, int& b) {\n    int tmp = a;\n    a = b;\n    b = tmp;\n}\n\n"),
                starter=STARTER, require=[r"swapValues\s*\(\s*int\s*&"], forbid=[r"std::swap|\bswap\s*\("],
                fallback=[r"void\s+swapValues\s*\(\s*int\s*&\s*\w+\s*,\s*int\s*&\s*\w+\s*\)"]),
        ),
        lesson(
            "Overloading & defaults",
            "Functions can share a name if their parameters differ (overloading), and parameters can have default values:\n\ndouble area(double r) { return 3.14159 * r * r; }\nint area(int w, int h) { return w * h; }\n\nvoid greet(std::string name = \"friend\") {\n    std::cout << \"Hi \" << name;\n}\ngreet();   // Hi friend",
            mcq("What does area(3, 4) call?", ["The (int, int) version", "The (double) version", "Both", "An error"], 0),
            fill("Give times a default of 1.", "void beep(int times ___ 1) { }", "="),
            mcq("Which can't be used alone to overload a function?", ["The return type", "The number of parameters", "The parameter types", "Parameter order of different types"], 0),
            mcq("With void greet(std::string name = \"friend\"), what does greet(\"Ada\") print?", ["Hi Ada", "Hi friend", "An error", "Hi friend Ada"], 0),
            run("Write std::string repeat(std::string s, int times = 2) that returns s repeated. main prints repeat(\"ab\") and repeat(\"x\", 4) on separate lines.", "cpp",
                [t("Run")], ["abab\nxxxx"],
                prog('std::cout << repeat("ab") << "\\n";\nstd::cout << repeat("x", 4) << "\\n";', "#include <iostream>\n#include <string>\n",
                     before="std::string repeat(std::string s, int times = 2) {\n    std::string out;\n    for (int i = 0; i < times; i++) {\n        out += s;\n    }\n    return out;\n}\n\n"),
                starter=STARTER, require=[r"times\s*=\s*2"], fallback=[r"repeat\s*\(\s*std::string\s+\w+\s*,\s*int\s+\w+\s*=\s*2\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Vectors & strings",
        lesson(
            "std::vector",
            "#include <vector> for a resizable array:\n\nstd::vector<int> nums = {4, 8, 15};\nnums.push_back(16);   // add to the end\nnums.size()           // 4\nnums[0]               // 4\nnums.back()           // 16\nnums.pop_back();      // remove the last",
            mcq("What is v.size() after this?", ["3", "2", "4", "0"], 0, code="std::vector<int> v = {1, 2};\nv.push_back(3);"),
            fill("Add 7 to the end of v.", "v.___(7);", "push_back"),
            mcq("What is v[1]?", ["20", "10", "30", "An error"], 0, code="std::vector<int> v = {10, 20, 30};"),
            mcq("Which header is needed for std::vector?", ["<vector>", "<array>", "<list>", "<iostream>"], 0),
            run("Read n, then n numbers into a vector. Print them in reverse order separated by spaces.", "cpp",
                [t("5 numbers", stdin="5\n1 2 3 4 5"), t("one", stdin="1\n9")], ["5 4 3 2 1", "9"],
                prog('int n;\nstd::cin >> n;\nstd::vector<int> v(n);\nfor (int i = 0; i < n; i++) {\n    std::cin >> v[i];\n}\nfor (int i = n - 1; i >= 0; i--) {\n    std::cout << v[i] << (i > 0 ? " " : "\\n");\n}',
                     "#include <iostream>\n#include <vector>\n"),
                starter=STARTER, require=[r"std::vector|vector<"], fallback=[r"vector\s*<\s*int\s*>", r"\bfor\s*\("]),
        ),
        lesson(
            "Range-based for & algorithms",
            "Loop over every element directly:\n\nfor (int x : nums) {\n    std::cout << x << \" \";\n}\n\nUse auto& to modify elements in place: for (auto& x : nums) x *= 2;\n\n#include <algorithm> gives std::sort(v.begin(), v.end()), std::max_element, std::count, std::reverse …",
            mcq("What is printed?", ["2 4 6", "1 2 3", "An error", "6"], 0, code="std::vector<int> v = {1, 2, 3};\nfor (auto& x : v) x *= 2;\nfor (int x : v) std::cout << x << \" \";"),
            mcq("What is v afterwards?", ["{1, 2, 3}", "{2, 4, 6}", "{}", "An error"], 0, "Without &, x is a copy.", code="std::vector<int> v = {1, 2, 3};\nfor (auto x : v) x *= 2;"),
            fill("Sort the whole vector.", "std::sort(v.begin(), v.___());", "end"),
            mcq("Which header has std::sort?", ["<algorithm>", "<vector>", "<sort>", "<numeric>"], 0),
            run("Read n, then n numbers. Print the median (the middle value after sorting; n is odd).", "cpp",
                [t("5 numbers", stdin="5\n9 1 7 3 5"), t("3 numbers", stdin="3\n10 -2 4"), t("one", stdin="1\n42")], ["5", "4", "42"],
                prog("int n;\nstd::cin >> n;\nstd::vector<int> v(n);\nfor (auto& x : v) std::cin >> x;\nstd::sort(v.begin(), v.end());\nstd::cout << v[n / 2] << \"\\n\";",
                     "#include <algorithm>\n#include <iostream>\n#include <vector>\n"),
                starter=STARTER, require=[r"sort\("], fallback=[r"std::sort\s*\(|sort\s*\(", r"n\s*/\s*2"]),
        ),
        lesson(
            "String methods",
            "std::string has many helpers:\n\nstd::string s = \"hello world\";\ns.find(\"world\")        // 6 (or std::string::npos if absent)\ns.replace(0, 5, \"HELLO\") // \"HELLO world\"\ns.substr(6)              // \"world\"\nstd::toupper(c)         // one char to upper (from <cctype>)\nstd::to_string(42)      // \"42\"\nstd::stoi(\"42\")         // 42",
            mcq("What does s.find(\"z\") return if \"z\" is missing?", ["std::string::npos", "-1 as an int", "0", "An exception"], 0),
            fill("Turn the number 7 into a string.", "std::string s = std::___(7);", "to_string"),
            mcq("What is std::stoi(\"12\") + 1?", ["13", "121", "An error", "\"13\""], 0),
            mcq("What is s.substr(2) for s = \"coding\"?", ['"ding"', '"co"', '"odin"', '"di"'], 0),
            run("Read a line and print how many vowels (a, e, i, o, u - either case) it contains.", "cpp",
                [t("Hello World", stdin="Hello World"), t("rhythm", stdin="rhythm"), t("AEIOU aeiou", stdin="AEIOU aeiou")], ["3", "0", "10"],
                prog('std::string line;\nstd::getline(std::cin, line);\nint count = 0;\nfor (char c : line) {\n    char l = std::tolower(c);\n    if (l == \'a\' || l == \'e\' || l == \'i\' || l == \'o\' || l == \'u\') count++;\n}\nstd::cout << count << "\\n";',
                     "#include <cctype>\n#include <iostream>\n#include <string>\n"),
                starter=STARTER, fallback=[r"getline\s*\(", r"'a'|\"aeiou\"|\"AEIOU", r"\bfor\s*\("]),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Classes",
        lesson(
            "Classes & objects",
            "A class groups data (members) and functions (methods):\n\nclass Dog {\npublic:\n    std::string name;\n    void bark() {\n        std::cout << name << \" says woof\\n\";\n    }\n};   // <- note the semicolon!\n\nDog d;\nd.name = \"Rex\";\nd.bark();",
            mcq("What's easy to forget after a class definition?", ["The semicolon ;", "A return", "main()", "#include"], 0),
            fill("Members after this label can be used outside the class.", "class A {\n___:\n    int x;\n};", "public"),
            mcq("What is the default access in a class?", ["private", "public", "protected", "none"], 0),
            mcq("How do you call bark on object d?", ["d.bark();", "d->bark;", "bark(d);", "Dog.bark();"], 0),
            run("Write class Counter with a private int count = 0, void increment() and int get() const. main reads n, increments n times and prints get().", "cpp",
                [t("3", stdin="3"), t("0", stdin="0")], ["3", "0"],
                prog("int n;\nstd::cin >> n;\nCounter c;\nfor (int i = 0; i < n; i++) c.increment();\nstd::cout << c.get() << \"\\n\";",
                     before="class Counter {\nprivate:\n    int count = 0;\n\npublic:\n    void increment() {\n        count++;\n    }\n    int get() const {\n        return count;\n    }\n};\n\n"),
                starter=STARTER, require=[r"class\s+Counter", r"private"], fallback=[r"class\s+Counter", r"void\s+increment\s*\(\s*\)", r"int\s+get\s*\(\s*\)"]),
        ),
        lesson(
            "Constructors",
            "A constructor initialises an object. The member initializer list is the idiomatic way:\n\nclass Point {\npublic:\n    int x, y;\n    Point(int x, int y) : x(x), y(y) {}\n};\n\nPoint p(3, 4);   // or Point p{3, 4};",
            mcq("What does a constructor return?", ["Nothing - it has no return type", "void", "The object", "int"], 0),
            fill("Initialise member x from parameter x.", "Point(int x) ___ x(x) {}", ":"),
            mcq("When is the constructor called?", ["When the object is created", "When main ends", "When a method is called", "Never automatically"], 0),
            order("Order the class.", ["class Cat {", "public:", "    std::string name;", "    Cat(std::string n) : name(n) {}", "};"]),
            run("Write class Fraction with a constructor Fraction(int n, int d) and a method double value() const. main reads n and d and prints value() with 3 decimals.", "cpp",
                [t("1 4", stdin="1 4"), t("2 3", stdin="2 3")], ["0.250", "0.667"],
                prog("int n, d;\nstd::cin >> n >> d;\nFraction f(n, d);\nstd::cout << std::fixed << std::setprecision(3) << f.value() << \"\\n\";",
                     "#include <iomanip>\n#include <iostream>\n",
                     before="class Fraction {\n    int num, den;\n\npublic:\n    Fraction(int n, int d) : num(n), den(d) {}\n    double value() const {\n        return static_cast<double>(num) / den;\n    }\n};\n\n"),
                starter=STARTER, require=[r"class\s+Fraction", r"Fraction\s*\(\s*int"], fallback=[r"class\s+Fraction", r"Fraction\s*\(\s*int\s+\w+\s*,\s*int\s+\w+\s*\)", r"double\s+value\s*\("]),
        ),
        lesson(
            "Inheritance & virtual",
            "A class can derive from another. Mark methods virtual so derived classes can override them:\n\nclass Shape {\npublic:\n    virtual double area() const { return 0; }\n    virtual ~Shape() = default;\n};\n\nclass Square : public Shape {\n    double s;\npublic:\n    Square(double s) : s(s) {}\n    double area() const override { return s * s; }\n};",
            mcq("Which keyword lets a derived class override a method through a base pointer?", ["virtual", "override", "static", "friend"], 0),
            fill("Square inherits publicly from Shape.", "class Square ___ public Shape { };", ":"),
            mcq("What does override do?", ["Makes the compiler check that you really override a base method", "Creates a new method", "Makes it private", "Nothing"], 0),
            mcq("Why give a base class a virtual destructor?", ["So deleting through a base pointer cleans up correctly", "It's faster", "It's required for all classes", "To prevent inheritance"], 0),
            run("Write Shape (virtual double area() const) with derived Circle(r) and Rect(w, h). main stores new Circle(1) and new Rect(2, 3) in a std::vector<Shape*>, prints each area with 2 decimals, then deletes them.",
                "cpp", [t("Run")], ["3.14\n6.00"],
                "#include <iomanip>\n#include <iostream>\n#include <vector>\n\nclass Shape {\npublic:\n    virtual double area() const { return 0; }\n    virtual ~Shape() = default;\n};\n\nclass Circle : public Shape {\n    double r;\n\npublic:\n    Circle(double r) : r(r) {}\n    double area() const override { return 3.14159265 * r * r; }\n};\n\nclass Rect : public Shape {\n    double w, h;\n\npublic:\n    Rect(double w, double h) : w(w), h(h) {}\n    double area() const override { return w * h; }\n};\n\nint main() {\n    std::vector<Shape*> shapes = {new Circle(1), new Rect(2, 3)};\n    std::cout << std::fixed << std::setprecision(2);\n    for (Shape* s : shapes) {\n        std::cout << s->area() << \"\\n\";\n        delete s;\n    }\n    return 0;\n}\n",
                starter=STARTER, require=[r"virtual", r":\s*public\s+Shape"], fallback=[r"virtual\s+double\s+area", r"class\s+Circle\s*:\s*public\s+Shape", r"class\s+Rect\s*:\s*public\s+Shape"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Pointers & the STL",
        lesson(
            "Pointers",
            "A pointer stores a memory address:\n\nint x = 10;\nint* p = &x;    // & = address of x\nstd::cout << *p;  // 10  (* = value at the address)\n*p = 20;          // changes x to 20\n\nnullptr means 'points nowhere'. Prefer references and smart pointers in modern C++, but pointers are everywhere in real code.",
            mcq("What does &x give?", ["The address of x", "The value of x", "A copy of x", "x doubled"], 0),
            mcq("What is x afterwards?", ["20", "10", "An address", "An error"], 0, code="int x = 10;\nint* p = &x;\n*p = 20;"),
            fill("A pointer that points nowhere.", "int* p = ___;", "nullptr"),
            mcq("With int* p = &x;, what does *p mean?", ["The value stored at the address in p", "The address of p", "p multiplied", "A new int"], 0),
            run("Write void doubleIt(int* p) that doubles the value p points to. main reads a number, calls doubleIt(&n) twice and prints n.", "cpp",
                [t("5", stdin="5"), t("-3", stdin="-3")], ["20", "-12"],
                prog("int n;\nstd::cin >> n;\ndoubleIt(&n);\ndoubleIt(&n);\nstd::cout << n << \"\\n\";", before="void doubleIt(int* p) {\n    *p *= 2;\n}\n\n"),
                starter=STARTER, require=[r"doubleIt\s*\(\s*int\s*\*", r"&n"], fallback=[r"void\s+doubleIt\s*\(\s*int\s*\*\s*\w+\s*\)", r"\*\s*\w+\s*\*=|\*\s*\w+\s*=\s*\*", r"doubleIt\(\s*&n\s*\)"]),
        ),
        lesson(
            "std::map",
            "#include <map> for key → value lookups, kept sorted by key:\n\nstd::map<std::string, int> ages;\nages[\"Ada\"] = 36;\nages.count(\"Bob\")   // 0 (not present)\nfor (const auto& [name, age] : ages) {\n    std::cout << name << \" \" << age << \"\\n\";\n}\n\nstd::unordered_map is faster but unordered.",
            mcq("In what order does a std::map iterate?", ["Sorted by key", "Insertion order", "Random", "Sorted by value"], 0),
            mcq("What happens when you read m[\"new\"] for a missing key?", ["It inserts the key with a default value (0 for int)", "An exception", "Undefined behaviour", "Returns -1"], 0),
            fill("Check whether key k exists.", "if (m.___(k) > 0) { }", "count"),
            mcq("Which header provides std::map?", ["<map>", "<dictionary>", "<unordered>", "<vector>"], 0),
            run("Read words until end of input and print each distinct word with its count, in alphabetical order, as: word count", "cpp",
                [t("repeats", stdin="the cat and the hat"), t("single", stdin="zebra")], ["and 1\ncat 1\nhat 1\nthe 2", "zebra 1"],
                prog('std::map<std::string, int> counts;\nstd::string w;\nwhile (std::cin >> w) {\n    counts[w]++;\n}\nfor (const auto& [word, c] : counts) {\n    std::cout << word << " " << c << "\\n";\n}',
                     "#include <iostream>\n#include <map>\n#include <string>\n"),
                starter=STARTER, require=[r"map\s*<"], fallback=[r"std::map\s*<|map\s*<", r"while\s*\(\s*(std::)?cin\s*>>"]),
        ),
        lesson(
            "Smart pointers & RAII",
            "Manual new/delete is easy to get wrong. Smart pointers free memory automatically when they go out of scope (RAII):\n\n#include <memory>\nauto p = std::make_unique<int>(42);\nstd::cout << *p;   // 42\n// no delete needed\n\nstd::shared_ptr allows several owners; the object is freed when the last one goes away.",
            mcq("What does std::unique_ptr do when it goes out of scope?", ["Deletes the object it owns", "Nothing", "Copies the object", "Throws"], 0),
            fill("Create a unique_ptr to a new int holding 5.", "auto p = std::___<int>(5);", "make_unique"),
            mcq("What does RAII stand for (roughly)?", ["Resources are tied to object lifetimes", "Random Access Is Instant", "Run All Inline Instructions", "A kind of loop"], 0),
            mcq("Can you copy a std::unique_ptr?", ["No - it can only be moved", "Yes", "Only if const", "Only with new"], 0),
            run("Create a std::vector<std::unique_ptr<std::string>> with three names read from input, then print them joined by \", \" (no manual new/delete).", "cpp",
                [t("three", stdin="Ada Grace Linus")], ["Ada, Grace, Linus"],
                prog('std::vector<std::unique_ptr<std::string>> names;\nstd::string s;\nfor (int i = 0; i < 3 && std::cin >> s; i++) {\n    names.push_back(std::make_unique<std::string>(s));\n}\nfor (size_t i = 0; i < names.size(); i++) {\n    std::cout << *names[i] << (i + 1 < names.size() ? ", " : "\\n");\n}',
                     "#include <iostream>\n#include <memory>\n#include <string>\n#include <vector>\n"),
                starter=STARTER, require=[r"make_unique"], forbid=[r"\bnew\s+std::string|\bdelete\b"],
                fallback=[r"unique_ptr\s*<\s*std::string\s*>", r"make_unique"]),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
    EXPERT,
    EXPERT2,
)
