"""C++ - Intermediate and Advanced sections (units 9-16). Runnable code targets C++17."""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit

STARTER = "#include <iostream>\n\nint main() {\n    \n    return 0;\n}\n"


def prog(body: str, includes: str = "#include <iostream>\n", before: str = "") -> str:
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"{includes}\n{before}int main() {{\n{inner}\n    return 0;\n}}\n"


INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · STL containers",
        lesson(
            "std::map & std::set",
            "std::map<K, V> keeps keys SORTED; std::set<T> keeps unique sorted values:\n\nstd::map<std::string, int> age;\nage[\"ada\"] = 36;               // insert or update\nif (age.count(\"bo\")) { ... }   // exists?\nfor (const auto& [name, a] : age) std::cout << name << a;   // C++17 structured binding\n\nstd::set<int> s{3, 1, 3};       // {1, 3}\n\nstd::unordered_map / unordered_set are hash-based: faster, but unordered.",
            mcq("What order does std::map iterate in?", ["Sorted by key", "Insertion order", "Random", "Sorted by value"], 0),
            mcq("What does m[\"x\"] do if \"x\" isn't in the map?", ["Inserts it with a default value", "Throws", "Returns null", "Nothing"], 0),
            fill("C++17 structured binding over a map.", "for (const auto& [key, ___] : m) { }", "value"),
            mcq("What is std::set<int>{5, 1, 5, 3}.size()?", ["3", "4", "2", "1"], 0),
            run("Read words until end of input and print each distinct word with its count in alphabetical order as word count, one per line.", "cpp",
                [t("repeats", stdin="b a c a b a"), t("one", stdin="solo")], ["a 3\nb 2\nc 1", "solo 1"],
                prog("std::map<std::string, int> counts;\nstd::string w;\nwhile (std::cin >> w) counts[w]++;\nfor (const auto& [word, n] : counts) std::cout << word << \" \" << n << \"\\n\";",
                     includes="#include <iostream>\n#include <map>\n#include <string>\n"),
                starter=STARTER, require=[r"std::map|\bmap\s*<"], fallback=[r"map\s*<\s*(std::)?string\s*,\s*int\s*>", r"while\s*\(\s*(std::)?cin\s*>>"]),
        ),
        lesson(
            "pair, stack & queue",
            "std::pair<A, B> holds two values: auto p = std::make_pair(\"ada\", 36); p.first, p.second. Pairs compare by first, then second.\n\nContainer adapters:\nstd::stack<int> s;  s.push(1); s.top(); s.pop();\nstd::queue<int> q;  q.push(1); q.front(); q.pop();\nstd::priority_queue<int> pq;   // largest on top\n\nNote: pop() returns void - read top()/front() first.",
            mcq("What does std::stack::pop() return?", ["void - use top() first", "The top element", "A bool", "A pair"], 0),
            mcq("Which element is on top of std::priority_queue<int> by default?", ["The largest", "The smallest", "The newest", "The oldest"], 0),
            fill("Access the second value of a pair.", "int age = p.___;", "second"),
            mcq("How do pairs compare?", ["By first, then by second", "By second only", "By address", "They can't"], 0),
            run("Read n and then n numbers. Using std::priority_queue, print the 3 largest in descending order separated by spaces (fewer if n < 3).", "cpp",
                [t("6", stdin="6\n4 9 1 7 3 9"), t("2", stdin="2\n5 8")], ["9 9 7", "8 5"],
                prog("int n;\nstd::cin >> n;\nstd::priority_queue<int> pq;\nfor (int i = 0; i < n; i++) {\n    int x;\n    std::cin >> x;\n    pq.push(x);\n}\nfor (int i = 0; i < 3 && !pq.empty(); i++) {\n    if (i) std::cout << \" \";\n    std::cout << pq.top();\n    pq.pop();\n}\nstd::cout << \"\\n\";",
                     includes="#include <iostream>\n#include <queue>\n"),
                starter=STARTER, require=[r"priority_queue"], fallback=[r"priority_queue\s*<", r"\.top\(\)"]),
        ),
        lesson(
            "Custom sorting",
            "std::sort takes an optional comparator - any callable returning true when a should come BEFORE b:\n\nstruct Player { std::string name; int score; };\nstd::sort(v.begin(), v.end(), [](const Player& a, const Player& b) {\n    if (a.score != b.score) return a.score > b.score;   // high first\n    return a.name < b.name;                              // tie: by name\n});\n\nstd::stable_sort keeps equal elements in their original order.",
            mcq("What must a comparator return for a before b?", ["true", "false", "-1", "0"], 0),
            mcq("Which sort preserves the order of equal elements?", ["std::stable_sort", "std::sort", "std::partial_sort", "std::nth_element"], 0),
            fill("Sort a vector descending.", "std::sort(v.begin(), v.end(), std::___<int>());", "greater"),
            mcq("Why pass const Player& in the comparator?", ["Avoid copying and prevent changes", "It's required", "To sort faster always", "To allow modification"], 0),
            run("Read lines 'name score' until end of input into a vector of structs. Sort by score descending, ties by name ascending, and print name:score lines.", "cpp",
                [t("ties", stdin="ada 90\nbo 95\ncy 90\ndi 70")], ["bo:95\nada:90\ncy:90\ndi:70"],
                prog("std::vector<Player> v;\nPlayer p;\nwhile (std::cin >> p.name >> p.score) v.push_back(p);\nstd::sort(v.begin(), v.end(), [](const Player& a, const Player& b) {\n    if (a.score != b.score) return a.score > b.score;\n    return a.name < b.name;\n});\nfor (const auto& x : v) std::cout << x.name << \":\" << x.score << \"\\n\";",
                     includes="#include <algorithm>\n#include <iostream>\n#include <string>\n#include <vector>\n",
                     before="struct Player {\n    std::string name;\n    int score;\n};\n\n"),
                starter=STARTER, require=[r"sort\s*\("], fallback=[r"struct\s+\w+", r"sort\s*\([^;]*\[\s*\]"]),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · References & memory",
        lesson(
            "References & const",
            "A reference is another name for an existing variable:\n\nvoid doubleIt(int& x) { x *= 2; }   // changes the caller's variable\nint n = 5; doubleIt(n);              // n is 10\n\nPass large objects by const reference to avoid copies without allowing changes:\nint total(const std::vector<int>& v);\n\nA const member function promises not to change the object: int size() const;",
            mcq("What does void f(int& x) allow?", ["f changes the caller's variable", "Nothing - it copies", "Only reading x", "Passing a pointer"], 0),
            mcq("Why use const std::vector<int>& for a parameter?", ["No copy, and no modification", "It's faster to write", "It allows resize", "It's required"], 0),
            fill("Declare a member function that doesn't modify the object.", "int size() ___;", "const"),
            mcq("Can a reference be re-bound to another variable?", ["No", "Yes", "Only const ones", "Only in loops"], 0),
            run("Write void minmax(const std::vector<int>& v, int& lo, int& hi) that sets lo and hi through references. main reads n numbers and prints lo hi.", "cpp",
                [t("mixed", stdin="5\n4 -2 9 0 3"), t("one", stdin="1\n7")], ["-2 9", "7 7"],
                prog("int n;\nstd::cin >> n;\nstd::vector<int> v(n);\nfor (int& x : v) std::cin >> x;\nint lo, hi;\nminmax(v, lo, hi);\nstd::cout << lo << \" \" << hi << \"\\n\";",
                     includes="#include <iostream>\n#include <vector>\n",
                     before="void minmax(const std::vector<int>& v, int& lo, int& hi) {\n    lo = hi = v[0];\n    for (int x : v) {\n        if (x < lo) lo = x;\n        if (x > hi) hi = x;\n    }\n}\n\n"),
                starter=STARTER, require=[r"int\s*&\s*\w+\s*,\s*int\s*&"], fallback=[r"const\s+(std::)?vector<int>\s*&", r"int\s*&\s*lo"]),
        ),
        lesson(
            "Dynamic memory",
            "new allocates on the heap; you must delete it yourself:\n\nint* p = new int(42);   delete p;\nint* arr = new int[n];  delete[] arr;   // [] for arrays!\n\nForgetting delete leaks memory; deleting twice is undefined behaviour. In modern C++ you rarely write new/delete - use std::vector, std::string, or smart pointers (Unit 14) instead. This is RAII: resources are tied to object lifetimes.",
            mcq("How do you free memory from new int[10]?", ["delete[] p;", "delete p;", "free(p);", "It frees itself"], 0),
            mcq("What is a memory leak?", ["Allocated memory that's never freed", "Reading past an array", "A null pointer", "Stack overflow"], 0),
            fill("Allocate an array of n ints.", "int* a = ___ int[n];", "new"),
            mcq("What does RAII mean in practice?", ["Objects release their resources in their destructors", "Always use new", "Never use classes", "Use global variables"], 0),
            run("Read n and n ints into a dynamically allocated array (new int[n]), print them in reverse separated by spaces, then free it with delete[].", "cpp",
                [t("4", stdin="4\n1 2 3 4"), t("1", stdin="1\n9")], ["4 3 2 1", "9"],
                prog("int n;\nstd::cin >> n;\nint* a = new int[n];\nfor (int i = 0; i < n; i++) std::cin >> a[i];\nfor (int i = n - 1; i >= 0; i--) std::cout << a[i] << (i ? \" \" : \"\\n\");\ndelete[] a;"),
                starter=STARTER, require=[r"new\s+int\s*\[", r"delete\s*\[\s*\]"], fallback=[r"new\s+int\s*\[", r"delete\s*\[\s*\]"]),
        ),
        lesson(
            "Constructors & destructors",
            "A destructor (~ClassName) runs automatically when an object's lifetime ends - perfect for cleanup:\n\nclass Logger {\npublic:\n    Logger(std::string n) : name(n) { std::cout << \"start \" << name << \"\\n\"; }\n    ~Logger() { std::cout << \"end \" << name << \"\\n\"; }\nprivate:\n    std::string name;\n};\n\nLocal objects are destroyed in REVERSE order of construction when their scope ends. The `: name(n)` part is a member initializer list.",
            mcq("When does a local object's destructor run?", ["When it goes out of scope", "Never", "At program start", "Only with delete"], 0),
            mcq("In which order are locals a then b destroyed?", ["b, then a", "a, then b", "Random", "Together"], 0),
            fill("Destructor of class Logger.", "___Logger() { }", "~"),
            mcq("What is `: name(n)` in a constructor?", ["A member initializer list", "Inheritance", "A cast", "A lambda"], 0),
            run("Write class Scope that prints 'enter <name>' in its constructor and 'exit <name>' in its destructor. In main create Scope a(\"outer\"), then in an inner { } block create Scope b(\"inner\") and print 'work'. After the block print 'done'.", "cpp",
                [t("Run")], ["enter outer\nenter inner\nwork\nexit inner\ndone\nexit outer"],
                prog("Scope a(\"outer\");\n{\n    Scope b(\"inner\");\n    std::cout << \"work\\n\";\n}\nstd::cout << \"done\\n\";",
                     includes="#include <iostream>\n#include <string>\n",
                     before="class Scope {\npublic:\n    explicit Scope(std::string n) : name(std::move(n)) {\n        std::cout << \"enter \" << name << \"\\n\";\n    }\n    ~Scope() {\n        std::cout << \"exit \" << name << \"\\n\";\n    }\n\nprivate:\n    std::string name;\n};\n\n"),
                starter=STARTER, require=[r"~\s*Scope\s*\("], fallback=[r"~\s*Scope\s*\(", r"class\s+Scope"]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Classes in depth",
        lesson(
            "Operator overloading",
            "Give your types natural syntax:\n\nstruct Vec { double x, y; };\nVec operator+(const Vec& a, const Vec& b) { return {a.x + b.x, a.y + b.y}; }\nbool operator==(const Vec& a, const Vec& b) { return a.x == b.x && a.y == b.y; }\nstd::ostream& operator<<(std::ostream& os, const Vec& v) {\n    return os << \"(\" << v.x << \", \" << v.y << \")\";\n}\n\nOnly overload when the meaning is obvious.",
            mcq("What should operator<< for output return?", ["The ostream reference", "void", "A string", "bool"], 0),
            fill("Declare the + operator for Vec.", "Vec ___+(const Vec& a, const Vec& b);", "operator"),
            mcq("Which is a good use of operator overloading?", ["+ for adding vectors", "+ to delete a file", "== to print", "<< to sort"], 0),
            mcq("Why return os from operator<<?", ["So outputs can be chained: cout << a << b", "It's faster", "To close the stream", "No reason"], 0),
            run("Write struct Fraction {int n, d;} with operator+ (reduced using std::gcd) and operator<< printing n/d. main reads a b c d and prints a/b + c/d.", "cpp",
                [t("halves", stdin="1 2 1 3"), t("reduce", stdin="1 4 1 4")], ["5/6", "1/2"],
                prog("int a, b, c, d;\nstd::cin >> a >> b >> c >> d;\nstd::cout << Fraction{a, b} + Fraction{c, d} << \"\\n\";",
                     includes="#include <iostream>\n#include <numeric>\n",
                     before="struct Fraction {\n    int n, d;\n};\n\nFraction operator+(const Fraction& a, const Fraction& b) {\n    int n = a.n * b.d + b.n * a.d, d = a.d * b.d;\n    int g = std::gcd(n, d);\n    return {n / g, d / g};\n}\n\nstd::ostream& operator<<(std::ostream& os, const Fraction& f) {\n    return os << f.n << \"/\" << f.d;\n}\n\n"),
                starter=STARTER, require=[r"operator\s*\+", r"operator\s*<<"], fallback=[r"operator\s*\+\s*\(", r"operator\s*<<\s*\("]),
        ),
        lesson(
            "Inheritance & virtual",
            "Mark a method virtual so calls through a base pointer/reference use the derived version:\n\nclass Shape {\npublic:\n    virtual double area() const = 0;   // pure virtual: abstract\n    virtual ~Shape() = default;          // ALWAYS virtual destructor in a base\n};\nclass Circle : public Shape {\n    double r;\npublic:\n    Circle(double r) : r(r) {}\n    double area() const override { return 3.14159 * r * r; }\n};",
            mcq("What does = 0 after a virtual function mean?", ["Pure virtual - subclasses must implement it", "Returns 0", "It's disabled", "It's static"], 0),
            mcq("Why should a base class have a virtual destructor?", ["So deleting via a base pointer runs the derived destructor", "For speed", "It's required to compile", "To prevent copying"], 0),
            fill("Mark that a method overrides a base virtual method.", "double area() const ___ { }", "override"),
            mcq("What happens if area() is NOT virtual and called through Shape&?", ["Shape's version runs", "Circle's version runs", "Compile error", "Crash"], 0),
            run("Write abstract class Animal with pure virtual std::string sound() const and a name. Dog says Woof, Cat says Meow. main stores std::unique_ptr<Animal> in a vector and prints name: sound for Rex (dog) and Tom (cat).", "cpp",
                [t("Run")], ["Rex: Woof\nTom: Meow"],
                prog("std::vector<std::unique_ptr<Animal>> zoo;\nzoo.push_back(std::make_unique<Dog>(\"Rex\"));\nzoo.push_back(std::make_unique<Cat>(\"Tom\"));\nfor (const auto& a : zoo) std::cout << a->name << \": \" << a->sound() << \"\\n\";",
                     includes="#include <iostream>\n#include <memory>\n#include <string>\n#include <vector>\n",
                     before="class Animal {\npublic:\n    explicit Animal(std::string n) : name(std::move(n)) {}\n    virtual ~Animal() = default;\n    virtual std::string sound() const = 0;\n    std::string name;\n};\n\nclass Dog : public Animal {\npublic:\n    using Animal::Animal;\n    std::string sound() const override { return \"Woof\"; }\n};\n\nclass Cat : public Animal {\npublic:\n    using Animal::Animal;\n    std::string sound() const override { return \"Meow\"; }\n};\n\n"),
                starter=STARTER, require=[r"virtual"], fallback=[r"virtual\s+std::string\s+sound\s*\(\s*\)\s*const\s*=\s*0", r":\s*public\s+Animal"]),
        ),
        lesson(
            "Static members & the rule of three",
            "static members are shared by all objects: static int count; (define it outside: int Widget::count = 0; or use inline static in C++17).\n\nRule of three: if a class needs a custom destructor, copy constructor OR copy assignment, it probably needs all three - typically because it owns raw memory. Better: own resources through std::vector / smart pointers so the defaults just work (rule of zero).",
            mcq("What does the rule of zero recommend?", ["Use members that manage themselves so you write none of the special functions", "Write all five", "Never use classes", "Avoid constructors"], 0),
            fill("C++17 in-class definition of a shared counter.", "inline ___ int count = 0;", "static"),
            mcq("Which three functions does the rule of three name?", ["Destructor, copy constructor, copy assignment", "Constructor, getter, setter", "new, delete, sizeof", "main, init, exit"], 0),
            mcq("Why is a default copy dangerous for a class holding a raw owning pointer?", ["Both copies delete the same memory", "It's slow", "It doesn't compile", "It isn't"], 0),
            run("Write class Widget with a C++17 inline static live counter: +1 in the constructor, -1 in the destructor, and static int live(). main: create a, then in a block create b and c and print live(), then print live() after the block.", "cpp",
                [t("Run")], ["3\n1"],
                prog("Widget a;\n{\n    Widget b, c;\n    std::cout << Widget::live() << \"\\n\";\n}\nstd::cout << Widget::live() << \"\\n\";",
                     before="class Widget {\npublic:\n    Widget() { ++count; }\n    ~Widget() { --count; }\n    static int live() { return count; }\n\nprivate:\n    inline static int count = 0;\n};\n\n"),
                starter=STARTER, require=[r"static"], fallback=[r"static\s+int", r"~\s*Widget"]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Streams & strings",
        lesson(
            "stringstream",
            "<sstream> lets you treat a string like a stream:\n\nstd::istringstream in(\"3 4 5\");\nint x, sum = 0;\nwhile (in >> x) sum += x;            // 12\n\nstd::ostringstream out;\nout << \"id-\" << 42;\nstd::string s = out.str();           // \"id-42\"\n\nstd::getline(stream, line, ',') splits on a delimiter.",
            mcq("Which class builds a string with <<?", ["std::ostringstream", "std::istringstream", "std::string", "std::cin"], 0),
            fill("Get the built string.", "std::string s = out.___();", "str"),
            mcq("What does std::getline(ss, part, ',') do?", ["Reads up to the next comma", "Reads a whole file", "Splits on spaces", "Writes a comma"], 0),
            mcq("Which header provides stringstreams?", ["<sstream>", "<string>", "<iostream>", "<fstream>"], 0),
            run("Read one line of comma-separated integers (e.g. 3,10,-2). Print the count and sum as count=… sum=…", "cpp",
                [t("csv", stdin="3,10,-2,7"), t("one", stdin="42")], ["count=4 sum=18", "count=1 sum=42"],
                prog("std::string line, part;\nstd::getline(std::cin, line);\nstd::istringstream in(line);\nint count = 0, sum = 0;\nwhile (std::getline(in, part, ',')) {\n    count++;\n    sum += std::stoi(part);\n}\nstd::cout << \"count=\" << count << \" sum=\" << sum << \"\\n\";",
                     includes="#include <iostream>\n#include <sstream>\n#include <string>\n"),
                starter=STARTER, require=[r"stringstream"], fallback=[r"istringstream|stringstream", r"getline\s*\([^)]*','"]),
        ),
        lesson(
            "Formatting with iomanip",
            "<iomanip> controls number and column formatting:\n\nstd::cout << std::fixed << std::setprecision(2) << 3.14159;   // 3.14\nstd::cout << std::setw(6) << 42;                                // \"    42\"\nstd::cout << std::left << std::setw(8) << \"name\" << \"|\";     // \"name    |\"\nstd::cout << std::setfill('0') << std::setw(3) << 7;           // 007\n\nsetw applies only to the NEXT item; the others are sticky.",
            mcq("Does std::setw apply to all following outputs?", ["No - only the next one", "Yes", "Only to numbers", "Only with fixed"], 0),
            fill("Show two digits after the decimal point.", "std::cout << std::fixed << std::___(2) << x;", "setprecision"),
            mcq("What does std::setfill('0') << std::setw(3) << 7 print?", ["007", "7", "700", "  7"], 0),
            mcq("Which manipulator left-aligns in a column?", ["std::left", "std::right", "std::fixed", "std::setw"], 0),
            run("Read lines 'item price qty' until end of input and print a receipt: item left-aligned in 8 chars, then the line total with 2 decimals right-aligned in 8 chars. Finish with TOTAL formatted the same way.", "cpp",
                [t("receipt", stdin="tea 2.5 2\ncake 3.25 1")], ["tea         5.00\ncake        3.25\nTOTAL       8.25"],
                prog("std::string item;\ndouble price, total = 0;\nint qty;\nstd::cout << std::fixed << std::setprecision(2);\nwhile (std::cin >> item >> price >> qty) {\n    double line = price * qty;\n    total += line;\n    std::cout << std::left << std::setw(8) << item << std::right << std::setw(8) << line << \"\\n\";\n}\nstd::cout << std::left << std::setw(8) << \"TOTAL\" << std::right << std::setw(8) << total << \"\\n\";",
                     includes="#include <iomanip>\n#include <iostream>\n#include <string>\n"),
                starter=STARTER, require=[r"setw", r"setprecision"], fallback=[r"setw\s*\(\s*8\s*\)", r"setprecision\s*\(\s*2\s*\)"]),
        ),
        lesson(
            "string_view & string algorithms",
            "std::string has useful members: find, substr, replace, rfind, starts with via rfind(prefix, 0) == 0 (or starts_with in C++20).\n\nstd::string_view (C++17) is a cheap, non-owning view of characters - great for read-only parameters:\nbool isPalindrome(std::string_view s);\n\nstd::string::npos means 'not found'.",
            mcq("What does s.find(\"x\") return when not found?", ["std::string::npos", "-1 as int", "0", "An exception"], 0),
            mcq("Does std::string_view own its characters?", ["No - it's just a view", "Yes", "Only for literals", "Only on the heap"], 0),
            fill("Get 3 characters starting at index 2.", "std::string part = s.___(2, 3);", "substr"),
            mcq("Danger of string_view?", ["It dangles if the viewed string is destroyed", "It's slow", "It can't be printed", "It copies everything"], 0),
            run("Read a line and replace every occurrence of 'cat' with 'dog' using find/replace in a loop, then print it.", "cpp",
                [t("many", stdin="the cat saw a cat-shaped catalog"), t("none", stdin="no pets")], ["the dog saw a dog-shaped dogalog", "no pets"],
                prog("std::string s;\nstd::getline(std::cin, s);\nstd::size_t pos = 0;\nwhile ((pos = s.find(\"cat\", pos)) != std::string::npos) {\n    s.replace(pos, 3, \"dog\");\n    pos += 3;\n}\nstd::cout << s << \"\\n\";",
                     includes="#include <iostream>\n#include <string>\n"),
                starter=STARTER, require=[r"\.find\s*\(", r"\.replace\s*\("], fallback=[r"\.find\s*\(", r"\.replace\s*\(", r"npos"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Templates",
        lesson(
            "Function templates",
            "Templates write code once for many types; the compiler generates a version per type used:\n\ntemplate <typename T>\nT biggest(const std::vector<T>& v) {\n    T best = v[0];\n    for (const T& x : v) if (x > best) best = x;\n    return best;\n}\n\nbiggest(std::vector<int>{1, 5});        // T = int\nbiggest(std::vector<std::string>{\"a\"});  // T = std::string",
            mcq("When are template versions generated?", ["At compile time, per type used", "At run time", "Never", "At link time only"], 0),
            fill("Start a function template.", "___ <typename T>\nT twice(T x) { return x + x; }", "template"),
            mcq("What does biggest require of T in the example?", ["That T supports >", "That T is a number", "Nothing", "That T is a class"], 0),
            mcq("Where should template definitions usually live?", ["In headers", "In .cpp files only", "In main", "Anywhere - it doesn't matter"], 0),
            run("Write template <typename T> void printAll(const std::vector<T>& v, const std::string& sep) printing elements joined by sep and a newline. main prints {1,2,3} with \", \" and {\"a\",\"b\"} with \"-\".", "cpp",
                [t("Run")], ["1, 2, 3\na-b"],
                prog("printAll(std::vector<int>{1, 2, 3}, \", \");\nprintAll(std::vector<std::string>{\"a\", \"b\"}, \"-\");",
                     includes="#include <iostream>\n#include <string>\n#include <vector>\n",
                     before="template <typename T>\nvoid printAll(const std::vector<T>& v, const std::string& sep) {\n    for (std::size_t i = 0; i < v.size(); i++) {\n        if (i) std::cout << sep;\n        std::cout << v[i];\n    }\n    std::cout << \"\\n\";\n}\n\n"),
                starter=STARTER, require=[r"template\s*<\s*(typename|class)"], fallback=[r"template\s*<\s*(typename|class)\s+T\s*>", r"printAll"]),
        ),
        lesson(
            "Class templates",
            "Containers are class templates:\n\ntemplate <typename T>\nclass Stack {\n    std::vector<T> items;\npublic:\n    void push(const T& x) { items.push_back(x); }\n    T pop() { T x = items.back(); items.pop_back(); return x; }\n    bool empty() const { return items.empty(); }\n};\n\nStack<int> s;  Stack<std::string> names;\n\nC++17 can often deduce the arguments: std::pair p{1, 2.5};",
            mcq("How do you create a Stack of doubles?", ["Stack<double> s;", "Stack s(double);", "Stack[double] s;", "template Stack<double>"], 0),
            fill("Declare a class template with two type parameters.", "template <typename K, ___ V>\nclass Pair { };", "typename"),
            mcq("Is std::vector a class template?", ["Yes", "No", "Only std::vector<int>", "It's a macro"], 0),
            mcq("What is class template argument deduction (C++17)?", ["The compiler infers template arguments from constructor arguments", "Run-time typing", "Inheritance", "A cast"], 0),
            run("Write template <typename T> class MinStack with push, pop, top and getMin all O(1) (keep a second vector of minimums). main pushes 5 3 7 3, prints getMin, pops twice, prints getMin and top.", "cpp",
                [t("Run")], ["3\n3 3"],
                prog("MinStack<int> s;\nfor (int x : {5, 3, 7, 3}) s.push(x);\nstd::cout << s.getMin() << \"\\n\";\ns.pop();\ns.pop();\nstd::cout << s.getMin() << \" \" << s.top() << \"\\n\";",
                     includes="#include <iostream>\n#include <vector>\n",
                     before="template <typename T>\nclass MinStack {\n    std::vector<T> items, mins;\n\npublic:\n    void push(const T& x) {\n        items.push_back(x);\n        if (mins.empty() || x <= mins.back()) mins.push_back(x);\n    }\n    void pop() {\n        if (items.back() == mins.back()) mins.pop_back();\n        items.pop_back();\n    }\n    const T& top() const { return items.back(); }\n    const T& getMin() const { return mins.back(); }\n};\n\n"),
                starter=STARTER, require=[r"template\s*<"], fallback=[r"template\s*<\s*(typename|class)\s+T\s*>\s*class\s+MinStack"]),
        ),
        lesson(
            "constexpr & auto",
            "constexpr values and functions can be computed at COMPILE time:\n\nconstexpr int square(int x) { return x * x; }\nconstexpr int N = square(12);      // 144, no run-time cost\nint arr[N];\n\nauto deduces types: auto it = m.begin();\ndecltype(expr) gives the type of an expression.\nif constexpr (std::is_integral_v<T>) { ... } picks a branch at compile time in templates.",
            mcq("What's special about a constexpr variable?", ["Its value is known at compile time", "It's mutable", "It's global", "It's on the heap"], 0),
            fill("Compile-time branch in a template.", "if ___ (std::is_integral_v<T>) { }", "constexpr"),
            mcq("What does auto x = 3.0; make x?", ["double", "float", "int", "auto"], 0),
            mcq("Can a constexpr function also run at run time?", ["Yes, with non-constant arguments", "No", "Only in templates", "Only in main"], 0),
            run("Write constexpr long long factorial(int n) and a static_assert that factorial(5) == 120. main reads n and prints factorial(n).", "cpp",
                [t("5", stdin="5"), t("20", stdin="20")], ["120", "2432902008176640000"],
                prog("int n;\nstd::cin >> n;\nstd::cout << factorial(n) << \"\\n\";",
                     before="constexpr long long factorial(int n) {\n    return n <= 1 ? 1 : n * factorial(n - 1);\n}\n\nstatic_assert(factorial(5) == 120);\n\n"),
                starter=STARTER, require=[r"constexpr", r"static_assert"], fallback=[r"constexpr\s+(long\s+long|unsigned\s+long\s+long|std::uint64_t|long)", r"static_assert"]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Modern C++",
        lesson(
            "Lambdas & captures",
            "Lambdas are inline function objects:\n\nauto add = [](int a, int b) { return a + b; };\nint bonus = 10;\nauto withBonus = [bonus](int x) { return x + bonus; };   // capture by value\nint count = 0;\nauto inc = [&count]() { count++; };                       // by reference\n\n[=] captures everything used by value, [&] by reference. std::function<int(int)> can store any callable.",
            mcq("What does [&count] capture?", ["count by reference", "count by value", "Everything", "Nothing"], 0),
            mcq("What happens to a by-value capture if the original changes later?", ["The lambda keeps its copy", "The lambda sees the change", "Compile error", "Crash"], 0),
            fill("A type that can hold any callable taking an int and returning int.", "std::___<int(int)> f;", "function"),
            mcq("What does [] mean in a lambda?", ["The capture list - empty captures nothing", "An array", "Optional args", "A template"], 0),
            run("Write std::function<int(int)> makeCounter(int start) returning a lambda that captures a counter (use mutable) and returns start, start+1… on each call. main calls a counter from 10 three times, and a second one from 0 once.", "cpp",
                [t("Run")], ["10 11 12 0"],
                prog("auto a = makeCounter(10);\nauto b = makeCounter(0);\nint x = a(0), y = a(0), z = a(0);\nstd::cout << x << \" \" << y << \" \" << z << \" \" << b(0) << \"\\n\";",
                     includes="#include <functional>\n#include <iostream>\n",
                     before="std::function<int(int)> makeCounter(int start) {\n    return [n = start](int) mutable { return n++; };\n}\n\n"),
                starter=STARTER, require=[r"\[[^\]]*\]\s*\([^)]*\)\s*mutable"], fallback=[r"mutable", r"std::function"]),
        ),
        lesson(
            "Smart pointers",
            "Smart pointers free memory automatically:\n\nstd::unique_ptr<T> - single owner; can be moved, not copied.\nauto p = std::make_unique<Node>(5);\n\nstd::shared_ptr<T> - shared ownership with a reference count; freed when the last owner goes away.\nauto a = std::make_shared<Data>();\nauto b = a;            // use_count() == 2\n\nstd::weak_ptr breaks cycles between shared_ptrs.",
            mcq("Can a std::unique_ptr be copied?", ["No - only moved", "Yes", "Only if const", "Only to shared_ptr"], 0),
            mcq("When is a shared_ptr's object deleted?", ["When the last shared_ptr to it is destroyed", "Immediately", "Never", "At program end only"], 0),
            fill("Create a shared pointer.", "auto p = std::___<int>(7);", "make_shared"),
            mcq("What solves reference cycles between shared_ptrs?", ["std::weak_ptr", "std::unique_ptr", "Raw pointers always", "delete"], 0),
            run("Make a std::shared_ptr<std::string> a holding \"hi\". Print a.use_count(), then in a block copy it to b and print the count, then print the count after the block.", "cpp",
                [t("Run")], ["1\n2\n1"],
                prog("auto a = std::make_shared<std::string>(\"hi\");\nstd::cout << a.use_count() << \"\\n\";\n{\n    auto b = a;\n    std::cout << a.use_count() << \"\\n\";\n}\nstd::cout << a.use_count() << \"\\n\";",
                     includes="#include <iostream>\n#include <memory>\n#include <string>\n"),
                starter=STARTER, require=[r"make_shared", r"use_count"], forbid=[r"<<\s*[12]\s*<<"], fallback=[r"make_shared", r"use_count\s*\(\s*\)"]),
        ),
        lesson(
            "Move semantics",
            "Moving transfers resources instead of copying them:\n\nstd::vector<int> big(1'000'000);\nstd::vector<int> other = std::move(big);   // O(1): steals the buffer; big is now empty-ish\n\nstd::move doesn't move anything itself - it casts to an rvalue reference (T&&) so the move constructor is chosen. After a move, only assign to or destroy the moved-from object.\n\nReturning local objects by value is cheap (move or copy elision).",
            mcq("What does std::move actually do?", ["Casts to an rvalue reference", "Copies memory", "Deletes the object", "Moves it to the heap"], 0),
            mcq("What can you safely do with a moved-from std::string?", ["Assign a new value or destroy it", "Rely on its old content", "Nothing at all", "Read past its end"], 0),
            fill("An rvalue reference parameter.", "void take(std::string___ s);", "&&"),
            mcq("Is returning a big local vector by value expensive?", ["No - it's moved or elided", "Yes, always a full copy", "It's not allowed", "Only with const"], 0),
            run("Create std::vector<std::string> a {\"x\", \"y\", \"z\"}. Move it into b with std::move. Print b.size(), then a.empty() as 1/0 (moved-from vectors are empty in practice), then push \"w\" to a and print a.size().", "cpp",
                [t("Run")], ["3\n1\n1"],
                prog("std::vector<std::string> a{\"x\", \"y\", \"z\"};\nstd::vector<std::string> b = std::move(a);\nstd::cout << b.size() << \"\\n\";\nstd::cout << a.empty() << \"\\n\";\na.push_back(\"w\");\nstd::cout << a.size() << \"\\n\";",
                     includes="#include <iostream>\n#include <string>\n#include <utility>\n#include <vector>\n"),
                starter=STARTER, require=[r"std::move"], fallback=[r"std::move\s*\(\s*a\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · STL algorithms",
        lesson(
            "Searching & counting",
            "<algorithm> works on iterator ranges:\n\nstd::find(v.begin(), v.end(), 7)                // iterator or end()\nstd::count_if(v.begin(), v.end(), [](int x) { return x > 0; })\nstd::any_of / all_of / none_of\nstd::min_element / max_element\nstd::binary_search / lower_bound on SORTED ranges",
            mcq("What does std::find return when the value is missing?", ["The end iterator", "nullptr", "-1", "An exception"], 0),
            fill("Count the positive values.", "int n = std::___(v.begin(), v.end(), [](int x) { return x > 0; });", "count_if"),
            mcq("What does std::lower_bound need?", ["A sorted range", "A map", "Unique values", "Nothing"], 0),
            mcq("What does *std::max_element(v.begin(), v.end()) give?", ["The largest value", "Its index", "The last value", "The size"], 0),
            run("Read n numbers. Using <algorithm> functions (no hand-written loops for the queries), print: count of evens, whether any is negative (yes/no), and the largest value.", "cpp",
                [t("mixed", stdin="6\n4 -3 8 1 6 2"), t("pos", stdin="3\n1 3 5")], ["4 yes 8", "0 no 5"],
                prog("int n;\nstd::cin >> n;\nstd::vector<int> v(n);\nfor (int& x : v) std::cin >> x;\nauto evens = std::count_if(v.begin(), v.end(), [](int x) { return x % 2 == 0; });\nbool neg = std::any_of(v.begin(), v.end(), [](int x) { return x < 0; });\nint big = *std::max_element(v.begin(), v.end());\nstd::cout << evens << \" \" << (neg ? \"yes\" : \"no\") << \" \" << big << \"\\n\";",
                     includes="#include <algorithm>\n#include <iostream>\n#include <vector>\n"),
                starter=STARTER, require=[r"count_if", r"any_of", r"max_element"], fallback=[r"count_if", r"any_of", r"max_element"]),
        ),
        lesson(
            "Transforming ranges",
            "std::transform(in.begin(), in.end(), out.begin(), f)   // map\nstd::accumulate(v.begin(), v.end(), 0)                 // sum (<numeric>)\nstd::remove_if + erase  - the erase-remove idiom\nv.erase(std::remove_if(v.begin(), v.end(), isOdd), v.end());\nstd::unique removes CONSECUTIVE duplicates (sort first).\nstd::reverse, std::rotate, std::iota fill sequences.",
            mcq("Why is erase needed after std::remove_if?", ["remove_if only shifts kept items; erase shrinks the container", "It isn't", "To sort", "To free memory immediately"], 0),
            fill("Sum a vector.", "int total = std::___(v.begin(), v.end(), 0);", "accumulate"),
            mcq("What does std::unique do on {1,1,2,1}?", ["Removes consecutive duplicates only", "Removes all duplicates", "Sorts", "Nothing"], 0),
            mcq("Which header has std::accumulate?", ["<numeric>", "<algorithm>", "<vector>", "<cmath>"], 0),
            run("Read n numbers. Sort them, remove duplicates (sort + unique + erase), square each with std::transform, and print them space-separated, then the sum with std::accumulate on the next line.", "cpp",
                [t("dups", stdin="6\n3 1 3 2 1 2"), t("one", stdin="1\n-4")], ["1 4 9\n14", "16\n16"],
                prog("int n;\nstd::cin >> n;\nstd::vector<long long> v(n);\nfor (auto& x : v) std::cin >> x;\nstd::sort(v.begin(), v.end());\nv.erase(std::unique(v.begin(), v.end()), v.end());\nstd::transform(v.begin(), v.end(), v.begin(), [](long long x) { return x * x; });\nfor (std::size_t i = 0; i < v.size(); i++) std::cout << (i ? \" \" : \"\") << v[i];\nstd::cout << \"\\n\" << std::accumulate(v.begin(), v.end(), 0LL) << \"\\n\";",
                     includes="#include <algorithm>\n#include <iostream>\n#include <numeric>\n#include <vector>\n"),
                starter=STARTER, require=[r"unique", r"transform", r"accumulate"], fallback=[r"std::unique", r"std::transform", r"std::accumulate"]),
        ),
        lesson(
            "Iterators",
            "Iterators are generalized pointers into containers:\n\nfor (auto it = v.begin(); it != v.end(); ++it) std::cout << *it;\nv.rbegin()/rend() iterate backwards.\nstd::next(it, 2), std::distance(a, b)\n\nCategories: input → forward → bidirectional (list, map) → random access (vector, deque) - std::sort needs random access.\n\nCareful: inserting into a vector can invalidate existing iterators.",
            mcq("What does *it give?", ["The element the iterator points to", "The index", "The container", "The next iterator"], 0),
            mcq("Why can't std::sort sort a std::list?", ["list iterators aren't random access (use list.sort())", "Lists can't be sorted", "It can", "Lists are const"], 0),
            fill("Iterate backwards.", "for (auto it = v.___(); it != v.rend(); ++it)", "rbegin"),
            mcq("What can happen to vector iterators after push_back?", ["They can be invalidated", "Nothing", "They point to the new item", "They become const"], 0),
            run("Read a line of words. Using reverse iterators (rbegin/rend) on a vector, print the words in reverse order separated by spaces.", "cpp",
                [t("sentence", stdin="one two three four")], ["four three two one"],
                prog("std::vector<std::string> words;\nstd::string w;\nwhile (std::cin >> w) words.push_back(w);\nfor (auto it = words.rbegin(); it != words.rend(); ++it) {\n    if (it != words.rbegin()) std::cout << \" \";\n    std::cout << *it;\n}\nstd::cout << \"\\n\";",
                     includes="#include <iostream>\n#include <string>\n#include <vector>\n"),
                starter=STARTER, require=[r"rbegin"], fallback=[r"rbegin\s*\(\s*\)", r"rend\s*\(\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Algorithms",
        lesson(
            "Graphs & BFS",
            "Store a graph as an adjacency list: std::vector<std::vector<int>> adj(n);\n\nBreadth-first search finds shortest paths in unweighted graphs:\n\nstd::vector<int> dist(n, -1);\nstd::queue<int> q; q.push(s); dist[s] = 0;\nwhile (!q.empty()) {\n    int u = q.front(); q.pop();\n    for (int v : adj[u]) if (dist[v] == -1) { dist[v] = dist[u] + 1; q.push(v); }\n}",
            mcq("Which data structure does BFS use?", ["A queue", "A stack", "A heap", "A set"], 0),
            mcq("What does BFS find in an unweighted graph?", ["Shortest paths (fewest edges)", "Longest paths", "Minimum spanning tree", "Cycles only"], 0),
            fill("An adjacency list for n nodes.", "std::vector<std::___<int>> adj(n);", "vector"),
            mcq("What's BFS's complexity?", ["O(V + E)", "O(V²) always", "O(log V)", "O(E log V)"], 0),
            run("Read n m, then m undirected edges u v (0-based). Print the BFS distance from node 0 to every node, space-separated (-1 if unreachable).", "cpp",
                [t("graph", stdin="6 5\n0 1\n0 2\n1 3\n2 3\n3 4")], ["0 1 1 2 3 -1"],
                prog("int n, m;\nstd::cin >> n >> m;\nstd::vector<std::vector<int>> adj(n);\nfor (int i = 0; i < m; i++) {\n    int u, v;\n    std::cin >> u >> v;\n    adj[u].push_back(v);\n    adj[v].push_back(u);\n}\nstd::vector<int> dist(n, -1);\nstd::queue<int> q;\nq.push(0);\ndist[0] = 0;\nwhile (!q.empty()) {\n    int u = q.front();\n    q.pop();\n    for (int v : adj[u]) {\n        if (dist[v] == -1) {\n            dist[v] = dist[u] + 1;\n            q.push(v);\n        }\n    }\n}\nfor (int i = 0; i < n; i++) std::cout << (i ? \" \" : \"\") << dist[i];\nstd::cout << \"\\n\";",
                     includes="#include <iostream>\n#include <queue>\n#include <vector>\n"),
                starter=STARTER, require=[r"queue"], fallback=[r"queue\s*<\s*int\s*>", r"\.front\(\)"]),
        ),
        lesson(
            "Binary search",
            "Binary search halves the range each step - O(log n):\n\nint lo = 0, hi = n - 1;\nwhile (lo <= hi) {\n    int mid = lo + (hi - lo) / 2;   // avoids overflow\n    if (a[mid] == x) return mid;\n    if (a[mid] < x) lo = mid + 1; else hi = mid - 1;\n}\n\n'Binary search on the answer' also solves problems like 'smallest capacity that works' when feasibility is monotonic.",
            mcq("Why write lo + (hi - lo) / 2?", ["(lo + hi) can overflow", "It's faster", "It rounds up", "Style only"], 0),
            mcq("How many steps for 1,000,000 sorted items at most?", ["About 20", "About 1000", "1,000,000", "About 500,000"], 0),
            fill("Move right when the middle is too small.", "if (a[mid] < x) lo = mid ___ 1;", "+"),
            mcq("What does 'binary search on the answer' require?", ["A monotonic yes/no check", "A sorted input array", "A graph", "Nothing"], 0),
            run("Integer square root: read n (0 ≤ n ≤ 10^18) and print floor(sqrt(n)) using binary search on the answer with unsigned long long / __int128-safe checks (no std::sqrt).", "cpp",
                [t("small", stdin="17"), t("square", stdin="144"), t("huge", stdin="1000000000000000000"), t("zero", stdin="0")], ["4", "12", "1000000000", "0"],
                prog("unsigned long long n;\nstd::cin >> n;\nunsigned long long lo = 0, hi = 2000000000ULL;\nwhile (lo < hi) {\n    unsigned long long mid = lo + (hi - lo + 1) / 2;\n    if (mid <= n / (mid ? mid : 1)) lo = mid;\n    else hi = mid - 1;\n}\nstd::cout << lo << \"\\n\";"),
                starter=STARTER, require=[r"while"], forbid=[r"sqrt"], fallback=[r"while\s*\(\s*lo\s*<", r"mid"]),
        ),
        lesson(
            "Dynamic programming",
            "Dynamic programming solves overlapping subproblems once and builds up a table:\n\nLongest common subsequence:\ndp[i][j] = a[i-1] == b[j-1] ? dp[i-1][j-1] + 1\n                            : std::max(dp[i-1][j], dp[i][j-1]);\n\nSteps: define the state, the recurrence, the base cases, the order of filling.",
            mcq("What does DP rely on?", ["Overlapping subproblems and optimal substructure", "Randomness", "Sorting", "Recursion without memory"], 0),
            mcq("LCS of \"ABCBDAB\" and \"BDCABA\" has length…", ["4", "3", "5", "6"], 0),
            fill("Base case: an empty string has LCS length…", "dp[0][j] = ___;", "0"),
            mcq("What is the time complexity of the LCS table for lengths n and m?", ["O(n·m)", "O(n + m)", "O(2^n)", "O(log n)"], 0),
            run("Coin change: read the amount and then the coin values until end of input. Print the minimum number of coins to make the amount, or -1 if impossible (bottom-up DP).", "cpp",
                [t("classic", stdin="11\n1 2 5"), t("impossible", stdin="3\n2"), t("zero", stdin="0\n1")], ["3", "-1", "0"],
                prog("int amount;\nstd::cin >> amount;\nstd::vector<int> coins;\nint c;\nwhile (std::cin >> c) coins.push_back(c);\nconst int INF = 1e9;\nstd::vector<int> dp(amount + 1, INF);\ndp[0] = 0;\nfor (int a = 1; a <= amount; a++)\n    for (int coin : coins)\n        if (coin <= a && dp[a - coin] != INF) dp[a] = std::min(dp[a], dp[a - coin] + 1);\nstd::cout << (dp[amount] == INF ? -1 : dp[amount]) << \"\\n\";",
                     includes="#include <algorithm>\n#include <iostream>\n#include <vector>\n"),
                starter=STARTER, require=[r"vector|\[\s*\w+\s*\+\s*1\s*\]"], fallback=[r"dp\s*\[", r"min"]),
        ),
    ),
)
