"""Data Structures & Algorithms - taught in Python (runs in the browser with Pyodide).

8 units: Beginner (1-4), Intermediate (5-6), Advanced (7-8). Projects are added to units 4, 6 and 8
(see projects_dsa.py).
"""
from .dsl import code, course, fill, lesson, mcq, order, run, section, t, unit

BEGINNER = section(
    "Beginner",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · Thinking in algorithms",
        lesson(
            "What is an algorithm?",
            "An algorithm is a precise, step-by-step recipe that always finishes and solves a problem.\n\nFinding the largest number:\n\n1. Remember the first number as the best so far.\n2. Look at each other number; if it's bigger, remember it instead.\n3. When you run out of numbers, the remembered one is the answer.\n\nGood algorithms are correct (right answer for EVERY input, including empty or tiny ones) and efficient (they don't waste work).",
            mcq("Which is NOT a property of an algorithm?", ["It finishes after a finite number of steps", "Each step is precise", "It must be written in Python", "It produces an answer"], 2,
                "An algorithm is an idea - you can write it in any language, or on paper."),
            mcq("What does this return for [4, 9, 2]?", ["4", "9", "2", "15"], 1,
                code="def biggest(nums):\n    best = nums[0]\n    for n in nums[1:]:\n        if n > best:\n            best = n\n    return best"),
            mcq("Which input is most likely to break a careless 'find the biggest' algorithm?", ["[3, 1, 2]", "[] (an empty list)", "[10, 20]", "[5, 5, 5]"], 1,
                "Always think about edge cases: empty input, one item, duplicates, negatives."),
            order("Order the steps of 'find the smallest number'.",
                  ["smallest = nums[0]", "for n in nums:", "    if n < smallest:", "        smallest = n", "print(smallest)"]),
            run("Read numbers on one line and print the largest WITHOUT using max().", "python",
                [t("mixed", stdin="4 9 2 7"), t("negatives", stdin="-5 -2 -9"), t("one", stdin="42")],
                ["9", "-2", "42"],
                "nums = [int(x) for x in input().split()]\nbest = nums[0]\nfor n in nums[1:]:\n    if n > best:\n        best = n\nprint(best)",
                forbid=[r"\bmax\s*\("], hint="Start with best = nums[0] and compare each number."),
        ),
        lesson(
            "Counting steps",
            "We compare algorithms by how the number of steps GROWS with the input size n - not by seconds, which depend on the computer.\n\nfor x in items:          # runs n times\n    total += x\n\nfor a in items:          # n times...\n    for b in items:      # ...n times each  ->  n * n steps\n        ...\n\nA loop that halves the problem each time (n, n/2, n/4, ... 1) runs about log2(n) times.",
            mcq("How many times does the inner line run when n = 4?", ["4", "8", "16", "2"], 2, code="for i in range(n):\n    for j in range(n):\n        count += 1"),
            mcq("Roughly how many times does this loop run for n = 1024?", ["1024", "10", "512", "32"], 1, "1024 halves 10 times to reach 1 (2^10 = 1024).",
                code="while n > 1:\n    n = n // 2"),
            mcq("Two loops one after the other, each over n items, take about…", ["n steps", "2n steps", "n² steps", "log n steps"], 1,
                "Sequential loops ADD (n + n); nested loops MULTIPLY (n × n)."),
            fill("Complete the loop so it runs exactly n times.", "for i in ___(n):", "range"),
            run("Write count_pairs(n) that RETURNS how many times a nested loop over range(n) and range(n) would run its body, by actually counting with two loops.", "python",
                [t("n=3", append="print(count_pairs(3))"), t("n=10", append="print(count_pairs(10))"), t("n=0", append="print(count_pairs(0))")],
                ["9", "100", "0"], "def count_pairs(n):\n    count = 0\n    for i in range(n):\n        for j in range(n):\n            count += 1\n    return count",
                starter="def count_pairs(n):\n    count = 0\n    # two nested loops here\n    return count\n", require=[r"for[\s\S]*for"]),
        ),
        lesson(
            "Big-O notation",
            "Big-O describes the growth rate, ignoring constants and small terms:\n\n  O(1)        constant      - list[i], dict lookup\n  O(log n)    logarithmic   - binary search\n  O(n)        linear        - one loop over the data\n  O(n log n)  linearithmic  - good sorting (sorted())\n  O(n²)       quadratic     - every pair (nested loops)\n\n3n + 5 is O(n). n² + n is O(n²). For big inputs, the lower the class, the faster.",
            mcq("What is the Big-O of 5n + 100?", ["O(5n)", "O(n)", "O(100)", "O(n²)"], 1, "Drop constants and smaller terms."),
            mcq("Which is the FASTEST growth class for large n?", ["O(n²)", "O(n)", "O(log n)", "O(n log n)"], 2),
            mcq("Looking up a key in a Python dict is on average…", ["O(1)", "O(n)", "O(log n)", "O(n²)"], 0, "Dicts and sets use hashing."),
            mcq("What is the complexity of checking every pair in a list?", ["O(n)", "O(n²)", "O(log n)", "O(1)"], 1),
            run("Write has_duplicate(nums) that returns True if any value appears twice. Make it O(n) by using a set (no nested loops).", "python",
                [t("dup", append="print(has_duplicate([3, 1, 4, 1, 5]))"), t("none", append="print(has_duplicate([1, 2, 3]))"),
                 t("empty", append="print(has_duplicate([]))")],
                ["True", "False", "False"],
                "def has_duplicate(nums):\n    seen = set()\n    for n in nums:\n        if n in seen:\n            return True\n        seen.add(n)\n    return False",
                require=[r"set\(\)|\{\s*\}|set\("], forbid=[r"for[^\n]*\n\s+for"], hint="Keep a set of numbers you've seen."),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Arrays & two pointers",
        lesson(
            "Arrays & prefix sums",
            "A Python list is a dynamic array: items sit side by side, so nums[i] is O(1).\n\nA prefix sum array answers 'sum of nums[a..b]' in O(1) after O(n) setup:\n\nprefix = [0]\nfor n in nums:\n    prefix.append(prefix[-1] + n)\n# sum of nums[a:b] == prefix[b] - prefix[a]\n\nnums = [3, 1, 4] -> prefix = [0, 3, 4, 8]",
            mcq("For nums = [2, 5, 1], what is prefix?", ["[2, 7, 8]", "[0, 2, 7, 8]", "[0, 2, 5, 1]", "[8, 6, 1]"], 1),
            mcq("With prefix = [0, 3, 4, 8, 9], what is the sum of nums[1:3]?", ["5", "4", "8", "1"], 0, "prefix[3] - prefix[1] = 8 - 3 = 5."),
            mcq("What is the cost of nums[i] in a Python list?", ["O(n)", "O(log n)", "O(1)", "O(i)"], 2),
            fill("Complete the prefix sum update.", "prefix.append(prefix[___] + n)", ["-1"]),
            run("First line: numbers. Then each following line has two indexes a b. Print the sum of nums[a:b] (b not included) for each, using a prefix sum.", "python",
                [t("queries", stdin="3 1 4 1 5 9\n0 3\n2 6\n5 6"), t("whole", stdin="10 20\n0 2\n1 1")],
                ["8\n19\n9", "30\n0"],
                "import sys\nlines = sys.stdin.read().split('\\n')\nnums = [int(x) for x in lines[0].split()]\nprefix = [0]\nfor n in nums:\n    prefix.append(prefix[-1] + n)\nfor line in lines[1:]:\n    if line.strip():\n        a, b = map(int, line.split())\n        print(prefix[b] - prefix[a])",
                require=[r"prefix"], hint="Read all lines with sys.stdin.read().split('\\n')."),
        ),
        lesson(
            "Two pointers",
            "Two pointers walk the data from two ends (or at two speeds) to avoid a nested loop.\n\nIs a string a palindrome?\n\ni, j = 0, len(s) - 1\nwhile i < j:\n    if s[i] != s[j]:\n        return False\n    i += 1\n    j -= 1\nreturn True\n\nIn a SORTED list, finding two numbers that add to a target: move the left pointer up if the sum is too small, the right one down if too big. O(n) instead of O(n²).",
            mcq("For a sorted list, the pair sum is too SMALL. What do you do?", ["Move the right pointer left", "Move the left pointer right", "Stop", "Restart"], 1,
                "Moving left to the right picks a bigger number."),
            mcq("What does is_pal('level') return with the code above?", ["True", "False", "An error", "'level'"], 0),
            mcq("Two pointers on a sorted list turn an O(n²) pair search into…", ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 0),
            order("Order the two-pointer loop.", ["i, j = 0, len(s) - 1", "while i < j:", "    if s[i] != s[j]:", "        return False", "    i, j = i + 1, j - 1", "return True"]),
            run("Write pair_sum(nums, target) for a SORTED list: return the two numbers (as a tuple, smaller first) that add up to target, or None. Use two pointers.", "python",
                [t("found", append="print(pair_sum([1, 3, 4, 6, 9], 10))"), t("ends", append="print(pair_sum([2, 5, 8], 10))"),
                 t("none", append="print(pair_sum([1, 2, 3], 100))")],
                ["(1, 9)", "(2, 8)", "None"],
                "def pair_sum(nums, target):\n    i, j = 0, len(nums) - 1\n    while i < j:\n        s = nums[i] + nums[j]\n        if s == target:\n            return (nums[i], nums[j])\n        if s < target:\n            i += 1\n        else:\n            j -= 1\n    return None",
                require=[r"while"], forbid=[r"for[^\n]*\n\s+for"]),
        ),
        lesson(
            "Sliding window",
            "A sliding window keeps a running result for a block of k neighbours, updating it as the window moves instead of re-adding everything:\n\nwindow = sum(nums[:k])\nbest = window\nfor i in range(k, len(nums)):\n    window += nums[i] - nums[i - k]   # add the new, drop the old\n    best = max(best, window)\n\nThat's O(n) instead of O(n·k).",
            mcq("When the window slides one step right, what changes?", ["Everything is recomputed", "One item is added and one is removed", "Two items are added", "Nothing"], 1),
            mcq("nums = [1, 2, 3, 4], k = 2. What is the best window sum?", ["7", "3", "10", "5"], 0, "3 + 4 = 7."),
            fill("Update the window when index i enters.", "window += nums[i] - nums[i - ___]", "k"),
            mcq("Complexity of the sliding-window maximum sum?", ["O(n·k)", "O(n)", "O(k)", "O(n²)"], 1),
            run("First line: daily step counts. Second line: k. Print the best total over any k consecutive days using a sliding window.", "python",
                [t("week", stdin="3000 8000 2000 9000 7000 1000\n3"), t("k=1", stdin="5 9 2\n1"), t("all", stdin="1 2 3\n3")],
                ["19000", "9", "6"],
                "nums = [int(x) for x in input().split()]\nk = int(input())\nwindow = sum(nums[:k])\nbest = window\nfor i in range(k, len(nums)):\n    window += nums[i] - nums[i - k]\n    best = max(best, window)\nprint(best)",
                require=[r"-\s*nums\[\s*i\s*-\s*k\s*\]"], hint="window += nums[i] - nums[i - k]"),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Hashing",
        lesson(
            "Sets for fast membership",
            "A set stores unique items and answers 'is x in here?' in O(1) on average, using a hash of x.\n\nseen = set()\nseen.add(3)\n3 in seen        # True\n\nSet algebra:\na | b   union          a & b   intersection\na - b   difference     a ^ b   in exactly one\n\nOnly hashable (immutable) things can go in a set: numbers, strings, tuples - not lists.",
            mcq("What is {1, 2, 3} & {2, 3, 4}?", ["{1, 2, 3, 4}", "{2, 3}", "{1, 4}", "{1}"], 1),
            mcq("Average cost of x in some_list vs x in some_set?", ["O(1) vs O(n)", "O(n) vs O(1)", "Both O(1)", "Both O(n)"], 1),
            mcq("Which can NOT be added to a set?", ["(1, 2)", "'hi'", "[1, 2]", "3.5"], 2, "Lists are mutable, so they aren't hashable."),
            fill("Items in a but not in b.", "only_a = a ___ b", "-"),
            run("Two lines of words. Print the words that appear in BOTH lines, sorted alphabetically, space-separated (or 'none').", "python",
                [t("common", stdin="red green blue cyan\nblue black red"), t("none", stdin="a b\nc d")],
                ["blue red", "none"],
                "a = set(input().split())\nb = set(input().split())\ncommon = sorted(a & b)\nprint(' '.join(common) if common else 'none')",
                require=[r"set\("]),
        ),
        lesson(
            "Dictionaries for counting",
            "A dict maps keys to values with O(1) average lookups - perfect for counting:\n\ncounts = {}\nfor word in words:\n    counts[word] = counts.get(word, 0) + 1\n\ncollections.Counter does the same and more:\n\nfrom collections import Counter\nCounter('banana').most_common(1)   # [('a', 3)]",
            mcq("What does counts.get('x', 0) return if 'x' isn't a key?", ["None", "An error", "0", "'x'"], 2),
            mcq("What is Counter('aab')['a']?", ["1", "2", "3", "'aa'"], 1),
            fill("Count each letter.", "counts[ch] = counts.___(ch, 0) + 1", "get"),
            mcq("Which structure answers 'how many times has X appeared?' fastest?", ["A list", "A dict", "A string", "A tuple"], 1),
            run("Read a sentence. Print the most common word (lower-case) and its count like: the 3. On a tie, pick the word that comes first alphabetically.", "python",
                [t("the", stdin="The cat and the dog and THE bird"), t("tie", stdin="b a b a c")],
                ["the 3", "a 2"],
                "words = input().lower().split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nbest = min(counts, key=lambda w: (-counts[w], w))\nprint(best, counts[best])",
                hint="min(counts, key=lambda w: (-counts[w], w)) handles the tie."),
        ),
        lesson(
            "Two-sum with a hash map",
            "Classic interview question: find two numbers in an UNSORTED list that add to target.\n\nBrute force checks every pair: O(n²). With a dict of 'value -> index' seen so far it's one pass, O(n):\n\nseen = {}\nfor i, n in enumerate(nums):\n    need = target - n\n    if need in seen:\n        return (seen[need], i)\n    seen[n] = i",
            mcq("For each number n, what do we look for in the dict?", ["n", "target", "target - n", "n * 2"], 2),
            mcq("Why store the number AFTER checking?", ["It's faster", "So a number isn't paired with itself", "Dicts require it", "It doesn't matter"], 1),
            mcq("Complexity of the hash-map two-sum?", ["O(n²)", "O(n log n)", "O(n)", "O(1)"], 2),
            order("Order the loop body.", ["need = target - n", "if need in seen:", "    return (seen[need], i)", "seen[n] = i"]),
            run("Write two_sum(nums, target) returning the pair of INDEXES (i, j) with i < j, or None. One pass with a dict.", "python",
                [t("basic", append="print(two_sum([2, 7, 11, 15], 9))"), t("later", append="print(two_sum([3, 2, 4], 6))"),
                 t("same value", append="print(two_sum([5, 5], 10))"), t("none", append="print(two_sum([1, 2], 7))")],
                ["(0, 1)", "(1, 2)", "(0, 1)", "None"],
                "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        need = target - n\n        if need in seen:\n            return (seen[need], i)\n        seen[n] = i\n    return None",
                forbid=[r"for[^\n]*\n\s+for"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Stacks & queues",
        lesson(
            "Stacks",
            "A stack is Last-In-First-Out (LIFO), like a pile of plates. A Python list works great:\n\nstack = []\nstack.append('a')   # push\nstack.append('b')\nstack.pop()         # 'b' - the last one in\nstack[-1]           # peek at the top\n\nStacks power undo, the browser back button, and checking brackets.",
            mcq("Push 1, push 2, push 3, pop. What's on top?", ["1", "2", "3", "Nothing"], 1),
            mcq("Which list method pops from the top of a list used as a stack?", ["pop(0)", "pop()", "remove()", "del"], 1, "pop() takes from the end in O(1); pop(0) is O(n)."),
            fill("Peek at the top without removing it.", "top = stack[___]", ["-1"]),
            mcq("Undo in a text editor is best modelled by a…", ["Queue", "Stack", "Set", "Dict"], 1),
            run("Write balanced(s) that returns True if every (, [ and { is closed in the right order. Ignore other characters. Use a stack.", "python",
                [t("ok", append="print(balanced('(a[b]{c})'))"), t("wrong order", append="print(balanced('([)]'))"),
                 t("unclosed", append="print(balanced('(('))"), t("extra close", append="print(balanced('())'))"), t("empty", append="print(balanced(''))")],
                ["True", "False", "False", "False", "True"],
                "def balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack",
                require=[r"append", r"pop"]),
        ),
        lesson(
            "Queues with deque",
            "A queue is First-In-First-Out (FIFO), like a line at a shop. Use collections.deque - popping from the front of a list is O(n), but deque.popleft() is O(1):\n\nfrom collections import deque\nq = deque()\nq.append('Ada')     # join the back\nq.append('Bo')\nq.popleft()         # 'Ada' - first come, first served",
            mcq("Enqueue A, B, C then dequeue once. Who's next in line?", ["A", "B", "C", "Nobody"], 1),
            mcq("Why use deque instead of list.pop(0)?", ["deque sorts items", "popleft() is O(1); list.pop(0) is O(n)", "Lists can't hold strings", "No reason"], 1),
            fill("Take the person at the front.", "first = q.___()", "popleft"),
            mcq("A printer handling jobs in arrival order is a…", ["Stack", "Queue", "Tree", "Set"], 1),
            run("Hot potato: names on line 1, k on line 2. Players stand in a circle; repeatedly pass the potato k times (move the front to the back k times), then the person at the front is out. Print each person as they're out, then 'winner: NAME'.", "python",
                [t("four", stdin="Ada Bo Cy Di\n2"), t("k=0", stdin="A B C\n0")],
                ["Cy\nBo\nDi\nwinner: Ada", "A\nB\nwinner: C"],
                "from collections import deque\nq = deque(input().split())\nk = int(input())\nwhile len(q) > 1:\n    for _ in range(k):\n        q.append(q.popleft())\n    print(q.popleft())\nprint('winner:', q[0])",
                require=[r"deque", r"popleft"]),
        ),
        lesson(
            "Monotonic stack",
            "A neat stack trick: 'next greater element'. Walk the list, keeping a stack of indexes still waiting for a bigger number. When a bigger one arrives, it's the answer for everything smaller on the stack:\n\nresult = [-1] * len(nums)\nstack = []\nfor i, n in enumerate(nums):\n    while stack and nums[stack[-1]] < n:\n        result[stack.pop()] = n\n    stack.append(i)\n\nEach index is pushed and popped once: O(n).",
            mcq("Next greater element of each item in [2, 1, 3]?", ["[3, 3, -1]", "[1, 3, -1]", "[3, -1, -1]", "[-1, 3, 3]"], 0),
            mcq("Why is the monotonic stack O(n) despite the inner while loop?", ["Python is fast", "Each index is pushed and popped at most once", "The list is sorted", "It isn't"], 1),
            fill("Pop while the top is smaller than n.", "while stack and nums[stack[-1]] ___ n:", "<"),
            mcq("What does the stack store in this algorithm?", ["Values", "Indexes waiting for a bigger value", "Answers", "Sums"], 1),
            run("Daily temperatures: read temperatures on one line and print, for each day, how many days you wait for a WARMER day (0 if never), space-separated. Use a monotonic stack.", "python",
                [t("week", stdin="73 74 75 71 69 72 76 73"), t("cooling", stdin="30 20 10")],
                ["1 1 4 2 1 1 0 0", "0 0 0"],
                "temps = [int(x) for x in input().split()]\nwait = [0] * len(temps)\nstack = []\nfor i, t in enumerate(temps):\n    while stack and temps[stack[-1]] < t:\n        j = stack.pop()\n        wait[j] = i - j\n    stack.append(i)\nprint(' '.join(map(str, wait)))",
                require=[r"while\s+stack"], hint="Store indexes; the wait is i - j."),
        ),
    ),
)

INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Searching & sorting",
        lesson(
            "Binary search",
            "In a SORTED list, binary search halves the range each step: O(log n). A million items take about 20 steps.\n\ndef search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1",
            mcq("Binary search needs the list to be…", ["Short", "Sorted", "Unique", "Numbers only"], 1),
            mcq("About how many steps for 1,000,000 sorted items?", ["1,000,000", "1,000", "20", "2"], 2, "2^20 ≈ 1,000,000."),
            mcq("nums[mid] is smaller than the target. What next?", ["hi = mid - 1", "lo = mid + 1", "return mid", "mid += 1"], 1),
            fill("Compute the middle index.", "mid = (lo + hi) ___ 2", "//"),
            run("Write first_at_least(nums, x): for a sorted list, return the index of the FIRST value >= x (or len(nums) if none). Use binary search - no loops over every item.", "python",
                [t("middle", append="print(first_at_least([1, 3, 3, 5, 8], 3))"), t("between", append="print(first_at_least([1, 3, 5], 4))"),
                 t("too big", append="print(first_at_least([1, 2], 9))"), t("empty", append="print(first_at_least([], 1))")],
                ["1", "2", "2", "0"],
                "def first_at_least(nums, x):\n    lo, hi = 0, len(nums)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] < x:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo",
                require=[r"while", r"//\s*2"], forbid=[r"for\s+\w+\s+in\s+nums", r"\bbisect\b"]),
        ),
        lesson(
            "Sorting algorithms",
            "Insertion sort grows a sorted part one item at a time - O(n²), but fast on nearly-sorted data.\n\nMerge sort splits the list in half, sorts each half (recursively) and merges them - O(n log n) always:\n\ndef merge(a, b):\n    out, i, j = [], 0, 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            out.append(a[i]); i += 1\n        else:\n            out.append(b[j]); j += 1\n    return out + a[i:] + b[j:]\n\nPython's sorted() uses Timsort - a merge/insertion hybrid, O(n log n).",
            mcq("Best-known complexity of merge sort?", ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], 1),
            mcq("merge([1, 4], [2, 3]) returns…", ["[1, 4, 2, 3]", "[1, 2, 3, 4]", "[2, 3, 1, 4]", "[4, 3, 2, 1]"], 1),
            mcq("A sort is STABLE if…", ["it never crashes", "equal items keep their original order", "it uses no memory", "it's O(n)"], 1, "Python's sorted() is stable."),
            order("Order merge sort.", ["def merge_sort(nums):", "    if len(nums) <= 1:", "        return nums", "    mid = len(nums) // 2", "    return merge(merge_sort(nums[:mid]), merge_sort(nums[mid:]))"]),
            run("Implement merge_sort(nums) (with your own merge) - don't use sorted() or .sort().", "python",
                [t("mixed", append="print(merge_sort([5, 2, 9, 1, 5, 6]))"), t("empty", append="print(merge_sort([]))"),
                 t("negatives", append="print(merge_sort([3, -1, 0, -7]))")],
                ["[1, 2, 5, 5, 6, 9]", "[]", "[-7, -1, 0, 3]"],
                "def merge(a, b):\n    out, i, j = [], 0, 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            out.append(a[i])\n            i += 1\n        else:\n            out.append(b[j])\n            j += 1\n    return out + a[i:] + b[j:]\n\n\ndef merge_sort(nums):\n    if len(nums) <= 1:\n        return nums\n    mid = len(nums) // 2\n    return merge(merge_sort(nums[:mid]), merge_sort(nums[mid:]))",
                forbid=[r"\bsorted\s*\(", r"\.sort\s*\("], require=[r"merge_sort\([^)]*\[[^\]]*:"]),
        ),
        lesson(
            "Sorting with keys",
            "Most real sorting is sorted() with a key:\n\npeople.sort(key=lambda p: p['age'])\nsorted(words, key=lambda w: (-len(w), w))   # longest first, then A-Z\n\nTuples compare item by item, so a tuple key gives tie-breakers for free. The bisect module keeps a list sorted as you insert:\n\nimport bisect\nbisect.insort(scores, 72)",
            mcq("sorted(['bb', 'a', 'cc'], key=lambda w: (-len(w), w))?", ["['a', 'bb', 'cc']", "['bb', 'cc', 'a']", "['cc', 'bb', 'a']", "['a', 'cc', 'bb']"], 1),
            mcq("What does bisect.insort(nums, x) do?", ["Sorts nums", "Inserts x keeping nums sorted", "Finds x", "Removes x"], 1),
            fill("Sort from highest to lowest.", "sorted(nums, ___=True)", "reverse"),
            mcq("Why use a tuple as a sort key?", ["To sort faster", "To break ties with a second value", "Tuples are required", "To remove duplicates"], 1),
            run("Read lines 'name score' until the input ends. Print them sorted by score high-to-low, ties by name A-Z, as: name score", "python",
                [t("ties", stdin="Bo 80\nAda 95\nCy 80\nDi 60")],
                ["Ada 95\nBo 80\nCy 80\nDi 60"],
                "import sys\nrows = []\nfor line in sys.stdin.read().splitlines():\n    if line.strip():\n        name, score = line.split()\n        rows.append((name, int(score)))\nfor name, score in sorted(rows, key=lambda r: (-r[1], r[0])):\n    print(name, score)",
                require=[r"key\s*="]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Recursion & linked lists",
        lesson(
            "Recursion",
            "A recursive function calls itself on a smaller version of the problem, and has a base case that stops it:\n\ndef factorial(n):\n    if n <= 1:          # base case\n        return 1\n    return n * factorial(n - 1)\n\nEvery call waits on the call stack until the smaller one returns. Forget the base case and you get RecursionError.",
            mcq("What does factorial(4) return?", ["4", "10", "24", "16"], 2),
            mcq("What happens without a base case?", ["It returns None", "It recurses until RecursionError", "It returns 0", "Python adds one"], 1),
            fill("Recursive sum of a list.", "return nums[0] + total(nums[___:])", "1"),
            mcq("What does f(3) print?", ["1 2 3", "3 2 1", "3", "Nothing"], 1, code="def f(n):\n    if n == 0:\n        return\n    print(n, end=' ')\n    f(n - 1)"),
            run("Write flatten(items) that returns a flat list from nested lists of any depth, using recursion.", "python",
                [t("nested", append="print(flatten([1, [2, [3, 4]], 5]))"), t("deep", append="print(flatten([[[[]]], [6]]))"),
                 t("flat", append="print(flatten([1, 2]))")],
                ["[1, 2, 3, 4, 5]", "[6]", "[1, 2]"],
                "def flatten(items):\n    out = []\n    for x in items:\n        if isinstance(x, list):\n            out.extend(flatten(x))\n        else:\n            out.append(x)\n    return out",
                require=[r"flatten\(\s*x\s*\)|flatten\(\s*\w+\s*\)[\s\S]*flatten"]),
        ),
        lesson(
            "Memoization",
            "Naive recursive Fibonacci recomputes the same values again and again - exponential time. Memoization caches each answer:\n\nfrom functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nNow each fib(k) is computed once: O(n). This 'remember sub-results' idea is the heart of dynamic programming.",
            mcq("Why is naive recursive fib(40) slow?", ["Python is slow", "It recomputes the same values exponentially many times", "Recursion is always slow", "Big numbers"], 1),
            mcq("What does @lru_cache do?", ["Speeds up loops", "Remembers results for arguments already seen", "Limits recursion", "Runs in parallel"], 1),
            fill("Cache results in a dict.", "if n in memo:\n    return memo[___]", "n"),
            mcq("With memoization, fib(n) takes…", ["O(2ⁿ)", "O(n)", "O(n²)", "O(1)"], 1),
            run("Count the ways to climb n stairs taking 1 or 2 steps at a time. Write ways(n) with memoization (a dict or lru_cache). ways(0) is 1.", "python",
                [t("n=4", append="print(ways(4))"), t("n=10", append="print(ways(10))"), t("n=60 (must be fast)", append="print(ways(60))")],
                ["5", "89", "2504730781961"],
                "from functools import lru_cache\n\n\n@lru_cache(maxsize=None)\ndef ways(n):\n    if n <= 1:\n        return 1\n    return ways(n - 1) + ways(n - 2)",
                require=[r"lru_cache|cache|memo"]),
        ),
        lesson(
            "Linked lists",
            "A linked list is a chain of nodes; each holds a value and a reference to the next:\n\nclass Node:\n    def __init__(self, value, next=None):\n        self.value = value\n        self.next = next\n\nhead = Node(1, Node(2, Node(3)))\n\nInserting at the front is O(1) (no shifting), but reaching item i is O(i) - you must walk the chain.",
            mcq("Cost of inserting at the FRONT of a linked list?", ["O(n)", "O(1)", "O(log n)", "O(n²)"], 1),
            mcq("Cost of reading the i-th item of a linked list?", ["O(1)", "O(i)", "O(log i)", "O(i²)"], 1),
            fill("Move to the next node.", "node = node.___", "next"),
            order("Order the loop that prints every value.", ["node = head", "while node is not None:", "    print(node.value)", "    node = node.next"]),
            run("Using the given Node class, write reverse(head) that reverses the list IN PLACE and returns the new head. (The tests print the list.)", "python",
                [t("three", append="h = reverse(Node(1, Node(2, Node(3))))\nwhile h:\n    print(h.value, end=' ')\n    h = h.next\nprint()"),
                 t("one", append="h = reverse(Node(7))\nprint(h.value, h.next)"), t("empty", append="print(reverse(None))")],
                ["3 2 1", "7 None", "None"],
                "class Node:\n    def __init__(self, value, next=None):\n        self.value = value\n        self.next = next\n\n\ndef reverse(head):\n    prev = None\n    while head:\n        head.next, prev, head = prev, head, head.next\n    return prev",
                starter="class Node:\n    def __init__(self, value, next=None):\n        self.value = value\n        self.next = next\n\n\ndef reverse(head):\n    pass\n",
                forbid=[r"\blist\(", r"\[\s*\]"], hint="Keep prev, walk head forward, and point each node back to prev."),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Trees & heaps",
        lesson(
            "Binary trees",
            "A binary tree node has a value and up to two children:\n\nclass Tree:\n    def __init__(self, value, left=None, right=None):\n        self.value, self.left, self.right = value, left, right\n\nDepth-first traversals visit nodes in different orders:\n  pre-order   node, left, right\n  in-order    left, node, right\n  post-order  left, right, node\n\nMost tree code is a short recursive function: handle None, then recurse into left and right.",
            mcq("In-order traversal visits…", ["node, left, right", "left, node, right", "left, right, node", "level by level"], 1),
            mcq("Height of a tree with only a root (counting nodes)?", ["0", "1", "2", "None"], 1),
            fill("Recurse into the left child.", "return 1 + count(t.___) + count(t.right)", "left"),
            mcq("What's the usual base case in tree recursion?", ["t.value == 0", "t is None", "t.left is t.right", "len(t) == 1"], 1),
            run("Using the Tree class, write height(t) (number of nodes on the longest root-to-leaf path; None has height 0) and leaves(t) (how many nodes have no children).", "python",
                [t("tree", append="t = Tree(1, Tree(2, Tree(4), Tree(5)), Tree(3, None, Tree(6, Tree(7))))\nprint(height(t), leaves(t))"),
                 t("single", append="print(height(Tree(9)), leaves(Tree(9)))"), t("empty", append="print(height(None), leaves(None))")],
                ["4 3", "1 1", "0 0"],
                "class Tree:\n    def __init__(self, value, left=None, right=None):\n        self.value, self.left, self.right = value, left, right\n\n\ndef height(t):\n    if t is None:\n        return 0\n    return 1 + max(height(t.left), height(t.right))\n\n\ndef leaves(t):\n    if t is None:\n        return 0\n    if t.left is None and t.right is None:\n        return 1\n    return leaves(t.left) + leaves(t.right)",
                starter="class Tree:\n    def __init__(self, value, left=None, right=None):\n        self.value, self.left, self.right = value, left, right\n\n\ndef height(t):\n    pass\n\n\ndef leaves(t):\n    pass\n"),
        ),
        lesson(
            "Binary search trees",
            "In a binary search tree (BST), everything in the left subtree is smaller than the node and everything in the right subtree is bigger. So search goes one way at each step:\n\ndef contains(t, x):\n    while t:\n        if x == t.value:\n            return True\n        t = t.left if x < t.value else t.right\n    return False\n\nBalanced BSTs give O(log n) search/insert; an unbalanced one (insert 1, 2, 3, 4...) degrades to a linked list, O(n). An in-order traversal of a BST yields the values sorted.",
            mcq("Inserting 1, 2, 3, 4, 5 in order into a plain BST makes it…", ["Perfectly balanced", "A chain - effectively a linked list", "Empty", "A heap"], 1),
            mcq("In-order traversal of a BST gives the values…", ["Reversed", "Sorted ascending", "Random", "Level by level"], 1),
            mcq("Searching for 3 at a node with value 5, you go…", ["Right", "Left", "Both ways", "Stop"], 1),
            fill("Pick the subtree to continue in.", "t = t.left if x ___ t.value else t.right", "<"),
            run("Write insert(t, x) returning the (new) root of a BST with x added (ignore duplicates), and inorder(t) returning the values as a list. The tests insert numbers then print inorder.", "python",
                [t("numbers", append="root = None\nfor x in [50, 30, 70, 20, 40, 60, 80, 30]:\n    root = insert(root, x)\nprint(inorder(root))"),
                 t("chain", append="root = None\nfor x in [3, 2, 1]:\n    root = insert(root, x)\nprint(inorder(root), root.value)")],
                ["[20, 30, 40, 50, 60, 70, 80]", "[1, 2, 3] 3"],
                "class Tree:\n    def __init__(self, value, left=None, right=None):\n        self.value, self.left, self.right = value, left, right\n\n\ndef insert(t, x):\n    if t is None:\n        return Tree(x)\n    if x < t.value:\n        t.left = insert(t.left, x)\n    elif x > t.value:\n        t.right = insert(t.right, x)\n    return t\n\n\ndef inorder(t):\n    if t is None:\n        return []\n    return inorder(t.left) + [t.value] + inorder(t.right)",
                starter="class Tree:\n    def __init__(self, value, left=None, right=None):\n        self.value, self.left, self.right = value, left, right\n\n\ndef insert(t, x):\n    pass\n\n\ndef inorder(t):\n    pass\n",
                forbid=[r"\bsorted\s*\(", r"\.sort\s*\("]),
        ),
        lesson(
            "Heaps & priority queues",
            "A heap always gives you the smallest item in O(1) and adds/removes in O(log n). Python's heapq turns a list into a min-heap:\n\nimport heapq\ntasks = []\nheapq.heappush(tasks, (2, 'write'))\nheapq.heappush(tasks, (1, 'plan'))\nheapq.heappop(tasks)          # (1, 'plan') - lowest priority number first\nheapq.nlargest(3, scores)     # top 3 without sorting everything\n\nFor a max-heap, push negative numbers.",
            mcq("heapq in Python is a…", ["Max-heap", "Min-heap", "Sorted list", "Queue"], 1),
            mcq("Cost of heappush / heappop?", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 1),
            fill("Take the smallest item.", "smallest = heapq.___(h)", "heappop"),
            mcq("How do you get max-heap behaviour with heapq?", ["heapq.maxheap()", "Push negated values", "Sort in reverse", "It's impossible"], 1),
            run("Read numbers (line 1) and k (line 2). Print the k largest, biggest first, space-separated - using a heap of size k (heapq), not by sorting all the numbers.", "python",
                [t("top3", stdin="5 1 9 3 7 9 2\n3"), t("k=1", stdin="4 8 6\n1")],
                ["9 9 7", "8"],
                "import heapq\nnums = [int(x) for x in input().split()]\nk = int(input())\nheap = []\nfor n in nums:\n    heapq.heappush(heap, n)\n    if len(heap) > k:\n        heapq.heappop(heap)\nprint(' '.join(map(str, sorted(heap, reverse=True))))",
                require=[r"heapq"], forbid=[r"sorted\(\s*nums", r"nums\.sort"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Graphs & dynamic programming",
        lesson(
            "Graphs & BFS",
            "A graph is nodes connected by edges - cities and roads, people and friendships. Store it as an adjacency list:\n\ngraph = {'A': ['B', 'C'], 'B': ['A', 'D'], ...}\n\nBreadth-first search explores in rings from the start, so it finds the FEWEST edges to every node:\n\nfrom collections import deque\ndist = {start: 0}\nq = deque([start])\nwhile q:\n    node = q.popleft()\n    for nb in graph[node]:\n        if nb not in dist:\n            dist[nb] = dist[node] + 1\n            q.append(nb)",
            mcq("BFS uses a…", ["Stack", "Queue", "Heap", "Set only"], 1),
            mcq("BFS finds the path with the fewest…", ["Edges", "Nodes visited overall", "Weights", "Cycles"], 0),
            mcq("Why keep track of visited nodes?", ["Speed only", "To avoid looping forever on cycles", "To sort", "It's optional"], 1),
            fill("Explore each neighbour.", "for nb in graph[___]:", "node"),
            run("Line 1: start node. Then edges 'A B' (undirected) until the input ends. Print every reachable node with its distance from the start, sorted by distance then name, as: B 1", "python",
                [t("graph", stdin="A\nA B\nA C\nB D\nC D\nD E\nX Y")],
                ["A 0\nB 1\nC 1\nD 2\nE 3"],
                "import sys\nfrom collections import deque\nlines = sys.stdin.read().splitlines()\nstart = lines[0].strip()\ngraph = {}\nfor line in lines[1:]:\n    if line.strip():\n        a, b = line.split()\n        graph.setdefault(a, []).append(b)\n        graph.setdefault(b, []).append(a)\ndist = {start: 0}\nq = deque([start])\nwhile q:\n    node = q.popleft()\n    for nb in graph.get(node, []):\n        if nb not in dist:\n            dist[nb] = dist[node] + 1\n            q.append(nb)\nfor node in sorted(dist, key=lambda n: (dist[n], n)):\n    print(node, dist[node])",
                require=[r"popleft"]),
        ),
        lesson(
            "DFS & connected components",
            "Depth-first search goes as deep as possible before backing up - recursion or an explicit stack:\n\ndef dfs(node, seen):\n    seen.add(node)\n    for nb in graph[node]:\n        if nb not in seen:\n            dfs(nb, seen)\n\nRun DFS from every unvisited node and you've found the connected components - the separate 'islands' of a graph.",
            mcq("DFS naturally uses…", ["A queue", "A stack (or recursion)", "A heap", "Sorting"], 1),
            mcq("A graph with edges A-B, C-D and a lone node E has how many components?", ["1", "2", "3", "5"], 2),
            fill("Mark the node as visited.", "seen.___(node)", "add"),
            mcq("BFS vs DFS - which guarantees the fewest-edges path?", ["DFS", "BFS", "Both", "Neither"], 1),
            run("Count islands: read a grid of '#' (land) and '.' (water) until the input ends. Land cells touching up/down/left/right form one island. Print the number of islands.", "python",
                [t("three", stdin="##..#\n#...#\n..#..\n....."), t("none", stdin="...\n..."), t("one", stdin="##\n##")],
                ["3", "0", "1"],
                "import sys\ngrid = [list(r) for r in sys.stdin.read().split() if r]\nrows, cols = len(grid), len(grid[0]) if grid else 0\n\n\ndef sink(r, c):\n    stack = [(r, c)]\n    while stack:\n        r, c = stack.pop()\n        if 0 <= r < rows and 0 <= c < cols and grid[r][c] == '#':\n            grid[r][c] = '.'\n            stack += [(r + 1, c), (r - 1, c), (r, c + 1), (r, c - 1)]\n\n\nislands = 0\nfor r in range(rows):\n    for c in range(cols):\n        if grid[r][c] == '#':\n            islands += 1\n            sink(r, c)\nprint(islands)",
                hint="When you find land, count it and 'sink' the whole island with DFS so it isn't counted again."),
        ),
        lesson(
            "Dynamic programming",
            "Dynamic programming (DP) solves a problem by building answers to smaller sub-problems in a table, each computed once.\n\nCoin change - the fewest coins that make an amount:\n\nbest = [0] + [inf] * amount\nfor a in range(1, amount + 1):\n    for c in coins:\n        if c <= a:\n            best[a] = min(best[a], best[a - c] + 1)\n\nThe recipe: define what best[a] means, find how it depends on smaller entries, fill the table in order.",
            mcq("Coins [1, 3, 4], amount 6. Fewest coins?", ["3 (4+1+1)", "2 (3+3)", "6", "1"], 1, "Greedy picks 4 first and needs 3 coins; DP finds 3 + 3."),
            mcq("DP is useful when a problem has…", ["No sub-problems", "Overlapping sub-problems", "Only one answer", "Random input"], 1),
            fill("best[a] depends on best[a - ___]", "best[a] = min(best[a], best[a - ___] + 1)", "c"),
            mcq("Complexity of the coin-change table above?", ["O(amount)", "O(amount × coins)", "O(2^amount)", "O(coins)"], 1),
            run("Read coin values (line 1) and an amount (line 2). Print the fewest coins that make the amount exactly, or -1 if it's impossible. Use DP.", "python",
                [t("3+3", stdin="1 3 4\n6"), t("impossible", stdin="2\n3"), t("zero", stdin="5 10\n0"), t("bigger", stdin="1 5 10 25\n63")],
                ["2", "-1", "0", "6"],
                "coins = [int(x) for x in input().split()]\namount = int(input())\ninf = float('inf')\nbest = [0] + [inf] * amount\nfor a in range(1, amount + 1):\n    for c in coins:\n        if c <= a:\n            best[a] = min(best[a], best[a - c] + 1)\nprint(best[amount] if best[amount] != inf else -1)",
                require=[r"for[\s\S]*for"]),
        ),
    ),
)

COURSE = course(
    "dsa", "Data Structures & Algorithms", "🧮", "Think like an engineer: Big-O, hashing, stacks, trees, graphs and dynamic programming - in Python.",
    BEGINNER, INTERMEDIATE, ADVANCED,
)
