from .dsl import course, fill, lesson, mcq, order, run, t, unit
from .htmlcss_adv import ADVANCED, INTERMEDIATE

# HTML/CSS "run" exercises render the learner's page in a script-less sandboxed frame (600x400)
# and read back text, element counts, attributes or COMPUTED CSS values.

PAGE = "<!DOCTYPE html>\n<html>\n  <head>\n    <title>My page</title>\n  </head>\n  <body>\n    \n  </body>\n</html>\n"


def page(body: str, style: str = "") -> str:
    head = f"    <title>My page</title>\n" + (f"    <style>\n{style}\n    </style>\n" if style else "")
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"<!DOCTYPE html>\n<html>\n  <head>\n{head}  </head>\n  <body>\n{inner}\n  </body>\n</html>\n"


def styled(css: str, body: str) -> str:
    return page(body, "\n".join("      " + line for line in css.split("\n")))


COURSE = course(
    "html-css", "HTML & CSS", "🎨", "Build and style web pages - the foundation of everything on the web.",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · HTML basics",
        lesson(
            "Tags & page structure",
            "HTML describes a page's content with tags. Most come in pairs - an opening <tag> and a closing </tag>:\n\n<!DOCTYPE html>\n<html>\n  <head>\n    <title>My page</title>\n  </head>\n  <body>\n    <h1>Hello!</h1>\n    <p>Welcome to my page.</p>\n  </body>\n</html>\n\n<head> holds information ABOUT the page; <body> holds what you see.",
            mcq("Where does the visible content go?", ["<body>", "<head>", "<title>", "<html> only"], 0),
            fill("Close the paragraph.", "<p>Hello___", "</p>"),
            mcq("What does <title> set?", ["The text on the browser tab", "The biggest heading", "The page's first paragraph", "The URL"], 0),
            order("Order the page skeleton.", ["<!DOCTYPE html>", "<html>", "<head><title>Hi</title></head>", "<body><p>Hi!</p></body>", "</html>"]),
            run("Make a page whose body contains a heading (h1) saying Hello, Web! and a paragraph saying I am learning HTML.", "html",
                [t("heading text", selector="h1", prop="text"), t("paragraph text", selector="p", prop="text")], ["Hello, Web!", "I am learning HTML."],
                page("<h1>Hello, Web!</h1>\n<p>I am learning HTML.</p>"), starter=PAGE),
        ),
        lesson(
            "Headings & paragraphs",
            "There are six heading levels, <h1> (most important) to <h6>. Use them in order, like an outline - one <h1> per page is a good rule.\n\n<p> makes a paragraph. <br> is a line break (a void tag with no closing tag). <hr> draws a horizontal rule.\n\nBrowsers collapse extra spaces and newlines in your HTML into a single space.",
            mcq("Which heading is the most important?", ["<h1>", "<h6>", "<head>", "<header>"], 0),
            mcq("Which tag has no closing tag?", ["<br>", "<p>", "<h2>", "<body>"], 0),
            fill("A second-level heading.", "<___>Chapter 1</h2>", "h2"),
            mcq("How is <p>Hi     there</p> displayed?", ["Hi there", "Hi     there", "Hi\\nthere", "An error"], 0, "HTML collapses runs of whitespace."),
            run("Write a recipe outline: one h1 \"Pancakes\", then two h2 headings \"Ingredients\" and \"Method\", each followed by one paragraph (any text).", "html",
                [t("h1", selector="h1", prop="text"), t("number of h2", selector="h2", prop="count"), t("second h2", selector="h2:nth-of-type(2)", prop="text"),
                 t("number of paragraphs", selector="p", prop="count")],
                ["Pancakes", "2", "Method", "2"],
                page("<h1>Pancakes</h1>\n<h2>Ingredients</h2>\n<p>Flour, eggs, milk.</p>\n<h2>Method</h2>\n<p>Mix and fry.</p>"), starter=PAGE),
        ),
        lesson(
            "Text formatting",
            "Inline tags mark up words inside text:\n\n<strong>important</strong>   bold, and meaningful to screen readers\n<em>emphasis</em>            italic stress\n<code>print()</code>         code\n<mark>highlight</mark>\n\nPrefer <strong>/<em> (meaning) over <b>/<i> (looks only).\n\nSpecial characters: &lt; for <, &gt; for >, &amp; for &.",
            mcq("Which tag marks text as strongly important?", ["<strong>", "<b>", "<big>", "<important>"], 0),
            mcq("How do you show a literal < in HTML text?", ["&lt;", "\\<", "<<", "&less;"], 0),
            fill("Emphasise the word.", "I <___>really</em> like it.", "em"),
            mcq("Which tag is meant for inline code?", ["<code>", "<pre>", "<script>", "<kbd> only"], 0),
            run("Write a paragraph: Use <strong>print()</strong>-style markup so the paragraph reads exactly  Always use < and > carefully  where \"Always\" is in <strong> and \"carefully\" is in <em>.", "html",
                [t("paragraph text", selector="p", prop="text"), t("strong", selector="p strong", prop="text"), t("em", selector="p em", prop="text")],
                ["Always use < and > carefully", "Always", "carefully"],
                page("<p><strong>Always</strong> use &lt; and &gt; <em>carefully</em></p>"), starter=PAGE, hint="Write &lt; and &gt; for the angle brackets."),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Links, images & lists",
        lesson(
            "Links",
            "<a> makes a link. href is where it goes:\n\n<a href=\"https://example.com\">Visit Example</a>\n<a href=\"about.html\">About us</a>        (a page on your site)\n<a href=\"#contact\">Jump to contact</a>   (an element with id=\"contact\")\n<a href=\"mailto:hi@example.com\">Email</a>\n\ntarget=\"_blank\" opens a new tab - add rel=\"noopener\" for safety.",
            mcq("Which attribute sets a link's destination?", ["href", "src", "link", "to"], 0),
            fill("Link to the element with id=\"top\".", '<a href="___">Back to top</a>', "#top"),
            mcq("What does target=\"_blank\" do?", ["Opens the link in a new tab", "Makes the link invisible", "Removes the link", "Downloads it"], 0),
            mcq("Which is the clickable text?", ["Docs", "https://docs.dev", "href", "a"], 0, code='<a href="https://docs.dev">Docs</a>'),
            run("Create a link with the text Codeingo that goes to https://codeingo.dev and opens in a new tab safely (target and rel).", "html",
                [t("text", selector="a", prop="text"), t("href", selector="a", prop="attr:href"), t("target", selector="a", prop="attr:target"),
                 t("rel", selector="a", prop="attr:rel")],
                ["Codeingo", "https://codeingo.dev", "_blank", "noopener"],
                page('<a href="https://codeingo.dev" target="_blank" rel="noopener">Codeingo</a>'), starter=PAGE),
        ),
        lesson(
            "Images",
            "<img> shows an image. It's a void tag:\n\n<img src=\"cat.jpg\" alt=\"A ginger cat asleep on a sofa\" width=\"300\">\n\nsrc - the image file or URL\nalt - a text description for screen readers and when the image can't load. Always write a meaningful alt! (Use alt=\"\" for purely decorative images.)",
            mcq("Which attribute gives the image's file?", ["src", "href", "img", "file"], 0),
            mcq("Why is alt text important?", ["Screen reader users and failed loads get a description", "It makes images load faster", "It's the file name", "It's optional decoration"], 0),
            fill("Describe the image.", '<img src="logo.png" ___="Codeingo logo">', "alt"),
            mcq("What's the right alt for a decorative divider line image?", ['alt=""', 'alt="image"', "No alt attribute", 'alt="divider.png"'], 0),
            run("Add an image with src photo.jpg, alt text Sunset over the sea, and width 320.", "html",
                [t("src", selector="img", prop="attr:src"), t("alt", selector="img", prop="attr:alt"), t("width", selector="img", prop="attr:width")],
                ["photo.jpg", "Sunset over the sea", "320"], page('<img src="photo.jpg" alt="Sunset over the sea" width="320">'), starter=PAGE),
        ),
        lesson(
            "Lists",
            "Unordered (bulleted) list:\n<ul>\n  <li>Milk</li>\n  <li>Eggs</li>\n</ul>\n\nOrdered (numbered) list:\n<ol>\n  <li>Preheat</li>\n  <li>Bake</li>\n</ol>\n\nEach item is an <li>. Lists can be nested - put a <ul> inside an <li>.",
            mcq("Which makes a numbered list?", ["<ol>", "<ul>", "<li>", "<nl>"], 0),
            fill("One list item.", "<___>Bread</li>", "li"),
            mcq("What goes directly inside <ul>?", ["<li> elements", "<p> elements", "Text only", "<ol> only"], 0),
            order("Order the list.", ["<ol>", "  <li>Wake up</li>", "  <li>Code</li>", "</ol>"]),
            run("Make an ordered list of three steps: Plan, Build, Test - and after it an unordered list with two items: HTML, CSS.", "html",
                [t("steps", selector="ol li", prop="count"), t("last step", selector="ol li:last-child", prop="text"), t("bullets", selector="ul li", prop="count"),
                 t("first bullet", selector="ul li", prop="text")],
                ["3", "Test", "2", "HTML"], page("<ol>\n  <li>Plan</li>\n  <li>Build</li>\n  <li>Test</li>\n</ol>\n<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>"), starter=PAGE),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Page structure",
        lesson(
            "Semantic layout",
            "Semantic tags describe what a section IS - great for accessibility and search engines:\n\n<header>  top of the page or a section\n<nav>     main navigation links\n<main>    the main content (once per page)\n<article> a self-contained piece (a post)\n<section> a themed group\n<aside>   related side content\n<footer>  bottom info\n\n<div> and <span> are generic boxes with no meaning.",
            mcq("Which tag should wrap your site's main navigation links?", ["<nav>", "<menu>", "<div class=\"nav\">", "<links>"], 0),
            mcq("How many <main> elements should a page have?", ["One", "As many as you like", "None", "One per section"], 0),
            fill("Bottom-of-page information.", "<___>© 2026 Codeingo</footer>", "footer"),
            mcq("What's the difference between <div> and <span>?", ["div is a block box, span is inline", "span is bigger", "No difference", "div is semantic"], 0),
            run("Build a page with a header containing an h1 \"Blog\", a nav with 2 links, a main containing one article with an h2, and a footer.", "html",
                [t("header h1", selector="header h1", prop="text"), t("nav links", selector="nav a", prop="count"), t("article heading", selector="main article h2", prop="count"),
                 t("footer", selector="footer", prop="count")],
                ["Blog", "2", "1", "1"],
                page('<header>\n  <h1>Blog</h1>\n  <nav>\n    <a href="/">Home</a>\n    <a href="/about">About</a>\n  </nav>\n</header>\n<main>\n  <article>\n    <h2>First post</h2>\n    <p>Hello!</p>\n  </article>\n</main>\n<footer>© 2026</footer>'),
                starter=PAGE),
        ),
        lesson(
            "Tables",
            "Tables show data in rows and columns:\n\n<table>\n  <thead>\n    <tr><th>Name</th><th>Score</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Ada</td><td>95</td></tr>\n  </tbody>\n</table>\n\n<tr> row · <th> header cell · <td> data cell. Use tables for data, not page layout.",
            mcq("Which tag is a table row?", ["<tr>", "<td>", "<row>", "<th>"], 0),
            mcq("Which cell is a column heading?", ["<th>", "<td>", "<thead>", "<h1>"], 0),
            fill("A normal data cell.", "<tr><___>42</td></tr>", "td"),
            mcq("Should you use tables to lay out a whole page?", ["No - use CSS (flexbox/grid)", "Yes", "Only for headers", "Only in emails"], 0),
            run("Make a table with a header row (Language, Year) and two body rows: Python 1991 and JavaScript 1995.", "html",
                [t("header cells", selector="thead th", prop="count"), t("body rows", selector="tbody tr", prop="count"),
                 t("second row, first cell", selector="tbody tr:nth-child(2) td", prop="text"), t("all data cells", selector="td", prop="count")],
                ["2", "2", "JavaScript", "4"],
                page("<table>\n  <thead>\n    <tr><th>Language</th><th>Year</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Python</td><td>1991</td></tr>\n    <tr><td>JavaScript</td><td>1995</td></tr>\n  </tbody>\n</table>"),
                starter=PAGE),
        ),
        lesson(
            "Forms",
            "Forms collect input:\n\n<form action=\"/signup\" method=\"post\">\n  <label for=\"email\">Email</label>\n  <input id=\"email\" name=\"email\" type=\"email\" required>\n  <button type=\"submit\">Sign up</button>\n</form>\n\nInput types: text, email, password, number, checkbox, radio, date…\nA <label for> linked to the input's id makes it accessible and clickable.",
            mcq("How is a <label> linked to its input?", ["label for=\"x\" matches input id=\"x\"", "By being next to it", "label name matches input name", "They can't be linked"], 0),
            fill("A password field.", '<input type="___" name="pw">', "password"),
            mcq("What does the required attribute do?", ["The browser won't submit the form while it's empty", "Makes it bold", "Encrypts it", "Nothing"], 0),
            mcq("Which input type shows a checkbox?", ['type="checkbox"', 'type="check"', 'type="tick"', 'type="bool"'], 0),
            run("Make a login form: a labelled email input (id email, type email, required), a labelled password input (id pw, type password) and a submit button with the text Log in.", "html",
                [t("email type", selector="#email", prop="attr:type"), t("email required", selector="#email", prop="attr:required"),
                 t("email label", selector="label[for=email]", prop="count"), t("password label", selector="label[for=pw]", prop="count"),
                 t("password type", selector="#pw", prop="attr:type"), t("button", selector="form button", prop="text")],
                ["email", "", "1", "1", "password", "Log in"],
                page('<form>\n  <label for="email">Email</label>\n  <input id="email" type="email" required>\n  <label for="pw">Password</label>\n  <input id="pw" type="password">\n  <button type="submit">Log in</button>\n</form>'),
                starter=PAGE),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · CSS basics",
        lesson(
            "Selectors & colour",
            "CSS styles HTML. A rule is a selector plus declarations:\n\np {\n  color: navy;\n  background-color: lightyellow;\n}\n\nPut CSS in a <style> element in <head> (or a separate .css file). Colours can be names (red), hex (#ff0000) or rgb(255, 0, 0).",
            mcq("In p { color: red; }, what is p?", ["The selector", "The property", "The value", "The declaration"], 0),
            fill("Make h1 text green.", "h1 { ___: green; }", "color"),
            mcq("Which sets the background colour?", ["background-color", "bgcolor", "color", "fill"], 0),
            mcq("Which hex colour is pure red?", ["#ff0000", "#00ff00", "#0000ff", "#000000"], 0),
            run("Style the page so every h1 is red (#ff0000) and every paragraph has a light yellow background (#ffffcc).", "html",
                [t("h1 colour", selector="h1", prop="color"), t("p background", selector="p", prop="background-color")],
                ["rgb(255, 0, 0)", "rgb(255, 255, 204)"],
                styled("h1 { color: #ff0000; }\np { background-color: #ffffcc; }", "<h1>Title</h1>\n<p>Some text.</p>"),
                starter=styled("", "<h1>Title</h1>\n<p>Some text.</p>")),
        ),
        lesson(
            "Classes & ids",
            "Target specific elements:\n\n.card { … }      class selector - use on many elements: <div class=\"card\">\n#logo { … }      id selector - one element: <img id=\"logo\">\nnav a { … }      descendant - <a> inside <nav>\nh1, h2 { … }     group - both\n\nWhen rules conflict, the more specific one wins: id > class > tag.",
            mcq("Which selector targets class=\"card\"?", [".card", "#card", "card", "*card"], 0),
            mcq("Which selects id=\"logo\"?", ["#logo", ".logo", "logo", "@logo"], 0),
            fill("Select links inside nav.", "nav ___ { color: white; }", "a"),
            mcq("Which rule wins for <p class=\"note\">? p { color: red } .note { color: blue }", ["blue - class beats tag", "red - it comes first", "Both mix", "Neither"], 0),
            run("Make elements with class warning have orange text (#ff8800) and the element with id total have bold text (font-weight 700).", "html",
                [t("warning colour", selector=".warning", prop="color"), t("second warning", selector="li.warning", prop="color"),
                 t("total weight", selector="#total", prop="font-weight"), t("normal p", selector="p:not(.warning):not(#total)", prop="color")],
                ["rgb(255, 136, 0)", "rgb(255, 136, 0)", "700", "rgb(0, 0, 0)"],
                styled(".warning { color: #ff8800; }\n#total { font-weight: 700; }",
                       '<p class="warning">Low stock</p>\n<ul>\n  <li class="warning">Check order</li>\n</ul>\n<p id="total">Total: 42</p>\n<p>Thanks!</p>'),
                starter=styled("", '<p class="warning">Low stock</p>\n<ul>\n  <li class="warning">Check order</li>\n</ul>\n<p id="total">Total: 42</p>\n<p>Thanks!</p>')),
        ),
        lesson(
            "Fonts & text",
            "Text properties:\n\nfont-family: Georgia, serif;   (fallbacks after the comma)\nfont-size: 20px;\nfont-weight: 700;              (bold)\nline-height: 1.5;\ntext-align: center;\ntext-transform: uppercase;\nletter-spacing: 2px;",
            mcq("Which property makes text bold?", ["font-weight", "font-style", "text-bold", "font-size"], 0),
            fill("Centre the text.", "h1 { text-align: ___; }", "center"),
            mcq("Why list several fonts in font-family?", ["Fallbacks if the first isn't available", "To mix them", "For speed", "It's required"], 0),
            mcq("Which makes TEXT UPPER-CASE without changing the HTML?", ["text-transform: uppercase", "font-variant: caps", "text-case: upper", "font-style: upper"], 0),
            run("Style h1 with font-size 32px, centred text and uppercase letters. Style p with a line-height of 24px.", "html",
                [t("h1 size", selector="h1", prop="font-size"), t("h1 align", selector="h1", prop="text-align"), t("h1 transform", selector="h1", prop="text-transform"),
                 t("p line-height", selector="p", prop="line-height")],
                ["32px", "center", "uppercase", "24px"],
                styled("h1 {\n  font-size: 32px;\n  text-align: center;\n  text-transform: uppercase;\n}\np { line-height: 24px; }", "<h1>Welcome</h1>\n<p>Nice to see you.</p>"),
                starter=styled("", "<h1>Welcome</h1>\n<p>Nice to see you.</p>")),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · The box model",
        lesson(
            "Margin & padding",
            "Every element is a box:\n\n  margin   - space OUTSIDE the border (pushes other boxes away)\n  border   - the edge\n  padding  - space INSIDE, between border and content\n  content\n\npadding: 10px;              all sides\npadding: 10px 20px;         top/bottom, left/right\nmargin: 0 auto;             centre a block that has a width",
            mcq("Which space is inside the border?", ["padding", "margin", "outline", "gap"], 0),
            mcq("What does padding: 5px 10px mean?", ["5px top & bottom, 10px left & right", "5px left, 10px right", "5px all, 10px extra", "10px all"], 0),
            fill("Centre a fixed-width block horizontally.", ".box { width: 300px; margin: 0 ___; }", "auto"),
            mcq("Which property pushes neighbouring elements away?", ["margin", "padding", "border", "width"], 0),
            run("Give .card 16px of padding on every side and a 24px bottom margin.", "html",
                [t("padding top", selector=".card", prop="padding-top"), t("padding left", selector=".card", prop="padding-left"),
                 t("margin bottom", selector=".card", prop="margin-bottom")],
                ["16px", "16px", "24px"], styled(".card {\n  padding: 16px;\n  margin-bottom: 24px;\n}", '<div class="card">One</div>\n<div class="card">Two</div>'),
                starter=styled("", '<div class="card">One</div>\n<div class="card">Two</div>')),
        ),
        lesson(
            "Borders & box-sizing",
            "border: 2px solid black;   (width, style, colour)\nborder-radius: 8px;         rounded corners (50% on a square = circle)\n\nBy default width sets only the CONTENT width - padding and border are added on top. box-sizing: border-box makes width include them, which is much easier:\n\n*, *::before, *::after { box-sizing: border-box; }",
            mcq("With box-sizing: content-box, width 100px + 10px padding each side = ?", ["120px total", "100px total", "110px total", "80px total"], 0),
            mcq("What does box-sizing: border-box do?", ["width includes padding and border", "Removes borders", "Adds a border", "Nothing"], 0),
            fill("Round the corners.", ".btn { border-___: 12px; }", "radius"),
            mcq("Which is a valid border?", ["border: 1px solid #ccc;", "border: solid;1px", "border = 1px", "border: #ccc 1px dashed solid"], 0),
            run("Give .avatar a 3px solid border in #1d6ff2, a width and height of 80px INCLUDING the border (box-sizing), and make it a circle.", "html",
                [t("border width", selector=".avatar", prop="border-top-width"), t("border colour", selector=".avatar", prop="border-top-color"),
                 t("box-sizing", selector=".avatar", prop="box-sizing"), t("radius", selector=".avatar", prop="border-top-left-radius")],
                ["3px", "rgb(29, 111, 242)", "border-box", "50%"],
                styled(".avatar {\n  width: 80px;\n  height: 80px;\n  border: 3px solid #1d6ff2;\n  box-sizing: border-box;\n  border-radius: 50%;\n}", '<div class="avatar"></div>'),
                starter=styled("", '<div class="avatar"></div>')),
        ),
        lesson(
            "display",
            "display controls how a box behaves:\n\nblock         takes the full width, starts on a new line (div, p, h1)\ninline        flows inside text, width/height ignored (span, a)\ninline-block  flows inline but accepts width/height\nnone          hidden completely (takes no space)\n\nvisibility: hidden hides but still takes up space.",
            mcq("Which display value hides an element and removes its space?", ["none", "hidden", "invisible", "block"], 0),
            mcq("What's the default display of <span>?", ["inline", "block", "flex", "none"], 0),
            fill("Let a link accept width and height while staying in the line.", "a { display: ___; }", "inline-block"),
            mcq("What does visibility: hidden do?", ["Hides it but keeps its space", "Removes it completely", "Makes it transparent to clicks only", "Nothing"], 0),
            run("Hide the element with class ad completely, and make the nav links inline-blocks.", "html",
                [t("ad", selector=".ad", prop="display"), t("links", selector="nav a", prop="display")], ["none", "inline-block"],
                styled(".ad { display: none; }\nnav a { display: inline-block; }", '<nav>\n  <a href="#">Home</a>\n  <a href="#">Shop</a>\n</nav>\n<div class="ad">Buy now!</div>'),
                starter=styled("", '<nav>\n  <a href="#">Home</a>\n  <a href="#">Shop</a>\n</nav>\n<div class="ad">Buy now!</div>')),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Layout",
        lesson(
            "Flexbox basics",
            "Flexbox lays children out in a row (or column):\n\n.row {\n  display: flex;\n  gap: 16px;              space between items\n  flex-direction: row;    or column\n  flex-wrap: wrap;        allow new lines\n}\n\n.item { flex: 1; }        items share the free space equally",
            mcq("Which property turns on flexbox for the children?", ["display: flex", "flex: 1", "position: flex", "layout: flex"], 0),
            fill("Put 12px of space between flex items.", ".row { display: flex; ___: 12px; }", "gap"),
            mcq("How do you stack flex items vertically?", ["flex-direction: column", "flex-wrap: wrap", "display: block", "align-items: column"], 0),
            mcq("What does flex: 1 on every child do?", ["They share the free space equally", "Only the first grows", "They shrink to nothing", "Nothing"], 0),
            run("Make .row a flex container with a 10px gap, and make each .item take an equal share (flex: 1).", "html",
                [t("container", selector=".row", prop="display"), t("gap", selector=".row", prop="column-gap"), t("item grow", selector=".item", prop="flex-grow")],
                ["flex", "10px", "1"],
                styled(".row {\n  display: flex;\n  gap: 10px;\n}\n.item { flex: 1; }", '<div class="row">\n  <div class="item">A</div>\n  <div class="item">B</div>\n  <div class="item">C</div>\n</div>'),
                starter=styled("", '<div class="row">\n  <div class="item">A</div>\n  <div class="item">B</div>\n  <div class="item">C</div>\n</div>')),
        ),
        lesson(
            "Flex alignment",
            "Two axes: MAIN (the direction items flow) and CROSS (perpendicular).\n\njustify-content  - along the main axis: flex-start | center | space-between | space-around\nalign-items      - along the cross axis: stretch | center | flex-start | flex-end\n\nPerfect centring:\n.center { display: flex; justify-content: center; align-items: center; }",
            mcq("In a row, which property spaces items horizontally?", ["justify-content", "align-items", "text-align", "vertical-align"], 0),
            mcq("What does justify-content: space-between do?", ["First item at the start, last at the end, equal gaps between", "Centres everything", "Adds margins", "Stacks items"], 0),
            fill("Centre items vertically in a row.", ".row { display: flex; align-items: ___; }", "center"),
            mcq("What's align-items' default?", ["stretch", "center", "flex-start", "baseline"], 0),
            run("Make the header a flex row with its logo and menu pushed to opposite ends (space-between) and vertically centred.", "html",
                [t("display", selector="header", prop="display"), t("justify", selector="header", prop="justify-content"), t("align", selector="header", prop="align-items")],
                ["flex", "space-between", "center"],
                styled("header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}", "<header>\n  <strong>Logo</strong>\n  <nav>Menu</nav>\n</header>"),
                starter=styled("", "<header>\n  <strong>Logo</strong>\n  <nav>Menu</nav>\n</header>")),
        ),
        lesson(
            "CSS Grid",
            "Grid lays items out in rows AND columns:\n\n.gallery {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);   three equal columns\n  gap: 8px;\n}\n\nfr = a fraction of the free space. Make an item span two columns: grid-column: span 2;",
            mcq("What does repeat(3, 1fr) create?", ["Three equal columns", "Three rows", "One 3px column", "Three grids"], 0),
            fill("Turn on grid layout.", ".gallery { display: ___; }", "grid"),
            mcq("What does 1fr mean?", ["One fraction of the free space", "1 frame", "1 font-relative unit", "1 pixel"], 0),
            mcq("How do you make an item cover two columns?", ["grid-column: span 2", "width: 2", "colspan: 2", "grid-span: 2"], 0),
            run("Make .gallery a grid with 3 equal columns and a 6px gap (the page is 600px wide; body margin is removed for you).", "html",
                [t("display", selector=".gallery", prop="display"), t("columns", selector=".gallery", prop="grid-template-columns"), t("gap", selector=".gallery", prop="row-gap")],
                ["grid", "196px 196px 196px", "6px"],
                styled("body { margin: 0; }\n.gallery {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 6px;\n}",
                       '<div class="gallery">\n  <div>1</div>\n  <div>2</div>\n  <div>3</div>\n  <div>4</div>\n</div>'),
                starter=styled("body { margin: 0; }", '<div class="gallery">\n  <div>1</div>\n  <div>2</div>\n  <div>3</div>\n  <div>4</div>\n</div>'),
                hint="(600px - 2 × 6px gap) / 3 = 196px per column."),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · More styling",
        lesson(
            "Colours & backgrounds",
            "Colour formats:\n  #1d6ff2            hex\n  rgb(29, 111, 242)   red, green, blue 0-255\n  rgb(0 0 0 / 50%)    with transparency\n  hsl(220 90% 53%)    hue, saturation, lightness\n\nBackgrounds: background-color, background-image: url(bg.png), linear-gradient(to right, #1d6ff2, #22c55e). opacity: 0.5 fades the whole element.",
            mcq("What is #000000?", ["Black", "White", "Grey", "Transparent"], 0),
            mcq("In rgb(255, 0, 0), which colour is it?", ["Red", "Green", "Blue", "Yellow"], 0),
            fill("A gradient from left to right.", "background: linear-___(to right, red, blue);", "gradient"),
            mcq("What does opacity: 0 do?", ["Makes the element fully transparent (still takes space)", "Removes it", "Makes it black", "Nothing"], 0),
            run("Give .hero a background colour of rgb(29, 111, 242), white text, and opacity 0.9.", "html",
                [t("background", selector=".hero", prop="background-color"), t("text colour", selector=".hero", prop="color"), t("opacity", selector=".hero", prop="opacity")],
                ["rgb(29, 111, 242)", "rgb(255, 255, 255)", "0.9"],
                styled(".hero {\n  background-color: rgb(29, 111, 242);\n  color: white;\n  opacity: 0.9;\n}", '<section class="hero">Learn to code</section>'),
                starter=styled("", '<section class="hero">Learn to code</section>')),
        ),
        lesson(
            "Pseudo-classes",
            "Pseudo-classes select elements by state or position:\n\na:hover         when the mouse is over it\ninput:focus     while it's being typed in\nli:first-child  the first item\nli:last-child\nli:nth-child(2)      the 2nd\ntr:nth-child(even)   every even row (zebra stripes)",
            mcq("Which pseudo-class styles an element under the mouse?", [":hover", ":active", ":focus", ":over"], 0),
            mcq("What does li:nth-child(odd) select?", ["The 1st, 3rd, 5th … items", "Only the 1st", "Even items", "The last item"], 0),
            fill("Style an input while it's being typed in.", "input:___ { outline: 2px solid blue; }", "focus"),
            mcq("Which selects the last <li> in its list?", ["li:last-child", "li:end", "li:final", "li:nth-child(last)"], 0),
            run("Zebra-stripe the list: every EVEN li gets background #eeeeee, and the first li is bold (font-weight 700).", "html",
                [t("2nd item", selector="li:nth-child(2)", prop="background-color"), t("3rd item", selector="li:nth-child(3)", prop="background-color"),
                 t("4th item", selector="li:nth-child(4)", prop="background-color"), t("first weight", selector="li:first-child", prop="font-weight")],
                ["rgb(238, 238, 238)", "rgba(0, 0, 0, 0)", "rgb(238, 238, 238)", "700"],
                styled("li:nth-child(even) { background-color: #eeeeee; }\nli:first-child { font-weight: 700; }", "<ul>\n  <li>One</li>\n  <li>Two</li>\n  <li>Three</li>\n  <li>Four</li>\n</ul>"),
                starter=styled("", "<ul>\n  <li>One</li>\n  <li>Two</li>\n  <li>Three</li>\n  <li>Four</li>\n</ul>")),
        ),
        lesson(
            "Positioning",
            "position changes how a box is placed:\n\nstatic    normal flow (default)\nrelative  nudged from where it would be; becomes a reference for absolute children\nabsolute  placed relative to the nearest positioned ancestor (removed from flow)\nfixed     stuck to the viewport (e.g. a chat button)\nsticky    normal until you scroll past, then sticks\n\nUse top / right / bottom / left to move it, z-index to layer it.",
            mcq("Which position keeps an element in the same place while the page scrolls?", ["fixed", "absolute", "relative", "static"], 0),
            mcq("An absolute element is positioned relative to…", ["its nearest positioned ancestor", "the element before it", "always the page", "its own normal place"], 0),
            fill("Make the parent a reference for absolute children.", ".card { position: ___; }", "relative"),
            mcq("What does a higher z-index do?", ["Puts the element on top of others", "Makes it bigger", "Moves it down", "Nothing"], 0),
            run("Put a .badge in the top-right corner of .card: make .card position relative, and .badge position absolute with top 0 and right 0.", "html",
                [t("card position", selector=".card", prop="position"), t("badge position", selector=".badge", prop="position"),
                 t("badge top", selector=".badge", prop="top"), t("badge right", selector=".badge", prop="right")],
                ["relative", "absolute", "0px", "0px"],
                styled(".card { position: relative; }\n.badge {\n  position: absolute;\n  top: 0;\n  right: 0;\n}", '<div class="card">\n  Course\n  <span class="badge">NEW</span>\n</div>'),
                starter=styled("", '<div class="card">\n  Course\n  <span class="badge">NEW</span>\n</div>')),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Responsive & accessible",
        lesson(
            "Media queries",
            "Media queries apply CSS only on some screens:\n\n.menu { display: flex; }\n\n@media (max-width: 700px) {\n  .menu { flex-direction: column; }\n}\n\nAlways include <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> so phones use their real width. 'Mobile-first' means writing phone styles first, then min-width queries for bigger screens.",
            mcq("When does @media (max-width: 700px) apply?", ["When the viewport is 700px wide or less", "Above 700px", "Always", "Only when printing"], 0),
            fill("Styles for screens at least 900px wide.", "@media (___: 900px) { … }", "min-width"),
            mcq("Why add the viewport meta tag?", ["So phones render at their real width instead of zooming out", "For SEO only", "To enable CSS", "It's decoration"], 0),
            mcq("What does 'mobile-first' mean?", ["Write small-screen styles first, add min-width queries for bigger screens", "Only support phones", "Design on a phone", "Load mobile scripts first"], 0),
            run("The preview is 600px wide. Make .menu a flex row by default, but a column at max-width 700px (so it's a column here). Also hide .desktop-only at that size.", "html",
                [t("menu display", selector=".menu", prop="display"), t("direction", selector=".menu", prop="flex-direction"), t("desktop-only", selector=".desktop-only", prop="display")],
                ["flex", "column", "none"],
                styled(".menu { display: flex; }\n@media (max-width: 700px) {\n  .menu { flex-direction: column; }\n  .desktop-only { display: none; }\n}",
                       '<nav class="menu">\n  <a href="#">Home</a>\n  <a href="#">Learn</a>\n</nav>\n<p class="desktop-only">Keyboard shortcuts: press ?</p>'),
                starter=styled("", '<nav class="menu">\n  <a href="#">Home</a>\n  <a href="#">Learn</a>\n</nav>\n<p class="desktop-only">Keyboard shortcuts: press ?</p>'),
                require=[r"@media"]),
        ),
        lesson(
            "Relative units",
            "Fixed px don't adapt. Relative units do:\n\nrem  relative to the ROOT font size (usually 16px): 1.5rem = 24px\nem   relative to the element's own font size\n%    relative to the parent (for widths)\nvw / vh  1% of the viewport width / height\n\nUsing rem for font sizes respects users who enlarge text in their browser.",
            mcq("If the root font size is 16px, what is 2rem?", ["32px", "16px", "2px", "8px"], 0),
            mcq("What is 50vw?", ["Half the viewport width", "50 pixels", "Half the parent", "50% of the font"], 0),
            fill("Font size 1.25 × the root size.", "p { font-size: 1.25___; }", "rem"),
            mcq("Why prefer rem over px for font sizes?", ["It respects the user's browser text size setting", "It's shorter", "It's faster", "px is invalid"], 0),
            run("With body margin 0 (the preview is 600px wide), make h1 2rem, and make .panel 50% wide with 1rem padding.", "html",
                [t("h1 size", selector="h1", prop="font-size"), t("panel width", selector=".panel", prop="width"), t("panel padding", selector=".panel", prop="padding-left")],
                ["32px", "300px", "16px"],
                styled("body { margin: 0; }\nh1 { font-size: 2rem; }\n.panel {\n  width: 50%;\n  padding: 1rem;\n}", '<h1>Hi</h1>\n<div class="panel">Half width</div>'),
                starter=styled("body { margin: 0; }", '<h1>Hi</h1>\n<div class="panel">Half width</div>'), require=[r"rem", r"%"]),
        ),
        lesson(
            "Accessibility",
            "Accessible pages work for everyone, including screen-reader and keyboard users:\n\n- Meaningful alt text on images\n- Every input has a <label>\n- Use real <button>s for actions and <a href> for navigation\n- Headings in order (h1 → h2 → h3)\n- Enough colour contrast; don't rely on colour alone\n- Icon-only buttons need a name: <button aria-label=\"Close\">✕</button>\n- Set the page language: <html lang=\"en\">",
            mcq("How do you give an icon-only button an accessible name?", ["aria-label=\"Close\"", "title only", "alt=\"Close\"", "It doesn't need one"], 0),
            mcq("Which element should perform an action like 'Save'?", ["<button>", "<div onclick>", "<span>", "<a> without href"], 0),
            fill("Declare the page's language.", '<html ___="en">', "lang"),
            mcq("Why not rely on colour alone (e.g. red = error)?", ["Colour-blind users may not see the difference", "Colours are slow", "It's invalid HTML", "Screens can't show red"], 0),
            run("Fix this form for accessibility: give the image alt text Company logo, label the search input (id q) with a label reading Search, and give the icon-only button aria-label Submit search.", "html",
                [t("alt", selector="img", prop="attr:alt"), t("label for", selector="label[for=q]", prop="text"), t("button name", selector="button", prop="attr:aria-label")],
                ["Company logo", "Search", "Submit search"],
                page('<img src="logo.png" alt="Company logo">\n<form>\n  <label for="q">Search</label>\n  <input id="q" type="search">\n  <button aria-label="Submit search">🔍</button>\n</form>'),
                starter=page('<img src="logo.png">\n<form>\n  <input id="q" type="search">\n  <button>🔍</button>\n</form>')),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
)
