"""HTML & CSS - Intermediate and Advanced sections (units 9-16).

Run exercises render in a script-less sandboxed frame (600x400) and read back text, counts,
attributes or COMPUTED CSS values, so every check here is something the browser itself reports.
"""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit

PAGE = "<!DOCTYPE html>\n<html>\n  <head>\n    <title>My page</title>\n  </head>\n  <body>\n    \n  </body>\n</html>\n"
STYLED = "<!DOCTYPE html>\n<html>\n  <head>\n    <title>My page</title>\n    <style>\n      \n    </style>\n  </head>\n  <body>\n    \n  </body>\n</html>\n"


def page(body: str, style: str = "", head: str = "") -> str:
    h = "    <title>My page</title>\n" + head + (f"    <style>\n{style}\n    </style>\n" if style else "")
    inner = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"<!DOCTYPE html>\n<html>\n  <head>\n{h}  </head>\n  <body>\n{inner}\n  </body>\n</html>\n"


def styled(css: str, body: str, head: str = "") -> str:
    return page(body, "\n".join("      " + line for line in css.split("\n")), head)


def starter_with(body: str) -> str:
    """A styled starter whose body already holds the markup, so the lesson is about the CSS."""
    return styled("", body)


INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · Forms in depth",
        lesson(
            "Built-in validation",
            "Browsers validate forms before submitting - no JavaScript needed:\n\n<input type=\"email\" name=\"email\" required>\n<input type=\"number\" min=\"1\" max=\"10\" step=\"1\">\n<input name=\"code\" pattern=\"[A-Z]{3}[0-9]{2}\" title=\"3 letters + 2 digits\">\n<input name=\"user\" minlength=\"3\" maxlength=\"20\">\n\nClient-side validation is for convenience - ALWAYS validate again on the server.",
            mcq("Is browser validation enough for security?", ["No - always validate on the server too", "Yes", "Only with HTTPS", "Only for email"], 0),
            fill("Make the field mandatory.", '<input name="email" ___>', "required"),
            mcq("What does pattern=\"[0-9]{4}\" require?", ["Exactly four digits", "Up to four digits", "Four letters", "Any number"], 0),
            mcq("Which input type gives mobile users an email keyboard and checks the format?", ['type="email"', 'type="text"', 'type="mail"', 'type="address"'], 0),
            run("Make a sign-up form with: an email input named email that is required; a password input named password with minlength 8; a number input named age with min 13 and max 120; and a submit button.", "html",
                [t("email required", selector="input[name=email]", prop="attr:required"), t("email type", selector="input[name=email]", prop="attr:type"),
                 t("password minlength", selector="input[name=password]", prop="attr:minlength"), t("age min", selector="input[name=age]", prop="attr:min"),
                 t("age max", selector="input[name=age]", prop="attr:max"), t("submit", selector="form button, form input[type=submit]", prop="count")],
                ["", "email", "8", "13", "120", "1"],
                page('<form>\n  <input type="email" name="email" required>\n  <input type="password" name="password" minlength="8">\n  <input type="number" name="age" min="13" max="120">\n  <button type="submit">Sign up</button>\n</form>'),
                starter=PAGE),
        ),
        lesson(
            "Choices: select, radio, checkbox",
            "Let users pick from options:\n\n<select name=\"plan\">\n  <option value=\"free\">Free</option>\n  <option value=\"pro\" selected>Pro</option>\n</select>\n\n<input type=\"radio\" name=\"size\" value=\"s\" id=\"s\"> <label for=\"s\">Small</label>\n<input type=\"radio\" name=\"size\" value=\"m\" id=\"m\"> <label for=\"m\">Medium</label>\n\nRadios sharing a name form ONE group (pick one). Checkboxes are independent. Group related controls in <fieldset> with a <legend>.",
            mcq("What makes radio buttons a single group?", ["The same name attribute", "The same id", "Being in a <div>", "The same value"], 0),
            fill("Pre-select an option.", '<option value="pro" ___>Pro</option>', "selected"),
            mcq("What does <legend> do?", ["Captions a <fieldset>", "Adds a tooltip", "Labels a link", "Creates a list"], 0),
            mcq("Which lets users choose several independent options?", ["Checkboxes", "Radios", "<select> (single)", "A text input"], 0),
            run("Build a fieldset with legend Size containing three radio inputs in the group size (values s, m, l), each with a matching <label for>. Make m checked.", "html",
                [t("legend", selector="fieldset legend", prop="text"), t("radios", selector="input[type=radio][name=size]", prop="count"),
                 t("labels", selector="label[for]", prop="count"), t("checked", selector="input[type=radio]:checked", prop="attr:value")],
                ["Size", "3", "3", "m"],
                page('<fieldset>\n  <legend>Size</legend>\n  <input type="radio" name="size" value="s" id="size-s"> <label for="size-s">Small</label>\n  <input type="radio" name="size" value="m" id="size-m" checked> <label for="size-m">Medium</label>\n  <input type="radio" name="size" value="l" id="size-l"> <label for="size-l">Large</label>\n</fieldset>'),
                starter=PAGE),
        ),
        lesson(
            "Styling form states",
            "CSS can react to form state:\n\ninput:focus { outline: 2px solid blue; }\ninput:invalid { border-color: red; }\ninput:required { ... }\ninput:disabled { opacity: 0.5; }\ninput:checked + label { font-weight: bold; }\ninput::placeholder { color: gray; }\n\nNever remove focus outlines without providing a visible replacement - keyboard users rely on them.",
            mcq("Which pseudo-class matches a field whose value fails validation?", [":invalid", ":error", ":wrong", ":bad"], 0),
            fill("Style the placeholder text.", "input::___ { color: gray; }", "placeholder"),
            mcq("Why keep visible focus styles?", ["Keyboard users need to see where they are", "SEO", "Speed", "They're required by HTML"], 0),
            mcq("What does input:checked + label select?", ["The label right after a checked input", "All labels", "Checked labels", "The input"], 0),
            run("The markup is given. Write CSS so required inputs get a 2px solid border, empty-required (invalid) inputs have border-color rgb(220, 38, 38), and disabled inputs have opacity 0.5.", "html",
                [t("invalid border", selector="#name", prop="border-top-color"), t("border width", selector="#name", prop="border-top-width"),
                 t("valid border", selector="#city", prop="border-top-color"), t("disabled", selector="#zip", prop="opacity")],
                ["rgb(220, 38, 38)", "2px", "rgb(0, 0, 0)", "0.5"],
                styled("input:required {\n  border: 2px solid black;\n}\ninput:invalid {\n  border-color: rgb(220, 38, 38);\n}\ninput:disabled {\n  opacity: 0.5;\n}",
                       '<input id="name" required>\n<input id="city" required value="Oslo">\n<input id="zip" disabled>'),
                starter=starter_with('<input id="name" required>\n<input id="city" required value="Oslo">\n<input id="zip" disabled>'),
                require=[r":invalid", r":disabled"]),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · Selectors & the cascade",
        lesson(
            "Combinators & attribute selectors",
            "Combine selectors to target precisely:\n\nnav a          descendant (any depth)\nul > li        direct child\nh2 + p         the next sibling\nh2 ~ p         all following siblings\n\nAttribute selectors:\na[target]               has the attribute\na[href^=\"https\"]        starts with\na[href$=\".pdf\"]         ends with\ninput[type=\"email\"]     equals",
            mcq("What does ul > li match?", ["li elements that are direct children of ul", "Any li inside ul", "The li after a ul", "ul inside li"], 0),
            fill("Links whose href ends with .pdf.", 'a[href___".pdf"]', "$="),
            mcq("What does h2 + p select?", ["The paragraph immediately after an h2", "All paragraphs after h2", "Paragraphs inside h2", "Both h2 and p"], 0),
            mcq("Which matches every link starting with https?", ['a[href^="https"]', 'a[href$="https"]', 'a[href*="https"]only', 'a:https'], 0),
            run("Without adding classes, style: external links (href starting with https) color rgb(22, 163, 74); PDF links font-weight 700; and only the paragraph directly after the h2 gets font-size 20px.", "html",
                [t("external", selector="#ext", prop="color"), t("pdf", selector="#pdf", prop="font-weight"), t("first p", selector="#p1", prop="font-size"), t("second p", selector="#p2", prop="font-size")],
                ["rgb(22, 163, 74)", "700", "20px", "16px"],
                styled('a[href^="https"] {\n  color: rgb(22, 163, 74);\n}\na[href$=".pdf"] {\n  font-weight: 700;\n}\nh2 + p {\n  font-size: 20px;\n}',
                       '<a id="ext" href="https://example.com">Site</a>\n<a id="pdf" href="/guide.pdf">Guide</a>\n<h2>Intro</h2>\n<p id="p1">Lead paragraph.</p>\n<p id="p2">Body text.</p>'),
                starter=starter_with('<a id="ext" href="https://example.com">Site</a>\n<a id="pdf" href="/guide.pdf">Guide</a>\n<h2>Intro</h2>\n<p id="p1">Lead paragraph.</p>\n<p id="p2">Body text.</p>'),
                forbid=[r"#ext|#pdf|#p1"], hint="Use attribute selectors and the + combinator, not ids."),
        ),
        lesson(
            "Specificity",
            "When rules conflict, the more SPECIFIC selector wins (then the later one):\n\ninline style       1,0,0,0\n#id               0,1,0,0\n.class, [attr], :hover   0,0,1,0\ntag, ::before     0,0,0,1\n\n#nav a (0,1,0,1) beats .menu a.link (0,0,2,1).\n!important overrides all of this - avoid it except as a last resort. Keep specificity low and flat (one class per rule) for maintainable CSS.",
            mcq("Which wins: .btn.primary or #save?", ["#save", ".btn.primary", "The later one", "Neither"], 0),
            mcq("Two selectors have equal specificity. Which wins?", ["The one that appears later", "The first", "Neither", "The shorter"], 0),
            fill("Specificity of .card p", "0,0,1,___", "1"),
            mcq("Why avoid !important?", ["It breaks the normal cascade and is hard to override", "It's slow", "It's invalid", "Browsers ignore it"], 0),
            mcq("What color is the text?", ["green", "red", "blue", "black"], 0,
                code='<p id="x" class="note">Hi</p>\n\n#x { color: green; }\n.note { color: red; }\np.note { color: blue; }'),
        ),
        lesson(
            "Pseudo-classes & pseudo-elements",
            "Structural pseudo-classes:\nli:first-child   li:last-child   li:nth-child(2n)   li:nth-child(3)   p:not(.intro)\n\nPseudo-elements create virtual elements:\n.price::before { content: \"$\"; }\np::first-line { font-weight: bold; }\n\nPseudo-classes use one colon (:), pseudo-elements two (::).",
            mcq("What does li:nth-child(2n) match?", ["Every even item", "The second item", "Every odd item", "The last two"], 0),
            fill("Insert text before an element.", '.price::before { ___: "$"; }', "content"),
            mcq("How many colons does a pseudo-element use?", ["Two (::)", "One (:)", "None", "Three"], 0),
            mcq("What does p:not(.intro) select?", ["Paragraphs without the intro class", "Only .intro", "Nothing", "Elements that aren't p"], 0),
            run("Style the given list: even items get background-color rgb(240, 253, 244), the first item font-weight 700, the last item has no bottom border (border-bottom-style none) while others have 1px solid borders.", "html",
                [t("even bg", selector="li:nth-of-type(2)", prop="background-color"), t("odd bg", selector="li:nth-of-type(3)", prop="background-color"),
                 t("first bold", selector="li:nth-of-type(1)", prop="font-weight"), t("middle border", selector="li:nth-of-type(2)", prop="border-bottom-style"),
                 t("last border", selector="li:nth-of-type(4)", prop="border-bottom-style")],
                ["rgb(240, 253, 244)", "rgba(0, 0, 0, 0)", "700", "solid", "none"],
                styled("li {\n  border-bottom: 1px solid #ccc;\n}\nli:nth-child(even) {\n  background-color: rgb(240, 253, 244);\n}\nli:first-child {\n  font-weight: 700;\n}\nli:last-child {\n  border-bottom: none;\n}",
                       "<ul>\n  <li>One</li>\n  <li>Two</li>\n  <li>Three</li>\n  <li>Four</li>\n</ul>"),
                starter=starter_with("<ul>\n  <li>One</li>\n  <li>Two</li>\n  <li>Three</li>\n  <li>Four</li>\n</ul>"),
                require=[r":nth-child|:nth-of-type", r":last-child|:last-of-type"]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Layout in depth",
        lesson(
            "Grid template areas",
            "Name the regions of a layout and place items by name:\n\n.page {\n  display: grid;\n  grid-template-columns: 150px 1fr;\n  grid-template-areas:\n    \"header header\"\n    \"side   main\"\n    \"footer footer\";\n}\nheader { grid-area: header; }\naside  { grid-area: side; }\n\nThe ASCII-art layout is easy to read and to rearrange in media queries.",
            mcq("What does grid-area: side do on an item?", ["Places it in the area named side", "Sets its width", "Hides it", "Creates a new grid"], 0),
            fill("Name the layout regions.", "grid-template-___: \"header header\" \"side main\";", "areas"),
            mcq("How do you make the header span both columns?", ['Repeat its name: "header header"', "colspan=2", "width: 200%", "float: both"], 0),
            mcq("What does a . in grid-template-areas mean?", ["An empty cell", "A class", "Any area", "A gap"], 0),
            run("The layout has header, aside, main and footer inside .page. Make .page a grid 600px wide (body margin 0) with columns 200px 1fr and areas header header / side main / footer footer.", "html",
                [t("main left", selector="main", prop="width"), t("header width", selector="header", prop="width"), t("aside width", selector="aside", prop="width"),
                 t("footer width", selector="footer", prop="width")],
                ["400px", "600px", "200px", "600px"],
                styled('body {\n  margin: 0;\n}\n.page {\n  display: grid;\n  width: 600px;\n  grid-template-columns: 200px 1fr;\n  grid-template-areas:\n    "header header"\n    "side main"\n    "footer footer";\n}\nheader {\n  grid-area: header;\n}\naside {\n  grid-area: side;\n}\nmain {\n  grid-area: main;\n}\nfooter {\n  grid-area: footer;\n}',
                       '<div class="page">\n  <header>Header</header>\n  <aside>Menu</aside>\n  <main>Content</main>\n  <footer>Footer</footer>\n</div>'),
                starter=starter_with('<div class="page">\n  <header>Header</header>\n  <aside>Menu</aside>\n  <main>Content</main>\n  <footer>Footer</footer>\n</div>'),
                require=[r"grid-template-areas", r"grid-area"]),
        ),
        lesson(
            "Responsive grids without media queries",
            "repeat(auto-fit, minmax(...)) creates as many columns as fit:\n\n.cards {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\n  gap: 16px;\n}\n\nEach card is at least 150px; extra space is shared. On a phone you get 1 column, on a laptop 4+ - with zero media queries.",
            mcq("What does minmax(150px, 1fr) mean?", ["At least 150px, at most one share of free space", "Exactly 150px", "150 columns", "Between 1 and 150 pixels"], 0),
            fill("Fit as many columns as possible.", "repeat(auto-___, minmax(150px, 1fr))", "fit"),
            mcq("auto-fit vs auto-fill: which collapses empty tracks so items stretch?", ["auto-fit", "auto-fill", "Both", "Neither"], 0),
            mcq("What does gap add?", ["Space between grid tracks", "Padding inside items", "Margins outside the grid", "Borders"], 0),
            run("With body margin 0 and .cards exactly 600px wide, make .cards a grid with repeat(auto-fit, minmax(180px, 1fr)) and gap 0. Six cards should form 3 columns of 200px.", "html",
                [t("columns", selector=".cards", prop="grid-template-columns"), t("card width", selector=".card", prop="width")],
                ["200px 200px 200px", "200px"],
                styled("body {\n  margin: 0;\n}\n.cards {\n  width: 600px;\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));\n  gap: 0;\n}",
                       '<div class="cards">\n  <div class="card">1</div>\n  <div class="card">2</div>\n  <div class="card">3</div>\n  <div class="card">4</div>\n  <div class="card">5</div>\n  <div class="card">6</div>\n</div>'),
                starter=starter_with('<div class="cards">\n  <div class="card">1</div>\n  <div class="card">2</div>\n  <div class="card">3</div>\n  <div class="card">4</div>\n  <div class="card">5</div>\n  <div class="card">6</div>\n</div>'),
                require=[r"auto-fit|auto-fill", r"minmax"]),
        ),
        lesson(
            "Positioning",
            "position changes how an element is placed:\n\nstatic    - normal flow (default)\nrelative  - offset from its normal spot; becomes a containing block\nabsolute  - removed from flow, placed relative to the nearest positioned ancestor\nfixed     - relative to the viewport (stays when scrolling)\nsticky    - normal until it hits an offset, then sticks\n\nz-index orders overlapping positioned elements.",
            mcq("An absolute element is placed relative to…", ["Its nearest positioned ancestor", "The body always", "The previous sibling", "The viewport always"], 0),
            fill("Keep a header visible at the top while scrolling its section.", "position: ___; top: 0;", "sticky"),
            mcq("Which value does NOT take the element out of normal flow?", ["relative", "absolute", "fixed", "none of these"], 0),
            mcq("What does z-index affect?", ["Stacking order of overlapping positioned elements", "Zoom", "Font size", "Grid order"], 0),
            run("Place a .badge in the top-right corner of .card: .card is position relative, 300px × 200px; .badge is absolute with top 8px and right 8px, 40px wide.", "html",
                [t("card position", selector=".card", prop="position"), t("badge position", selector=".badge", prop="position"),
                 t("top", selector=".badge", prop="top"), t("right", selector=".badge", prop="right"), t("left (computed)", selector=".badge", prop="left")],
                ["relative", "absolute", "8px", "8px", "252px"],
                styled(".card {\n  position: relative;\n  width: 300px;\n  height: 200px;\n}\n.badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n  width: 40px;\n}",
                       '<div class="card">\n  <span class="badge">New</span>\n</div>'),
                starter=starter_with('<div class="card">\n  <span class="badge">New</span>\n</div>'),
                require=[r"position\s*:\s*relative", r"position\s*:\s*absolute"]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Responsive design",
        lesson(
            "Media queries",
            "Media queries apply CSS only when conditions match:\n\n.grid { grid-template-columns: 1fr; }          /* mobile first */\n@media (min-width: 700px) {\n  .grid { grid-template-columns: 1fr 1fr; }\n}\n@media (prefers-reduced-motion: reduce) { * { animation: none; } }\n\nMobile-first: write the small-screen styles first, then ADD complexity with min-width queries. Don't forget <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.",
            mcq("What does mobile-first mean?", ["Base styles for small screens, min-width queries for bigger ones", "Only support phones", "max-width queries only", "Phones load first"], 0),
            fill("Apply styles on screens at least 700px wide.", "@media (___-width: 700px) { }", "min"),
            mcq("Why is the viewport meta tag needed?", ["Otherwise phones render a zoomed-out desktop width", "SEO", "Fonts", "It isn't"], 0),
            mcq("prefers-reduced-motion lets you…", ["Respect users who want less animation", "Speed up pages", "Detect phones", "Disable CSS"], 0),
            run("The preview frame is 600px wide. Mobile-first: .box has font-size 14px by default, 18px at min-width 500px, and 24px at min-width 900px.", "html",
                [t("font size at 600px", selector=".box", prop="font-size")], ["18px"],
                styled(".box {\n  font-size: 14px;\n}\n@media (min-width: 500px) {\n  .box {\n    font-size: 18px;\n  }\n}\n@media (min-width: 900px) {\n  .box {\n    font-size: 24px;\n  }\n}",
                       '<div class="box">Responsive</div>'),
                starter=starter_with('<div class="box">Responsive</div>'),
                require=[r"@media\s*\(\s*min-width\s*:\s*500px", r"@media\s*\(\s*min-width\s*:\s*900px"]),
        ),
        lesson(
            "Fluid sizing: clamp, min, max",
            "Make sizes scale smoothly between limits:\n\nh1 { font-size: clamp(1.5rem, 4vw, 3rem); }   /* min, preferred, max */\n.wrap { width: min(100% - 2rem, 70ch); }\n.side { width: max(200px, 25%); }\n\nUnits: rem (root font size), em (parent's), vw/vh (1% of viewport), ch (width of '0'), % (of the container).",
            mcq("What does clamp(16px, 5vw, 32px) do?", ["Uses 5vw but never below 16px or above 32px", "Always 16px", "Averages the three", "Picks randomly"], 0),
            fill("Never wider than 70 characters.", "max-width: 70___;", "ch"),
            mcq("1vw is…", ["1% of the viewport width", "1 pixel", "1% of the parent", "The root font size"], 0),
            mcq("rem is relative to…", ["The root (html) font size", "The parent's font size", "The viewport", "The element itself"], 0),
            run("In the 600px-wide frame, set h1 font-size to clamp(20px, 5vw, 40px), .small to clamp(20px, 2vw, 40px) and .big to clamp(20px, 10vw, 40px).", "html",
                [t("preferred wins", selector="h1", prop="font-size"), t("min wins", selector=".small", prop="font-size"), t("max wins", selector=".big", prop="font-size")],
                ["30px", "20px", "40px"],
                styled("h1 {\n  font-size: clamp(20px, 5vw, 40px);\n}\n.small {\n  font-size: clamp(20px, 2vw, 40px);\n}\n.big {\n  font-size: clamp(20px, 10vw, 40px);\n}",
                       '<h1>Fluid</h1>\n<p class="small">Small</p>\n<p class="big">Big</p>'),
                starter=starter_with('<h1>Fluid</h1>\n<p class="small">Small</p>\n<p class="big">Big</p>'),
                require=[r"clamp\s*\("]),
        ),
        lesson(
            "Responsive images",
            "Serve the right image for each screen:\n\n<img src=\"photo-800.jpg\"\n     srcset=\"photo-400.jpg 400w, photo-800.jpg 800w, photo-1600.jpg 1600w\"\n     sizes=\"(min-width: 800px) 50vw, 100vw\"\n     alt=\"…\" width=\"800\" height=\"600\" loading=\"lazy\">\n\n<picture> lets you switch formats or crops:\n<picture>\n  <source srcset=\"photo.avif\" type=\"image/avif\">\n  <img src=\"photo.jpg\" alt=\"…\">\n</picture>\n\nwidth/height attributes reserve space and prevent layout shift.",
            mcq("What does 800w in srcset describe?", ["That image file is 800 pixels wide", "Display it at 800px", "800 KB", "A breakpoint"], 0),
            mcq("Why set width and height on images?", ["The browser reserves space, avoiding layout shift", "To stretch them", "SEO only", "They're required"], 0),
            fill("Defer offscreen images.", '<img src="a.jpg" alt="" loading="___">', "lazy"),
            mcq("What is <source type=\"image/avif\"> inside <picture> for?", ["Use AVIF when supported, else fall back to the <img>", "Download AVIF", "Convert images", "Nothing"], 0),
            run("Add a <picture> with a <source> for photo.webp (type image/webp) and an <img> fallback photo.jpg with alt 'Mountain lake', width 800, height 600 and loading lazy.", "html",
                [t("source type", selector="picture source", prop="attr:type"), t("source srcset", selector="picture source", prop="attr:srcset"),
                 t("img alt", selector="picture img", prop="attr:alt"), t("img lazy", selector="picture img", prop="attr:loading"),
                 t("img height", selector="picture img", prop="attr:height")],
                ["image/webp", "photo.webp", "Mountain lake", "lazy", "600"],
                page('<picture>\n  <source srcset="photo.webp" type="image/webp">\n  <img src="photo.jpg" alt="Mountain lake" width="800" height="600" loading="lazy">\n</picture>'),
                starter=PAGE),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Custom properties & theming",
        lesson(
            "CSS variables",
            "Custom properties store values you can reuse and change:\n\n:root {\n  --brand: #2563eb;\n  --space: 8px;\n}\n.btn {\n  background: var(--brand);\n  padding: calc(var(--space) * 2);\n}\n\nThey cascade and inherit like normal properties, so you can override them on any element. var(--x, fallback) supplies a default.",
            mcq("Where are global variables usually declared?", [":root", "body only", "*", "html::before"], 0),
            fill("Use a variable.", "color: ___(--brand);", "var"),
            mcq("What does var(--gap, 12px) do if --gap isn't set?", ["Uses 12px", "Fails", "Uses 0", "Uses the parent gap"], 0),
            mcq("Can a custom property be overridden inside one component?", ["Yes - set it on that element", "No, they're global", "Only with !important", "Only in JS"], 0),
            run("Define --brand: rgb(37, 99, 235) and --space: 8px on :root. .btn uses background-color var(--brand) and padding calc(var(--space) * 2). Inside .danger, override --brand to rgb(220, 38, 38).", "html",
                [t("brand", selector="#ok", prop="background-color"), t("padding", selector="#ok", prop="padding-top"), t("override", selector="#del", prop="background-color")],
                ["rgb(37, 99, 235)", "16px", "rgb(220, 38, 38)"],
                styled(":root {\n  --brand: rgb(37, 99, 235);\n  --space: 8px;\n}\n.btn {\n  background-color: var(--brand);\n  padding: calc(var(--space) * 2);\n}\n.danger {\n  --brand: rgb(220, 38, 38);\n}",
                       '<button id="ok" class="btn">Save</button>\n<div class="danger">\n  <button id="del" class="btn">Delete</button>\n</div>'),
                starter=starter_with('<button id="ok" class="btn">Save</button>\n<div class="danger">\n  <button id="del" class="btn">Delete</button>\n</div>'),
                require=[r"--brand\s*:", r"var\(\s*--brand"], forbid=[r"#del|#ok"]),
        ),
        lesson(
            "Themes & dark mode",
            "Theme switching = swapping variable values:\n\n:root { --bg: white; --text: #111; }\n[data-theme=\"dark\"] { --bg: #0b0f0c; --text: #e5e7eb; }\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) { --bg: #0b0f0c; --text: #e5e7eb; }\n}\nbody { background: var(--bg); color: var(--text); }\n\ncolor-scheme: light dark; also themes form controls and scrollbars. (That's exactly how Codeingo's light/dark themes work!)",
            mcq("How does a theme switch typically work with variables?", ["Change the variables on a parent; everything using them updates", "Rewrite every rule", "Load a new page", "Use images"], 0),
            fill("Detect the OS dark setting.", "@media (prefers-color-___: dark) { }", "scheme"),
            mcq("What does color-scheme: light dark tell the browser?", ["The page supports both, so built-in UI can match", "Force dark", "Invert colors", "Nothing"], 0),
            mcq("Why keep a manual theme toggle as well?", ["Users may want a different theme than their OS", "SEO", "It's required", "Speed"], 0),
            run("Define --bg: rgb(255, 255, 255) and --text: rgb(17, 17, 17) on :root, and in [data-theme=\"dark\"] set --bg: rgb(0, 0, 0) and --text: rgb(34, 197, 94). Panels use background-color var(--bg) and color var(--text).", "html",
                [t("light bg", selector="#light", prop="background-color"), t("dark bg", selector="#dark .panel", prop="background-color"), t("dark text", selector="#dark .panel", prop="color")],
                ["rgb(255, 255, 255)", "rgb(0, 0, 0)", "rgb(34, 197, 94)"],
                styled(':root {\n  --bg: rgb(255, 255, 255);\n  --text: rgb(17, 17, 17);\n}\n[data-theme="dark"] {\n  --bg: rgb(0, 0, 0);\n  --text: rgb(34, 197, 94);\n}\n.panel {\n  background-color: var(--bg);\n  color: var(--text);\n}',
                       '<div id="light" class="panel">Light</div>\n<div id="dark" data-theme="dark">\n  <div class="panel">Dark</div>\n</div>'),
                starter=starter_with('<div id="light" class="panel">Light</div>\n<div id="dark" data-theme="dark">\n  <div class="panel">Dark</div>\n</div>'),
                require=[r"\[data-theme", r"var\(\s*--bg"]),
        ),
        lesson(
            "calc() & modern color",
            "calc mixes units: width: calc(100% - 2 * 24px);\n\nModern color syntax and functions:\nrgb(37 99 235 / 50%)          -- space-separated with alpha\nhsl(142 71% 45%)               -- hue, saturation, lightness\ncolor-mix(in srgb, var(--brand) 80%, white)   -- tints\n\nHSL makes palettes easy: keep the hue, change the lightness.",
            mcq("What does calc(100% - 48px) allow?", ["Mixing percentages and pixels", "Only pixel math", "JavaScript", "Nothing"], 0),
            mcq("In hsl(142 71% 45%), what is 142?", ["The hue angle", "Red", "Opacity", "Lightness"], 0),
            fill("Spaces around operators are required for…", "calc(100% ___ 2rem)", "-"),
            mcq("What does rgb(0 0 0 / 50%) mean?", ["Black at 50% opacity", "Grey", "Invalid", "50% red"], 0),
            run("With body margin 0, make .bar width calc(100% - 2 * 50px) inside the 600px frame and .tint background-color rgb(37 99 235 / 50%).", "html",
                [t("width", selector=".bar", prop="width"), t("alpha color", selector=".tint", prop="background-color")],
                ["500px", "rgba(37, 99, 235, 0.5)"],
                styled("body {\n  margin: 0;\n}\n.bar {\n  width: calc(100% - 2 * 50px);\n}\n.tint {\n  background-color: rgb(37 99 235 / 50%);\n}",
                       '<div class="bar">Bar</div>\n<div class="tint">Tint</div>'),
                starter=starter_with('<div class="bar">Bar</div>\n<div class="tint">Tint</div>'),
                require=[r"calc\s*\("], forbid=[r"width\s*:\s*500px"]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Motion",
        lesson(
            "Transitions",
            "Transitions animate between states:\n\n.btn {\n  transition: transform 150ms ease-out, background-color 200ms;\n}\n.btn:hover { transform: translateY(-2px); }\n\nFor smooth 60 fps, animate transform and opacity - they're handled by the compositor. Animating width, top or margin triggers layout on every frame.",
            mcq("Which properties animate most smoothly?", ["transform and opacity", "width and height", "margin and padding", "top and left"], 0),
            fill("Animate opacity over 0.3 seconds.", "transition: ___ 0.3s;", "opacity"),
            mcq("What does ease-out do?", ["Starts fast, slows at the end", "Starts slow", "Constant speed", "Bounces"], 0),
            mcq("When does a transition run?", ["When a property value changes", "On page load always", "Every second", "Only with JS"], 0),
            run("Give .card a transition of transform 200ms ease-out, and on :hover translate it up (transform: translateY(-4px)). The check reads the transition settings.", "html",
                [t("property", selector=".card", prop="transition-property"), t("duration", selector=".card", prop="transition-duration"),
                 t("timing", selector=".card", prop="transition-timing-function")],
                ["transform", "0.2s", "ease-out"],
                styled(".card {\n  transition: transform 200ms ease-out;\n}\n.card:hover {\n  transform: translateY(-4px);\n}", '<div class="card">Hover me</div>'),
                starter=starter_with('<div class="card">Hover me</div>'),
                require=[r":hover", r"translate"]),
        ),
        lesson(
            "Transforms",
            "transform moves, scales, rotates and skews WITHOUT affecting layout:\n\ntransform: translate(10px, -5px);\ntransform: scale(1.1);\ntransform: rotate(45deg);\ntransform: translateX(-50%) rotate(10deg);   /* combined, applied right-to-left */\ntransform-origin: top left;\n\nOther elements don't move - the element is painted elsewhere.",
            mcq("Does transform change the space an element takes in layout?", ["No", "Yes", "Only scale", "Only translate"], 0),
            fill("Rotate a quarter turn.", "transform: rotate(___deg);", "90"),
            mcq("What does transform-origin change?", ["The point transforms happen around", "The element's position", "The z-index", "The animation speed"], 0),
            mcq("What does scale(2) do to a 50px box visually?", ["Draws it 100px wide", "Makes it 52px", "Nothing", "Moves it"], 0),
            run("Make .spinner rotate 45deg, .zoom scale to 1.5, and .shift translate 20px right. The checks read the computed transform matrices.", "html",
                [t("rotate", selector=".spinner", prop="transform"), t("scale", selector=".zoom", prop="transform"), t("translate", selector=".shift", prop="transform")],
                ["matrix(0.707107, 0.707107, -0.707107, 0.707107, 0, 0)", "matrix(1.5, 0, 0, 1.5, 0, 0)", "matrix(1, 0, 0, 1, 20, 0)"],
                styled(".spinner {\n  transform: rotate(45deg);\n}\n.zoom {\n  transform: scale(1.5);\n}\n.shift {\n  transform: translateX(20px);\n}",
                       '<div class="spinner">A</div>\n<div class="zoom">B</div>\n<div class="shift">C</div>'),
                starter=starter_with('<div class="spinner">A</div>\n<div class="zoom">B</div>\n<div class="shift">C</div>'),
                hint="Browsers report transforms as matrix(...) values - just write rotate/scale/translate."),
        ),
        lesson(
            "Keyframe animations",
            "@keyframes define multi-step animations:\n\n@keyframes pulse {\n  0%, 100% { transform: scale(1); }\n  50%      { transform: scale(1.1); }\n}\n.dot { animation: pulse 1.2s ease-in-out infinite; }\n\nAlways respect users who prefer less motion:\n@media (prefers-reduced-motion: reduce) { .dot { animation: none; } }",
            mcq("What does infinite mean in an animation?", ["Repeat forever", "Very slow", "Never start", "Loop once"], 0),
            fill("Define an animation.", "@___ fade { from { opacity: 0; } to { opacity: 1; } }", "keyframes"),
            mcq("What do from and to equal?", ["0% and 100%", "0s and 1s", "Start and end of the page", "Nothing"], 0),
            mcq("Which media feature lets you turn animations off for sensitive users?", ["prefers-reduced-motion", "prefers-color-scheme", "hover", "orientation"], 0),
            run("Create @keyframes bounce (translateY 0 → -10px → 0) and apply it to .ball: name bounce, duration 800ms, ease-in-out, infinite.", "html",
                [t("name", selector=".ball", prop="animation-name"), t("duration", selector=".ball", prop="animation-duration"),
                 t("timing", selector=".ball", prop="animation-timing-function"), t("count", selector=".ball", prop="animation-iteration-count")],
                ["bounce", "0.8s", "ease-in-out", "infinite"],
                styled("@keyframes bounce {\n  0%,\n  100% {\n    transform: translateY(0);\n  }\n  50% {\n    transform: translateY(-10px);\n  }\n}\n.ball {\n  animation: bounce 800ms ease-in-out infinite;\n}",
                       '<div class="ball"></div>'),
                starter=starter_with('<div class="ball"></div>'),
                require=[r"@keyframes\s+bounce"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · Modern CSS",
        lesson(
            ":is, :where & :has",
            "Newer selectors cut repetition and add power:\n\n:is(h1, h2, h3) a { ... }      /* any of these */\n:where(ul, ol) { margin: 0 }   /* same, but ZERO specificity - easy to override */\n.card:has(img) { padding: 0 }  /* parent selector! a card that contains an image */\nform:has(input:invalid) button { opacity: .5 }\n\n:has lets a parent react to its children - something that used to need JavaScript.",
            mcq("What's special about :where()?", ["It always has zero specificity", "It's faster", "It only matches ids", "It selects parents"], 0),
            fill("Select cards that contain an image.", ".card:___(img)", "has"),
            mcq(":is(h1, h2) span matches…", ["spans inside h1 or h2", "only h1", "h1 and h2 themselves", "nothing"], 0),
            mcq("What did :has() make possible in pure CSS?", ["Styling a parent based on its children", "Animations", "Variables", "Grids"], 0),
            run("Using :has, give .card elements that contain an img border-color rgb(22, 163, 74) (others keep rgb(0, 0, 0)), and using :is make links inside h2 or h3 font-weight 700 in one rule.", "html",
                [t("with image", selector="#c1", prop="border-top-color"), t("without image", selector="#c2", prop="border-top-color"),
                 t("h2 link", selector="h2 a", prop="font-weight"), t("h3 link", selector="h3 a", prop="font-weight"), t("p link", selector="p a", prop="font-weight")],
                ["rgb(22, 163, 74)", "rgb(0, 0, 0)", "700", "700", "400"],
                styled(".card {\n  border: 2px solid rgb(0, 0, 0);\n}\n.card:has(img) {\n  border-color: rgb(22, 163, 74);\n}\n:is(h2, h3) a {\n  font-weight: 700;\n}\nh2,\nh3 {\n  font-weight: 400;\n}",
                       '<div id="c1" class="card"><img src="a.png" alt="A" width="10" height="10"></div>\n<div id="c2" class="card">Text only</div>\n<h2><a href="#">Two</a></h2>\n<h3><a href="#">Three</a></h3>\n<p><a href="#">Para</a></p>'),
                starter=styled(".card {\n  border: 2px solid rgb(0, 0, 0);\n}\nh2,\nh3 {\n  font-weight: 400;\n}",
                               '<div id="c1" class="card"><img src="a.png" alt="A" width="10" height="10"></div>\n<div id="c2" class="card">Text only</div>\n<h2><a href="#">Two</a></h2>\n<h3><a href="#">Three</a></h3>\n<p><a href="#">Para</a></p>'),
                require=[r":has\(", r":is\("], forbid=[r"#c1"]),
        ),
        lesson(
            "aspect-ratio & object-fit",
            "aspect-ratio keeps a shape as the width changes:\n.video { width: 100%; aspect-ratio: 16 / 9; }\n.avatar { width: 64px; aspect-ratio: 1; border-radius: 50%; }\n\nobject-fit controls how images fill their box:\ncover - fill and crop    contain - fit inside, letterbox    fill - stretch (default)\nobject-position picks the focal point.",
            mcq("What does aspect-ratio: 16 / 9 do with width 320px?", ["Height becomes 180px", "Width becomes 16px", "Nothing", "Height 320px"], 0),
            fill("Fill the box and crop the overflow.", "object-fit: ___;", "cover"),
            mcq("Which object-fit shows the whole image with possible empty space?", ["contain", "cover", "fill", "none"], 0),
            mcq("aspect-ratio: 1 makes…", ["A square", "A circle", "A 1px box", "Nothing"], 0),
            run("Make .video 320px wide with aspect-ratio 16 / 9, and .avatar 64px wide, square via aspect-ratio, with object-fit cover.", "html",
                [t("video height", selector=".video", prop="height"), t("avatar height", selector=".avatar", prop="height"), t("fit", selector=".avatar", prop="object-fit")],
                ["180px", "64px", "cover"],
                styled(".video {\n  width: 320px;\n  aspect-ratio: 16 / 9;\n}\n.avatar {\n  display: block;\n  width: 64px;\n  aspect-ratio: 1;\n  object-fit: cover;\n}",
                       '<div class="video"></div>\n<img class="avatar" src="me.png" alt="Me">'),
                starter=starter_with('<div class="video"></div>\n<img class="avatar" src="me.png" alt="Me">'),
                require=[r"aspect-ratio"], forbid=[r"height\s*:\s*(180|64)px"]),
        ),
        lesson(
            "Logical properties & nesting",
            "Logical properties follow the writing direction, so layouts work in right-to-left languages:\nmargin-inline-start (instead of margin-left), padding-block (top + bottom), inline-size (width), inset: 0.\n\nNative CSS nesting (2023+) keeps related rules together:\n.card {\n  padding: 1rem;\n  & h2 { margin: 0; }\n  &:hover { outline: 2px solid; }\n}",
            mcq("What does padding-block set in a left-to-right language?", ["Top and bottom padding", "Left and right", "All four", "Only top"], 0),
            fill("Width in logical terms.", "___-size: 300px;", "inline"),
            mcq("In native CSS nesting, what does & refer to?", ["The parent selector", "Any element", "The root", "A variable"], 0),
            mcq("Why use margin-inline-start instead of margin-left?", ["It flips automatically for right-to-left text", "It's shorter", "Speed", "It's required"], 0),
            run("Using native nesting inside .card: give .card padding-block 12px and padding-inline 24px, & h2 margin-block 0, and &.wide inline-size 400px.", "html",
                [t("pad top", selector="#c", prop="padding-top"), t("pad left", selector="#c", prop="padding-left"), t("h2 margin", selector="#c h2", prop="margin-top"),
                 t("wide width", selector="#w", prop="width")],
                ["12px", "24px", "0px", "400px"],
                styled(".card {\n  padding-block: 12px;\n  padding-inline: 24px;\n  & h2 {\n    margin-block: 0;\n  }\n  &.wide {\n    inline-size: 400px;\n    box-sizing: content-box;\n  }\n}",
                       '<div id="c" class="card"><h2>Title</h2></div>\n<div id="w" class="card wide">Wide</div>'),
                starter=starter_with('<div id="c" class="card"><h2>Title</h2></div>\n<div id="w" class="card wide">Wide</div>'),
                require=[r"&", r"padding-block|padding-inline"]),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Accessibility & production",
        lesson(
            "ARIA",
            "First rule of ARIA: prefer native HTML (<button>, <nav>, <dialog>) - it's accessible for free. Use ARIA to fill gaps:\n\naria-label=\"Close\"                 name for an icon-only button\naria-expanded=\"false\"              state of a disclosure/menu\naria-describedby=\"hint\"            links help text\naria-live=\"polite\"                  announce updates (toasts)\naria-hidden=\"true\"                  hide decorative icons\naria-current=\"page\"                 the active nav link",
            mcq("What's the first rule of ARIA?", ["Use native HTML elements when possible", "Use ARIA everywhere", "Hide everything", "Only use roles"], 0),
            fill("Name an icon-only button.", '<button aria-___="Close">✕</button>', "label"),
            mcq("Which attribute announces dynamic updates to screen readers?", ["aria-live", "aria-hidden", "aria-label", "role=status only"], 0),
            mcq("Mark the current page link in navigation:", ['aria-current="page"', 'aria-selected="true"', 'class="active" only', 'aria-page'], 0),
            run("Build: a menu toggle button with aria-expanded false and aria-controls menu, an icon-only close button labelled 'Close' with a decorative <span aria-hidden=\"true\">✕</span>, a nav whose second link has aria-current page, and a <div aria-live=\"polite\"> status.", "html",
                [t("expanded", selector="button[aria-controls=menu]", prop="attr:aria-expanded"), t("close label", selector="button[aria-label]", prop="attr:aria-label"),
                 t("hidden icon", selector="button[aria-label] span", prop="attr:aria-hidden"), t("current", selector="nav a:nth-of-type(2)", prop="attr:aria-current"),
                 t("live", selector="[aria-live]", prop="attr:aria-live")],
                ["false", "Close", "true", "page", "polite"],
                page('<button aria-expanded="false" aria-controls="menu">Menu</button>\n<ul id="menu" hidden><li>Item</li></ul>\n<button aria-label="Close"><span aria-hidden="true">✕</span></button>\n<nav>\n  <a href="/">Home</a>\n  <a href="/learn" aria-current="page">Learn</a>\n</nav>\n<div aria-live="polite"></div>'),
                starter=PAGE),
        ),
        lesson(
            "Accessible focus & visually-hidden text",
            "Keyboard users must see focus and reach everything:\n\n:focus-visible { outline: 3px solid var(--brand); outline-offset: 2px; }\n\nA 'skip link' jumps past navigation. Text for screen readers only uses the visually-hidden pattern (NOT display: none, which hides it from screen readers too):\n\n.sr-only {\n  position: absolute; width: 1px; height: 1px;\n  overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap;\n}",
            mcq("Why not use display: none for screen-reader text?", ["Screen readers ignore display: none too", "It's slow", "It's invalid", "It shows the text"], 0),
            fill("Style focus only when it should be visible (keyboard).", ":focus-___ { outline: 3px solid; }", "visible"),
            mcq("What does a skip link do?", ["Lets keyboard users jump straight to the main content", "Skips ads", "Reloads the page", "Hides the menu"], 0),
            mcq("Which contrast ratio does WCAG AA require for body text?", ["4.5:1", "2:1", "10:1", "1:1"], 0),
            run("Write the .sr-only class (position absolute, width 1px, height 1px, overflow hidden, white-space nowrap) and a :focus-visible rule with a 3px solid outline. The page has a skip link as the first element.", "html",
                [t("position", selector=".sr-only", prop="position"), t("width", selector=".sr-only", prop="width"), t("overflow", selector=".sr-only", prop="overflow"),
                 t("still displayed", selector=".sr-only", prop="display"), t("skip link first", selector="body > a:first-child", prop="attr:href")],
                ["absolute", "1px", "hidden", "block", "#main"],
                styled(".sr-only {\n  position: absolute;\n  width: 1px;\n  height: 1px;\n  overflow: hidden;\n  clip: rect(0 0 0 0);\n  white-space: nowrap;\n}\n:focus-visible {\n  outline: 3px solid;\n}",
                       '<a href="#main">Skip to content</a>\n<nav>Menu</nav>\n<main id="main">\n  <button>Save <span class="sr-only">your profile</span></button>\n</main>'),
                starter=starter_with('<a href="#main">Skip to content</a>\n<nav>Menu</nav>\n<main id="main">\n  <button>Save <span class="sr-only">your profile</span></button>\n</main>'),
                require=[r":focus-visible"], forbid=[r"display\s*:\s*none"]),
        ),
        lesson(
            "Head, SEO & performance",
            "A production <head>:\n\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Unique, descriptive title</title>\n<meta name=\"description\" content=\"…\">\n<link rel=\"icon\" href=\"/favicon.svg\">\n<meta property=\"og:title\" content=\"…\">     <!-- link previews -->\n<link rel=\"preload\" href=\"/font.woff2\" as=\"font\" type=\"font/woff2\" crossorigin>\n\nAlso: lazy-load offscreen images, defer scripts (<script defer>), and set lang on <html>.",
            mcq("Which meta tag controls the search-result snippet?", ['name="description"', 'name="keywords"', 'charset', 'name="robots" only'], 0),
            fill("Social link-preview title.", '<meta property="og:___" content="Codeingo">', "title"),
            mcq("What does <script defer> do?", ["Downloads in parallel and runs after the HTML is parsed", "Never runs", "Runs first", "Blocks rendering"], 0),
            mcq("Why set lang=\"en\" on <html>?", ["Screen readers and translators use it", "SEO only", "Fonts", "It's required to render"], 0),
            run("Write a full page with lang=\"en\" on <html> and a head containing meta charset utf-8, the viewport meta tag, title 'Codeingo - Learn to code', a meta description, and an og:title meta.", "html",
                [t("lang", selector="html", prop="attr:lang"), t("charset", selector="meta[charset]", prop="attr:charset"),
                 t("viewport", selector="meta[name=viewport]", prop="attr:content"), t("title", selector="title", prop="text"),
                 t("description", selector="meta[name=description]", prop="count"), t("og", selector="meta[property='og:title']", prop="count")],
                ["en", "utf-8", "width=device-width, initial-scale=1", "Codeingo - Learn to code", "1", "1"],
                '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Codeingo - Learn to code</title>\n    <meta name="description" content="Bite-sized coding lessons with real code.">\n    <meta property="og:title" content="Codeingo">\n  </head>\n  <body>\n    <h1>Codeingo</h1>\n  </body>\n</html>\n',
                starter=PAGE),
        ),
    ),
)
