from .dsl import code, course, fill, lesson, mcq, order, run, t, unit
from .java_adv import ADVANCED, INTERMEDIATE
from .java_expert import EXPERT
from .java_expert2 import EXPERT2

MAIN = "public class Main {\n    public static void main(String[] args) {\n        \n    }\n}\n"
SCAN = "import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        \n    }\n}\n"


def prog(body: str, imports: str = "", extra: str = "") -> str:
    """Wrap statements in a Main class (4-space indented body)."""
    inner = "\n".join(("        " + line) if line else "" for line in body.split("\n"))
    return f"{imports}public class Main {{\n{extra}    public static void main(String[] args) {{\n{inner}\n    }}\n}}\n"


def scan(body: str, extra: str = "") -> str:
    return prog("Scanner in = new Scanner(System.in);\n" + body, "import java.util.Scanner;\n\n", extra)


COURSE = course(
    "java", "Java", "☕", "Strongly-typed and object-oriented - powers Android apps and big backends.",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · First programs",
        lesson(
            "Your first program",
            "Every Java program lives in a class, and starts running in main:\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello!\");\n    }\n}\n\nStatements end with ; and code blocks go in { }.",
            order("Order the lines to make a valid program.",
                  ["public class Main {", "    public static void main(String[] args) {", '        System.out.println("Hello");', "    }", "}"]),
            fill("Print a line in Java.", 'System.out.___("Hi");', "println"),
            mcq("Which method does Java run first?", ["main", "start", "run", "init"], 0),
            mcq("Java statements end with…", [";", ":", ".", "nothing"], 0),
            run("Print exactly: Hello, Java!", "java", [t("Run")], ["Hello, Java!"], prog('System.out.println("Hello, Java!");'), starter=MAIN,
                fallback=[r'System\.out\.println\(\s*"Hello, Java!"\s*\)\s*;']),
        ),
        lesson(
            "print vs println & comments",
            "println prints and then moves to a new line; print stays on the same line:\n\nSystem.out.print(\"A\");\nSystem.out.print(\"B\");\nSystem.out.println(\"C\");   // ABC then a newline\n\nComments: // one line   /* many lines */\nEscape sequences inside strings: \\n new line, \\t tab, \\\" a quote.",
            mcq("What is printed?", ["AB", "A\nB", "A B", "BA"], 0, "print doesn't add a newline.", code='System.out.print("A");\nSystem.out.print("B");'),
            mcq("Which is a Java comment?", ["// note", "# note", "<!-- note -->", "-- note"], 0),
            fill("Put a line break inside the string.", 'System.out.print("Line 1___Line 2");', "\\n"),
            mcq("How do you print a double quote inside a string?", ['\\"', "''", '""', "/\""], 0),
            run("Print this exact 3-line box using println:\n+--+\n|  |\n+--+", "java", [t("Run")], ["+--+\n|  |\n+--+"],
                prog('System.out.println("+--+");\nSystem.out.println("|  |");\nSystem.out.println("+--+");'), starter=MAIN,
                fallback=[r"println\(\s*\"\+--\+\"", r"println\(\s*\"\|  \|\""]),
        ),
        lesson(
            "Arithmetic",
            "Java does maths with + - * / and % (remainder):\n\nSystem.out.println(7 + 3);   // 10\nSystem.out.println(7 / 2);   // 3   (int / int drops the decimals!)\nSystem.out.println(7.0 / 2); // 3.5\nSystem.out.println(7 % 2);   // 1\n\nMath.pow(2, 3) is 8.0, Math.sqrt(16) is 4.0.",
            mcq("What is 7 / 2 in Java (both ints)?", ["3", "3.5", "4", "An error"], 0, "Integer division drops the remainder."),
            mcq("What is 7.0 / 2?", ["3.5", "3", "3.0", "4"], 0, "One decimal operand makes it decimal division."),
            mcq("What is 17 % 5?", ["2", "3", "3.4", "5"], 0),
            fill("Square root of 81.", "double r = Math.___(81);", "sqrt"),
            run("Print the number of seconds in a day, then in a week - each on its own line (calculate them, don't type the answers).", "java",
                [t("Run")], ["86400\n604800"], prog("System.out.println(60 * 60 * 24);\nSystem.out.println(60 * 60 * 24 * 7);"), starter=MAIN,
                require=[r"\*"], forbid=[r"86400|604800"], fallback=[r"60\s*\*\s*60\s*\*\s*24"]),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Variables & types",
        lesson(
            "Primitive types",
            "Java variables have a fixed type:\n\nint age = 20;          // whole numbers\ndouble price = 9.99;   // decimals\nchar grade = 'A';      // one character (single quotes)\nboolean ok = true;     // true / false\nlong big = 9000000000L;\n\nYou can't put a value of the wrong type in a variable.",
            mcq("Which type stores whole numbers?", ["int", "double", "boolean", "char"], 0),
            mcq("Which is a valid char?", ["'A'", '"A"', "A", "'AB'"], 0, "chars use single quotes and hold exactly one character."),
            fill("Declare a decimal variable.", "___ price = 4.99;", "double"),
            mcq("What happens?", ["Compile error", "x becomes 3", "x becomes 3.7", "x becomes 4"], 0, "A double can't go into an int without a cast.", code="int x = 3.7;"),
            run("Declare int apples = 7 and int friends = 2. Print how many apples each friend gets and how many are left, as: 3 each, 1 left", "java",
                [t("Run")], ["3 each, 1 left"], prog('int apples = 7;\nint friends = 2;\nSystem.out.println(apples / friends + " each, " + apples % friends + " left");'),
                starter=MAIN, require=[r"int\s+apples\s*=\s*7", r"%"], fallback=[r"int\s+apples\s*=\s*7", r"apples\s*/\s*friends", r"apples\s*%\s*friends"]),
        ),
        lesson(
            "Strings",
            "String (capital S) holds text. Join with +:\n\nString name = \"Ada\";\nString msg = \"Hi \" + name + \"!\";\nname.length()        // 3\nname.toUpperCase()   // \"ADA\"\nname.charAt(0)       // 'A'\n\nCompare strings with .equals(), NOT == :\nname.equals(\"Ada\")   // true",
            mcq("How should you compare two Strings for equal text?", ["a.equals(b)", "a == b", "a = b", "a.compare(b)"], 0),
            mcq("What is \"Java\".length()?", ["4", "3", "5", "An error"], 0),
            fill("Get the first character of s.", "char first = s.___(0);", "charAt"),
            mcq("What is \"Score: \" + 5 + 5?", ['"Score: 55"', '"Score: 10"', "An error", '"Score: 5 5"'], 0, "Left to right: string + 5 gives a string, then + 5 appends."),
            run("Read a name (one line) and print: Hello, <NAME>! with the name in capitals.", "java",
                [t("ada", stdin="ada"), t("Linus", stdin="Linus")], ["Hello, ADA!", "Hello, LINUS!"],
                scan('String name = in.nextLine();\nSystem.out.println("Hello, " + name.toUpperCase() + "!");'), starter=SCAN,
                fallback=[r"nextLine\(\)", r"toUpperCase\(\)"]),
        ),
        lesson(
            "Casting & constants",
            "Convert between number types by casting:\n\ndouble d = 9.8;\nint i = (int) d;     // 9 (drops the decimals)\ndouble avg = (double) 7 / 2;   // 3.5\n\nConvert text to numbers: Integer.parseInt(\"42\"), Double.parseDouble(\"3.5\").\n\nfinal makes a constant: final double PI = 3.14159;",
            mcq("What is (int) 9.99?", ["9", "10", "9.99", "An error"], 0, "Casting to int cuts off the decimal part."),
            mcq("What is (double) 7 / 2?", ["3.5", "3", "3.0", "4"], 0),
            fill("Turn \"42\" into an int.", 'int n = Integer.___("42");', "parseInt"),
            mcq("What does final do?", ["Makes a variable a constant", "Ends the program", "Deletes a variable", "Makes it public"], 0),
            run("Read two whole numbers (on separate lines) and print their average with a decimal point (e.g. 3.5).", "java",
                [t("3 and 4", stdin="3\n4"), t("10 and 20", stdin="10\n20"), t("1 and 2", stdin="1\n2")], ["3.5", "15.0", "1.5"],
                scan("int a = in.nextInt();\nint b = in.nextInt();\nSystem.out.println((a + b) / 2.0);"), starter=SCAN,
                fallback=[r"nextInt\(\)", r"2\.0|\(double\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Decisions",
        lesson(
            "if / else",
            "if runs code when a condition is true:\n\nif (score >= 50) {\n    System.out.println(\"Pass\");\n} else if (score >= 40) {\n    System.out.println(\"Almost\");\n} else {\n    System.out.println(\"Fail\");\n}\n\nComparisons: == != < > <= >=",
            mcq("What is printed for score = 45?", ["Almost", "Pass", "Fail", "Nothing"], 0,
                code='if (score >= 50) {\n    System.out.println("Pass");\n} else if (score >= 40) {\n    System.out.println("Almost");\n} else {\n    System.out.println("Fail");\n}'),
            fill("Conditions go inside…", "if ___x > 0) { }", "("),
            order("Order the check.", ["if (age >= 18) {", '    System.out.println("Adult");', "} else {", '    System.out.println("Minor");', "}"]),
            mcq("Which operator means 'not equal'?", ["!=", "<>", "=!", "~="], 0),
            run("Read a whole number and print Positive, Negative or Zero.", "java",
                [t("5", stdin="5"), t("-8", stdin="-8"), t("0", stdin="0")], ["Positive", "Negative", "Zero"],
                scan('int n = in.nextInt();\nif (n > 0) {\n    System.out.println("Positive");\n} else if (n < 0) {\n    System.out.println("Negative");\n} else {\n    System.out.println("Zero");\n}'),
                starter=SCAN, require=[r"\bif\s*\("], fallback=[r"\bif\s*\(\s*n\s*>\s*0", r"else", r"Negative"]),
        ),
        lesson(
            "Logical operators",
            "Combine conditions:\n\n&&  and  - both true\n||  or   - at least one true\n!   not  - flips true/false\n\nif (age >= 13 && age <= 19) { ... }\nif (day.equals(\"Sat\") || day.equals(\"Sun\")) { ... }",
            mcq("What is true && false?", ["false", "true", "An error", "null"], 0),
            mcq("What is !(5 > 3)?", ["false", "true", "5", "An error"], 0),
            fill("True when either is true.", "boolean weekend = isSat ___ isSun;", "||"),
            mcq("Which checks 1 ≤ n ≤ 10?", ["n >= 1 && n <= 10", "1 <= n <= 10", "n >= 1 || n <= 10", "n in 1..10"], 0,
                "Java can't chain comparisons like 1 <= n <= 10."),
            run("Read a year and print Leap or Common. (Leap: divisible by 4 and not by 100, or divisible by 400.)", "java",
                [t("2024", stdin="2024"), t("1900", stdin="1900"), t("2000", stdin="2000"), t("2023", stdin="2023")],
                ["Leap", "Common", "Leap", "Common"],
                scan('int y = in.nextInt();\nif ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0) {\n    System.out.println("Leap");\n} else {\n    System.out.println("Common");\n}'),
                starter=SCAN, require=[r"&&|\|\|"], fallback=[r"%\s*4", r"%\s*100", r"%\s*400"]),
        ),
        lesson(
            "switch",
            "switch picks a branch based on one value. Modern Java has an arrow form:\n\nString name = switch (day) {\n    case 1 -> \"Mon\";\n    case 2 -> \"Tue\";\n    default -> \"Other\";\n};\n\nThe classic form needs break after each case to stop 'fall-through'.",
            mcq("In a classic switch, what does break do?", ["Stops fall-through into the next case", "Ends the program", "Skips default", "Nothing"], 0),
            fill("The branch used when no case matches.", "___ -> \"Unknown\";", "default"),
            mcq("What is x?", ['"two"', '"one"', '"other"', "An error"], 0, code='int n = 2;\nString x = switch (n) {\n    case 1 -> "one";\n    case 2 -> "two";\n    default -> "other";\n};'),
            mcq("Can a switch compare Strings in Java?", ["Yes", "No", "Only in arrow form", "Only with equals"], 0),
            run("Read a month number (1-12) and print how many days it has in a non-leap year, using a switch.", "java",
                [t("2", stdin="2"), t("4", stdin="4"), t("12", stdin="12")], ["28", "30", "31"],
                scan("int m = in.nextInt();\nint days = switch (m) {\n    case 2 -> 28;\n    case 4, 6, 9, 11 -> 30;\n    default -> 31;\n};\nSystem.out.println(days);"),
                starter=SCAN, require=[r"\bswitch\b"], fallback=[r"\bswitch\s*\(", r"28", r"30"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Loops",
        lesson(
            "while loops",
            "while repeats while its condition is true:\n\nint n = 3;\nwhile (n > 0) {\n    System.out.println(n);\n    n--;\n}\n\nn-- subtracts 1, n++ adds 1. Make sure the loop can end!",
            mcq("How many times does Hi print?", ["3", "2", "4", "Forever"], 0, code='int i = 0;\nwhile (i < 3) {\n    System.out.println("Hi");\n    i++;\n}'),
            fill("Add 1 to count.", "count___;", "++"),
            mcq("What's wrong?", ["It never ends", "Syntax error", "It never runs", "Nothing"], 0, code="int n = 0;\nwhile (n < 5) {\n    System.out.println(n);\n}"),
            order("Order the countdown.", ["int n = 3;", "while (n > 0) {", "    System.out.println(n);", "    n--;", "}"]),
            run("Read a positive whole number and print the sum of its digits (use % 10 and / 10 in a while loop).", "java",
                [t("123", stdin="123"), t("9999", stdin="9999"), t("5", stdin="5")], ["6", "36", "5"],
                scan("int n = in.nextInt();\nint sum = 0;\nwhile (n > 0) {\n    sum += n % 10;\n    n /= 10;\n}\nSystem.out.println(sum);"), starter=SCAN,
                require=[r"\bwhile\b"], fallback=[r"\bwhile\s*\(", r"%\s*10", r"/=?\s*10"]),
        ),
        lesson(
            "for loops",
            "for puts start, condition and step on one line:\n\nfor (int i = 1; i <= 5; i++) {\n    System.out.println(i);\n}\n\nCount down: for (int i = 10; i > 0; i--)\nStep by 2:  for (int i = 0; i < 10; i += 2)",
            mcq("What does this print?", ["0 2 4", "0 1 2 3 4", "2 4", "0 2 4 6"], 0, code="for (int i = 0; i < 5; i += 2) {\n    System.out.print(i + \" \");\n}"),
            fill("Loop from 1 to 10 inclusive.", "for (int i = 1; i ___ 10; i++)", "<="),
            mcq("How many times does the body run?", ["10", "9", "11", "0"], 0, code="for (int i = 0; i < 10; i++) { }"),
            code("Write a for loop header that counts i down from 5 to 1.", [r"for\s*\(\s*int\s+i\s*=\s*5\s*;\s*i\s*(>\s*0|>=\s*1)\s*;\s*i--\s*\)"],
                 "for (int i = 5; i > 0; i--)"),
            run("Read n and print the multiplication table for n from 1 to 5, formatted like: 3 x 1 = 3", "java",
                [t("3", stdin="3"), t("7", stdin="7")], ["3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15", "7 x 1 = 7\n7 x 2 = 14\n7 x 3 = 21\n7 x 4 = 28\n7 x 5 = 35"],
                scan('int n = in.nextInt();\nfor (int i = 1; i <= 5; i++) {\n    System.out.println(n + " x " + i + " = " + (n * i));\n}'), starter=SCAN,
                require=[r"\bfor\b|\bwhile\b"], fallback=[r"\bfor\s*\(", r"\*\s*i|i\s*\*"]),
        ),
        lesson(
            "Nested loops & break",
            "Loops can go inside loops - the inner one runs fully for each outer round:\n\nfor (int row = 1; row <= 3; row++) {\n    for (int col = 1; col <= row; col++) {\n        System.out.print(\"*\");\n    }\n    System.out.println();\n}\n\nbreak exits the innermost loop; continue skips to its next round.",
            mcq("How many stars are printed in total?", ["6", "3", "9", "4"], 0, "1 + 2 + 3 = 6.",
                code='for (int r = 1; r <= 3; r++) {\n    for (int c = 1; c <= r; c++) {\n        System.out.print("*");\n    }\n}'),
            fill("Skip to the next round of the loop.", "if (i % 2 == 0) ___;", "continue"),
            mcq("Which loop does break exit?", ["The innermost loop it's in", "All loops", "The outer loop", "The whole method"], 0),
            mcq("What is printed?", ["1 2", "1 2 3", "3", "1 2 3 4"], 0, code='for (int i = 1; i <= 4; i++) {\n    if (i == 3) break;\n    System.out.print(i + " ");\n}'),
            run("Read n and print a right triangle of stars with n rows (row 1 has 1 star, row n has n stars).", "java",
                [t("3", stdin="3"), t("1", stdin="1")], ["*\n**\n***", "*"],
                scan('int n = in.nextInt();\nfor (int r = 1; r <= n; r++) {\n    for (int c = 1; c <= r; c++) {\n        System.out.print("*");\n    }\n    System.out.println();\n}'),
                starter=SCAN, require=[r"for[\s\S]*for|while[\s\S]*while|for[\s\S]*while|repeat\("], fallback=[r"for\s*\([\s\S]*for\s*\(|repeat\("]),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Methods",
        lesson(
            "Defining methods",
            "A method is a named, reusable block. For now, make them static inside Main:\n\nstatic void greet(String name) {\n    System.out.println(\"Hi \" + name);\n}\n\n...then call it from main: greet(\"Ada\");\n\nvoid means the method doesn't return a value.",
            mcq("What does void mean?", ["The method returns nothing", "The method is empty", "The method is private", "It's an error"], 0),
            fill("Call the method greet with \"Bo\".", '___("Bo");', "greet"),
            mcq("Where must a method be written?", ["Inside a class, outside other methods", "Inside main", "Outside any class", "Anywhere"], 0),
            order("Order the method.", ["static void hello() {", '    System.out.println("Hello");', "}"]),
            run("Write a method static void line(int n, char c) that prints the character c n times on one line. main reads n and calls line(n, '=') then line(n, '-').",
                "java", [t("4", stdin="4"), t("1", stdin="1")], ["====\n----", "=\n-"],
                scan("int n = in.nextInt();\nline(n, '=');\nline(n, '-');",
                     extra="    static void line(int n, char c) {\n        for (int i = 0; i < n; i++) {\n            System.out.print(c);\n        }\n        System.out.println();\n    }\n\n"),
                starter=SCAN, require=[r"static\s+void\s+line\s*\("], fallback=[r"static\s+void\s+line\s*\(\s*int\s+\w+\s*,\s*char\s+\w+\s*\)", r"line\(\s*n\s*,\s*'='\s*\)"]),
        ),
        lesson(
            "Parameters & return",
            "A method can take values in (parameters) and send one back with return. The return type goes before the name:\n\nstatic int square(int n) {\n    return n * n;\n}\n\nint s = square(5);   // 25\n\nstatic boolean isEven(int n) { return n % 2 == 0; }",
            mcq("What does add(2, 3) return?", ["5", "23", "void", "An error"], 0, code="static int add(int a, int b) {\n    return a + b;\n}"),
            fill("This method returns a decimal number.", "static ___ half(int n) {\n    return n / 2.0;\n}", "double"),
            mcq("What's wrong?", ["It doesn't return a value on every path", "Nothing", "Wrong parameter type", "It needs void"], 0,
                code="static int sign(int n) {\n    if (n > 0) {\n        return 1;\n    }\n}"),
            mcq("Which call is valid for static int max(int a, int b)?", ["int m = max(3, 9);", "max(3);", 'String m = max(3, 9);', "max(3, 9, 1);"], 0),
            run("Write static int max3(int a, int b, int c) that returns the largest of three numbers. main reads three numbers and prints max3 of them.", "java",
                [t("1 9 4", stdin="1 9 4"), t("7 7 2", stdin="7 7 2"), t("-5 -2 -9", stdin="-5 -2 -9")], ["9", "7", "-2"],
                scan("int a = in.nextInt(), b = in.nextInt(), c = in.nextInt();\nSystem.out.println(max3(a, b, c));",
                     extra="    static int max3(int a, int b, int c) {\n        int m = a;\n        if (b > m) m = b;\n        if (c > m) m = c;\n        return m;\n    }\n\n"),
                starter=SCAN, require=[r"static\s+int\s+max3\s*\(", r"\breturn\b"], fallback=[r"static\s+int\s+max3\s*\(", r"\breturn\b", r"max3\("]),
        ),
        lesson(
            "Overloading",
            "Several methods can share a name if their parameters differ - that's overloading:\n\nstatic int area(int side) { return side * side; }\nstatic int area(int w, int h) { return w * h; }\n\narea(4)     // 16\narea(3, 5)  // 15\n\nJava picks the right one from the arguments.",
            mcq("What decides which overload is called?", ["The number and types of arguments", "The method's order in the file", "The return type only", "Random"], 0),
            mcq("What does area(3, 5) return?", ["15", "9", "25", "An error"], 0, code="static int area(int s) { return s * s; }\nstatic int area(int w, int h) { return w * h; }"),
            fill("Overloading means methods share the same…", "They have the same ___ but different parameters.", ["name", "method name"]),
            mcq("Is this a valid overload of static int f(int x)?", ["static int f(double x)", "static double f(int x)", "static int f(int y)", "static void f(int x)"], 0,
                "Only the parameter list can distinguish overloads, not the return type or parameter names."),
            run("Write two overloads: static String describe(int n) returning \"int n\" and static String describe(String s) returning \"text s\". main prints describe(42) then describe(\"hi\").",
                "java", [t("Run")], ["int 42\ntext hi"],
                prog('System.out.println(describe(42));\nSystem.out.println(describe("hi"));',
                     extra='    static String describe(int n) {\n        return "int " + n;\n    }\n\n    static String describe(String s) {\n        return "text " + s;\n    }\n\n'),
                starter=MAIN, require=[r"describe\s*\(\s*int\s+\w+\s*\)", r"describe\s*\(\s*String\s+\w+\s*\)"],
                fallback=[r"describe\s*\(\s*int\s+\w+\s*\)", r"describe\s*\(\s*String\s+\w+\s*\)"]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Arrays & lists",
        lesson(
            "Arrays",
            "An array holds a fixed number of values of one type:\n\nint[] nums = {4, 8, 15};\nnums[0]        // 4\nnums.length    // 3 (no brackets - it's a field)\nnums[1] = 99;\n\nint[] empty = new int[5];   // five zeros\n\nIndexes go from 0 to length - 1.",
            mcq("What is nums[2]?", ["30", "20", "10", "An error"], 0, code="int[] nums = {10, 20, 30};"),
            mcq("What happens with nums[3]?", ["ArrayIndexOutOfBoundsException", "0", "null", "30"], 0, code="int[] nums = {10, 20, 30};"),
            fill("Get how many items the array has.", "int n = nums.___;", "length"),
            mcq("What is in new int[3]?", ["0, 0, 0", "null, null, null", "Nothing - it's an error", "1, 2, 3"], 0),
            run("Read n, then n whole numbers. Print the largest one.", "java",
                [t("5 numbers", stdin="5\n3 9 2 7 4"), t("negatives", stdin="3\n-5 -1 -8"), t("one", stdin="1\n42")], ["9", "-1", "42"],
                scan("int n = in.nextInt();\nint[] nums = new int[n];\nfor (int i = 0; i < n; i++) {\n    nums[i] = in.nextInt();\n}\nint max = nums[0];\nfor (int x : nums) {\n    if (x > max) max = x;\n}\nSystem.out.println(max);"),
                starter=SCAN, require=[r"\[\s*\]"], fallback=[r"new\s+int\s*\[", r"\bfor\s*\("]),
        ),
        lesson(
            "Looping over arrays",
            "Use an index loop when you need the position:\n\nfor (int i = 0; i < nums.length; i++) {\n    System.out.println(i + \": \" + nums[i]);\n}\n\nUse an enhanced for-each loop when you only need the values:\n\nint sum = 0;\nfor (int n : nums) {\n    sum += n;\n}",
            mcq("What is printed?", ["6", "3", "123", "An error"], 0, code="int[] a = {1, 2, 3};\nint sum = 0;\nfor (int x : a) {\n    sum += x;\n}\nSystem.out.println(sum);"),
            fill("Loop over every value of nums.", "for (int n ___ nums) { }", ":"),
            mcq("Which loop gives you the index?", ["for (int i = 0; i < a.length; i++)", "for (int x : a)", "Both", "Neither"], 0),
            order("Order the loop that prints each item.", ['String[] names = {"Ada", "Bo"};', "for (String n : names) {", "    System.out.println(n);", "}"]),
            run("Read n, then n whole numbers. Print how many are above the average (use a double for the average).", "java",
                [t("1..5", stdin="5\n1 2 3 4 5"), t("all equal", stdin="3\n7 7 7"), t("one high", stdin="4\n1 1 1 9")], ["2", "0", "1"],
                scan("int n = in.nextInt();\nint[] a = new int[n];\ndouble sum = 0;\nfor (int i = 0; i < n; i++) {\n    a[i] = in.nextInt();\n    sum += a[i];\n}\ndouble avg = sum / n;\nint count = 0;\nfor (int x : a) {\n    if (x > avg) count++;\n}\nSystem.out.println(count);"),
                starter=SCAN, fallback=[r"new\s+int\s*\[", r"for\s*\([\s\S]*for\s*\("]),
        ),
        lesson(
            "ArrayList",
            "ArrayList is a resizable list:\n\nimport java.util.ArrayList;\n\nArrayList<String> names = new ArrayList<>();\nnames.add(\"Ada\");\nnames.add(\"Bo\");\nnames.get(0);       // \"Ada\"\nnames.size();       // 2\nnames.remove(\"Bo\");\nnames.contains(\"Ada\");  // true\n\nFor numbers use the wrapper type: ArrayList<Integer>.",
            mcq("How do you get the number of items in an ArrayList?", ["list.size()", "list.length", "list.length()", "list.count"], 0),
            fill("Add \"milk\" to the list.", 'shopping.___("milk");', "add"),
            mcq("Which type do you use for a list of ints?", ["ArrayList<Integer>", "ArrayList<int>", "ArrayList[int]", "IntList"], 0),
            mcq("What does list.get(1) return for [\"a\", \"b\", \"c\"]?", ['"b"', '"a"', '"c"', "An error"], 0),
            run("Read words (one line) until the word end. Print how many unique words were read, then the words in order of first appearance separated by spaces.", "java",
                [t("with repeats", stdin="red blue red green blue end"), t("just end", stdin="end")], ["3\nred blue green", "0\n"],
                prog('Scanner in = new Scanner(System.in);\nArrayList<String> words = new ArrayList<>();\nwhile (in.hasNext()) {\n    String w = in.next();\n    if (w.equals("end")) break;\n    if (!words.contains(w)) words.add(w);\n}\nSystem.out.println(words.size());\nSystem.out.println(String.join(" ", words));',
                     "import java.util.ArrayList;\nimport java.util.Scanner;\n\n"),
                starter=SCAN, require=[r"ArrayList"], fallback=[r"ArrayList<String>", r"\.contains\(", r"\.add\("]),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Classes & objects",
        lesson(
            "Classes & objects",
            "A class is a blueprint; objects are built from it with new:\n\nclass Dog {\n    String name;\n    void bark() {\n        System.out.println(name + \" says woof\");\n    }\n}\n\nDog d = new Dog();\nd.name = \"Rex\";\nd.bark();   // Rex says woof\n\n(Only one public class per file; other classes go without 'public'.)",
            mcq("What creates an object from a class?", ["new", "create", "make", "class"], 0),
            fill("Create a Dog object.", "Dog d = ___ Dog();", "new"),
            mcq("What are the variables inside a class called?", ["Fields", "Loops", "Packages", "Imports"], 0),
            mcq("What is printed?", ["Rex says woof", "name says woof", "null says woof", "An error"], 0,
                code='Dog d = new Dog();\nd.name = "Rex";\nd.bark();'),
            run("Add a class Counter (outside Main) with an int field count and a method void increment(). main creates a Counter, calls increment() 3 times and prints count.",
                "java", [t("Run")], ["3"],
                "class Counter {\n    int count;\n\n    void increment() {\n        count++;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Counter c = new Counter();\n        c.increment();\n        c.increment();\n        c.increment();\n        System.out.println(c.count);\n    }\n}\n",
                starter=MAIN, require=[r"class\s+Counter", r"new\s+Counter\(\)"], fallback=[r"class\s+Counter", r"void\s+increment\s*\(\s*\)", r"new\s+Counter\(\)"]),
        ),
        lesson(
            "Constructors",
            "A constructor sets up a new object. It has the class's name and no return type:\n\nclass Point {\n    int x, y;\n    Point(int x, int y) {\n        this.x = x;   // this.x is the field, x is the parameter\n        this.y = y;\n    }\n}\n\nPoint p = new Point(3, 4);",
            mcq("What is a constructor's return type?", ["It has none", "void", "The class", "Object"], 0),
            fill("Assign the parameter to the field of the same name.", "___.name = name;", "this"),
            mcq("When does the constructor run?", ["When you create the object with new", "When the program starts", "When a method is called", "Never automatically"], 0),
            order("Order the class with a constructor.", ["class Cat {", "    String name;", "    Cat(String name) {", "        this.name = name;", "    }", "}"]),
            run("Write class Rect with a constructor Rect(int w, int h), and methods int area() and int perimeter(). main reads w and h, then prints the area and perimeter on separate lines.",
                "java", [t("3 4", stdin="3 4"), t("5 5", stdin="5 5")], ["12\n14", "25\n20"],
                "import java.util.Scanner;\n\nclass Rect {\n    int w, h;\n\n    Rect(int w, int h) {\n        this.w = w;\n        this.h = h;\n    }\n\n    int area() {\n        return w * h;\n    }\n\n    int perimeter() {\n        return 2 * (w + h);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        Rect r = new Rect(in.nextInt(), in.nextInt());\n        System.out.println(r.area());\n        System.out.println(r.perimeter());\n    }\n}\n",
                starter=SCAN, require=[r"class\s+Rect", r"Rect\s*\(\s*int"], fallback=[r"class\s+Rect", r"Rect\s*\(\s*int\s+\w+\s*,\s*int\s+\w+\s*\)", r"int\s+area\s*\(\s*\)"]),
        ),
        lesson(
            "Encapsulation",
            "Hide fields with private and control access through methods (getters/setters):\n\nclass Account {\n    private double balance;\n    public double getBalance() { return balance; }\n    public void deposit(double amt) {\n        if (amt > 0) balance += amt;\n    }\n}\n\nNow nobody can set a negative balance directly.",
            mcq("What does private mean?", ["Only code inside the class can use it", "Nobody can use it", "Only subclasses", "It's constant"], 0),
            mcq("What is a getter?", ["A method that returns a field's value", "A constructor", "A loop", "A private field"], 0),
            fill("Hide this field from other classes.", "___ int age;", "private"),
            mcq("Why use a setter instead of a public field?", ["To validate new values", "It's faster", "Fields can't be changed", "It's required by Java"], 0),
            run("Write class Temperature with a private double celsius, a constructor, getCelsius() and getFahrenheit() (C × 9 / 5 + 32). main reads a celsius value and prints both getters' results on separate lines.",
                "java", [t("100", stdin="100"), t("-40", stdin="-40"), t("37.5", stdin="37.5")], ["100.0\n212.0", "-40.0\n-40.0", "37.5\n99.5"],
                "import java.util.Scanner;\n\nclass Temperature {\n    private double celsius;\n\n    Temperature(double celsius) {\n        this.celsius = celsius;\n    }\n\n    double getCelsius() {\n        return celsius;\n    }\n\n    double getFahrenheit() {\n        return celsius * 9 / 5 + 32;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        Temperature t = new Temperature(in.nextDouble());\n        System.out.println(t.getCelsius());\n        System.out.println(t.getFahrenheit());\n    }\n}\n",
                starter=SCAN, require=[r"private\s+double\s+celsius"], fallback=[r"private\s+double\s+celsius", r"getFahrenheit\s*\(", r"9\s*/\s*5|1\.8"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Inheritance & exceptions",
        lesson(
            "Inheritance",
            "A class can extend another and inherit its fields and methods:\n\nclass Animal {\n    String name;\n    String sound() { return \"...\"; }\n}\n\nclass Cat extends Animal {\n    @Override\n    String sound() { return \"Meow\"; }\n}\n\nCat overrides sound(). An Animal variable can hold a Cat: Animal a = new Cat();",
            mcq("Which keyword makes a class inherit from another?", ["extends", "inherits", "implements", "super"], 0),
            mcq("What does @Override indicate?", ["The method replaces a parent's method", "The method is new", "The method is private", "Nothing"], 0),
            fill("Call the parent class's constructor.", "___(name);", "super"),
            mcq("What does a.sound() return?", ['"Meow"', '"..."', "An error", "null"], 0, "The object's real type (Cat) decides which method runs.",
                code="Animal a = new Cat();"),
            run("Write class Shape with double area() returning 0, and subclasses Circle(double r) and Square(double s) that override area(). main prints the areas of new Circle(1) and new Square(3) formatted with printf(\"%.2f%n\", ...).",
                "java", [t("Run")], ["3.14\n9.00"],
                "class Shape {\n    double area() {\n        return 0;\n    }\n}\n\nclass Circle extends Shape {\n    double r;\n\n    Circle(double r) {\n        this.r = r;\n    }\n\n    @Override\n    double area() {\n        return Math.PI * r * r;\n    }\n}\n\nclass Square extends Shape {\n    double s;\n\n    Square(double s) {\n        this.s = s;\n    }\n\n    @Override\n    double area() {\n        return s * s;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Shape[] shapes = {new Circle(1), new Square(3)};\n        for (Shape sh : shapes) {\n            System.out.printf(\"%.2f%n\", sh.area());\n        }\n    }\n}\n",
                starter=MAIN, require=[r"extends\s+Shape"], fallback=[r"class\s+Circle\s+extends\s+Shape", r"class\s+Square\s+extends\s+Shape", r"double\s+area\s*\(\s*\)"]),
        ),
        lesson(
            "Interfaces",
            "An interface lists methods a class promises to provide:\n\ninterface Greeter {\n    String greet(String name);\n}\n\nclass Friendly implements Greeter {\n    public String greet(String name) {\n        return \"Hi \" + name + \"!\";\n    }\n}\n\nA class can implement many interfaces (but extend only one class).",
            mcq("Which keyword makes a class use an interface?", ["implements", "extends", "uses", "interface"], 0),
            mcq("How many classes can a Java class extend?", ["One", "Any number", "Two", "None"], 0),
            fill("Declare an interface.", "___ Drawable {\n    void draw();\n}", "interface"),
            mcq("Can you create an object with new Greeter() if Greeter is an interface?", ["No", "Yes", "Only in main", "Only if it has no methods"], 0),
            run("Write interface Scorer { int score(String word); } and a class LengthScorer implementing it (score = word length × 10). main reads a word and prints its score.",
                "java", [t("java", stdin="java"), t("hi", stdin="hi")], ["40", "20"],
                "import java.util.Scanner;\n\ninterface Scorer {\n    int score(String word);\n}\n\nclass LengthScorer implements Scorer {\n    public int score(String word) {\n        return word.length() * 10;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        Scorer s = new LengthScorer();\n        System.out.println(s.score(in.next()));\n    }\n}\n",
                starter=SCAN, require=[r"interface\s+Scorer", r"implements\s+Scorer"], fallback=[r"interface\s+Scorer", r"implements\s+Scorer", r"length\(\)\s*\*\s*10"]),
        ),
        lesson(
            "Exceptions",
            "Errors at run time are exceptions. Handle them with try/catch:\n\ntry {\n    int n = Integer.parseInt(text);\n    System.out.println(100 / n);\n} catch (NumberFormatException e) {\n    System.out.println(\"Not a number\");\n} catch (ArithmeticException e) {\n    System.out.println(\"Can't divide by zero\");\n}\n\nThrow your own: throw new IllegalArgumentException(\"Bad age\");",
            mcq("Which exception does Integer.parseInt(\"abc\") throw?", ["NumberFormatException", "ArithmeticException", "NullPointerException", "IOException"], 0),
            mcq("Which exception does 5 / 0 (ints) throw?", ["ArithmeticException", "NumberFormatException", "None - it gives Infinity", "IndexOutOfBoundsException"], 0),
            fill("Handle the exception.", "try {\n    risky();\n} ___ (Exception e) {\n    System.out.println(\"Failed\");\n}", "catch"),
            mcq("When does a finally block run?", ["Always", "Only on exceptions", "Only without exceptions", "Never"], 0),
            run("Read two tokens a and b. Print a / b (integer division). Print Not a number if either isn't an integer, or Cannot divide by zero if b is 0.",
                "java", [t("7 2", stdin="7 2"), t("5 0", stdin="5 0"), t("x 2", stdin="x 2")], ["3", "Cannot divide by zero", "Not a number"],
                scan('try {\n    int a = Integer.parseInt(in.next());\n    int b = Integer.parseInt(in.next());\n    System.out.println(a / b);\n} catch (NumberFormatException e) {\n    System.out.println("Not a number");\n} catch (ArithmeticException e) {\n    System.out.println("Cannot divide by zero");\n}'),
                starter=SCAN, require=[r"\btry\b", r"\bcatch\b"], fallback=[r"\btry\s*\{", r"NumberFormatException", r"ArithmeticException"]),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
    EXPERT,
    EXPERT2,
)
