"""Java - Intermediate and Advanced sections (units 9-16).

Runnable exercises stick to Java 11-15 features so they also compile on older sandbox runners;
newer features (records, sealed classes, pattern matching) are taught in the quiz exercises.
"""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit

MAIN = "public class Main {\n    public static void main(String[] args) {\n        \n    }\n}\n"
SCAN = "import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        \n    }\n}\n"


def prog(body: str, imports: str = "import java.util.*;\n\n", extra: str = "", before: str = "") -> str:
    inner = "\n".join(("        " + line) if line else "" for line in body.split("\n"))
    return f"{imports}{before}public class Main {{\n{extra}    public static void main(String[] args) {{\n{inner}\n    }}\n}}\n"


def scan(body: str, extra: str = "", before: str = "") -> str:
    return prog("Scanner in = new Scanner(System.in);\n" + body, extra=extra, before=before)


INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · Strings & utilities",
        lesson(
            "StringBuilder",
            "Strings are immutable - every + creates a new String. In loops, use StringBuilder:\n\nStringBuilder sb = new StringBuilder();\nfor (int i = 0; i < 3; i++) {\n    sb.append(i).append(',');\n}\nsb.setLength(sb.length() - 1);   // drop last comma\nString s = sb.toString();        // \"0,1,2\"\n\nIt also has reverse(), insert(), deleteCharAt().",
            mcq("Why use StringBuilder in a loop?", ["It avoids creating a new String every time", "Strings can't be joined", "It's required by Java", "It's thread-safe"], 0),
            fill("Turn the builder into a String.", "String result = sb.___();", "toString"),
            mcq("What is new StringBuilder(\"abc\").reverse().toString()?", ['"cba"', '"abc"', '"bca"', "An error"], 0),
            mcq("Are Java Strings mutable?", ["No", "Yes", "Only with final", "Only in loops"], 0),
            run("Read a line and print it with each word reversed but the word order kept (e.g. 'hello world' → 'olleh dlrow'), using StringBuilder.", "java",
                [t("two words", stdin="hello world"), t("one", stdin="Java")], ["olleh dlrow", "avaJ"],
                scan('String[] words = in.nextLine().split(" ");\nStringBuilder out = new StringBuilder();\nfor (int i = 0; i < words.length; i++) {\n    if (i > 0) out.append(\' \');\n    out.append(new StringBuilder(words[i]).reverse());\n}\nSystem.out.println(out);'),
                starter=SCAN, require=[r"StringBuilder"], fallback=[r"StringBuilder", r"\.reverse\(\)", r"split\("]),
        ),
        lesson(
            "Wrapper classes & Math",
            "Every primitive has a wrapper class: int → Integer, double → Double, char → Character, boolean → Boolean. Collections need wrappers; Java converts automatically (autoboxing).\n\nInteger.parseInt(\"42\")   Integer.MAX_VALUE   Character.isDigit('7')\nMath.abs(-3)  Math.max(a, b)  Math.round(2.5)  Math.floorMod(-7, 3)\n\nCompare wrapper objects with .equals(), not ==.",
            mcq("Which is the wrapper for int?", ["Integer", "Int", "Number", "IntWrapper"], 0),
            mcq("What is Integer.MAX_VALUE + 1?", ["Integer.MIN_VALUE (it overflows)", "An exception", "2147483648", "Infinity"], 0),
            fill("Check whether c is a digit.", "if (Character.___(c)) { }", "isDigit"),
            mcq("What is Math.floorMod(-7, 3)?", ["2", "-1", "1", "-2"], 0, "floorMod always returns a result with the divisor's sign; -7 % 3 would give -1."),
            run("Read a line and print three counts: letters, digits and other characters, as letters=… digits=… other=…", "java",
                [t("mixed", stdin="Java 21 rocks!"), t("digits", stdin="2026")], ["letters=9 digits=2 other=3", "letters=0 digits=4 other=0"],
                scan('String s = in.nextLine();\nint letters = 0, digits = 0, other = 0;\nfor (char c : s.toCharArray()) {\n    if (Character.isLetter(c)) letters++;\n    else if (Character.isDigit(c)) digits++;\n    else other++;\n}\nSystem.out.println("letters=" + letters + " digits=" + digits + " other=" + other);'),
                starter=SCAN, require=[r"Character\.is"], fallback=[r"Character\.isLetter", r"Character\.isDigit"]),
        ),
        lesson(
            "static members",
            "static fields and methods belong to the CLASS, not to each object:\n\nclass Ticket {\n    private static int nextId = 1;   // shared by all tickets\n    private final int id;\n    Ticket() { id = nextId++; }\n    static int issued() { return nextId - 1; }\n}\n\nfinal means 'can't be reassigned'. static final fields are constants: static final double TAX = 0.2;",
            mcq("How many copies of a static field exist?", ["One, shared by the class", "One per object", "None until used", "Two"], 0),
            mcq("Can a static method use this?", ["No - there's no object", "Yes", "Only in constructors", "Only if final"], 0),
            fill("A class-wide constant.", "static ___ int MAX = 10;", "final"),
            mcq("How do you call a static method from outside?", ["ClassName.method()", "new ClassName().method() only", "method() only", "this.method()"], 0),
            run("Write class Ticket where each new Ticket gets the next id (1, 2, 3…) from a static counter, plus a static issued() method. main reads n, creates n tickets, prints the last ticket's id and issued().", "java",
                [t("3", stdin="3"), t("1", stdin="1")], ["3 3", "1 1"],
                scan('int n = in.nextInt();\nTicket last = null;\nfor (int i = 0; i < n; i++) last = new Ticket();\nSystem.out.println(last.getId() + " " + Ticket.issued());',
                     before="class Ticket {\n    private static int nextId = 1;\n    private final int id;\n\n    Ticket() {\n        id = nextId++;\n    }\n\n    int getId() {\n        return id;\n    }\n\n    static int issued() {\n        return nextId - 1;\n    }\n}\n\n"),
                starter=SCAN, require=[r"\bstatic\s+int\s+\w+\s*=", r"\bstatic\s+int\s+issued"], fallback=[r"static\s+int\s+\w+\s*=\s*1", r"static\s+int\s+issued\s*\("]),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · Collections",
        lesson(
            "List & ArrayList in depth",
            "Program to the interface: List<String> names = new ArrayList<>();\n\nnames.add(\"Ada\"); names.add(0, \"Bo\");   names.remove(\"Ada\");\nnames.contains(\"Bo\"); names.indexOf(\"Bo\"); names.size();\nCollections.sort(names);  names.sort(Comparator.reverseOrder());\nList<Integer> fixed = List.of(1, 2, 3);   // immutable\n\nfor-each to read; use an Iterator (or removeIf) to remove while looping.",
            mcq("Why write List<String> list = new ArrayList<>()?", ["Code depends on the interface, so the implementation can change", "It's faster", "It's required", "ArrayList isn't a type"], 0),
            mcq("What happens if you add to List.of(1, 2)?", ["UnsupportedOperationException", "It works", "A compile error", "It returns false"], 0),
            fill("Remove all even numbers in place.", "nums.___(n -> n % 2 == 0);", "removeIf"),
            mcq("Which sorts a list of Strings alphabetically?", ["Collections.sort(list)", "list.order()", "Arrays.sort(list)", "list.sorted()"], 0),
            run("Read integers until end of input into a List<Integer>. Remove the negatives, sort descending, and print the list (Java's toString, e.g. [5, 3]).", "java",
                [t("mixed", stdin="4 -2 9 0 -7 3"), t("all negative", stdin="-1 -2")], ["[9, 4, 3, 0]", "[]"],
                scan("List<Integer> nums = new ArrayList<>();\nwhile (in.hasNextInt()) nums.add(in.nextInt());\nnums.removeIf(n -> n < 0);\nnums.sort(Comparator.reverseOrder());\nSystem.out.println(nums);"),
                starter=SCAN, require=[r"List<Integer>"], fallback=[r"List<Integer>", r"removeIf|\.remove\(|Iterator", r"sort"]),
        ),
        lesson(
            "HashMap",
            "Map<K, V> stores key → value pairs; HashMap is the usual choice:\n\nMap<String, Integer> stock = new HashMap<>();\nstock.put(\"apple\", 5);\nstock.get(\"apple\");               // 5\nstock.getOrDefault(\"pear\", 0);    // 0\nstock.merge(\"apple\", 1, Integer::sum);   // +1\nfor (Map.Entry<String, Integer> e : stock.entrySet()) { ... }\n\nTreeMap keeps keys sorted; LinkedHashMap keeps insertion order.",
            mcq("What does map.get(key) return for a missing key?", ["null", "0", "An exception", "\"\""], 0),
            mcq("Which Map keeps its keys sorted?", ["TreeMap", "HashMap", "LinkedHashMap", "ArrayMap"], 0),
            fill("Read a count, defaulting to 0.", "int c = counts.___(word, 0);", "getOrDefault"),
            mcq("What does counts.merge(w, 1, Integer::sum) do?", ["Adds 1 to w's count (or sets it to 1)", "Replaces the map", "Removes w", "Nothing"], 0),
            run("Read words until end of input and print each word with its count in alphabetical order, as word=count, one per line (use a TreeMap).", "java",
                [t("repeats", stdin="the cat and the hat the end"), t("one", stdin="solo")], ["and=1\ncat=1\nend=1\nhat=1\nthe=3", "solo=1"],
                scan('Map<String, Integer> counts = new TreeMap<>();\nwhile (in.hasNext()) counts.merge(in.next(), 1, Integer::sum);\nfor (Map.Entry<String, Integer> e : counts.entrySet()) {\n    System.out.println(e.getKey() + "=" + e.getValue());\n}'),
                starter=SCAN, require=[r"TreeMap"], fallback=[r"TreeMap", r"entrySet|keySet|forEach"]),
        ),
        lesson(
            "HashSet & Deque",
            "Set<T> holds unique values: Set<String> seen = new HashSet<>(); seen.add(x) returns false if x was already there.\n\nDeque<T> is a double-ended queue - use ArrayDeque as a stack or a queue:\n\nDeque<Integer> stack = new ArrayDeque<>();\nstack.push(1); stack.pop(); stack.peek();\nDeque<String> queue = new ArrayDeque<>();\nqueue.offer(\"a\"); queue.poll();",
            mcq("What does set.add(x) return if x is already present?", ["false", "true", "An exception", "null"], 0),
            mcq("Which class is recommended for a stack in modern Java?", ["ArrayDeque", "Stack", "Vector", "LinkedList only"], 0),
            fill("Take the next item from the front of the queue.", "String next = queue.___();", "poll"),
            mcq("Does a HashSet keep insertion order?", ["No (LinkedHashSet does)", "Yes", "It sorts", "Only for Strings"], 0),
            run("Read a line of brackets and print balanced or unbalanced, using an ArrayDeque as a stack. Consider (), [] and {}.", "java",
                [t("ok", stdin="{[()()]}"), t("wrong pair", stdin="(]"), t("unclosed", stdin="((")], ["balanced", "unbalanced", "unbalanced"],
                scan('String s = in.nextLine();\nDeque<Character> stack = new ArrayDeque<>();\nboolean ok = true;\nfor (char c : s.toCharArray()) {\n    if (c == \'(\' || c == \'[\' || c == \'{\') stack.push(c);\n    else if (c == \')\' || c == \']\' || c == \'}\') {\n        char open = c == \')\' ? \'(\' : c == \']\' ? \'[\' : \'{\';\n        if (stack.isEmpty() || stack.pop() != open) {\n            ok = false;\n            break;\n        }\n    }\n}\nSystem.out.println(ok && stack.isEmpty() ? "balanced" : "unbalanced");'),
                starter=SCAN, require=[r"ArrayDeque"], fallback=[r"ArrayDeque", r"\.push\(", r"\.pop\("]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Polymorphism & interfaces",
        lesson(
            "Abstract classes",
            "An abstract class can't be instantiated; it defines common code plus abstract methods subclasses MUST implement:\n\nabstract class Shape {\n    abstract double area();\n    String describe() { return getClass().getSimpleName() + \" \" + area(); }\n}\nclass Square extends Shape {\n    double s;\n    Square(double s) { this.s = s; }\n    double area() { return s * s; }\n}",
            mcq("Can you write new Shape() if Shape is abstract?", ["No", "Yes", "Only in main", "Only with no methods"], 0),
            mcq("What must a concrete subclass do with abstract methods?", ["Implement them all", "Ignore them", "Call super", "Make them static"], 0),
            fill("Declare a method with no body that subclasses must implement.", "___ double area();", "abstract"),
            mcq("Abstract class vs interface: which can hold instance fields?", ["Abstract class", "Interface", "Both", "Neither"], 0),
            run("Write abstract class Employee(name) with abstract double pay() and String payslip() returning name + \": \" + pay formatted to 2 decimals. Add Salaried(name, annual) paying annual/12 and Hourly(name, rate, hours).", "java",
                [t("payslips", stdin="")], ["Ada: 5000.00\nBo: 412.50"],
                prog('List<Employee> staff = List.of(new Salaried("Ada", 60000), new Hourly("Bo", 16.5, 25));\nfor (Employee e : staff) System.out.println(e.payslip());',
                     before='abstract class Employee {\n    protected final String name;\n\n    Employee(String name) {\n        this.name = name;\n    }\n\n    abstract double pay();\n\n    String payslip() {\n        return name + ": " + String.format("%.2f", pay());\n    }\n}\n\nclass Salaried extends Employee {\n    private final double annual;\n\n    Salaried(String name, double annual) {\n        super(name);\n        this.annual = annual;\n    }\n\n    double pay() {\n        return annual / 12;\n    }\n}\n\nclass Hourly extends Employee {\n    private final double rate, hours;\n\n    Hourly(String name, double rate, double hours) {\n        super(name);\n        this.rate = rate;\n        this.hours = hours;\n    }\n\n    double pay() {\n        return rate * hours;\n    }\n}\n\n'),
                starter=MAIN, require=[r"abstract\s+class\s+Employee", r"abstract\s+double\s+pay"],
                fallback=[r"abstract\s+class\s+Employee", r"extends\s+Employee[\s\S]*extends\s+Employee"]),
        ),
        lesson(
            "Polymorphism",
            "One interface, many implementations. Code written against a parent type works with every subtype:\n\ninterface Notifier { void send(String msg); }\nclass Email implements Notifier { ... }\nclass Sms implements Notifier { ... }\n\nList<Notifier> all = List.of(new Email(), new Sms());\nfor (Notifier n : all) n.send(\"Hi\");   // each does its own thing\n\nJava picks the method from the object's REAL type at run time (dynamic dispatch).",
            mcq("Which method runs for Notifier n = new Sms(); n.send(\"x\")?", ["Sms.send", "Notifier.send", "Both", "None - interfaces can't run"], 0),
            mcq("What is dynamic dispatch?", ["Choosing the overriding method by the object's actual type at run time", "Overloading", "Static methods", "Casting"], 0),
            fill("Email provides the Notifier methods.", "class Email ___ Notifier { }", "implements"),
            mcq("Can an interface have method bodies?", ["Yes - default and static methods", "Never", "Only private ones", "Only in Java 8 or earlier"], 0),
            run("Write interface Discount { double apply(double price); } with implementations PercentOff(p) and FixedOff(amount, never below 0). main applies a list of discounts in order to price 80 and prints the final price with 2 decimals.", "java",
                [t("chain", stdin="")], ["50.00"],
                prog('List<Discount> discounts = List.of(new PercentOff(25), new FixedOff(10));\ndouble price = 80;\nfor (Discount d : discounts) price = d.apply(price);\nSystem.out.printf("%.2f%n", price);',
                     before="interface Discount {\n    double apply(double price);\n}\n\nclass PercentOff implements Discount {\n    private final double percent;\n\n    PercentOff(double percent) {\n        this.percent = percent;\n    }\n\n    public double apply(double price) {\n        return price * (1 - percent / 100);\n    }\n}\n\nclass FixedOff implements Discount {\n    private final double amount;\n\n    FixedOff(double amount) {\n        this.amount = amount;\n    }\n\n    public double apply(double price) {\n        return Math.max(0, price - amount);\n    }\n}\n\n"),
                starter=MAIN, require=[r"interface\s+Discount", r"implements\s+Discount"], fallback=[r"interface\s+Discount", r"implements\s+Discount[\s\S]*implements\s+Discount"]),
        ),
        lesson(
            "Comparable & Comparator",
            "Make objects sortable:\n\nclass Player implements Comparable<Player> {\n    public int compareTo(Player o) { return Integer.compare(score, o.score); }\n}\nCollections.sort(players);   // natural order\n\nOr pass a Comparator for any order:\nplayers.sort(Comparator.comparing(Player::getName));\nplayers.sort(Comparator.comparingInt(Player::getScore).reversed().thenComparing(Player::getName));",
            mcq("What does compareTo return when this < other?", ["A negative number", "A positive number", "0", "false"], 0),
            fill("Sort by score, highest first.", "list.sort(Comparator.comparingInt(Player::getScore).___());", "reversed"),
            mcq("When do you need a Comparator instead of Comparable?", ["To sort in an order other than the natural one", "Never", "For primitives", "For Strings only"], 0),
            mcq("Why use Integer.compare(a, b) instead of a - b?", ["a - b can overflow", "It's shorter", "It's required", "No reason"], 0),
            run("Read lines of 'name score' until end of input. Print them sorted by score descending, ties by name ascending, as name:score.", "java",
                [t("ties", stdin="ada 90\nbo 95\ncy 90\ndi 70")], ["bo:95\nada:90\ncy:90\ndi:70"],
                scan('List<Player> ps = new ArrayList<>();\nwhile (in.hasNext()) ps.add(new Player(in.next(), in.nextInt()));\nps.sort(Comparator.comparingInt(Player::getScore).reversed().thenComparing(Player::getName));\nfor (Player p : ps) System.out.println(p.getName() + ":" + p.getScore());',
                     before="class Player {\n    private final String name;\n    private final int score;\n\n    Player(String name, int score) {\n        this.name = name;\n        this.score = score;\n    }\n\n    String getName() {\n        return name;\n    }\n\n    int getScore() {\n        return score;\n    }\n}\n\n"),
                starter=SCAN, require=[r"Comparator|compareTo"], fallback=[r"Comparator|Comparable", r"\.sort\(|Collections\.sort"]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Exceptions in depth",
        lesson(
            "Checked vs unchecked",
            "Checked exceptions (IOException, …) MUST be caught or declared with throws. Unchecked ones (RuntimeException and subclasses: NullPointerException, IllegalArgumentException…) don't have to be.\n\nvoid load(String path) throws IOException { ... }\n\nUse unchecked exceptions for programming errors (bad arguments); checked ones for recoverable conditions the caller should plan for.",
            mcq("Is NullPointerException checked?", ["No - it's a RuntimeException", "Yes", "Only in main", "It isn't an exception"], 0),
            mcq("What must you do with a checked exception?", ["Catch it or declare it with throws", "Nothing", "Always rethrow", "Wrap it in a loop"], 0),
            fill("Declare that the method may throw.", "void read() ___ IOException { }", "throws"),
            mcq("Which is best for a negative quantity passed to a method?", ["IllegalArgumentException", "IOException", "Error", "Exception"], 0),
            run("Write static int safeDivide(String a, String b) that throws IllegalArgumentException(\"not a number: x\") for bad input and ArithmeticException for b = 0. main reads two tokens and prints the result or the exception's class simple name and message.", "java",
                [t("ok", stdin="10 3"), t("bad", stdin="10 x"), t("zero", stdin="1 0")], ["3", "IllegalArgumentException: not a number: x", "ArithmeticException: / by zero"],
                scan('try {\n    System.out.println(safeDivide(in.next(), in.next()));\n} catch (RuntimeException e) {\n    System.out.println(e.getClass().getSimpleName() + ": " + e.getMessage());\n}',
                     extra='    static int safeDivide(String a, String b) {\n        int x = parse(a), y = parse(b);\n        return x / y;\n    }\n\n    static int parse(String s) {\n        try {\n            return Integer.parseInt(s);\n        } catch (NumberFormatException e) {\n            throw new IllegalArgumentException("not a number: " + s);\n        }\n    }\n\n'),
                starter=SCAN, require=[r"IllegalArgumentException"], fallback=[r"throw\s+new\s+IllegalArgumentException", r"catch"]),
        ),
        lesson(
            "Custom exceptions",
            "Create your own exception types for your domain:\n\nclass InsufficientFundsException extends Exception {\n    private final double shortBy;\n    InsufficientFundsException(double shortBy) {\n        super(\"Short by \" + shortBy);\n        this.shortBy = shortBy;\n    }\n}\n\nExtend Exception for checked, RuntimeException for unchecked. Keep the original cause: new MyException(\"msg\", cause).",
            mcq("Which should a custom UNCHECKED exception extend?", ["RuntimeException", "Exception", "Error", "Throwable"], 0),
            fill("Pass the message to the parent constructor.", "___(\"Short by \" + amount);", "super"),
            mcq("Why keep the original exception as the cause?", ["The full stack trace shows what really went wrong", "It's faster", "It's required", "To hide it"], 0),
            mcq("Which is best practice?", ["Catch specific exceptions", "catch (Exception e) {} everywhere", "Never use exceptions", "Throw Error"], 0),
            run("Write InsufficientFundsException (checked) and class Account with withdraw(double) throwing it when funds are short. main reads a balance and withdrawals until input ends, printing ok <new balance> or failed: <message> for each.", "java",
                [t("mix", stdin="100 30 80 50"), t("exact", stdin="10 10")], ["ok 70.0\nfailed: Short by 10.0\nok 20.0", "ok 0.0"],
                scan('Account acc = new Account(in.nextDouble());\nwhile (in.hasNextDouble()) {\n    try {\n        acc.withdraw(in.nextDouble());\n        System.out.println("ok " + acc.getBalance());\n    } catch (InsufficientFundsException e) {\n        System.out.println("failed: " + e.getMessage());\n    }\n}',
                     before='class InsufficientFundsException extends Exception {\n    InsufficientFundsException(double shortBy) {\n        super("Short by " + shortBy);\n    }\n}\n\nclass Account {\n    private double balance;\n\n    Account(double balance) {\n        this.balance = balance;\n    }\n\n    void withdraw(double amount) throws InsufficientFundsException {\n        if (amount > balance) throw new InsufficientFundsException(amount - balance);\n        balance -= amount;\n    }\n\n    double getBalance() {\n        return balance;\n    }\n}\n\n'),
                starter=SCAN, require=[r"extends\s+Exception"], fallback=[r"class\s+InsufficientFundsException\s+extends\s+Exception", r"throws\s+InsufficientFundsException"]),
        ),
        lesson(
            "try-with-resources",
            "Resources like files, sockets and Scanners must be closed. try-with-resources closes them automatically - even if an exception is thrown:\n\ntry (BufferedReader r = new BufferedReader(new FileReader(\"data.txt\"))) {\n    String line;\n    while ((line = r.readLine()) != null) { ... }\n} catch (IOException e) {\n    ...\n}\n\nAny class implementing AutoCloseable works here.",
            mcq("What does try-with-resources guarantee?", ["The resource's close() is called", "No exceptions", "Faster I/O", "The file exists"], 0),
            mcq("Which interface must a resource implement?", ["AutoCloseable", "Closeable only", "Runnable", "Serializable"], 0),
            fill("Declare the resource in the try header.", "try (Scanner sc = new Scanner(System.in)) ___", "{"),
            mcq("When is close() called if the body throws?", ["Before the catch block runs", "Never", "After the program ends", "Only on success"], 0),
            run("Write a class Tracker implementing AutoCloseable that prints 'open <name>' when created and 'close <name>' in close(). In main use two Trackers a and b in ONE try-with-resources, print 'work', then throw new IllegalStateException(\"boom\") and catch it printing 'caught boom'.", "java",
                [t("Run")], ["open a\nopen b\nwork\nclose b\nclose a\ncaught boom"],
                prog('try (Tracker a = new Tracker("a"); Tracker b = new Tracker("b")) {\n    System.out.println("work");\n    throw new IllegalStateException("boom");\n} catch (IllegalStateException e) {\n    System.out.println("caught " + e.getMessage());\n}',
                     before='class Tracker implements AutoCloseable {\n    private final String name;\n\n    Tracker(String name) {\n        this.name = name;\n        System.out.println("open " + name);\n    }\n\n    @Override\n    public void close() {\n        System.out.println("close " + name);\n    }\n}\n\n'),
                starter=MAIN, require=[r"implements\s+AutoCloseable", r"try\s*\("], fallback=[r"implements\s+AutoCloseable", r"try\s*\(\s*Tracker"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Generics",
        lesson(
            "Generic methods",
            "Generics let one piece of code work with many types, safely:\n\nstatic <T> T firstOrDefault(List<T> list, T fallback) {\n    return list.isEmpty() ? fallback : list.get(0);\n}\n\nString s = firstOrDefault(names, \"none\");   // T = String\nInteger n = firstOrDefault(nums, 0);          // T = Integer\n\nThe compiler checks types - no casts needed.",
            mcq("Where does the type parameter go in a generic method?", ["Before the return type: static <T> T f(...)", "After the name", "In the body", "In the class only"], 0),
            mcq("What do generics prevent?", ["Wrong-type bugs at compile time and manual casts", "All exceptions", "NullPointerException", "Slow code"], 0),
            fill("Declare a generic method returning a List of T.", "static ___ List<T> repeat(T item, int n) { ... }", "<T>"),
            mcq("Can a generic type be a primitive like List<int>?", ["No - use List<Integer>", "Yes", "Only in arrays", "Only with var"], 0),
            run("Write a generic static <T> List<T> interleave(List<T> a, List<T> b) alternating items from both (leftovers appended). main prints interleave of two Integer lists and of two String lists.", "java",
                [t("Run")], ["[1, 10, 2, 20, 3]\n[a, x, b, y, z]"],
                prog('System.out.println(interleave(List.of(1, 2, 3), List.of(10, 20)));\nSystem.out.println(interleave(List.of("a", "b"), List.of("x", "y", "z")));',
                     extra="    static <T> List<T> interleave(List<T> a, List<T> b) {\n        List<T> out = new ArrayList<>();\n        for (int i = 0; i < Math.max(a.size(), b.size()); i++) {\n            if (i < a.size()) out.add(a.get(i));\n            if (i < b.size()) out.add(b.get(i));\n        }\n        return out;\n    }\n\n"),
                starter=MAIN, require=[r"static\s+<T>"], fallback=[r"static\s+<T>\s+List<T>\s+interleave"]),
        ),
        lesson(
            "Generic classes",
            "Classes can be generic too:\n\nclass Box<T> {\n    private T value;\n    Box(T value) { this.value = value; }\n    T get() { return value; }\n}\nBox<String> b = new Box<>(\"hi\");\n\nclass Pair<K, V> { final K key; final V value; ... }\n\nThis is how List<E>, Map<K, V> and Optional<T> are built.",
            mcq("How many type parameters does Map<K, V> have?", ["2", "1", "0", "Any number"], 0),
            fill("Declare a generic class.", "class Box___ { private T value; }", "<T>"),
            mcq("What does the diamond in new Box<>(\"hi\") do?", ["Lets the compiler infer the type argument", "Makes it raw", "Creates two boxes", "Nothing"], 0),
            mcq("Why avoid raw types like List list = new ArrayList();?", ["You lose type safety", "They're faster", "They're required", "They don't compile"], 0),
            run("Write a generic class Stack<T> backed by an ArrayList with push, pop (throws IllegalStateException(\"empty\") when empty), peek and isEmpty. main pushes 1..3, pops twice, then pops an empty String stack.", "java",
                [t("Run")], ["3\n2\nempty"],
                prog('Stack<Integer> s = new Stack<>();\nfor (int i = 1; i <= 3; i++) s.push(i);\nSystem.out.println(s.pop());\nSystem.out.println(s.pop());\nStack<String> e = new Stack<>();\ntry {\n    e.pop();\n} catch (IllegalStateException ex) {\n    System.out.println(ex.getMessage());\n}',
                     before='class Stack<T> {\n    private final List<T> items = new ArrayList<>();\n\n    void push(T item) {\n        items.add(item);\n    }\n\n    T pop() {\n        if (items.isEmpty()) throw new IllegalStateException("empty");\n        return items.remove(items.size() - 1);\n    }\n\n    T peek() {\n        return items.get(items.size() - 1);\n    }\n\n    boolean isEmpty() {\n        return items.isEmpty();\n    }\n}\n\n'),
                starter=MAIN, require=[r"class\s+Stack\s*<\s*T\s*>"], fallback=[r"class\s+Stack\s*<\s*T\s*>", r"IllegalStateException"]),
        ),
        lesson(
            "Bounded types & wildcards",
            "Restrict what a type parameter can be:\n\nstatic <T extends Comparable<T>> T max(List<T> list) { ... }   // T must be comparable\n\nWildcards for flexible parameters:\nstatic double sum(List<? extends Number> nums)   // a List of any Number subtype (read)\nstatic void fill(List<? super Integer> out)      // can ADD Integers\n\nRule of thumb (PECS): Producer Extends, Consumer Super.",
            mcq("What does <T extends Comparable<T>> guarantee?", ["T values can be compared with compareTo", "T is a subclass of Comparable class", "T is a number", "Nothing"], 0),
            mcq("Which parameter accepts both List<Integer> and List<Double>?", ["List<? extends Number>", "List<Number>", "List<Object>", "List<?super Integer>"], 0),
            fill("A list you can read Numbers from.", "static double sum(List<? ___ Number> nums)", "extends"),
            mcq("What does PECS stand for?", ["Producer Extends, Consumer Super", "Public Extends Class Super", "Primitive Equals Compare Sort", "None"], 0),
            run("Write static <T extends Comparable<T>> T maxOf(List<T> list) and static double sum(List<? extends Number> nums). main prints maxOf of an Integer list and a String list, and sum of a mixed Integer and Double list.", "java",
                [t("Run")], ["9\npear\n6.5"],
                prog('System.out.println(maxOf(List.of(3, 9, 2)));\nSystem.out.println(maxOf(List.of("apple", "pear", "fig")));\nList<Number> mixed = List.of(1, 2.5, 3);\nSystem.out.println(sum(mixed));',
                     extra="    static <T extends Comparable<T>> T maxOf(List<T> list) {\n        T best = list.get(0);\n        for (T x : list) if (x.compareTo(best) > 0) best = x;\n        return best;\n    }\n\n    static double sum(List<? extends Number> nums) {\n        double total = 0;\n        for (Number n : nums) total += n.doubleValue();\n        return total;\n    }\n\n"),
                starter=MAIN, require=[r"extends\s+Comparable", r"\?\s*extends\s+Number"], fallback=[r"<T\s+extends\s+Comparable<T>>", r"List<\?\s*extends\s+Number>"]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Lambdas & streams",
        lesson(
            "Lambdas & functional interfaces",
            "A lambda is a short anonymous function: (a, b) -> a + b. It can be used wherever a functional interface (one abstract method) is expected:\n\nFunction<String, Integer> len = s -> s.length();\nPredicate<Integer> isEven = n -> n % 2 == 0;\nBiFunction<Integer, Integer, Integer> add = Integer::sum;   // method reference\nRunnable task = () -> System.out.println(\"run\");\n\nlist.forEach(System.out::println);",
            mcq("What is a functional interface?", ["An interface with exactly one abstract method", "Any interface", "A class with lambdas", "A static method"], 0),
            mcq("What does Predicate<T> return?", ["boolean", "T", "void", "Object"], 0),
            fill("A method reference to String's length.", "Function<String, Integer> f = String::___;", "length"),
            mcq("Which interface takes no arguments and returns a value?", ["Supplier<T>", "Consumer<T>", "Runnable", "Predicate<T>"], 0),
            run("Write static List<Integer> transform(List<Integer> in, Predicate<Integer> keep, Function<Integer, Integer> f). main prints transform of 1..6 keeping evens and squaring, then keeping > 3 and negating.", "java",
                [t("Run")], ["[4, 16, 36]\n[-4, -5, -6]"],
                prog("List<Integer> nums = List.of(1, 2, 3, 4, 5, 6);\nSystem.out.println(transform(nums, n -> n % 2 == 0, n -> n * n));\nSystem.out.println(transform(nums, n -> n > 3, n -> -n));",
                     imports="import java.util.*;\nimport java.util.function.*;\n\n",
                     extra="    static List<Integer> transform(List<Integer> in, Predicate<Integer> keep, Function<Integer, Integer> f) {\n        List<Integer> out = new ArrayList<>();\n        for (Integer n : in) if (keep.test(n)) out.add(f.apply(n));\n        return out;\n    }\n\n"),
                starter=MAIN, require=[r"Predicate<", r"Function<", r"->"], fallback=[r"Predicate<Integer>", r"Function<Integer,\s*Integer>", r"->"]),
        ),
        lesson(
            "Streams",
            "Streams process collections declaratively:\n\nList<String> names = people.stream()\n    .filter(p -> p.getAge() >= 18)\n    .map(Person::getName)\n    .sorted()\n    .collect(Collectors.toList());\n\nint total = nums.stream().mapToInt(Integer::intValue).sum();\nMap<String, Long> byCity = people.stream().collect(Collectors.groupingBy(Person::getCity, Collectors.counting()));\n\nStreams are lazy: nothing runs until a terminal operation (collect, sum, forEach…).",
            mcq("Which is a terminal operation?", ["collect", "filter", "map", "sorted"], 0),
            mcq("Can you reuse a stream after a terminal operation?", ["No", "Yes", "Only parallel streams", "Only sorted ones"], 0),
            fill("Group items by a key.", "Collectors.___(Word::length)", "groupingBy"),
            mcq("What does .map(String::toUpperCase) do?", ["Transforms each element", "Filters elements", "Sorts", "Counts"], 0),
            run("Read words until end of input. Using streams, print the distinct words longer than 3 letters, lower-cased, sorted, joined with ', '.", "java",
                [t("mixed", stdin="The quick brown Fox jumps over the lazy dog QUICK")], ["brown, jumps, lazy, over, quick"],
                scan('List<String> words = new ArrayList<>();\nwhile (in.hasNext()) words.add(in.next());\nString result = words.stream()\n        .map(String::toLowerCase)\n        .filter(w -> w.length() > 3)\n        .distinct()\n        .sorted()\n        .collect(Collectors.joining(", "));\nSystem.out.println(result);',
                     ).replace("import java.util.*;\n", "import java.util.*;\nimport java.util.stream.*;\n"),
                starter=SCAN, require=[r"\.stream\(\)", r"Collectors\.joining"], fallback=[r"\.stream\(\)", r"\.filter\(", r"Collectors\.joining"]),
        ),
        lesson(
            "Optional",
            "Optional<T> makes 'maybe no value' explicit instead of returning null:\n\nOptional<User> found = users.stream().filter(u -> u.getId() == id).findFirst();\nString name = found.map(User::getName).orElse(\"unknown\");\nfound.ifPresent(u -> System.out.println(u.getName()));\n\nUse Optional for return values; don't use it for fields or parameters.",
            mcq("What does Optional.empty().orElse(\"x\") return?", ["\"x\"", "null", "An exception", "Optional[x]"], 0),
            mcq("What problem does Optional help avoid?", ["NullPointerExceptions from unexpected nulls", "Slow streams", "Overflow", "Deadlocks"], 0),
            fill("Run code only if a value is present.", "opt.___(v -> System.out.println(v));", "ifPresent"),
            mcq("Which stream method returns an Optional?", ["findFirst()", "collect()", "count()", "forEach()"], 0),
            run("Write static Optional<String> longestWord(List<String> words) (empty for an empty list). main prints the result in upper case or 'none', using map/orElse.", "java",
                [t("Run")], ["BANANA\nnone"],
                prog('System.out.println(longestWord(List.of("fig", "banana", "kiwi")).map(String::toUpperCase).orElse("none"));\nSystem.out.println(longestWord(List.of()).map(String::toUpperCase).orElse("none"));',
                     extra="    static Optional<String> longestWord(List<String> words) {\n        return words.stream().max(Comparator.comparingInt(String::length));\n    }\n\n"),
                starter=MAIN, require=[r"Optional<String>"], fallback=[r"Optional<String>\s+longestWord", r"orElse"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · Modern Java",
        lesson(
            "Enums",
            "An enum is a fixed set of named constants - and can have fields and methods:\n\nenum Planet {\n    MERCURY(3.303e23), EARTH(5.976e24);\n    private final double mass;\n    Planet(double mass) { this.mass = mass; }\n    double mass() { return mass; }\n}\n\nPlanet.valueOf(\"EARTH\"); Planet.values(); p.ordinal(); switch works on enums.",
            mcq("What does Day.values() return?", ["An array of all constants", "A list of names", "The first constant", "A Map"], 0),
            mcq("Can an enum have a constructor?", ["Yes (always private)", "No", "Only public ones", "Only static"], 0),
            fill("Turn the text \"MONDAY\" into the enum constant.", "Day d = Day.___(\"MONDAY\");", "valueOf"),
            mcq("Is comparing enums with == safe?", ["Yes - each constant is a single instance", "No, use equals only", "Only in switch", "Never"], 0),
            run("Write enum Coin { PENNY(1), NICKEL(5), DIME(10), QUARTER(25) } with a cents field. Read coin names until end of input and print the total in cents.", "java",
                [t("mix", stdin="QUARTER DIME DIME PENNY"), t("none", stdin="")], ["46", "0"],
                scan("int total = 0;\nwhile (in.hasNext()) total += Coin.valueOf(in.next()).cents();\nSystem.out.println(total);",
                     before="enum Coin {\n    PENNY(1), NICKEL(5), DIME(10), QUARTER(25);\n\n    private final int cents;\n\n    Coin(int cents) {\n        this.cents = cents;\n    }\n\n    int cents() {\n        return cents;\n    }\n}\n\n"),
                starter=SCAN, require=[r"\benum\s+Coin"], fallback=[r"enum\s+Coin", r"valueOf"]),
        ),
        lesson(
            "Records & sealed types",
            "Modern Java (16+) has records - concise, immutable data classes:\n\nrecord Point(int x, int y) {}\nPoint p = new Point(1, 2);\np.x();                    // accessor\np.equals(new Point(1, 2)) // true\nSystem.out.println(p);    // Point[x=1, y=2]\n\nsealed interfaces (17+) restrict which classes may implement them:\nsealed interface Shape permits Circle, Square {}\n\nPattern matching (21): if (obj instanceof Point(int x, int y)) { ... }",
            mcq("What does a record generate automatically?", ["Constructor, accessors, equals, hashCode and toString", "Only getters", "Setters", "Nothing"], 0),
            mcq("How do you read field x of record Point?", ["p.x()", "p.getX()", "p.x", "Point.x(p)"], 0),
            fill("Declare a record.", "___ Person(String name, int age) {}", "record"),
            mcq("What does sealed ... permits A, B mean?", ["Only A and B may implement it", "A and B are hidden", "It can't be implemented", "A and B are final"], 0),
            code("Write a record called Book with a String title and int pages.", [r"record\s+Book\s*\(\s*String\s+title\s*,\s*int\s+pages\s*\)\s*\{\s*\}"],
                 "record Book(String title, int pages) {}", hint="record Name(type name, type name) {}"),
        ),
        lesson(
            "Immutability & equals/hashCode",
            "Immutable objects can't change after construction - simpler and thread-safe:\n- make fields private final\n- no setters\n- copy mutable inputs (List.copyOf)\n\nIf you override equals, you MUST override hashCode consistently, or HashMap/HashSet break:\n\n@Override public boolean equals(Object o) { ... }\n@Override public int hashCode() { return Objects.hash(x, y); }",
            mcq("What breaks if equals is overridden but hashCode isn't?", ["HashMap/HashSet lookups", "Printing", "Sorting", "Nothing"], 0),
            fill("Build a hash code from several fields.", "return Objects.___(x, y);", "hash"),
            mcq("Which helps make a class immutable?", ["private final fields and no setters", "public fields", "static fields", "Getters only, no constructor"], 0),
            mcq("Why copy a List passed into an immutable class's constructor?", ["So the caller can't change it from outside later", "For speed", "It's required", "To sort it"], 0),
            run("Write an immutable class Point(int x, int y) with equals and hashCode (Objects.hash) and toString '(x, y)'. main adds new Point(1,2) twice and new Point(2,1) to a HashSet and prints its size and whether it contains new Point(2,1).", "java",
                [t("Run")], ["2 true"],
                prog('Set<Point> set = new HashSet<>();\nset.add(new Point(1, 2));\nset.add(new Point(1, 2));\nset.add(new Point(2, 1));\nSystem.out.println(set.size() + " " + set.contains(new Point(2, 1)));',
                     before='final class Point {\n    private final int x, y;\n\n    Point(int x, int y) {\n        this.x = x;\n        this.y = y;\n    }\n\n    @Override\n    public boolean equals(Object o) {\n        if (this == o) return true;\n        if (!(o instanceof Point)) return false;\n        Point p = (Point) o;\n        return x == p.x && y == p.y;\n    }\n\n    @Override\n    public int hashCode() {\n        return Objects.hash(x, y);\n    }\n\n    @Override\n    public String toString() {\n        return "(" + x + ", " + y + ")";\n    }\n}\n\n'),
                starter=MAIN, require=[r"hashCode\s*\(", r"equals\s*\(\s*Object"], fallback=[r"public\s+boolean\s+equals\s*\(\s*Object", r"public\s+int\s+hashCode\s*\("]),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Algorithms & concurrency",
        lesson(
            "Recursion & memoization",
            "Recursion solves a problem through smaller copies of itself. Memoization caches results so each subproblem is solved once:\n\nstatic Map<Integer, Long> memo = new HashMap<>();\nstatic long fib(int n) {\n    if (n < 2) return n;\n    if (memo.containsKey(n)) return memo.get(n);\n    long r = fib(n - 1) + fib(n - 2);\n    memo.put(n, r);\n    return r;\n}\n\nThat turns O(2^n) into O(n).",
            mcq("What's the complexity of naive recursive Fibonacci?", ["About O(2^n)", "O(n)", "O(log n)", "O(1)"], 0),
            mcq("What does memoization store?", ["Results of previous calls", "The call stack", "Loop counters", "Exceptions"], 0),
            fill("Use long because fib grows quickly.", "static ___ fib(int n)", "long"),
            mcq("What error does very deep recursion cause in Java?", ["StackOverflowError", "OutOfMemoryError only", "IllegalStateException", "None"], 0),
            run("Count the ways to climb n stairs taking 1 or 2 steps at a time, using memoized recursion with a long result. Read n and print the count.", "java",
                [t("3", stdin="3"), t("10", stdin="10"), t("80", stdin="80")], ["3", "89", "37889062373143906"],
                scan("System.out.println(ways(in.nextInt()));",
                     extra="    static Map<Integer, Long> memo = new HashMap<>();\n\n    static long ways(int n) {\n        if (n <= 1) return 1;\n        if (memo.containsKey(n)) return memo.get(n);\n        long r = ways(n - 1) + ways(n - 2);\n        memo.put(n, r);\n        return r;\n    }\n\n"),
                starter=SCAN, require=[r"Map<|long\[\]"], fallback=[r"static\s+long\s+\w+\s*\(\s*int", r"Map<Integer,\s*Long>|long\[\]"]),
        ),
        lesson(
            "Sorting & searching",
            "Know the classics:\n\nArrays.sort / Collections.sort - O(n log n) (dual-pivot quicksort / TimSort)\nArrays.binarySearch(sorted, key) - O(log n)\nInsertion sort - O(n²) but fast on nearly-sorted small inputs\nMerge sort - O(n log n), stable, used for objects\n\nAlways sort before binary search.",
            mcq("What does Arrays.binarySearch require?", ["A sorted array", "Unique values", "A List", "Nothing"], 0),
            mcq("Which sort is stable and O(n log n)?", ["Merge sort", "Quick sort", "Selection sort", "Bubble sort"], 0),
            fill("Sort an int array.", "Arrays.___(nums);", "sort"),
            mcq("What's insertion sort's worst case?", ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], 0),
            run("Implement insertion sort yourself (no Arrays.sort / Collections.sort). Read n and n ints, sort ascending, print them space-separated.", "java",
                [t("6", stdin="6\n5 2 9 1 5 6"), t("1", stdin="1\n7")], ["1 2 5 5 6 9", "7"],
                scan('int n = in.nextInt();\nint[] a = new int[n];\nfor (int i = 0; i < n; i++) a[i] = in.nextInt();\nfor (int i = 1; i < n; i++) {\n    int key = a[i], j = i - 1;\n    while (j >= 0 && a[j] > key) {\n        a[j + 1] = a[j];\n        j--;\n    }\n    a[j + 1] = key;\n}\nStringBuilder sb = new StringBuilder();\nfor (int i = 0; i < n; i++) sb.append(i > 0 ? " " : "").append(a[i]);\nSystem.out.println(sb);'),
                starter=SCAN, require=[r"\bwhile\b|\bfor\b"], forbid=[r"Arrays\.sort|Collections\.sort|\.sort\("], fallback=[r"for\s*\([\s\S]*(while|for)\s*\("]),
        ),
        lesson(
            "Threads & concurrency basics",
            "Run tasks at the same time with threads - but shared data needs care:\n\nExecutorService pool = Executors.newFixedThreadPool(4);\nFuture<Integer> f = pool.submit(() -> heavyWork());\nint result = f.get();          // waits for the result\npool.shutdown();\n\nAtomicInteger counter = new AtomicInteger();\ncounter.incrementAndGet();     // thread-safe ++\n\nA plain count++ from many threads is a race condition and loses updates.",
            mcq("Why can count++ from several threads give a wrong total?", ["It's a read-modify-write race", "Threads can't add", "Integers overflow", "It can't"], 0),
            mcq("What does future.get() do?", ["Waits for and returns the task's result", "Starts the task", "Cancels it", "Nothing"], 0),
            fill("Thread-safe increment.", "counter.___();", "incrementAndGet"),
            mcq("What should you call when you're done with an ExecutorService?", ["shutdown()", "close() only", "stop()", "Nothing"], 0),
            run("Using an ExecutorService with 4 threads, submit 4 tasks that each add 1 to a shared AtomicInteger 10,000 times. Wait for all, then print the total.", "java",
                [t("Run")], ["40000"],
                prog("ExecutorService pool = Executors.newFixedThreadPool(4);\nAtomicInteger counter = new AtomicInteger();\nList<Future<?>> futures = new ArrayList<>();\nfor (int t = 0; t < 4; t++) {\n    futures.add(pool.submit(() -> {\n        for (int i = 0; i < 10000; i++) counter.incrementAndGet();\n    }));\n}\nfor (Future<?> f : futures) {\n    try {\n        f.get();\n    } catch (Exception e) {\n        throw new RuntimeException(e);\n    }\n}\npool.shutdown();\nSystem.out.println(counter.get());",
                     imports="import java.util.*;\nimport java.util.concurrent.*;\nimport java.util.concurrent.atomic.*;\n\n"),
                starter=MAIN, require=[r"Executor", r"AtomicInteger"], forbid=[r"40000"], fallback=[r"Executors\.newFixedThreadPool", r"AtomicInteger", r"\.get\(\)"]),
        ),
    ),
)
