from .dsl import code, course, fill, lesson, mcq, order, run, t, unit
from .javascript_adv import ADVANCED, INTERMEDIATE
from .javascript_expert import EXPERT
from .javascript_expert2 import EXPERT2
from .javascript_start import START

COURSE = course(
    "javascript", "JavaScript", "⚡", "The language of the web - make pages interactive.",
    START,
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · First steps",
        lesson(
            "console.log",
            "console.log() prints values - it's how you see what your program is doing.\n\nconsole.log(\"Hello!\");\nconsole.log(42);\nconsole.log(\"Sum:\", 2 + 3);   // Sum: 5\n\nStatements usually end with a semicolon ;. Comments start with // (one line) or /* ... */ (many lines).",
            fill("Print a message to the console.", 'console.___("Hello");', "log", "console.log writes to the console."),
            mcq("What does console.log(2 + 3) print?", ["5", "23", "2 + 3", "undefined"], 0, "The numbers are added before printing."),
            mcq("Which is a JavaScript comment?", ["// note", "# note", "-- note", "<!-- note -->"], 0, "// starts a one-line comment."),
            mcq("What is printed?", ["Total: 10", "Total:10", "Total: 5 5", "An error"], 0, "Several values are printed separated by a space.",
                code='console.log("Total:", 5 + 5);'),
            run("Print exactly: Hello, JavaScript!", "javascript", [t("Run")], ["Hello, JavaScript!"], 'console.log("Hello, JavaScript!");',
                hint='console.log("...")'),
        ),
        lesson(
            "Numbers & math",
            "JavaScript has one number type for whole numbers and decimals:\n\n7 + 3    // 10\n7 / 2    // 3.5\n7 % 2    // 1   (remainder)\n2 ** 3   // 8   (power)\nMath.round(2.6)   // 3\nMath.floor(2.9)   // 2\nMath.max(4, 9)    // 9",
            mcq("What is 7 / 2?", ["3.5", "3", "4", "1"], 0, "Division keeps the decimal part."),
            mcq("What is 10 % 3?", ["1", "3", "0", "3.33"], 0, "% gives the remainder: 10 = 3×3 + 1."),
            fill("Round 4.7 to the nearest whole number.", "Math.___(4.7)", "round"),
            mcq("What is 2 + 3 * 2?", ["8", "10", "12", "7"], 0, "* happens before +."),
            run("There are 23 students and each table seats 4. Print how many FULL tables there are, then how many students are left over - each on its own line.",
                "javascript", [t("Run")], ["5\n3"], "console.log(Math.floor(23 / 4));\nconsole.log(23 % 4);", require=[r"Math\.floor|Math\.trunc|parseInt", r"%"]),
        ),
        lesson(
            "Strings & template literals",
            "Strings go in quotes: 'single', \"double\" or `backticks`.\n\nJoin with +: \"Code\" + \"ingo\"\n\nTemplate literals (backticks) put values inside ${ }:\n\nconst name = \"Ada\";\nconsole.log(`Hi ${name}, 2 + 2 = ${2 + 2}`);\n\n\"hello\".length is 5, \"hi\".toUpperCase() is \"HI\".",
            mcq("What is printed?", ["Hi Ada", "Hi ${name}", "`Hi Ada`", "An error"], 0, "Backticks make ${name} be replaced.",
                code='const name = "Ada";\nconsole.log(`Hi ${name}`);'),
            mcq("What is \"code\".length?", ["4", "5", "3", "undefined"], 0),
            fill("Make the text upper-case.", '"hello".___()', "toUpperCase"),
            mcq("What is printed?", ["55", "10", "An error", "5 5"], 0, "\"5\" is a string, so + joins instead of adding.", code='console.log("5" + 5);'),
            run("Complete greet(name, day) so it RETURNS the text: Happy <day>, <name>!", "javascript",
                [t('greet("Ada", "Monday")', append='console.log(greet("Ada", "Monday"));'),
                 t('greet("Bo", "Friday")', append='console.log(greet("Bo", "Friday"));')],
                ["Happy Monday, Ada!", "Happy Friday, Bo!"],
                "function greet(name, day) {\n  return `Happy ${day}, ${name}!`;\n}",
                starter="function greet(name, day) {\n  // return the greeting here\n}\n", require=[r"return"], hint="Use a template literal with backticks."),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Variables & types",
        lesson(
            "let & const",
            "Create variables with let (can change) or const (can't be reassigned):\n\nlet lives = 3;\nlives = lives - 1;   // OK\nconst name = \"Ada\";\nname = \"Bob\";        // TypeError!\n\nPrefer const, and use let only when the value must change. (Old code uses var - avoid it.)",
            mcq("Which keyword declares a variable that can't be reassigned?", ["const", "let", "var", "fixed"], 0),
            fill("Declare a changeable variable count set to 0.", "___ count = 0;", "let"),
            mcq("What happens?", ["TypeError: Assignment to constant variable", "Prints 2", "Prints 1", "Nothing"], 0,
                code="const x = 1;\nx = 2;\nconsole.log(x);"),
            order("Order the code so it prints 6.", ["let total = 1;", "total = total + 5;", "console.log(total);"]),
            run("Create a variable score set to 10. Add 5 to it, then double it, then print it.", "javascript", [t("Run")], ["30"],
                "let score = 10;\nscore = score + 5;\nscore = score * 2;\nconsole.log(score);", require=[r"let\s+score\s*=\s*10", r"console\.log\(\s*score\s*\)"]),
        ),
        lesson(
            "Types & typeof",
            "JavaScript's main types:\n\n  number     42, 3.14\n  string     \"hi\"\n  boolean    true, false\n  undefined  a variable with no value yet\n  null       'intentionally empty'\n  object     { }, [ ]\n\ntypeof tells you the type: typeof 42 is \"number\".",
            mcq("What is typeof \"42\"?", ["\"string\"", "\"number\"", "\"text\"", "\"object\""], 0, "It's in quotes, so it's a string."),
            mcq("What is printed?", ["undefined", "null", "0", "An error"], 0, "A declared variable with no value is undefined.", code="let x;\nconsole.log(x);"),
            fill("Check the type of value.", "console.log(___ value);", "typeof"),
            mcq("What is typeof true?", ['"boolean"', '"bool"', '"string"', '"true"'], 0),
            run("Write describe(value) that RETURNS a sentence like: 42 is a number", "javascript",
                [t("describe(42)", append="console.log(describe(42));"), t('describe("hi")', append='console.log(describe("hi"));'),
                 t("describe(true)", append="console.log(describe(true));")],
                ["42 is a number", "hi is a string", "true is a boolean"], "function describe(value) {\n  return `${value} is a ${typeof value}`;\n}",
                starter="function describe(value) {\n  \n}\n", require=[r"typeof"]),
        ),
        lesson(
            "Conversion & equality",
            "Convert values explicitly:\n\nNumber(\"42\")    // 42\nString(42)      // \"42\"\nparseInt(\"7px\") // 7\n\nCompare with === (strict: same type AND value). Avoid == - it converts types in surprising ways:\n\n5 === \"5\"   // false\n5 == \"5\"    // true  (!)",
            mcq("What is 5 === \"5\"?", ["false", "true", "undefined", "An error"], 0, "=== also compares types: number vs string."),
            mcq("What is Number(\"12\") + 1?", ["13", "121", "NaN", "An error"], 0),
            fill("Compare strictly (value AND type).", "if (a ___ b) { }", "==="),
            mcq("What is Number(\"hello\")?", ["NaN", "0", "undefined", "An error"], 0, "NaN means 'Not a Number'."),
            run("Write addStrings(a, b) that takes two numeric strings and RETURNS their numeric sum.", "javascript",
                [t('addStrings("2", "3")', append='console.log(addStrings("2", "3"));'), t('addStrings("10", "-4")', append='console.log(addStrings("10", "-4"));'),
                 t('addStrings("1.5", "1.5")', append='console.log(addStrings("1.5", "1.5"));')],
                ["5", "6", "3"], "function addStrings(a, b) {\n  return Number(a) + Number(b);\n}",
                starter="function addStrings(a, b) {\n  \n}\n", hint="Convert with Number() before adding."),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Making decisions",
        lesson(
            "Comparisons & booleans",
            "Comparisons produce true or false:\n\n5 > 3      // true\n5 <= 5     // true\n\"a\" !== \"b\" // true\n\nCombine with && (and), || (or), ! (not):\n\nage >= 13 && age <= 19   // is a teenager",
            mcq("What is 10 > 5 && 2 > 3?", ["false", "true", "undefined", "An error"], 0, "&& needs both sides true."),
            mcq("What is !true?", ["false", "true", "0", "null"], 0),
            fill("True if EITHER condition holds.", "const ok = isAdmin ___ isOwner;", "||"),
            mcq("What is 3 !== 3?", ["false", "true", "3", "An error"], 0),
            run("Write isTeen(age) that RETURNS true for ages 13 to 19 (inclusive), otherwise false.", "javascript",
                [t("isTeen(15)", append="console.log(isTeen(15));"), t("isTeen(12)", append="console.log(isTeen(12));"),
                 t("isTeen(19)", append="console.log(isTeen(19));"), t("isTeen(20)", append="console.log(isTeen(20));")],
                ["true", "false", "true", "false"], "function isTeen(age) {\n  return age >= 13 && age <= 19;\n}",
                starter="function isTeen(age) {\n  \n}\n", require=[r"&&"]),
        ),
        lesson(
            "if / else",
            "if runs a block when its condition is true:\n\nif (temp > 25) {\n  console.log(\"Hot\");\n} else if (temp > 15) {\n  console.log(\"Nice\");\n} else {\n  console.log(\"Cold\");\n}\n\nThe condition goes in ( ), the code in { }.",
            mcq("What is printed?", ["Nice", "Hot", "Cold", "Nothing"], 0,
                code='const temp = 20;\nif (temp > 25) {\n  console.log("Hot");\n} else if (temp > 15) {\n  console.log("Nice");\n} else {\n  console.log("Cold");\n}'),
            fill("Conditions go inside…", "if ___x > 0) { }", "("),
            order("Order the code so it prints Adult for age 20.", ["const age = 20;", "if (age >= 18) {", '  console.log("Adult");', "} else {", '  console.log("Minor");', "}"]),
            mcq("When does the else block run?", ["When every condition above it is false", "Always", "When the if is true", "Never"], 0),
            run("Write grade(score) that RETURNS \"A\" for 90+, \"B\" for 80-89, \"C\" for 70-79 and \"F\" otherwise.", "javascript",
                [t("grade(95)", append="console.log(grade(95));"), t("grade(85)", append="console.log(grade(85));"),
                 t("grade(70)", append="console.log(grade(70));"), t("grade(42)", append="console.log(grade(42));")],
                ["A", "B", "C", "F"],
                'function grade(score) {\n  if (score >= 90) {\n    return "A";\n  } else if (score >= 80) {\n    return "B";\n  } else if (score >= 70) {\n    return "C";\n  }\n  return "F";\n}',
                starter="function grade(score) {\n  \n}\n", require=[r"\bif\b"]),
        ),
        lesson(
            "switch & the ternary",
            "switch compares one value against many cases:\n\nswitch (day) {\n  case \"sat\":\n  case \"sun\":\n    console.log(\"Weekend\");\n    break;\n  default:\n    console.log(\"Weekday\");\n}\n\nThe ternary is a one-line if/else that produces a value:\n\nconst label = age >= 18 ? \"adult\" : \"minor\";",
            mcq("What is printed?", ["even", "odd", "true", "An error"], 0, "condition ? valueIfTrue : valueIfFalse", code='console.log(4 % 2 === 0 ? "even" : "odd");'),
            mcq("What does break do inside a switch?", ["Stops it falling through to the next case", "Ends the program", "Skips the default", "Nothing"], 0),
            fill("Finish the ternary.", 'const msg = ok ___ "yes" : "no";', "?"),
            mcq("In a switch, which label runs when no case matches?", ["default", "else", "otherwise", "case *"], 0),
            run("Write dayType(day) using a switch: RETURN \"Weekend\" for \"sat\" or \"sun\", otherwise \"Weekday\".", "javascript",
                [t('dayType("sat")', append='console.log(dayType("sat"));'), t('dayType("mon")', append='console.log(dayType("mon"));'),
                 t('dayType("sun")', append='console.log(dayType("sun"));')],
                ["Weekend", "Weekday", "Weekend"],
                'function dayType(day) {\n  switch (day) {\n    case "sat":\n    case "sun":\n      return "Weekend";\n    default:\n      return "Weekday";\n  }\n}',
                starter="function dayType(day) {\n  \n}\n", require=[r"\bswitch\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Loops",
        lesson(
            "for loops",
            "A for loop has three parts: start; condition; step.\n\nfor (let i = 0; i < 3; i++) {\n  console.log(i);   // 0, 1, 2\n}\n\ni++ adds 1 to i. The loop runs while the condition is true.",
            mcq("How many times does this loop run?", ["5", "4", "6", "Forever"], 0, code="for (let i = 0; i < 5; i++) { }"),
            mcq("What does i++ do?", ["Adds 1 to i", "Doubles i", "Prints i", "Resets i"], 0),
            fill("Loop from 1 up to and including 10.", "for (let i = 1; i ___ 10; i++) { }", "<="),
            order("Order a loop printing 0, 1, 2.", ["for (let i = 0; i < 3; i++) {", "  console.log(i);", "}"]),
            run("Write sumTo(n) that RETURNS 1 + 2 + … + n using a loop.", "javascript",
                [t("sumTo(5)", append="console.log(sumTo(5));"), t("sumTo(100)", append="console.log(sumTo(100));"), t("sumTo(1)", append="console.log(sumTo(1));")],
                ["15", "5050", "1"], "function sumTo(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    total += i;\n  }\n  return total;\n}",
                starter="function sumTo(n) {\n  \n}\n", require=[r"\bfor\b|\bwhile\b"]),
        ),
        lesson(
            "while loops",
            "while repeats as long as its condition is true:\n\nlet n = 3;\nwhile (n > 0) {\n  console.log(n);\n  n--;\n}\n\nMake sure something changes inside the loop, or it never stops.",
            mcq("What's wrong?", ["It never ends", "Syntax error", "It never runs", "Nothing"], 0, "n never changes.", code="let n = 0;\nwhile (n < 3) {\n  console.log(n);\n}"),
            fill("Subtract 1 from n.", "n___;", "--"),
            mcq("How many times does Hi print?", ["0", "1", "Forever", "2"], 0, "The condition is false from the start.", code='let x = 10;\nwhile (x < 5) {\n  console.log("Hi");\n}'),
            order("Order the countdown.", ["let n = 3;", "while (n > 0) {", "  console.log(n);", "  n--;", "}"]),
            run("Write countDigits(n) that RETURNS how many digits a positive whole number has, using a while loop (divide by 10 each time).", "javascript",
                [t("countDigits(7)", append="console.log(countDigits(7));"), t("countDigits(1234)", append="console.log(countDigits(1234));"),
                 t("countDigits(100000)", append="console.log(countDigits(100000));")],
                ["1", "4", "6"],
                "function countDigits(n) {\n  let count = 0;\n  while (n > 0) {\n    n = Math.floor(n / 10);\n    count++;\n  }\n  return count;\n}",
                starter="function countDigits(n) {\n  \n}\n", require=[r"\bwhile\b"], forbid=[r"\.length", r"String\(|toString"]),
        ),
        lesson(
            "break & continue",
            "break exits a loop; continue skips to the next round:\n\nfor (let i = 1; i <= 10; i++) {\n  if (i === 5) break;        // stop at 5\n  if (i % 2 === 0) continue; // skip evens\n  console.log(i);            // 1, 3\n}",
            mcq("What is printed?", ["1 2", "1 2 3", "3", "1 2 4"], 0, code="for (let i = 1; i < 5; i++) {\n  if (i === 3) break;\n  console.log(i);\n}"),
            mcq("What is printed?", ["1 2 4", "1 2", "1 2 3 4", "3"], 0, code="for (let i = 1; i < 5; i++) {\n  if (i === 3) continue;\n  console.log(i);\n}"),
            fill("Leave the loop immediately.", "if (found) ___;", "break"),
            mcq("Which keyword skips just the current iteration?", ["continue", "break", "return", "skip"], 0),
            run("Write firstMultiple(n, start) that RETURNS the first number ≥ start that is divisible by n (use a loop with break or return).", "javascript",
                [t("firstMultiple(7, 20)", append="console.log(firstMultiple(7, 20));"), t("firstMultiple(5, 5)", append="console.log(firstMultiple(5, 5));"),
                 t("firstMultiple(3, 10)", append="console.log(firstMultiple(3, 10));")],
                ["21", "5", "12"], "function firstMultiple(n, start) {\n  for (let i = start; ; i++) {\n    if (i % n === 0) {\n      return i;\n    }\n  }\n}",
                starter="function firstMultiple(n, start) {\n  \n}\n", require=[r"\bfor\b|\bwhile\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Functions",
        lesson(
            "Function basics",
            "A function is reusable code. Declare it, then call it:\n\nfunction greet(name) {\n  return \"Hi \" + name;\n}\n\nconsole.log(greet(\"Ada\"));  // Hi Ada\n\nreturn sends a value back. Without return, a function gives back undefined.",
            mcq("What does double(4) return?", ["8", "4", "undefined", "44"], 0, code="function double(n) {\n  return n * 2;\n}"),
            mcq("What does noReturn(4) return?", ["undefined", "8", "null", "An error"], 0, code="function noReturn(n) {\n  n * 2;\n}"),
            fill("Send a value back from a function.", "function five() {\n  ___ 5;\n}", "return"),
            order("Order: define the function, then call it.", ["function hello() {", '  console.log("hello");', "}", "hello();"]),
            run("Write area(width, height) that RETURNS the area of a rectangle.", "javascript",
                [t("area(3, 4)", append="console.log(area(3, 4));"), t("area(10, 2.5)", append="console.log(area(10, 2.5));")], ["12", "25"],
                "function area(width, height) {\n  return width * height;\n}", starter="function area(width, height) {\n  \n}\n", require=[r"return"]),
        ),
        lesson(
            "Arrow functions",
            "Arrow functions are a shorter way to write functions:\n\nconst double = (n) => n * 2;\nconst add = (a, b) => a + b;\nconst greet = (name) => {\n  const msg = `Hi ${name}`;\n  return msg;\n};\n\nWith one expression and no { }, the value is returned automatically.",
            mcq("What does square(5) return?", ["25", "10", "undefined", "5"], 0, code="const square = (n) => n * n;"),
            mcq("What does f(2) return?", ["undefined", "4", "2", "An error"], 0, "With { } you must write return explicitly.", code="const f = (n) => { n * 2 };"),
            fill("Complete the arrow function.", "const half = (n) ___ n / 2;", "=>"),
            code("Write an arrow function called triple that returns n * 3.", [r"const\s+triple\s*=\s*\(?\s*n\s*\)?\s*=>\s*(\{\s*return\s+)?n\s*\*\s*3"],
                 "const triple = (n) => n * 3;", hint="const triple = (n) => ..."),
            run("Write an arrow function clamp(n, min, max) that RETURNS n limited to the range min..max.", "javascript",
                [t("clamp(5, 0, 10)", append="console.log(clamp(5, 0, 10));"), t("clamp(-3, 0, 10)", append="console.log(clamp(-3, 0, 10));"),
                 t("clamp(42, 0, 10)", append="console.log(clamp(42, 0, 10));")],
                ["5", "0", "10"], "const clamp = (n, min, max) => Math.min(Math.max(n, min), max);", require=[r"=>"]),
        ),
        lesson(
            "Scope & default parameters",
            "Variables declared inside { } only exist inside that block (block scope):\n\nif (true) {\n  const secret = 42;\n}\nconsole.log(secret);  // ReferenceError\n\nParameters can have defaults:\n\nfunction greet(name = \"friend\") {\n  return `Hi ${name}`;\n}\ngreet();   // \"Hi friend\"",
            mcq("What happens?", ["ReferenceError", "Prints 1", "Prints undefined", "Prints null"], 0, "x only exists inside the block.",
                code="{\n  let x = 1;\n}\nconsole.log(x);"),
            mcq("What does greet() return?", ['"Hi friend"', '"Hi undefined"', "undefined", "An error"], 0, code='function greet(name = "friend") {\n  return `Hi ${name}`;\n}'),
            fill("Give tax a default of 0.2.", "function price(amount, tax ___ 0.2) { }", "="),
            mcq("Where can a variable declared with let inside a function be used?", ["Only inside that function", "Anywhere", "Only in other functions", "Only after the function"], 0),
            run("Write power(base, exp = 2) that RETURNS base to the power exp (exp defaults to 2).", "javascript",
                [t("power(5)", append="console.log(power(5));"), t("power(2, 10)", append="console.log(power(2, 10));"), t("power(3, 0)", append="console.log(power(3, 0));")],
                ["25", "1024", "1"], "function power(base, exp = 2) {\n  return base ** exp;\n}", require=[r"exp\s*=\s*2"]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Arrays",
        lesson(
            "Arrays",
            "Arrays hold ordered lists. Indexes start at 0:\n\nconst langs = [\"JS\", \"Python\", \"C\"];\nlangs[0]        // \"JS\"\nlangs.length    // 3\nlangs[langs.length - 1]  // \"C\" (last)\nlangs[1] = \"Go\";  // change an item",
            mcq("What is nums[1]?", ["20", "10", "30", "undefined"], 0, code="const nums = [10, 20, 30];"),
            mcq("What is [1, 2, 3].length?", ["3", "2", "4", "undefined"], 0),
            fill("Get the last item of arr.", "arr[arr.length ___ 1]", "-"),
            mcq("What is nums[5]?", ["undefined", "An error", "null", "0"], 0, "Reading past the end gives undefined.", code="const nums = [1, 2, 3];"),
            run("Write firstAndLast(arr) that RETURNS a string like \"first=1 last=5\".", "javascript",
                [t("[1, 2, 3, 4, 5]", append="console.log(firstAndLast([1, 2, 3, 4, 5]));"), t('["x"]', append='console.log(firstAndLast(["x"]));')],
                ["first=1 last=5", "first=x last=x"], "function firstAndLast(arr) {\n  return `first=${arr[0]} last=${arr[arr.length - 1]}`;\n}",
                starter="function firstAndLast(arr) {\n  \n}\n"),
        ),
        lesson(
            "Array methods",
            "Arrays have handy methods:\n\nconst a = [3, 1, 2];\na.push(4);         // add to end   -> [3, 1, 2, 4]\na.pop();           // remove last  -> [3, 1, 2]\na.includes(2);     // true\na.indexOf(1);      // 1\na.slice(0, 2);     // [3, 1]  (a copy)\na.join(\"-\");       // \"3-1-2\"\n[...a].sort((x, y) => x - y);  // [1, 2, 3]",
            mcq("What is printed?", ["[ 1, 2, 3 ]", "[ 1, 2 ]", "3", "undefined"], 0, "push adds to the end.", code="const a = [1, 2];\na.push(3);\nconsole.log(a);"),
            mcq("What is [\"a\", \"b\", \"c\"].join(\"+\")?", ['"a+b+c"', '"abc"', '["a+b+c"]', '"a,b,c"'], 0),
            fill("Check whether the array contains 7.", "nums.___(7)", "includes"),
            mcq("What does [5, 1, 10].sort() give?", ["[ 1, 10, 5 ]", "[ 1, 5, 10 ]", "[ 10, 5, 1 ]", "An error"], 0,
                "Without a compare function, sort() compares items as TEXT - \"10\" comes before \"5\". Use sort((a, b) => a - b)."),
            run("Write top3(nums) that RETURNS the three largest numbers, largest first, joined with \", \".", "javascript",
                [t("[5, 1, 9, 3, 7]", append="console.log(top3([5, 1, 9, 3, 7]));"), t("[10, 2, 30, 4]", append="console.log(top3([10, 2, 30, 4]));")],
                ["9, 7, 5", "30, 10, 4"], 'function top3(nums) {\n  return [...nums].sort((a, b) => b - a).slice(0, 3).join(", ");\n}',
                starter="function top3(nums) {\n  \n}\n", require=[r"\.sort\("]),
        ),
        lesson(
            "map, filter & reduce",
            "These methods transform arrays without loops:\n\nconst nums = [1, 2, 3, 4];\nnums.map(n => n * 2);           // [2, 4, 6, 8]\nnums.filter(n => n % 2 === 0);  // [2, 4]\nnums.reduce((sum, n) => sum + n, 0);  // 10\nnums.forEach(n => console.log(n));\n\nThey return NEW arrays and leave the original alone.",
            mcq("What does [1, 2, 3].map(n => n + 1) return?", ["[ 2, 3, 4 ]", "[ 1, 2, 3 ]", "6", "[ 1, 2, 3, 1 ]"], 0),
            mcq("What does [1, 2, 3, 4].filter(n => n > 2) return?", ["[ 3, 4 ]", "[ 1, 2 ]", "[ true, true ]", "2"], 0),
            fill("Add up all the numbers.", "const total = nums.___((sum, n) => sum + n, 0);", "reduce"),
            mcq("Which method runs a function for each item but returns nothing useful?", ["forEach", "map", "filter", "reduce"], 0),
            run("Write totalOfEvens(nums) that RETURNS the sum of the even numbers, using filter and reduce.", "javascript",
                [t("[1, 2, 3, 4]", append="console.log(totalOfEvens([1, 2, 3, 4]));"), t("[5, 7]", append="console.log(totalOfEvens([5, 7]));"),
                 t("[10, 11, 12]", append="console.log(totalOfEvens([10, 11, 12]));")],
                ["6", "0", "22"], "function totalOfEvens(nums) {\n  return nums.filter(n => n % 2 === 0).reduce((sum, n) => sum + n, 0);\n}",
                starter="function totalOfEvens(nums) {\n  \n}\n", require=[r"\.filter\(", r"\.reduce\("]),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Objects",
        lesson(
            "Objects",
            "Objects group related values as key: value pairs:\n\nconst user = { name: \"Ada\", age: 36 };\nuser.name        // \"Ada\"\nuser[\"age\"]      // 36\nuser.city = \"London\";  // add a property\ndelete user.age;\nObject.keys(user)  // [\"name\", \"city\"]",
            mcq("What is printed?", ["Ada", "name", "undefined", "An error"], 0, code='const user = { name: "Ada" };\nconsole.log(user.name);'),
            mcq("What is printed?", ["undefined", "null", "An error", '""'], 0, "Missing properties are undefined.", code='const user = { name: "Ada" };\nconsole.log(user.age);'),
            fill("Read the property whose name is stored in key.", "user___key]", "["),
            mcq("What does Object.keys({a: 1, b: 2}) return?", ["[ 'a', 'b' ]", "[ 1, 2 ]", "2", "{ a, b }"], 0),
            run("Write makeBook(title, pages) that RETURNS an object with those two properties plus read: false.", "javascript",
                [t('makeBook("Dune", 412)', append='const b = makeBook("Dune", 412);\nconsole.log(b.title, b.pages, b.read);'),
                 t("keys", append='console.log(Object.keys(makeBook("X", 1)).join(","));')],
                ["Dune 412 false", "title,pages,read"], "function makeBook(title, pages) {\n  return { title: title, pages: pages, read: false };\n}",
                starter="function makeBook(title, pages) {\n  \n}\n"),
        ),
        lesson(
            "Methods & this",
            "A function stored in an object is a method. Inside it, this refers to the object:\n\nconst counter = {\n  count: 0,\n  increment() {\n    this.count++;\n    return this.count;\n  },\n};\ncounter.increment();  // 1",
            mcq("What is printed?", ["Hi, I'm Ada", "Hi, I'm undefined", "Hi, I'm this.name", "An error"], 0,
                code='const p = {\n  name: "Ada",\n  hello() {\n    return "Hi, I\'m " + this.name;\n  },\n};\nconsole.log(p.hello());'),
            fill("Refer to the object's own count.", "increment() {\n  ___.count++;\n}", "this"),
            mcq("What is a method?", ["A function stored as an object property", "A type of loop", "A variable", "An array"], 0),
            order("Order the object with a method.", ["const dog = {", '  sound: "Woof",', "  speak() {", "    return this.sound;", "  },", "};"]),
            run("Create an object account with balance: 0 and methods deposit(amount) and withdraw(amount). withdraw must refuse (return false) if there's not enough money; both return true on success.",
                "javascript",
                [t("deposit + withdraw", append="account.deposit(50);\nconsole.log(account.withdraw(20), account.balance);"),
                 t("overdraw", append="account.deposit(10);\nconsole.log(account.withdraw(30), account.balance);")],
                ["true 30", "false 10"],
                "const account = {\n  balance: 0,\n  deposit(amount) {\n    this.balance += amount;\n    return true;\n  },\n  withdraw(amount) {\n    if (amount > this.balance) {\n      return false;\n    }\n    this.balance -= amount;\n    return true;\n  },\n};",
                starter="const account = {\n  balance: 0,\n};\n", require=[r"this\.balance"]),
        ),
        lesson(
            "Destructuring & JSON",
            "Destructuring pulls values out of objects and arrays:\n\nconst { name, age } = user;\nconst [first, second] = [10, 20];\n\nThe spread operator copies: const copy = { ...user, age: 37 };\n\nJSON turns objects into text and back:\nJSON.stringify({ a: 1 })   // '{\"a\":1}'\nJSON.parse('{\"a\":1}').a   // 1",
            mcq("What is x?", ["1", "2", "[ 1, 2 ]", "undefined"], 0, code="const [x, y] = [1, 2];"),
            mcq("What is JSON.stringify({ a: 1 })?", ['{"a":1}', "{ a: 1 }", "a=1", "[object Object]"], 0),
            fill("Pull name out of user.", "const { ___ } = user;", "name"),
            mcq("What is copy.age?", ["37", "36", "undefined", "An error"], 0, "Later properties overwrite earlier ones.",
                code='const user = { name: "Ada", age: 36 };\nconst copy = { ...user, age: 37 };'),
            run("Write summary(json) that parses a JSON string like '{\"name\":\"Ada\",\"langs\":[\"JS\",\"Py\"]}' and RETURNS \"Ada knows 2 languages\".", "javascript",
                [t("Ada", append='console.log(summary(\'{"name":"Ada","langs":["JS","Py"]}\'));'),
                 t("Linus", append='console.log(summary(\'{"name":"Linus","langs":["C"]}\'));')],
                ["Ada knows 2 languages", "Linus knows 1 languages"],
                "function summary(json) {\n  const { name, langs } = JSON.parse(json);\n  return `${name} knows ${langs.length} languages`;\n}",
                starter="function summary(json) {\n  \n}\n", require=[r"JSON\.parse"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Strings, classes & errors",
        lesson(
            "String methods",
            "Useful string methods (they return new strings):\n\n\"Hello\".toLowerCase()      // \"hello\"\n\"  hi  \".trim()            // \"hi\"\n\"a,b,c\".split(\",\")          // [\"a\", \"b\", \"c\"]\n\"banana\".replaceAll(\"a\", \"o\")  // \"bonono\"\n\"hello\".includes(\"ell\")     // true\n\"hello\".slice(1, 3)         // \"el\"\n\"hi\".repeat(3)              // \"hihihi\"",
            mcq("What is \"hello\".slice(1, 4)?", ['"ell"', '"hell"', '"ello"', '"el"'], 0, "From index 1 up to (not including) 4."),
            mcq("What is \"a-b-c\".split(\"-\")?", ["[ 'a', 'b', 'c' ]", "\"abc\"", "3", "[ 'a-b-c' ]"], 0),
            fill("Remove spaces at both ends.", "const clean = input.___();", "trim"),
            mcq("What is \"ab\".repeat(2)?", ['"abab"', '"ab2"', '"aabb"', "An error"], 0),
            run("Write isPalindrome(text) that RETURNS true if the text reads the same backwards, ignoring case and spaces.", "javascript",
                [t('"Racecar"', append='console.log(isPalindrome("Racecar"));'), t('"hello"', append='console.log(isPalindrome("hello"));'),
                 t('"Never odd or even"', append='console.log(isPalindrome("Never odd or even"));')],
                ["true", "false", "true"],
                'function isPalindrome(text) {\n  const clean = text.toLowerCase().replaceAll(" ", "");\n  return clean === clean.split("").reverse().join("");\n}',
                starter="function isPalindrome(text) {\n  \n}\n"),
        ),
        lesson(
            "Classes",
            "A class is a blueprint for creating objects:\n\nclass Dog {\n  constructor(name) {\n    this.name = name;\n  }\n  speak() {\n    return `${this.name} says woof`;\n  }\n}\n\nconst rex = new Dog(\"Rex\");\nrex.speak();   // \"Rex says woof\"",
            mcq("Which method runs when you create an object with new?", ["constructor", "init", "create", "new"], 0),
            fill("Create a new Dog.", 'const d = ___ Dog("Rex");', "new"),
            mcq("What is printed?", ["Ada", "name", "undefined", "An error"], 0,
                code='class Person {\n  constructor(name) {\n    this.name = name;\n  }\n}\nconsole.log(new Person("Ada").name);'),
            order("Order the class.", ["class Cat {", "  constructor(name) {", "    this.name = name;", "  }", "}"]),
            run("Write a class Rectangle with a constructor(width, height) and methods area() and isSquare().", "javascript",
                [t("3x4", append="const r = new Rectangle(3, 4);\nconsole.log(r.area(), r.isSquare());"),
                 t("5x5", append="const s = new Rectangle(5, 5);\nconsole.log(s.area(), s.isSquare());")],
                ["12 false", "25 true"],
                "class Rectangle {\n  constructor(width, height) {\n    this.width = width;\n    this.height = height;\n  }\n  area() {\n    return this.width * this.height;\n  }\n  isSquare() {\n    return this.width === this.height;\n  }\n}",
                starter="class Rectangle {\n  \n}\n", require=[r"\bclass\s+Rectangle", r"constructor\s*\("]),
        ),
        lesson(
            "Errors & try/catch",
            "When something fails, JavaScript throws an error. Catch it with try/catch:\n\ntry {\n  JSON.parse(\"not json\");\n} catch (err) {\n  console.log(\"Bad data:\", err.name);\n}\n\nThrow your own errors: throw new Error(\"Age must be positive\");",
            mcq("What is printed?", ["caught", "SyntaxError", "Nothing", "The program crashes"], 0,
                code='try {\n  JSON.parse("{oops");\n} catch (err) {\n  console.log("caught");\n}'),
            fill("Raise your own error.", '___ new Error("Too big");', "throw"),
            mcq("When does the finally block run?", ["Always, after try/catch", "Only on errors", "Only without errors", "Never"], 0),
            order("Order the try/catch.", ["try {", "  risky();", "} catch (err) {", "  console.log(err.message);", "}"]),
            run("Write safeParse(text) that RETURNS the parsed JSON value, or the string \"invalid\" if parsing fails.", "javascript",
                [t("valid", append='console.log(safeParse(\'{"ok":true}\').ok);'), t("invalid", append='console.log(safeParse("{bad"));'),
                 t("number", append='console.log(safeParse("42") + 1);')],
                ["true", "invalid", "43"], 'function safeParse(text) {\n  try {\n    return JSON.parse(text);\n  } catch (err) {\n    return "invalid";\n  }\n}',
                starter="function safeParse(text) {\n  \n}\n", require=[r"\btry\b", r"\bcatch\b"]),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
    EXPERT,
    EXPERT2,
)
