"""JavaScript - Intermediate and Advanced sections (units 9-16)."""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit


def call(expr: str) -> dict:
    return t(expr, append=f"console.log({expr});")


INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · Modern syntax",
        lesson(
            "Spread & rest",
            "... spreads an array/object out, or gathers the rest in:\n\nconst nums = [1, 2, 3];\nMath.max(...nums);              // 3 - spread as arguments\nconst more = [...nums, 4];       // copy + add\nconst user2 = { ...user, age: 37 };  // copy + override\n\nfunction sum(...values) {        // rest: gather arguments into an array\n  return values.reduce((a, b) => a + b, 0);\n}\nconst [first, ...others] = nums;  // rest in destructuring",
            mcq("What is [...[1, 2], ...[3]]?", ["[ 1, 2, 3 ]", "[ [ 1, 2 ], [ 3 ] ]", "6", "An error"], 0),
            mcq("In function f(...args), what is args?", ["An array of all arguments", "The first argument", "An object", "undefined"], 0),
            fill("Copy obj and override name.", "const copy = { ___obj, name: \"Bo\" };", "..."),
            mcq("What is rest after const [a, ...rest] = [1, 2, 3]?", ["[ 2, 3 ]", "[ 1, 2, 3 ]", "3", "2"], 0),
            run("Write mergeSettings(defaults, ...overrides) that returns a NEW object combining them, later objects winning, without changing defaults.", "javascript",
                [t("override", append='const d = { theme: "light", size: 2 };\nconsole.log(JSON.stringify(mergeSettings(d, { size: 3 }, { lang: "en" })));\nconsole.log(JSON.stringify(d));'),
                 t("none", append='console.log(JSON.stringify(mergeSettings({ a: 1 })));')],
                ['{"theme":"light","size":3,"lang":"en"}\n{"theme":"light","size":2}', '{"a":1}'],
                "function mergeSettings(defaults, ...overrides) {\n  return Object.assign({}, defaults, ...overrides);\n}", require=[r"\.\.\.\s*overrides"]),
        ),
        lesson(
            "Optional chaining & nullish coalescing",
            "?. stops safely when something is null/undefined instead of crashing:\n\nuser?.address?.city      // undefined instead of a TypeError\nuser.greet?.()           // only calls if greet exists\n\n?? gives a default ONLY for null/undefined (|| also replaces 0, \"\" and false):\n\nconst count = data.count ?? 0;   // keeps a real 0\nconst name = input || \"Anonymous\";",
            mcq("What is null ?? 'x'?", ["'x'", "null", "undefined", "An error"], 0),
            mcq("What is 0 ?? 5?", ["0", "5", "undefined", "null"], 0, "?? only replaces null and undefined - 0 is kept (0 || 5 would give 5)."),
            fill("Read city without crashing if address is missing.", "const city = user.address___city;", "?."),
            mcq("What does obj.method?.() do if method is undefined?", ["Returns undefined without calling", "Throws TypeError", "Calls obj", "Returns null"], 0),
            run("Write cityOf(user) returning the user's address city in upper case, or \"UNKNOWN\" if any part is missing - using ?. and ??.", "javascript",
                [call('cityOf({ address: { city: "Pune" } })'), call("cityOf({})"), call("cityOf(null)"), call('cityOf({ address: { city: "" } })')],
                ["PUNE", "UNKNOWN", "UNKNOWN", ""],
                'function cityOf(user) {\n  return user?.address?.city?.toUpperCase() ?? "UNKNOWN";\n}', require=[r"\?\.", r"\?\?"]),
        ),
        lesson(
            "Map & Set",
            "Map is a key → value collection where keys can be ANY type, and it keeps insertion order:\n\nconst counts = new Map();\ncounts.set(\"a\", 1);\ncounts.get(\"a\");         // 1\ncounts.has(\"b\");         // false\ncounts.size;             // 1\n\nSet stores unique values: new Set([1, 1, 2]).size is 2. [...new Set(arr)] removes duplicates.",
            mcq("What is new Set([1, 2, 2, 3]).size?", ["3", "4", "2", "undefined"], 0),
            mcq("Which method reads a Map value?", ["map.get(key)", "map[key]", "map.read(key)", "map.value(key)"], 0),
            fill("Remove duplicates from an array.", "const unique = [...new ___(arr)];", "Set"),
            mcq("Can a Map use an object as a key?", ["Yes", "No", "Only strings", "Only numbers"], 0),
            run("Write wordFrequency(text) that returns a Map of lower-cased word → count. The test prints the entries.", "javascript",
                [t("sentence", append='console.log([...wordFrequency("The cat and the hat")].map(([w, c]) => `${w}:${c}`).join(" "));'),
                 t("empty", append='console.log(wordFrequency("").size);')],
                ["the:2 cat:1 and:1 hat:1", "0"],
                'function wordFrequency(text) {\n  const counts = new Map();\n  for (const word of text.toLowerCase().split(" ").filter(Boolean)) {\n    counts.set(word, (counts.get(word) ?? 0) + 1);\n  }\n  return counts;\n}',
                require=[r"new\s+Map"]),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · Functions as values",
        lesson(
            "Closures",
            "A function remembers the variables around where it was created - a closure. It's how JS keeps private state:\n\nfunction makeCounter() {\n  let count = 0;              // private!\n  return () => ++count;\n}\nconst next = makeCounter();\nnext();  // 1\nnext();  // 2",
            mcq("What does the second call return?", ["2", "1", "0", "undefined"], 0, code="function make() {\n  let n = 0;\n  return () => ++n;\n}\nconst f = make();\nf();\nf();"),
            mcq("Can code outside makeCounter read count directly?", ["No - it's private to the closure", "Yes", "Only with this", "Only in strict mode"], 0),
            fill("Return a function that remembers n.", "function adder(n) {\n  ___ (x) => x + n;\n}", "return"),
            mcq("What is printed (var vs let in loops)?", ["0 1 2", "3 3 3", "undefined", "An error"], 0, "let creates a fresh i for each iteration, so each closure sees its own value.",
                code="const fns = [];\nfor (let i = 0; i < 3; i++) fns.push(() => i);\nconsole.log(fns.map((f) => f()).join(\" \"));"),
            run("Write once(fn) that returns a function which calls fn only the first time and returns that same result on every later call.", "javascript",
                [t("called once", append='let calls = 0;\nconst init = once(() => ++calls * 10);\nconsole.log(init(), init(), init(), calls);'),
                 t("passes args", append="const add = once((a, b) => a + b);\nconsole.log(add(2, 3), add(10, 10));")],
                ["10 10 10 1", "5 5"],
                "function once(fn) {\n  let done = false;\n  let result;\n  return (...args) => {\n    if (!done) {\n      done = true;\n      result = fn(...args);\n    }\n    return result;\n  };\n}",
                require=[r"function\s+once|const\s+once"]),
        ),
        lesson(
            "Higher-order functions",
            "A higher-order function takes or returns functions. You've used them: map, filter, setTimeout. Write your own:\n\nconst twice = (fn) => (x) => fn(fn(x));\nconst add3 = (x) => x + 3;\ntwice(add3)(10);   // 16\n\nCallbacks let the caller decide WHAT to do; your function decides WHEN.",
            mcq("What is twice((x) => x * 2)(5)?", ["20", "10", "25", "An error"], 0, code="const twice = (fn) => (x) => fn(fn(x));"),
            mcq("What is a callback?", ["A function passed in to be called later", "A recursive function", "A return value", "An error handler only"], 0),
            fill("Call the callback with each item.", "function each(arr, cb) {\n  for (const x of arr) ___(x);\n}", "cb"),
            mcq("Which of these is a higher-order function?", ["Array.prototype.map", "Math.max", "parseInt", "String"], 0),
            run("Write myFilter(arr, test) WITHOUT using .filter - return a new array of the items for which test(item, index) is true.", "javascript",
                [call("myFilter([1, 2, 3, 4], (n) => n % 2 === 0)"), call('myFilter(["a", "b", "c"], (x, i) => i !== 1)'), call("myFilter([], () => true)")],
                ["[ 2, 4 ]", "[ 'a', 'c' ]", "[]"],
                "function myFilter(arr, test) {\n  const out = [];\n  arr.forEach((item, i) => {\n    if (test(item, i)) out.push(item);\n  });\n  return out;\n}",
                forbid=[r"\.filter\("]),
        ),
        lesson(
            "Recursion",
            "A recursive function calls itself on a smaller part of the problem, until a base case:\n\nfunction sumDigits(n) {\n  if (n < 10) return n;                 // base case\n  return (n % 10) + sumDigits(Math.floor(n / 10));\n}\n\nRecursion is natural for nested data like trees and JSON.",
            mcq("What does every recursive function need?", ["A base case", "A loop", "A global variable", "async"], 0),
            mcq("What is depth(3)?", ["3", "0", "Infinite", "6"], 0, code="function depth(n) {\n  return n === 0 ? 0 : 1 + depth(n - 1);\n}"),
            fill("Recursive call on the rest of the array.", "const sum = (a) => a.length === 0 ? 0 : a[0] + sum(a.___(1));", "slice"),
            mcq("What error does unbounded recursion cause?", ["RangeError: Maximum call stack size exceeded", "TypeError", "SyntaxError", "None"], 0),
            run("Write countKeys(obj) that counts ALL keys in a nested object, recursively (nested objects count their own keys too).", "javascript",
                [call("countKeys({ a: 1, b: { c: 2, d: { e: 3 } } })"), call("countKeys({})"), call("countKeys({ x: [1, 2], y: null })")],
                ["5", "0", "2"],
                'function countKeys(obj) {\n  let total = 0;\n  for (const value of Object.values(obj)) {\n    total += 1;\n    if (value && typeof value === "object" && !Array.isArray(value)) {\n      total += countKeys(value);\n    }\n  }\n  return total;\n}',
                require=[r"countKeys\([^)]*\)[\s\S]*countKeys\("]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Arrays & objects in depth",
        lesson(
            "find, some, every & sort",
            "More array tools:\n\nusers.find((u) => u.id === 3)       // first match (or undefined)\nusers.findIndex(...)\nnums.some((n) => n < 0)             // at least one?\nnums.every((n) => n > 0)            // all?\npeople.sort((a, b) => a.age - b.age) // numeric sort (sorts IN PLACE)\nnames.sort((a, b) => a.localeCompare(b))",
            mcq("What does find return when nothing matches?", ["undefined", "null", "-1", "[]"], 0),
            mcq("What is [1, 2, 3].every((n) => n > 0)?", ["true", "false", "3", "[ 1, 2, 3 ]"], 0),
            fill("Sort numbers ascending.", "nums.sort((a, b) => a ___ b);", "-"),
            mcq("Does sort() change the original array?", ["Yes - use [...arr].sort() or toSorted() for a copy", "No", "Only for numbers", "Only for strings"], 0),
            run("Write topStudent(students) returning the NAME of the student with the highest score (first one wins ties), or null for an empty list - without mutating the input.", "javascript",
                [t("class", append='const s = [{ name: "Ada", score: 90 }, { name: "Bo", score: 95 }, { name: "Cy", score: 95 }];\nconsole.log(topStudent(s), s[0].name);'),
                 call("topStudent([])")],
                ["Bo Ada", "null"],
                "function topStudent(students) {\n  if (students.length === 0) return null;\n  return students.reduce((best, s) => (s.score > best.score ? s : best)).name;\n}"),
        ),
        lesson(
            "Object.entries & friends",
            "Turn objects into arrays and back:\n\nObject.keys(prices)     // [\"tea\", \"cake\"]\nObject.values(prices)   // [2, 3]\nObject.entries(prices)  // [[\"tea\", 2], [\"cake\", 3]]\nObject.fromEntries(entries)\n\nThe pattern: entries -> map/filter -> fromEntries transforms every value:\nObject.fromEntries(Object.entries(prices).map(([k, v]) => [k, v * 2]))",
            mcq("What does Object.entries({ a: 1 }) return?", ["[ [ 'a', 1 ] ]", "[ 'a', 1 ]", "{ a: 1 }", "[ 'a' ]"], 0),
            fill("Build an object back from [key, value] pairs.", "const obj = Object.___(pairs);", "fromEntries"),
            mcq("Which gives just the values?", ["Object.values(obj)", "Object.keys(obj)", "obj.values", "Object.get(obj)"], 0),
            mcq("In what order does Object.keys list string keys?", ["Insertion order", "Alphabetical", "Random", "Reverse"], 0),
            run("Write applyDiscount(prices, percent) returning a NEW object with every price reduced by percent and rounded to 2 decimals (as numbers).", "javascript",
                [t("10%", append='console.log(JSON.stringify(applyDiscount({ tea: 2.5, cake: 3.99 }, 10)));'),
                 t("unchanged input", append='const p = { a: 10 };\napplyDiscount(p, 50);\nconsole.log(p.a);')],
                ['{"tea":2.25,"cake":3.59}', "10"],
                "function applyDiscount(prices, percent) {\n  return Object.fromEntries(\n    Object.entries(prices).map(([item, price]) => [item, Math.round(price * (100 - percent)) / 100])\n  );\n}",
                require=[r"Object\.entries", r"Object\.fromEntries"]),
        ),
        lesson(
            "Copies & immutability",
            "Objects and arrays are passed by REFERENCE - two variables can point at the same object:\n\nconst a = { n: 1 };\nconst b = a;\nb.n = 2;     // a.n is 2 too!\n\nShallow copy: { ...a } or [...arr] - nested objects are still shared.\nDeep copy: structuredClone(a).\nObject.freeze(obj) prevents changes (shallowly).",
            mcq("What is a.n afterwards?", ["2", "1", "undefined", "An error"], 0, code="const a = { n: 1 };\nconst b = a;\nb.n = 2;"),
            mcq("After const c = { ...a }, is c.inner the same object as a.inner?", ["Yes - spread is a shallow copy", "No", "Only for arrays", "Only if frozen"], 0),
            fill("Deep-copy an object.", "const copy = ___(original);", "structuredClone"),
            mcq("What does Object.freeze do?", ["Prevents adding/changing/removing properties (shallowly)", "Deep-copies", "Deletes the object", "Makes it async"], 0),
            run("Write addTag(post, tag) that returns a NEW post with tag added to post.meta.tags, leaving the original post (including its nested arrays) untouched.", "javascript",
                [t("immutability", append='const post = { title: "Hi", meta: { tags: ["js"] } };\nconst next = addTag(post, "tips");\nconsole.log(next.meta.tags.join(","), post.meta.tags.join(","), next !== post);')],
                ["js,tips js true"],
                "function addTag(post, tag) {\n  return { ...post, meta: { ...post.meta, tags: [...post.meta.tags, tag] } };\n}",
                forbid=[r"\.push\("]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Classes in depth",
        lesson(
            "Inheritance & super",
            "extends creates a subclass; super calls the parent:\n\nclass Animal {\n  constructor(name) { this.name = name; }\n  speak() { return `${this.name} makes a sound`; }\n}\nclass Dog extends Animal {\n  constructor(name, breed) {\n    super(name);          // must come before using this\n    this.breed = breed;\n  }\n  speak() { return `${super.speak()} - woof`; }\n}",
            mcq("What must a subclass constructor do before using this?", ["Call super(...)", "Call this()", "Return", "Nothing"], 0),
            fill("Dog inherits from Animal.", "class Dog ___ Animal { }", "extends"),
            mcq("What does new Dog('Rex') instanceof Animal give?", ["true", "false", "undefined", "An error"], 0),
            mcq("How do you call the parent's version of speak inside Dog.speak?", ["super.speak()", "Animal.speak()", "this.parent.speak()", "base.speak()"], 0),
            run("Write class Employee(name, salary) with describe() → \"<name> earns <salary>\", and Manager extends Employee adding reports (an array) and overriding describe() to append \" and manages <n> people\".", "javascript",
                [t("employee", append='console.log(new Employee("Ada", 100).describe());'),
                 t("manager", append='const m = new Manager("Bo", 200, ["Ada", "Cy"]);\nconsole.log(m.describe(), m instanceof Employee);')],
                ["Ada earns 100", "Bo earns 200 and manages 2 people true"],
                "class Employee {\n  constructor(name, salary) {\n    this.name = name;\n    this.salary = salary;\n  }\n  describe() {\n    return `${this.name} earns ${this.salary}`;\n  }\n}\n\nclass Manager extends Employee {\n  constructor(name, salary, reports) {\n    super(name, salary);\n    this.reports = reports;\n  }\n  describe() {\n    return `${super.describe()} and manages ${this.reports.length} people`;\n  }\n}",
                require=[r"extends\s+Employee", r"super\("]),
        ),
        lesson(
            "Getters, setters & static",
            "get/set make methods look like properties - useful for computed or validated values. static members belong to the class itself:\n\nclass Circle {\n  constructor(r) { this.r = r; }\n  get area() { return Math.PI * this.r ** 2; }\n  set diameter(d) { this.r = d / 2; }\n  static unit() { return new Circle(1); }\n}\nnew Circle(2).area;   // no ()\nCircle.unit();",
            mcq("How do you read a getter named area?", ["obj.area", "obj.area()", "obj.getArea()", "get(obj.area)"], 0),
            mcq("How do you call a static method?", ["On the class: Circle.unit()", "On an instance", "With new", "It can't be called"], 0),
            fill("Define a computed property.", "___ fullName() {\n  return `${this.first} ${this.last}`;\n}", "get"),
            mcq("What's a common use of a setter?", ["Validating or converting a value when it's assigned", "Deleting properties", "Looping", "Making the class static"], 0),
            run("Write class Temperature with a celsius field, a fahrenheit getter AND setter (F = C × 9/5 + 32), and a static fromFahrenheit(f).", "javascript",
                [t("getter", append="console.log(new Temperature(100).fahrenheit);"),
                 t("setter", append="const t = new Temperature(0);\nt.fahrenheit = 212;\nconsole.log(t.celsius);"),
                 t("static", append="console.log(Temperature.fromFahrenheit(32).celsius);")],
                ["212", "100", "0"],
                "class Temperature {\n  constructor(celsius) {\n    this.celsius = celsius;\n  }\n  get fahrenheit() {\n    return (this.celsius * 9) / 5 + 32;\n  }\n  set fahrenheit(f) {\n    this.celsius = ((f - 32) * 5) / 9;\n  }\n  static fromFahrenheit(f) {\n    const t = new Temperature(0);\n    t.fahrenheit = f;\n    return t;\n  }\n}",
                require=[r"\bget\s+fahrenheit", r"\bset\s+fahrenheit", r"\bstatic\b"]),
        ),
        lesson(
            "Private fields",
            "Fields starting with # are truly private - only code inside the class can see them:\n\nclass Account {\n  #balance = 0;\n  deposit(n) { this.#balance += n; }\n  get balance() { return this.#balance; }\n}\nconst a = new Account();\na.#balance;   // SyntaxError outside the class\n\nThis is real encapsulation: outside code must use your methods.",
            mcq("What does # in front of a field name mean?", ["It's private to the class", "It's a comment", "It's static", "It's a number"], 0),
            mcq("Can outside code read obj.#secret?", ["No - it's a SyntaxError", "Yes", "Only in strict mode", "Only with getters"], 0),
            fill("Declare a private field starting at 0.", "class Counter {\n  ___count = 0;\n}", "#"),
            mcq("How should outside code read a private value?", ["Through a public method or getter", "With brackets obj['#x']", "With Object.keys", "It can't ever"], 0),
            run("Write class Stack with a PRIVATE array, and methods push(x), pop() (undefined when empty), peek(), and a size getter.", "javascript",
                [t("usage", append="const s = new Stack();\ns.push(1);\ns.push(2);\nconsole.log(s.peek(), s.pop(), s.size, s.pop(), s.pop());"),
                 t("encapsulated", append="console.log(Object.keys(new Stack()).length);")],
                ["2 2 1 1 undefined", "0"],
                "class Stack {\n  #items = [];\n  push(x) {\n    this.#items.push(x);\n  }\n  pop() {\n    return this.#items.pop();\n  }\n  peek() {\n    return this.#items[this.#items.length - 1];\n  }\n  get size() {\n    return this.#items.length;\n  }\n}",
                require=[r"#\w+"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Asynchronous JavaScript",
        lesson(
            "The event loop",
            "JavaScript runs one thing at a time. Slow work (timers, network) is handed off, and its callback is queued for later:\n\nconsole.log(\"A\");\nsetTimeout(() => console.log(\"B\"), 0);\nPromise.resolve().then(() => console.log(\"C\"));\nconsole.log(\"D\");\n// A D C B\n\nOrder: all synchronous code first, then promise callbacks (microtasks), then timers (tasks).",
            mcq("What is printed?", ["A D C B", "A B C D", "A C D B", "A D B C"], 0,
                code='console.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");'),
            mcq("Does setTimeout(fn, 0) run fn immediately?", ["No - after the current code and microtasks", "Yes", "Only in browsers", "Never"], 0),
            fill("Schedule work to run later.", "___(() => console.log(\"later\"), 100);", "setTimeout"),
            mcq("Why doesn't a long loop let timers fire?", ["JS is single-threaded - the loop must finish first", "Timers are broken", "Loops cancel timers", "It does"], 0),
            run("Without changing the order of the statements, make the program print 1, 2, 3, 4 in order by choosing for each line whether it runs now, in a microtask (queueMicrotask) or a timer (setTimeout). Fill in schedule().", "javascript",
                [t("order", append='schedule(\n  () => console.log(4),\n  () => console.log(2),\n  () => console.log(3),\n  () => console.log(1),\n);')],
                ["1\n2\n3\n4"],
                "function schedule(four, two, three, one) {\n  setTimeout(four, 0);\n  queueMicrotask(two);\n  queueMicrotask(three);\n  one();\n}",
                require=[r"setTimeout", r"queueMicrotask|Promise\.resolve"]),
        ),
        lesson(
            "Promises",
            "A Promise is a value that will arrive later (or fail):\n\nconst wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));\n\nwait(100)\n  .then(() => fetchUser(1))\n  .then((user) => console.log(user.name))\n  .catch((err) => console.log(\"failed:\", err.message));\n\nPromise.all([...]) waits for all; Promise.race for the first; Promise.allSettled for every outcome.",
            mcq("Which method handles a rejected promise?", [".catch()", ".then() only", ".finally() only", ".error()"], 0),
            mcq("When does Promise.all reject?", ["As soon as any promise rejects", "Only if all reject", "Never", "After all settle"], 0),
            fill("Create a promise that succeeds.", "new Promise((___, reject) => resolve(42));", "resolve"),
            mcq("What does Promise.allSettled give you?", ["Every result, fulfilled or rejected", "Only successes", "The fastest result", "Nothing"], 0),
            run("Write delay(ms, value) returning a promise that resolves to value after ms. Then use Promise.all in the test to collect several.", "javascript",
                [t("all", append="Promise.all([delay(30, 'a'), delay(10, 'b'), delay(20, 'c')]).then((v) => console.log(v.join('')));"),
                 t("race", append="Promise.race([delay(50, 'slow'), delay(5, 'fast')]).then(console.log);")],
                ["abc", "fast"],
                "function delay(ms, value) {\n  return new Promise((resolve) => setTimeout(() => resolve(value), ms));\n}",
                require=[r"new\s+Promise"]),
        ),
        lesson(
            "async / await",
            "async/await lets you write promise code that reads top to bottom:\n\nasync function loadProfile(id) {\n  try {\n    const user = await getUser(id);\n    const posts = await getPosts(user.id);\n    return { user, posts };\n  } catch (err) {\n    return null;\n  }\n}\n\nAn async function always returns a promise. Run independent work in parallel with await Promise.all([...]).",
            mcq("What does an async function return?", ["A Promise", "The value directly", "undefined", "A callback"], 0),
            mcq("How do you handle errors from await?", ["try/catch", ".then only", "They can't fail", "if (error)"], 0),
            fill("Wait for the promise inside an async function.", "const data = ___ fetchData();", "await"),
            mcq("Why use await Promise.all([a(), b()]) instead of two awaits in a row?", ["The two tasks run at the same time", "It's required", "It's more readable only", "It catches errors"], 0),
            run("Using async/await, write fetchAll(ids, getUser) that calls the async getUser for every id IN PARALLEL and returns their names; if any call fails, return the string \"error: \" + message.", "javascript",
                [t("ok", append='const getUser = async (id) => { await new Promise((r) => setTimeout(r, 20 - id)); return { name: "user" + id }; };\nfetchAll([1, 2, 3], getUser).then((r) => console.log(r));'),
                 t("failure", append='const bad = async (id) => { if (id === 2) throw new Error("not found"); return { name: "u" + id }; };\nfetchAll([1, 2], bad).then(console.log);')],
                ["[ 'user1', 'user2', 'user3' ]", "error: not found"],
                'async function fetchAll(ids, getUser) {\n  try {\n    const users = await Promise.all(ids.map((id) => getUser(id)));\n    return users.map((u) => u.name);\n  } catch (err) {\n    return "error: " + err.message;\n  }\n}',
                require=[r"\basync\b", r"\bawait\b", r"Promise\.all"]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Errors, iterators & generators",
        lesson(
            "Custom errors",
            "Extend Error to create meaningful error types:\n\nclass ValidationError extends Error {\n  constructor(field, message) {\n    super(message);\n    this.name = \"ValidationError\";\n    this.field = field;\n  }\n}\n\ntry { ... } catch (err) {\n  if (err instanceof ValidationError) show(err.field);\n  else throw err;    // re-throw what you can't handle\n}",
            mcq("What should a custom error class extend?", ["Error", "Object", "Exception", "Throwable"], 0),
            mcq("What should you do with errors you can't handle in a catch?", ["Re-throw them", "Ignore them", "Log and return", "Convert to strings"], 0),
            fill("Check the error's type.", "if (err ___ ValidationError) { }", "instanceof"),
            mcq("Why set this.name in a custom error?", ["So messages and logs show the right error type", "It's required", "For speed", "To make it private"], 0),
            run("Write class ValidationError (extends Error, with a field property) and parseAge(text) that throws ValidationError(\"age\", \"not a number\") or (\"age\", \"must be positive\"), else returns the number.", "javascript",
                [call('parseAge("42")'),
                 t("bad", append='try { parseAge("abc"); } catch (e) { console.log(e.name, e.field, e.message, e instanceof Error); }'),
                 t("negative", append='try { parseAge("-1"); } catch (e) { console.log(e.message); }')],
                ["42", "ValidationError age not a number true", "must be positive"],
                'class ValidationError extends Error {\n  constructor(field, message) {\n    super(message);\n    this.name = "ValidationError";\n    this.field = field;\n  }\n}\n\nfunction parseAge(text) {\n  const n = Number(text);\n  if (Number.isNaN(n)) throw new ValidationError("age", "not a number");\n  if (n <= 0) throw new ValidationError("age", "must be positive");\n  return n;\n}',
                require=[r"extends\s+Error", r"\bthrow\b"]),
        ),
        lesson(
            "Iterators",
            "Anything with a [Symbol.iterator]() method can be used in for...of and spread:\n\nconst range = {\n  from: 1, to: 3,\n  [Symbol.iterator]() {\n    let n = this.from, to = this.to;\n    return { next: () => (n <= to ? { value: n++, done: false } : { value: undefined, done: true }) };\n  },\n};\n[...range];   // [1, 2, 3]",
            mcq("What does an iterator's next() return?", ["An object { value, done }", "The next value only", "true/false", "An array"], 0),
            fill("The method that makes an object iterable.", "[Symbol.___]() { ... }", "iterator"),
            mcq("Which of these is NOT iterable by default?", ["A plain object {}", "An array", "A string", "A Map"], 0),
            mcq("What does done: true mean?", ["The iteration is finished", "An error happened", "The value is ready", "Restart"], 0),
            run("Make a class Countdown(start) iterable (implement [Symbol.iterator] returning an iterator object) so [...new Countdown(3)] gives [3, 2, 1].", "javascript",
                [call("[...new Countdown(3)]"), call("[...new Countdown(0)]"), t("for-of", append="for (const n of new Countdown(2)) console.log(n);")],
                ["[ 3, 2, 1 ]", "[]", "2\n1"],
                "class Countdown {\n  constructor(start) {\n    this.start = start;\n  }\n  [Symbol.iterator]() {\n    let n = this.start;\n    return {\n      next: () => (n > 0 ? { value: n--, done: false } : { value: undefined, done: true }),\n    };\n  }\n}",
                require=[r"Symbol\.iterator"], forbid=[r"function\s*\*|\*\s*\[Symbol"]),
        ),
        lesson(
            "Generators",
            "A generator function (function*) can pause with yield - it's the easy way to build iterators:\n\nfunction* idGenerator() {\n  let id = 1;\n  while (true) yield id++;\n}\nconst ids = idGenerator();\nids.next().value;  // 1\nids.next().value;  // 2\n\nGenerators are lazy: they only compute what you ask for, so infinite sequences are fine.",
            mcq("How is a generator function declared?", ["function* name()", "function name*()", "gen function name()", "async function name()"], 0),
            mcq("What does the first gen.next() return here?", ["{ value: 1, done: false }", "1", "{ value: 2, done: false }", "undefined"], 0, code="function* g() {\n  yield 1;\n  yield 2;\n}\nconst gen = g();"),
            fill("Pause and hand out a value.", "function* evens() {\n  for (let i = 0; ; i += 2) ___ i;\n}", "yield"),
            mcq("Can a generator be infinite?", ["Yes - values are produced only on demand", "No", "Only with a break", "Only async ones"], 0),
            run("Write a generator take(iterable, n) that yields the first n items of any iterable, and a generator naturals() yielding 1, 2, 3, … forever.", "javascript",
                [call("[...take(naturals(), 5)]"), call('[...take("hello", 3)].join("")'), call("[...take([1, 2], 10)]")],
                ["[ 1, 2, 3, 4, 5 ]", "hel", "[ 1, 2 ]"],
                "function* naturals() {\n  let n = 1;\n  while (true) yield n++;\n}\n\nfunction* take(iterable, n) {\n  if (n <= 0) return;\n  let count = 0;\n  for (const item of iterable) {\n    yield item;\n    if (++count >= n) return;\n  }\n}",
                require=[r"function\s*\*\s*take", r"function\s*\*\s*naturals", r"\byield\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · Functional patterns",
        lesson(
            "Composition & currying",
            "Build big functions from small ones:\n\nconst compose = (...fns) => (x) => fns.reduceRight((acc, f) => f(acc), x);\nconst pipe = (...fns) => (x) => fns.reduce((acc, f) => f(acc), x);\nconst slugify = pipe(trim, toLower, (s) => s.replaceAll(\" \", \"-\"));\n\nCurrying turns f(a, b) into f(a)(b), which makes partial application easy:\nconst add = (a) => (b) => a + b;\nconst add5 = add(5);",
            mcq("In which order does pipe(f, g)(x) apply the functions?", ["f first, then g", "g first, then f", "Both at once", "Only f"], 0),
            mcq("What is add(2)(3) for const add = (a) => (b) => a + b?", ["5", "23", "A function", "An error"], 0),
            fill("Apply each function in turn.", "const pipe = (...fns) => (x) => fns.___((acc, f) => f(acc), x);", "reduce"),
            mcq("What is a pure function?", ["Same inputs always give the same output, with no side effects", "A function with no parameters", "An arrow function", "A recursive function"], 0),
            run("Write pipe(...fns) and use it to build slugify(text): trim → lower-case → replace runs of spaces with a single '-' → remove characters other than a-z, 0-9 and '-'.", "javascript",
                [call('slugify("  Hello World  ")'), call('slugify("Learn   C++ & Java!")'), call("pipe()(42)")],
                ["hello-world", "learn-c-java", "42"],
                'const pipe = (...fns) => (x) => fns.reduce((acc, f) => f(acc), x);\n\nconst slugify = pipe(\n  (s) => s.trim(),\n  (s) => s.toLowerCase(),\n  (s) => s.replace(/\\s+/g, "-"),\n  (s) => s.replace(/[^a-z0-9-]/g, ""),\n  (s) => s.replace(/-+/g, "-"),\n);',
                require=[r"const\s+pipe|function\s+pipe"]),
        ),
        lesson(
            "Memoization",
            "Memoization caches a function's results by its arguments, trading memory for speed:\n\nfunction memoize(fn) {\n  const cache = new Map();\n  return (n) => {\n    if (!cache.has(n)) cache.set(n, fn(n));\n    return cache.get(n);\n  };\n}\n\nIt turns slow recursive algorithms (like naive Fibonacci, O(2^n)) into fast ones (O(n)).",
            mcq("When is memoization safe?", ["When the function is pure", "Always", "Only for async functions", "Never with numbers"], 0),
            mcq("What does a memoized function trade?", ["Memory for speed", "Speed for memory", "Accuracy for speed", "Nothing"], 0),
            fill("Return the cached result if we have it.", "if (cache.___(key)) return cache.get(key);", "has"),
            mcq("Roughly how many calls does naive fib(30) make?", ["About 1.6 million", "30", "About 900", "About 60"], 0),
            run("Write memoize(fn) for single-argument functions, and a memoized recursive fib so fib(70) is instant. The test also counts how often the underlying function runs.", "javascript",
                [call("fib(70)"), t("caches", append="let runs = 0;\nconst sq = memoize((n) => { runs++; return n * n; });\nsq(4); sq(4); sq(5);\nconsole.log(runs);")],
                ["190392490709135", "2"],
                "function memoize(fn) {\n  const cache = new Map();\n  return (n) => {\n    if (!cache.has(n)) cache.set(n, fn(n));\n    return cache.get(n);\n  };\n}\n\nconst fib = memoize((n) => (n < 2 ? n : fib(n - 1) + fib(n - 2)));",
                require=[r"memoize", r"\bMap\b|\{\s*\}|cache"]),
        ),
        lesson(
            "Debounce & throttle",
            "Control how often a function runs - essential for search boxes and scroll handlers:\n\ndebounce: run only after calls STOP for wait ms (e.g. search after typing pauses)\nthrottle: run at most once per wait ms (e.g. scroll position updates)\n\nfunction debounce(fn, wait) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), wait);\n  };\n}",
            mcq("Which suits a search box that should query after typing stops?", ["debounce", "throttle", "memoize", "setInterval"], 0),
            mcq("Which suits updating a progress bar at most every 100 ms while scrolling?", ["throttle", "debounce", "Promise.all", "memoize"], 0),
            fill("Cancel the previous scheduled call.", "___(timer);", "clearTimeout"),
            mcq("What does debounce do with 10 rapid calls?", ["Runs once, after they stop", "Runs 10 times", "Runs the first only, immediately", "Never runs"], 0),
            run("Write debounce(fn, wait). In the test, 3 rapid calls then a pause then 1 more call should run fn twice, with the LAST arguments of each burst.", "javascript",
                [t("bursts", append='const log = debounce((x) => console.log("run", x), 50);\nlog(1); log(2); log(3);\nsetTimeout(() => log(4), 200);')],
                ["run 3\nrun 4"],
                "function debounce(fn, wait) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), wait);\n  };\n}",
                require=[r"setTimeout", r"clearTimeout"]),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Data structures & algorithms",
        lesson(
            "Stacks & queues",
            "Two classic structures:\n\nStack - last in, first out (LIFO): push / pop. Undo history, matching brackets.\nQueue - first in, first out (FIFO): push / shift. Task lists, breadth-first search.\n\nconst stack = [];\nstack.push(\"a\"); stack.pop();\nconst queue = [];\nqueue.push(\"job1\"); queue.shift();",
            mcq("Which structure gives LIFO order?", ["Stack", "Queue", "Set", "Map"], 0),
            mcq("Which array method removes from the FRONT (queue)?", ["shift()", "pop()", "slice()", "splice(0)"], 0),
            fill("Take the most recently added item.", "const top = stack.___();", "pop"),
            mcq("Which structure suits checking balanced brackets?", ["Stack", "Queue", "Set", "Linked list"], 0),
            run("Write isBalanced(text) that returns true if all (), [] and {} brackets are properly nested and closed (other characters are ignored), using a stack.", "javascript",
                [call('isBalanced("{[()()]}")'), call('isBalanced("(]")'), call('isBalanced("((")'), call('isBalanced("fn(a[1]) { return; }")')],
                ["true", "false", "false", "true"],
                'function isBalanced(text) {\n  const pairs = { ")": "(", "]": "[", "}": "{" };\n  const stack = [];\n  for (const ch of text) {\n    if ("([{".includes(ch)) stack.push(ch);\n    else if (ch in pairs) {\n      if (stack.pop() !== pairs[ch]) return false;\n    }\n  }\n  return stack.length === 0;\n}',
                require=[r"\.push\(", r"\.pop\("]),
        ),
        lesson(
            "Searching & sorting",
            "Binary search finds an item in a SORTED array in O(log n) by halving the range:\n\nlet lo = 0, hi = arr.length - 1;\nwhile (lo <= hi) {\n  const mid = Math.floor((lo + hi) / 2);\n  if (arr[mid] === target) return mid;\n  if (arr[mid] < target) lo = mid + 1; else hi = mid - 1;\n}\n\nGood sorts (merge sort, the built-in sort) are O(n log n); simple ones (bubble, insertion) are O(n²).",
            mcq("What does binary search require?", ["Sorted data", "Unique values", "Numbers only", "A linked list"], 0),
            mcq("What's merge sort's time complexity?", ["O(n log n)", "O(n²)", "O(n)", "O(log n)"], 0),
            fill("Pick the middle index.", "const mid = Math.___((lo + hi) / 2);", "floor"),
            mcq("Which is O(n²)?", ["Bubble sort", "Binary search", "Merge sort", "Map lookup"], 0),
            run("Implement mergeSort(arr) (recursive, returns a new sorted array of numbers) without using .sort.", "javascript",
                [call("mergeSort([5, 2, 9, 1, 5, 6])"), call("mergeSort([])"), call("mergeSort([3, -1])")],
                ["[ 1, 2, 5, 5, 6, 9 ]", "[]", "[ -1, 3 ]"],
                "function mergeSort(arr) {\n  if (arr.length <= 1) return arr.slice();\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  const out = [];\n  let i = 0;\n  let j = 0;\n  while (i < left.length && j < right.length) {\n    out.push(left[i] <= right[j] ? left[i++] : right[j++]);\n  }\n  return out.concat(left.slice(i), right.slice(j));\n}",
                require=[r"mergeSort\([^)]*\)[\s\S]*mergeSort\("], forbid=[r"\.sort\("]),
        ),
        lesson(
            "Graphs & BFS",
            "A graph is nodes connected by edges - maps, social networks, dependencies. Store it as an adjacency list:\n\nconst graph = { A: [\"B\", \"C\"], B: [\"D\"], C: [\"D\"], D: [] };\n\nBreadth-first search (BFS) explores level by level with a queue, so it finds the SHORTEST path (fewest edges) in an unweighted graph.",
            mcq("Which structure does BFS use?", ["A queue", "A stack", "A heap", "Recursion only"], 0),
            mcq("What does BFS find in an unweighted graph?", ["The path with the fewest edges", "The longest path", "A random path", "Cycles only"], 0),
            fill("Remember nodes we've already seen.", "const visited = new ___([start]);", "Set"),
            mcq("What's an adjacency list?", ["Each node mapped to its neighbours", "A grid of 0/1", "A sorted array", "A tree"], 0),
            run("Write shortestPath(graph, start, goal) using BFS, returning the path as an array of nodes (or null if unreachable).", "javascript",
                [t("path", append='const g = { A: ["B", "C"], B: ["D"], C: ["D", "E"], D: ["F"], E: ["F"], F: [] };\nconsole.log(shortestPath(g, "A", "F").join("->"));'),
                 t("unreachable", append='console.log(shortestPath({ A: ["B"], B: [], C: [] }, "A", "C"));'),
                 t("same node", append='console.log(shortestPath({ A: [] }, "A", "A"));')],
                ["A->B->D->F", "null", "[ 'A' ]"],
                "function shortestPath(graph, start, goal) {\n  const queue = [[start]];\n  const visited = new Set([start]);\n  while (queue.length) {\n    const path = queue.shift();\n    const node = path[path.length - 1];\n    if (node === goal) return path;\n    for (const next of graph[node] ?? []) {\n      if (!visited.has(next)) {\n        visited.add(next);\n        queue.push([...path, next]);\n      }\n    }\n  }\n  return null;\n}",
                require=[r"\.shift\(\)|queue"]),
        ),
    ),
)
