"""Python - Intermediate and Advanced sections (units 9-16)."""
from .dsl import code, fill, lesson, mcq, order, run, section, t, unit

INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 9
    unit(
        "Unit 9 · Comprehensions & iteration",
        lesson(
            "List, dict & set comprehensions",
            "Comprehensions build collections in one readable line:\n\nsquares = [n * n for n in range(5)]            # [0, 1, 4, 9, 16]\nevens   = [n for n in nums if n % 2 == 0]\nlengths = {w: len(w) for w in [\"hi\", \"code\"]}  # {'hi': 2, 'code': 4}\nunique  = {c.lower() for c in \"AaBb\"}          # {'a', 'b'}\n\nRead them as: [expression  for item in iterable  if condition].",
            mcq("What is printed?", ["[1, 4, 9]", "[1, 2, 3]", "[2, 4, 6]", "14"], 0, code="print([n * n for n in [1, 2, 3]])"),
            mcq("What is printed?", ["{'a': 1, 'bb': 2}", "['a', 'bb']", "{1: 'a', 2: 'bb'}", "An error"], 0, code="print({w: len(w) for w in ['a', 'bb']})"),
            fill("Keep only the positive numbers.", "pos = [n for n in nums ___ n > 0]", "if"),
            mcq("Which brackets make a SET comprehension?", ["{x for x in data}", "[x for x in data]", "(x for x in data)", "<x for x in data>"], 0,
                "{…} with a single expression makes a set; with key: value it's a dict. (…) makes a generator."),
            run("Write squares_of_odds(nums) that returns a list of the squares of the odd numbers, using a list comprehension.", "python",
                [t("[1..6]", append="print(squares_of_odds([1, 2, 3, 4, 5, 6]))"), t("no odds", append="print(squares_of_odds([2, 4]))"),
                 t("negatives", append="print(squares_of_odds([-3, 7]))")],
                ["[1, 9, 25]", "[]", "[9, 49]"], "def squares_of_odds(nums):\n    return [n * n for n in nums if n % 2 != 0]",
                require=[r"\[[^\]]*\bfor\b[^\]]*\]"], hint="[n * n for n in nums if ...]"),
        ),
        lesson(
            "enumerate & zip",
            "enumerate gives you the index AND the item:\n\nfor i, name in enumerate([\"Ada\", \"Bo\"], start=1):\n    print(i, name)        # 1 Ada / 2 Bo\n\nzip walks several lists together:\n\nfor name, score in zip(names, scores):\n    print(name, score)\n\ndict(zip(keys, values)) builds a dictionary from two lists.",
            mcq("What is printed?", ["0 a\n1 b", "1 a\n2 b", "a 0\nb 1", "An error"], 0, code="for i, c in enumerate(['a', 'b']):\n    print(i, c)"),
            mcq("What is list(zip([1, 2, 3], ['x', 'y']))?", ["[(1, 'x'), (2, 'y')]", "[(1, 'x'), (2, 'y'), (3, None)]", "An error", "[1, 'x', 2, 'y']"], 0,
                "zip stops at the shortest input."),
            fill("Number the items starting at 1.", "for n, item in enumerate(items, ___=1):", "start"),
            mcq("What does dict(zip(['a', 'b'], [1, 2])) give?", ["{'a': 1, 'b': 2}", "[('a', 1), ('b', 2)]", "{'a': 'b', 1: 2}", "An error"], 0),
            run("Read a line of names and a line of scores (same count). Print a ranked list - highest score first - as: 1. Ada (91)", "python",
                [t("three", stdin="Ada Bo Cy\n91 78 85"), t("two", stdin="Zed Amy\n50 99")],
                ["1. Ada (91)\n2. Cy (85)\n3. Bo (78)", "1. Amy (99)\n2. Zed (50)"],
                'names = input().split()\nscores = [int(s) for s in input().split()]\nranked = sorted(zip(names, scores), key=lambda p: p[1], reverse=True)\nfor i, (name, score) in enumerate(ranked, start=1):\n    print(f"{i}. {name} ({score})")',
                require=[r"\bzip\(", r"\benumerate\("]),
        ),
        lesson(
            "Sorting with key & lambda",
            "sorted() returns a new sorted list; list.sort() sorts in place. key= says WHAT to sort by:\n\nwords = [\"banana\", \"Kiwi\", \"apple\"]\nsorted(words, key=len)                 # by length\nsorted(words, key=str.lower)           # case-insensitive\nsorted(people, key=lambda p: p[\"age\"], reverse=True)\n\nlambda makes a tiny unnamed function: lambda x: x * 2.",
            mcq("What is sorted(['bb', 'a', 'ccc'], key=len)?", ["['a', 'bb', 'ccc']", "['ccc', 'bb', 'a']", "['a', 'ccc', 'bb']", "An error"], 0),
            mcq("What does lambda x: x + 1 do?", ["Makes a small function that adds 1", "Adds 1 to x permanently", "Loops", "Nothing"], 0),
            fill("Sort largest first.", "sorted(nums, ___=True)", "reverse"),
            mcq("What's the difference between sorted(a) and a.sort()?", ["sorted returns a new list; sort changes a in place", "No difference", "sort returns a new list", "sorted only works on strings"], 0),
            run("Write sort_people(people) that takes a list of (name, age) tuples and returns them sorted by age (youngest first), with ties sorted by name.", "python",
                [t("mixed", append='print(sort_people([("Cy", 30), ("Ada", 25), ("Bo", 30)]))'), t("one", append='print(sort_people([("Solo", 1)]))')],
                ["[('Ada', 25), ('Bo', 30), ('Cy', 30)]", "[('Solo', 1)]"],
                "def sort_people(people):\n    return sorted(people, key=lambda p: (p[1], p[0]))", require=[r"\bkey\s*="],
                hint="A key can return a tuple: (age, name)."),
        ),
    ),
    # ------------------------------------------------------------------ 10
    unit(
        "Unit 10 · Functions in depth",
        lesson(
            "*args & **kwargs",
            "Accept any number of arguments:\n\ndef total(*nums):          # nums is a tuple\n    return sum(nums)\ntotal(1, 2, 3)             # 6\n\ndef show(**info):          # info is a dict\n    for k, v in info.items():\n        print(k, v)\nshow(name=\"Ada\", age=36)\n\n* and ** also UNPACK: total(*[1, 2, 3]), show(**{\"a\": 1}).",
            mcq("Inside def f(*args), what type is args?", ["tuple", "list", "dict", "set"], 0),
            mcq("Inside def f(**kwargs), what type is kwargs?", ["dict", "tuple", "list", "str"], 0),
            fill("Accept any number of positional arguments.", "def average(___nums):", "*"),
            mcq("What does f(*[1, 2]) do for def f(a, b)?", ["Calls f(1, 2)", "Calls f([1, 2])", "An error", "Calls f(1)"], 0),
            run("Write describe(name, *skills, **extra) that prints the name, then 'skills: ' and the skills joined by ', ', then each extra item as key=value (in the order given).", "python",
                [t("full", append='describe("Ada", "Python", "Maths", city="London", born=1815)'), t("minimal", append='describe("Bo")')],
                ["Ada\nskills: Python, Maths\ncity=London\nborn=1815", "Bo\nskills: "],
                'def describe(name, *skills, **extra):\n    print(name)\n    print("skills: " + ", ".join(skills))\n    for key, value in extra.items():\n        print(f"{key}={value}")',
                require=[r"\*\s*skills", r"\*\*\s*extra"]),
        ),
        lesson(
            "Scope & closures",
            "A function can use variables from the scope it was CREATED in - even after that scope has finished. That's a closure:\n\ndef make_multiplier(n):\n    def multiply(x):\n        return x * n      # remembers n\n    return multiply\n\ntriple = make_multiplier(3)\ntriple(5)   # 15\n\nTo change an outer variable from an inner function, declare it nonlocal.",
            mcq("What is double(4)?", ["8", "2", "4", "An error"], 0, code="def make(n):\n    return lambda x: x * n\n\ndouble = make(2)"),
            fill("Allow the inner function to change count.", "def counter():\n    count = 0\n    def step():\n        ___ count\n        count += 1\n        return count\n    return step", "nonlocal"),
            mcq("What does Python look up first: local or global names?", ["Local, then enclosing, then global, then built-ins", "Global first", "Built-ins first", "Random"], 0,
                "This is the LEGB rule."),
            mcq("What is printed?", ["5", "10", "An error", "None"], 0, "Assigning x inside f creates a NEW local x; the global is unchanged.",
                code="x = 5\ndef f():\n    x = 10\nf()\nprint(x)"),
            run("Write make_counter() that returns a function; each call of that function returns the next number starting at 1. Separate counters must be independent.", "python",
                [t("one counter", append="c = make_counter()\nprint(c(), c(), c())"), t("independent", append="a = make_counter()\nb = make_counter()\na(); a()\nprint(a(), b())")],
                ["1 2 3", "3 1"], "def make_counter():\n    count = 0\n    def step():\n        nonlocal count\n        count += 1\n        return count\n    return step",
                require=[r"def\s+make_counter"], forbid=[r"\bglobal\b"]),
        ),
        lesson(
            "Recursion",
            "A recursive function calls itself on a smaller problem, with a BASE CASE that stops:\n\ndef factorial(n):\n    if n <= 1:          # base case\n        return 1\n    return n * factorial(n - 1)\n\nRecursion shines on naturally nested data - folders, trees, nested lists.",
            mcq("What stops recursion running forever?", ["A base case", "A loop", "break", "return None"], 0),
            mcq("What is total(4)?", ["10", "4", "24", "Infinite"], 0, code="def total(n):\n    if n == 0:\n        return 0\n    return n + total(n - 1)"),
            fill("The recursive step for factorial.", "return n * factorial(n ___ 1)", "-"),
            mcq("Which error happens with no base case?", ["RecursionError", "ValueError", "StopIteration", "KeyError"], 0),
            run("Write flatten(items) that turns a nested list like [1, [2, [3, 4]], 5] into a flat list, recursively.", "python",
                [t("nested", append="print(flatten([1, [2, [3, 4]], 5]))"), t("deep", append="print(flatten([[[['x']]]]))"), t("empty", append="print(flatten([]))")],
                ["[1, 2, 3, 4, 5]", "['x']", "[]"],
                "def flatten(items):\n    out = []\n    for item in items:\n        if isinstance(item, list):\n            out.extend(flatten(item))\n        else:\n            out.append(item)\n    return out",
                require=[r"flatten\([^)]*\)[\s\S]*flatten\("]),
        ),
    ),
    # ------------------------------------------------------------------ 11
    unit(
        "Unit 11 · Modules & files",
        lesson(
            "Modules & the standard library",
            "import loads code from a module. Python ships with a huge standard library:\n\nimport math\nmath.sqrt(16)       # 4.0\nfrom math import pi, floor\nfrom collections import Counter\nCounter(\"banana\")   # Counter({'a': 3, 'n': 2, 'b': 1})\nimport datetime as dt   # 'as' gives a short name\n\nYour own .py files are modules too.",
            mcq("What does from math import sqrt do?", ["Lets you call sqrt() directly", "Imports all of math", "Defines sqrt", "Nothing"], 0),
            mcq("What is Counter('aab').most_common(1)?", ["[('a', 2)]", "('a', 2)", "{'a': 2}", "['a']"], 0),
            fill("Import datetime under the short name dt.", "import datetime ___ dt", "as"),
            mcq("Why prefer the standard library over writing your own?", ["It's tested, fast and well-known", "It's required", "It's shorter to type only", "It has no bugs ever"], 0),
            run("Read a sentence and print the 3 most common letters (ignore spaces, lower-case everything) as letter:count, using collections.Counter. Ties keep first-seen order.", "python",
                [t("hello world", stdin="Hello World"), t("banana", stdin="banana bread")], ["l:3\no:2\nh:1", "a:4\nb:2\nn:2"],
                'from collections import Counter\n\ntext = input().lower().replace(" ", "")\nfor letter, count in Counter(text).most_common(3):\n    print(f"{letter}:{count}")',
                require=[r"Counter"]),
        ),
        lesson(
            "Reading & writing files",
            "open() works with files. Always use with - it closes the file for you:\n\nwith open(\"notes.txt\", \"w\") as f:   # w = write (overwrite)\n    f.write(\"first line\\n\")\n\nwith open(\"notes.txt\") as f:        # default mode r = read\n    for line in f:\n        print(line.strip())\n\nModes: r read · w write · a append. (In Codeingo, files live in a temporary in-browser folder.)",
            mcq("Why use with open(...)?", ["It closes the file automatically, even on errors", "It's faster", "It reads the whole file", "It's required for reading"], 0),
            mcq("Which mode adds to the end of a file?", ["\"a\"", "\"w\"", "\"r\"", "\"+\""], 0),
            fill("Open for writing.", 'with open("out.txt", "___") as f:', "w"),
            mcq("What does line.strip() remove from a line read from a file?", ["Leading/trailing whitespace including the newline", "All spaces", "The first character", "Nothing"], 0),
            run("Write save_and_count(lines) that writes the list of strings to tasks.txt (one per line), then reads the file back and returns how many non-empty lines it has.", "python",
                [t("three", append='print(save_and_count(["code", "", "sleep", "repeat"]))'), t("none", append="print(save_and_count([]))")], ["3", "0"],
                'def save_and_count(lines):\n    with open("tasks.txt", "w") as f:\n        for line in lines:\n            f.write(line + "\\n")\n    count = 0\n    with open("tasks.txt") as f:\n        for line in f:\n            if line.strip():\n                count += 1\n    return count',
                require=[r"open\(", r"\bwith\b"]),
        ),
        lesson(
            "JSON",
            "JSON is the text format the web uses for data. The json module converts both ways:\n\nimport json\ntext = json.dumps({\"name\": \"Ada\", \"langs\": [\"py\"]})   # dict -> str\ndata = json.loads('{\"ok\": true}')                       # str -> dict\ndata[\"ok\"]   # True\n\njson.dumps(obj, indent=2) pretty-prints; json.dump / json.load work with files.",
            mcq("Which function turns a JSON string into Python data?", ["json.loads", "json.dumps", "json.parse", "json.read"], 0),
            mcq("What is json.dumps({'a': True})?", ['\'{"a": true}\'', "\"{'a': True}\"", "'{a: true}'", "An error"], 0, "JSON uses double quotes and lowercase true."),
            fill("Convert the dict to JSON text.", "text = json.___(data)", "dumps"),
            mcq("What Python type does a JSON array become?", ["list", "tuple", "dict", "set"], 0),
            run("Read one line of JSON describing an order like {\"items\": [{\"price\": 2.5, \"qty\": 2}, …]} and print the total cost with 2 decimals.", "python",
                [t("two items", stdin='{"items": [{"price": 2.5, "qty": 2}, {"price": 1.25, "qty": 4}]}'), t("empty", stdin='{"items": []}')], ["10.00", "0.00"],
                'import json\n\norder = json.loads(input())\ntotal = sum(item["price"] * item["qty"] for item in order["items"])\nprint(f"{total:.2f}")',
                require=[r"json\.loads"]),
        ),
    ),
    # ------------------------------------------------------------------ 12
    unit(
        "Unit 12 · Object-oriented Python",
        lesson(
            "Classes & objects",
            "A class bundles data (attributes) and behaviour (methods):\n\nclass Dog:\n    def __init__(self, name):\n        self.name = name          # attribute\n\n    def speak(self):              # method\n        return f\"{self.name} says woof\"\n\nrex = Dog(\"Rex\")\nrex.speak()\n\n__init__ runs when you create an object; self is the object itself.",
            mcq("What is self?", ["The object the method was called on", "The class", "A keyword for global", "The first argument passed by the caller"], 0),
            fill("The method that sets up a new object.", "def ___(self, name):", "__init__"),
            mcq("What is printed?", ["Rex", "name", "self.name", "An error"], 0, code='class Dog:\n    def __init__(self, name):\n        self.name = name\n\nprint(Dog("Rex").name)'),
            order("Order the class.", ["class Cat:", "    def __init__(self, name):", "        self.name = name", "    def meow(self):", '        return self.name + " says meow"']),
            run("Write a class BankAccount with owner and balance (default 0), deposit(amount), and withdraw(amount) which returns False (and changes nothing) if funds are insufficient, else True.", "python",
                [t("normal", append='acc = BankAccount("Ada")\nacc.deposit(100)\nprint(acc.withdraw(30), acc.balance)'),
                 t("overdraw", append='acc = BankAccount("Bo", 20)\nprint(acc.withdraw(50), acc.balance, acc.owner)')],
                ["True 70", "False 20 Bo"],
                "class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            return False\n        self.balance -= amount\n        return True",
                require=[r"class\s+BankAccount", r"__init__"]),
        ),
        lesson(
            "__str__ & __repr__",
            "Special 'dunder' methods customise how objects behave. __str__ is the friendly text for print(); __repr__ is the precise developer view:\n\nclass Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __repr__(self):\n        return f\"Point({self.x}, {self.y})\"\n    def __str__(self):\n        return f\"({self.x}, {self.y})\"\n\nprint(Point(1, 2))   # (1, 2)\n[Point(1, 2)]        # [Point(1, 2)] - lists show repr",
            mcq("Which method does print(obj) use?", ["__str__ (falling back to __repr__)", "__repr__ only", "__print__", "__init__"], 0),
            mcq("How does a list display the objects inside it?", ["Using each item's __repr__", "Using __str__", "As memory addresses always", "It can't"], 0),
            fill("Friendly text for print().", "def ___(self):\n    return self.name", "__str__"),
            mcq("What does 'dunder' mean?", ["Double underscore", "Dynamic underscore", "Default under", "Duplicate"], 0),
            run("Write class Money(amount, currency) whose __str__ gives '12.50 GBP' (2 decimals) and whose __repr__ gives \"Money(12.5, 'GBP')\".", "python",
                [t("print", append='print(Money(12.5, "GBP"))'), t("repr in list", append='print([Money(3, "EUR")])')],
                ["12.50 GBP", "[Money(3, 'EUR')]"],
                'class Money:\n    def __init__(self, amount, currency):\n        self.amount = amount\n        self.currency = currency\n\n    def __str__(self):\n        return f"{self.amount:.2f} {self.currency}"\n\n    def __repr__(self):\n        return f"Money({self.amount!r}, {self.currency!r})"',
                require=[r"__str__", r"__repr__"]),
        ),
        lesson(
            "Inheritance & super()",
            "A subclass inherits from a parent and can extend or override it:\n\nclass Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return \"...\"\n\nclass Cat(Animal):\n    def __init__(self, name, indoor):\n        super().__init__(name)    # run the parent's setup\n        self.indoor = indoor\n    def speak(self):              # override\n        return \"Meow\"\n\nisinstance(c, Animal) is True for a Cat.",
            mcq("What does super().__init__(name) do?", ["Runs the parent class's __init__", "Creates a new parent", "Calls itself", "Deletes the parent"], 0),
            mcq("Is a Cat instance also an instance of Animal?", ["Yes", "No", "Only after super()", "Only if Animal is empty"], 0),
            fill("Cat inherits from Animal.", "class Cat(___):", "Animal"),
            mcq("What is overriding?", ["Redefining a parent's method in the child", "Calling super()", "Deleting a method", "Adding attributes"], 0),
            run("Write Shape with area() returning 0 and describe() returning f\"{type(self).__name__} with area {area:.1f}\". Subclasses Rectangle(w, h) and Circle(r) (use math.pi) override area() only.", "python",
                [t("rectangle", append="print(Rectangle(3, 4).describe())"), t("circle", append="print(Circle(1).describe())"), t("base", append="print(Shape().describe())")],
                ["Rectangle with area 12.0", "Circle with area 3.1", "Shape with area 0.0"],
                'import math\n\n\nclass Shape:\n    def area(self):\n        return 0\n\n    def describe(self):\n        return f"{type(self).__name__} with area {self.area():.1f}"\n\n\nclass Rectangle(Shape):\n    def __init__(self, w, h):\n        self.w, self.h = w, h\n\n    def area(self):\n        return self.w * self.h\n\n\nclass Circle(Shape):\n    def __init__(self, r):\n        self.r = r\n\n    def area(self):\n        return math.pi * self.r ** 2',
                require=[r"class\s+Rectangle\s*\(\s*Shape\s*\)", r"class\s+Circle\s*\(\s*Shape\s*\)"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 13
    unit(
        "Unit 13 · Pythonic objects",
        lesson(
            "Operator overloading",
            "Dunder methods let your objects work with Python's operators and built-ins:\n\n__eq__ ==    __lt__ <    __add__ +    __len__ len()\n__contains__ in    __getitem__ obj[i]    __iter__ for loops\n\nclass Vector:\n    def __init__(self, x, y): self.x, self.y = x, y\n    def __add__(self, other): return Vector(self.x + other.x, self.y + other.y)\n    def __eq__(self, other): return (self.x, self.y) == (other.x, other.y)",
            mcq("Which method makes a + b work?", ["__add__", "__plus__", "__sum__", "__concat__"], 0),
            mcq("Which method does len(obj) call?", ["__len__", "__size__", "__count__", "__length__"], 0),
            fill("Make objects sortable with <.", "def ___(self, other):\n    return self.score < other.score", "__lt__"),
            mcq("Without __eq__, what does a == b compare for two objects?", ["Identity (whether they're the same object)", "All attributes", "Their __str__", "Always True"], 0),
            run("Write class Vector(x, y) supporting + (vector add), * by a number (scale), == and a repr like Vector(3, 4); also abs(v) giving the length.", "python",
                [t("add & repr", append="print(Vector(1, 2) + Vector(2, 2))"), t("scale", append="print(Vector(1, -2) * 3)"),
                 t("eq & abs", append="print(Vector(3, 4) == Vector(3, 4), abs(Vector(3, 4)))")],
                ["Vector(3, 4)", "Vector(3, -6)", "True 5.0"],
                'import math\n\n\nclass Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n\n    def __mul__(self, k):\n        return Vector(self.x * k, self.y * k)\n\n    def __eq__(self, other):\n        return (self.x, self.y) == (other.x, other.y)\n\n    def __abs__(self):\n        return math.hypot(self.x, self.y)\n\n    def __repr__(self):\n        return f"Vector({self.x}, {self.y})"',
                require=[r"__add__", r"__mul__", r"__eq__", r"__abs__"]),
        ),
        lesson(
            "Properties, classmethods & staticmethods",
            "@property makes a method behave like an attribute - great for computed or validated values:\n\nclass Temp:\n    def __init__(self, c): self.celsius = c\n    @property\n    def fahrenheit(self): return self.celsius * 9 / 5 + 32\n\n@classmethod gets the class (cls) - perfect for alternative constructors:\n    @classmethod\n    def from_f(cls, f): return cls((f - 32) * 5 / 9)\n\n@staticmethod is a plain function that lives in the class.",
            mcq("How do you read a @property named area?", ["obj.area", "obj.area()", "obj.get_area()", "area(obj)"], 0),
            mcq("What does a @classmethod receive first?", ["The class (cls)", "The instance (self)", "Nothing", "The module"], 0),
            fill("Add a validating setter for the property.", "@celsius.___\ndef celsius(self, value): ...", "setter"),
            mcq("When is @staticmethod appropriate?", ["A helper that needs neither self nor cls", "Constructors", "Every method", "Properties"], 0),
            run("Write class Temperature with a celsius property whose setter raises ValueError(\"below absolute zero\") under -273.15, a read-only fahrenheit property, and a classmethod from_fahrenheit(f).", "python",
                [t("convert", append="t = Temperature(100)\nprint(t.fahrenheit)"), t("classmethod", append="print(round(Temperature.from_fahrenheit(212).celsius, 1))"),
                 t("validation", append='try:\n    Temperature(-300)\nexcept ValueError as e:\n    print("Error:", e)')],
                ["212.0", "100.0", "Error: below absolute zero"],
                'class Temperature:\n    def __init__(self, celsius):\n        self.celsius = celsius\n\n    @property\n    def celsius(self):\n        return self._celsius\n\n    @celsius.setter\n    def celsius(self, value):\n        if value < -273.15:\n            raise ValueError("below absolute zero")\n        self._celsius = value\n\n    @property\n    def fahrenheit(self):\n        return self._celsius * 9 / 5 + 32\n\n    @classmethod\n    def from_fahrenheit(cls, f):\n        return cls((f - 32) * 5 / 9)',
                require=[r"@property", r"\.setter", r"@classmethod"]),
        ),
        lesson(
            "Dataclasses",
            "@dataclass writes __init__, __repr__ and __eq__ for you:\n\nfrom dataclasses import dataclass, field\n\n@dataclass\nclass Book:\n    title: str\n    pages: int\n    tags: list = field(default_factory=list)\n\nBook(\"Dune\", 412)   # Book(title='Dune', pages=412, tags=[])\n\n@dataclass(frozen=True) makes instances immutable (and hashable); order=True adds <, > comparisons.",
            mcq("Which methods does @dataclass generate by default?", ["__init__, __repr__ and __eq__", "Only __init__", "__str__ only", "None"], 0),
            mcq("Why use field(default_factory=list) instead of = []?", ["Each object gets its own new list", "It's faster", "Lists aren't allowed", "It's the same"], 0),
            fill("Make instances immutable.", "@dataclass(___=True)", "frozen"),
            mcq("What does order=True add?", ["Comparison operators like < based on the fields in order", "Sorting of fields", "A sort() method", "Nothing"], 0),
            run("Use @dataclass(order=True) to define Card(rank: int, suit: str). Write best(cards) returning the highest card (max). Print the repr.", "python",
                [t("max", append='print(best([Card(10, "hearts"), Card(12, "clubs"), Card(3, "spades")]))'),
                 t("tie on rank", append='print(best([Card(5, "a"), Card(5, "z")]))'), t("eq", append='print(Card(1, "x") == Card(1, "x"))')],
                ["Card(rank=12, suit='clubs')", "Card(rank=5, suit='z')", "True"],
                "from dataclasses import dataclass\n\n\n@dataclass(order=True)\nclass Card:\n    rank: int\n    suit: str\n\n\ndef best(cards):\n    return max(cards)",
                require=[r"@dataclass"]),
        ),
    ),
    # ------------------------------------------------------------------ 14
    unit(
        "Unit 14 · Iterators & generators",
        lesson(
            "The iterator protocol",
            "for loops call iter(obj) once, then next() until StopIteration:\n\nit = iter([1, 2])\nnext(it)   # 1\nnext(it)   # 2\nnext(it)   # StopIteration\n\nMake your own iterable class with __iter__ (return an iterator) and __next__ (return the next value or raise StopIteration).",
            mcq("What does next() raise when an iterator is exhausted?", ["StopIteration", "IndexError", "None", "EOFError"], 0),
            mcq("What is printed?", ["1 2", "1", "An error", "[1, 2]"], 0, code="it = iter([1, 2])\nprint(next(it), next(it))"),
            fill("The method a for loop calls first.", "def ___(self):\n    return self", "__iter__"),
            mcq("Can you loop over the same iterator twice?", ["No - it's used up after one pass", "Yes always", "Only lists", "Only with reset()"], 0),
            run("Write class Countdown(start) that can be used in a for loop, yielding start, start-1, … 1 by implementing __iter__ and __next__ (no generators).", "python",
                [t("3", append="print(list(Countdown(3)))"), t("0", append="print(list(Countdown(0)))"), t("for loop", append="for n in Countdown(2):\n    print(n)")],
                ["[3, 2, 1]", "[]", "2\n1"],
                "class Countdown:\n    def __init__(self, start):\n        self.current = start\n\n    def __iter__(self):\n        return self\n\n    def __next__(self):\n        if self.current <= 0:\n            raise StopIteration\n        value = self.current\n        self.current -= 1\n        return value",
                require=[r"__next__", r"StopIteration"], forbid=[r"\byield\b"]),
        ),
        lesson(
            "Generators",
            "A function with yield is a generator - it produces values lazily, one at a time:\n\ndef squares(n):\n    for i in range(n):\n        yield i * i\n\nfor s in squares(3): print(s)    # 0 1 4\n\nGenerator expressions: sum(x * x for x in range(10**6)) uses almost no memory.\nGenerators can be infinite: def naturals(): n = 0; while True: yield n; n += 1",
            mcq("What does calling a generator function return?", ["A generator object (no code has run yet)", "A list", "The first value", "None"], 0),
            mcq("What is list(g())?", ["[1, 2]", "[1]", "An error", "None"], 0, code="def g():\n    yield 1\n    yield 2"),
            fill("Produce a value and pause.", "def evens():\n    for n in range(0, 10, 2):\n        ___ n", "yield"),
            mcq("Why use a generator expression in sum(x*x for x in data)?", ["It doesn't build a whole list in memory", "It's required", "It sorts", "It's slower"], 0),
            run("Write a generator fibonacci() that yields the Fibonacci numbers forever (0, 1, 1, 2, …). Use itertools.islice in the tests to take some.", "python",
                [t("first 10", append="from itertools import islice\nprint(list(islice(fibonacci(), 10)))"),
                 t("first big one", append="print(next(n for n in fibonacci() if n > 1000))")],
                ["[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]", "1597"],
                "def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b",
                require=[r"\byield\b"]),
        ),
        lesson(
            "itertools",
            "itertools has fast building blocks for iteration:\n\nfrom itertools import count, chain, groupby, combinations, permutations, product, accumulate\nlist(chain([1], [2, 3]))          # [1, 2, 3]\nlist(combinations(\"abc\", 2))      # [('a','b'), ('a','c'), ('b','c')]\nlist(accumulate([1, 2, 3]))       # [1, 3, 6] running totals\nfor key, grp in groupby(sorted(words, key=len), key=len): ...",
            mcq("How many pairs does combinations('abcd', 2) produce?", ["6", "12", "4", "16"], 0),
            mcq("What does accumulate([2, 2, 2]) produce?", ["2, 4, 6", "6", "2, 2, 2", "8"], 0),
            fill("Glue several iterables together.", "for x in itertools.___(a, b, c):", "chain"),
            mcq("What must you usually do before groupby?", ["Sort by the same key", "Reverse", "Convert to a set", "Nothing"], 0, "groupby only groups CONSECUTIVE equal keys."),
            run("Read a line of words. Group them by length and print each group as 'length: words' (lengths ascending, words in alphabetical order, joined by spaces) using itertools.groupby.", "python",
                [t("mixed", stdin="pear fig apple kiwi date plum"), t("single", stdin="a")], ["3: fig\n4: date kiwi pear plum\n5: apple", "1: a"],
                'from itertools import groupby\n\nwords = sorted(input().split(), key=lambda w: (len(w), w))\nfor length, group in groupby(words, key=len):\n    print(f"{length}: {\' \'.join(group)}")',
                require=[r"groupby"]),
        ),
    ),
    # ------------------------------------------------------------------ 15
    unit(
        "Unit 15 · Functional tools & decorators",
        lesson(
            "map, filter & functools",
            "Functions are values - pass them around:\n\nlist(map(str.upper, [\"a\", \"b\"]))       # ['A', 'B']\nlist(filter(lambda n: n > 0, nums))\nfrom functools import reduce, partial, lru_cache\nreduce(lambda a, b: a * b, [1, 2, 3, 4])  # 24\nsquare = partial(pow, exp=2)\n\n@lru_cache memoises a function: repeated calls with the same arguments are instant.",
            mcq("What is list(map(len, ['a', 'bb']))?", ["[1, 2]", "['a', 'bb']", "3", "An error"], 0),
            mcq("What is reduce(lambda a, b: a + b, [1, 2, 3])?", ["6", "[1, 3, 6]", "123", "An error"], 0),
            fill("Cache the results of a slow function.", "@functools.___\ndef fib(n): ...", ["lru_cache", "cache"]),
            mcq("What does partial(f, 2) create?", ["A new function with the first argument fixed to 2", "A partial result", "A copy of f", "A generator"], 0),
            run("Write fib(n) (fib(0)=0, fib(1)=1) recursively but make it fast with functools.lru_cache, so fib(90) returns instantly.", "python",
                [t("small", append="print([fib(i) for i in range(8)])"), t("big", append="print(fib(90))")], ["[0, 1, 1, 2, 3, 5, 8, 13]", "2880067194370816120"],
                "from functools import lru_cache\n\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)",
                require=[r"lru_cache|@cache\b", r"fib\(\s*n\s*-\s*1\s*\)"]),
        ),
        lesson(
            "Decorators",
            "A decorator wraps a function to add behaviour - logging, timing, caching, access checks:\n\nimport functools\n\ndef shout(func):\n    @functools.wraps(func)          # keep the name/docstring\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs).upper()\n    return wrapper\n\n@shout\ndef greet(name):\n    return f\"hi {name}\"\n\ngreet(\"ada\")   # 'HI ADA'\n\n@shout is just shorthand for greet = shout(greet).",
            mcq("What is @deco above def f() equivalent to?", ["f = deco(f)", "deco = f(deco)", "f(deco)", "Nothing"], 0),
            mcq("Why use functools.wraps in a decorator?", ["The wrapper keeps the original function's name and docstring", "It's required to run", "It speeds it up", "It caches"], 0),
            fill("Forward any arguments to the original function.", "def wrapper(*args, ___kwargs):\n    return func(*args, **kwargs)", "**"),
            mcq("Can decorators take their own arguments, like @retry(times=3)?", ["Yes - with one more level of nested function", "No", "Only in classes", "Only built-in ones"], 0),
            run("Write a decorator count_calls that counts how many times the decorated function is called, exposing the number as func.calls.", "python",
                [t("three calls", append="@count_calls\ndef hello():\n    return 'hi'\n\nhello(); hello(); hello()\nprint(hello.calls)"),
                 t("keeps result & name", append="@count_calls\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3), add.calls, add.__name__)")],
                ["3", "5 1 add"],
                "import functools\n\n\ndef count_calls(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        wrapper.calls += 1\n        return func(*args, **kwargs)\n\n    wrapper.calls = 0\n    return wrapper",
                require=[r"def\s+count_calls", r"def\s+wrapper"]),
        ),
        lesson(
            "Context managers",
            "with guarantees clean-up code runs. Build your own with a class (__enter__/__exit__) or more simply with contextlib:\n\nfrom contextlib import contextmanager\n\n@contextmanager\ndef tag(name):\n    print(f\"<{name}>\")\n    try:\n        yield\n    finally:\n        print(f\"</{name}>\")\n\nwith tag(\"p\"):\n    print(\"hello\")",
            mcq("What runs the code after yield in a @contextmanager?", ["Leaving the with block (even on errors, with try/finally)", "Entering the with block", "Calling next()", "Nothing"], 0),
            mcq("Which method runs when a with block starts?", ["__enter__", "__init__", "__start__", "__open__"], 0),
            fill("Turn a generator into a context manager.", "@contextlib.___\ndef opened(path): ...", "contextmanager"),
            mcq("Why put the clean-up in finally?", ["So it runs even if the block raises", "It's faster", "It's required syntax", "To catch errors"], 0),
            run("Write a context manager indent() (with contextlib) that prints 'begin' on entry and 'end' on exit - even if an exception happens inside, which must still propagate.", "python",
                [t("normal", append='with indent():\n    print("  work")'),
                 t("exception", append='try:\n    with indent():\n        raise ValueError("boom")\nexcept ValueError as e:\n    print("caught", e)')],
                ["begin\n  work\nend", "begin\nend\ncaught boom"],
                'from contextlib import contextmanager\n\n\n@contextmanager\ndef indent():\n    print("begin")\n    try:\n        yield\n    finally:\n        print("end")',
                require=[r"contextmanager|__enter__"], hint="Wrap the yield in try/finally."),
        ),
    ),
    # ------------------------------------------------------------------ 16
    unit(
        "Unit 16 · Professional Python",
        lesson(
            "Type hints",
            "Type hints document what a function expects and returns. Tools like mypy check them before you run:\n\ndef average(nums: list[float]) -> float:\n    return sum(nums) / len(nums)\n\nfrom typing import Optional\ndef find(name: str) -> Optional[int]: ...   # int or None (also written int | None)\n\nPython itself doesn't enforce hints at run time.",
            mcq("Does Python stop you passing the wrong type at run time because of hints?", ["No - hints are for tools and readers", "Yes", "Only for ints", "Only with -O"], 0),
            fill("Annotate the return type.", "def area(w: float, h: float) ___ float:", "->"),
            mcq("What does Optional[str] mean?", ["A str or None", "An optional argument", "Any type", "A list of str"], 0),
            mcq("Which tool checks type hints statically?", ["mypy", "pip", "venv", "black"], 0),
            run("Write a fully type-hinted function word_lengths(words: list[str]) -> dict[str, int] mapping each word to its length; also print word_lengths.__annotations__['return'] in the test.", "python",
                [t("result", append='print(word_lengths(["hi", "code"]))'), t("annotation", append="print(word_lengths.__annotations__['return'])")],
                ["{'hi': 2, 'code': 4}", "dict[str, int]"],
                "def word_lengths(words: list[str]) -> dict[str, int]:\n    return {w: len(w) for w in words}",
                require=[r"words\s*:\s*list\[\s*str\s*\]", r"->\s*dict\[\s*str\s*,\s*int\s*\]"]),
        ),
        lesson(
            "Custom exceptions",
            "Define your own exception types to make errors meaningful:\n\nclass InsufficientFunds(Exception):\n    def __init__(self, needed):\n        super().__init__(f\"need {needed} more\")\n        self.needed = needed\n\nraise InsufficientFunds(30)\n\nraise NewError(...) from err keeps the original cause. Catch specific exceptions, never bare except:.",
            mcq("What should a custom exception inherit from?", ["Exception (or a subclass)", "BaseException always", "object", "Error"], 0),
            mcq("Why avoid a bare except:?", ["It also catches things like KeyboardInterrupt and hides bugs", "It's slower", "It's a syntax error", "It never catches anything"], 0),
            fill("Chain the original error as the cause.", "raise ConfigError(\"bad config\") ___ err", "from"),
            mcq("Where does the finally block run?", ["Always, after try/except", "Only on success", "Only on error", "Never"], 0),
            run("Write class ValidationError(Exception) and validate_age(age) which raises ValidationError('age must be an integer') for non-ints and ValidationError('age out of range') outside 0..150, else returns age.", "python",
                [t("ok", append="print(validate_age(30))"),
                 t("type", append="try:\n    validate_age('30')\nexcept ValidationError as e:\n    print(type(e).__name__, e)"),
                 t("range", append="try:\n    validate_age(200)\nexcept ValidationError as e:\n    print(e)"),
                 t("is an Exception", append="print(issubclass(ValidationError, Exception))")],
                ["30", "ValidationError age must be an integer", "age out of range", "True"],
                'class ValidationError(Exception):\n    pass\n\n\ndef validate_age(age):\n    if not isinstance(age, int):\n        raise ValidationError("age must be an integer")\n    if not 0 <= age <= 150:\n        raise ValidationError("age out of range")\n    return age',
                require=[r"class\s+ValidationError\s*\(\s*Exception\s*\)", r"\braise\b"]),
        ),
        lesson(
            "Algorithms & Big-O",
            "Big-O describes how running time grows with input size n:\n\nO(1)       dict lookup, list[i]\nO(log n)   binary search\nO(n)       one loop over the data\nO(n log n) good sorting (sorted())\nO(n²)      a loop inside a loop\n\nBinary search on a SORTED list halves the range every step:\n\nlo, hi = 0, len(a) - 1\nwhile lo <= hi:\n    mid = (lo + hi) // 2 ...",
            mcq("What is the time complexity of x in a_set?", ["O(1) on average", "O(n)", "O(log n)", "O(n²)"], 0),
            mcq("What is the complexity of checking every pair in a list?", ["O(n²)", "O(n)", "O(log n)", "O(1)"], 0),
            fill("Binary search requires the list to be…", "Binary search only works on ___ data.", "sorted"),
            mcq("Roughly how many steps does binary search need for 1,000,000 items?", ["About 20", "About 1,000", "About 500,000", "About 1,000,000"], 0, "log2(1,000,000) ≈ 20."),
            run("Write binary_search(items, target) returning the index of target in the sorted list, or -1. Don't use index(), in, or bisect - write the loop.", "python",
                [t("found", append="print(binary_search([1, 3, 5, 7, 9, 11], 7))"), t("missing", append="print(binary_search([1, 3, 5], 4))"),
                 t("edges", append="print(binary_search([2, 4], 2), binary_search([2, 4], 4), binary_search([], 1))")],
                ["3", "-1", "0 1 -1"],
                "def binary_search(items, target):\n    lo, hi = 0, len(items) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if items[mid] == target:\n            return mid\n        if items[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1",
                require=[r"\bwhile\b|binary_search\([^)]*\)[\s\S]*binary_search\("], forbid=[r"\.index\(", r"\bbisect\b", r"\bin\s+items\b"]),
        ),
    ),
)
