from .dsl import code, course, fill, lesson, mcq, order, run, t, unit
from .python_adv import ADVANCED, INTERMEDIATE
from .python_expert import EXPERT
from .python_expert2 import EXPERT2

Q = r"""(['"])"""  # an opening quote; close it with \1

COURSE = course(
    "python", "Python", "🐍", "The friendliest first language - readable, powerful and everywhere.",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · First steps",
        lesson(
            "Hello, Python",
            "Python runs your program line by line, top to bottom.\n\nprint() shows a value on the screen:\n\nprint(\"Hello!\")   # Hello!\nprint(42)         # 42\n\nText (a string) goes inside quotes. Numbers don't.",
            mcq("What does this code show?", ["Hi", "\"Hi\"", "print Hi", "An error"], 0,
                "print() shows the text itself - the quotes only mark where the text starts and ends.", "Quotes aren't printed.", code='print("Hi")'),
            fill("Complete the code so it shows a greeting.", '___("Hello, World!")', "print",
                 "print is the built-in function that displays output.", "Which function displays output?"),
            mcq("Which line is correct Python?", ['print("Hi")', 'Print("Hi")', 'print "Hi"', 'print(Hi")'], 0,
                "Python is case-sensitive (print, not Print), needs parentheses, and strings need matching quotes."),
            order("Put the lines in order so the program greets, then says goodbye.", ['print("Hello!")', 'print("How are you?")', 'print("Goodbye!")'],
                  "Python runs lines from top to bottom."),
            run("Write a program that prints exactly: Hello, World!", "python", [t("Run")], ["Hello, World!"],
                'print("Hello, World!")', explanation="Text goes inside quotes, and the quotes go inside print( ).",
                hint="print(\"...\") with the exact text."),
        ),
        lesson(
            "Comments & strings",
            "A comment starts with # - Python ignores it. Use comments to explain your code.\n\n# this line is ignored\nprint('Hi')  # so is this part\n\nStrings can use 'single' or \"double\" quotes. Joining strings with + is called concatenation:\n\nprint(\"Code\" + \"ingo\")   # Codeingo",
            mcq("Which symbol starts a comment in Python?", ["#", "//", "/*", "--"], 0, "Everything after # on a line is ignored.", "It's also called a hash."),
            mcq("What is printed?", ["Codeingo", "Code ingo", "Code+ingo", "An error"], 0, "+ joins two strings with nothing in between.",
                code='print("Code" + "ingo")'),
            fill("Join the two strings with a space in between.", 'print("Good" + ___ + "morning")', ['" "', "' '"],
                 "A string containing just a space is \" \".", "It's a string with one space in it."),
            mcq("How many lines does this program print?", ["1", "2", "3", "0"], 1, "The comment line is skipped, so only two print() calls run.",
                code='# greeting\nprint("Hi")\n# print("Hidden")\nprint("Bye")'),
            run("Print the word Python three times, each on its own line.", "python", [t("Run")], ["Python\nPython\nPython"],
                'print("Python")\nprint("Python")\nprint("Python")', hint="Three print() calls."),
        ),
        lesson(
            "Numbers & math",
            "Python is a great calculator:\n\nprint(7 + 3)    # 10\nprint(7 - 3)    # 4\nprint(7 * 3)    # 21\nprint(7 / 2)    # 3.5   (always a decimal)\nprint(7 // 2)   # 3     (whole-number division)\nprint(7 % 2)    # 1     (remainder)\nprint(2 ** 3)   # 8     (power)\n\nNormal maths order applies: * and / before + and -.",
            mcq("What is printed?", ["3.5", "3", "4", "1"], 0, "/ always gives a decimal (float) result.", code="print(7 / 2)"),
            mcq("What is printed?", ["1", "3", "3.5", "0"], 0, "% gives the remainder: 7 = 3×2 + 1.", code="print(7 % 2)"),
            mcq("What is printed?", ["14", "20", "10", "24"], 0, "* happens before +, so it's 2 + (3 × 4).", code="print(2 + 3 * 4)"),
            fill("Raise 2 to the power of 10.", "print(2 ___ 10)", "**", "** is the power operator.", "Two stars."),
            run("A pizza has 8 slices. Print how many slices each of 3 friends gets (whole slices), then how many are left over - each on its own line.",
                "python", [t("Run")], ["2\n2"], "print(8 // 3)\nprint(8 % 3)", require=[r"//", r"%"],
                hint="// gives whole slices, % gives the leftovers.", explanation="8 // 3 is 2 and 8 % 3 is 2."),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Variables & input",
        lesson(
            "Variables",
            "A variable is a name that stores a value. = puts the value on the right into the name on the left:\n\nscore = 10\nscore = score + 5\nprint(score)   # 15\n\nNames can use letters, digits and _, but can't start with a digit. Python style is snake_case: high_score.",
            mcq("What is printed?", ["7", "5", "x + 2", "52"], 0, "x starts at 5, then becomes 5 + 2.", code="x = 5\nx = x + 2\nprint(x)"),
            fill("Store the text \"Ada\" in a variable called name.", 'name ___ "Ada"', "=", "A single = assigns a value."),
            mcq("Which is a valid variable name?", ["2cool", "my_score", "my-score", "class"], 1,
                "Names can't start with a digit, can't contain -, and can't be keywords like class."),
            order("Put the lines in order so the program prints 21.", ["age = 20", "age = age + 1", "print(age)"],
                  "A variable must exist before it's changed or printed."),
            run("Create a variable apples = 12. Then eat 5 (subtract from the variable) and print how many apples are left.",
                "python", [t("Run")], ["7"], "apples = 12\napples = apples - 5\nprint(apples)", require=[r"apples\s*=\s*12", r"print\(\s*apples\s*\)"],
                hint="apples = apples - 5", explanation="Update the variable, then print it."),
        ),
        lesson(
            "Types & conversion",
            "Every value has a type:\n\n  int    whole numbers     42\n  float  decimals          3.14\n  str    text              \"hi\"\n  bool   True / False\n\ntype(x) tells you the type. Convert with int(), float(), str():\n\nage = \"20\"          # a string!\nprint(int(age) + 1) # 21\nprint(\"Age: \" + str(21))",
            mcq("What type is 3.0?", ["float", "int", "str", "bool"], 0, "Any number with a decimal point is a float."),
            mcq("What is printed?", ["55", "10", "An error", "5 5"], 0, "Both are strings, so + joins them.", code='print("5" + "5")'),
            mcq("What happens?", ["TypeError", "Prints Age: 21", "Prints Age:21", "Prints 21"], 0,
                "You can't + a str and an int - convert with str(21) first.", code='print("Age: " + 21)'),
            fill("Convert the string to a number so the sum works.", 'print(___("7") + 3)', "int", "int() turns \"7\" into 7."),
            run("The variable text holds \"41\". Convert it to a number, add 1, and print the result.", "python", [t("Run")], ["42"],
                'text = "41"\nnumber = int(text)\nprint(number + 1)', starter='text = "41"\n', require=[r"int\(", r'text\s*=\s*' + Q + r"41\1"],
                hint="int(text) + 1"),
        ),
        lesson(
            "Asking for input",
            "input() waits for the user to type something and returns it as a string:\n\nname = input()\nprint(\"Hello, \" + name)\n\nBecause input() always gives a string, convert it for maths:\n\nage = int(input())\nprint(age + 1)",
            mcq("What type does input() return?", ["str", "int", "float", "It depends"], 0, "input() always returns text."),
            fill("Read a whole number from the user.", "n = int(___())", "input"),
            order("Order the program: read a name, then greet it.", ["name = input()", 'greeting = "Hi, " + name', "print(greeting)"]),
            mcq("The user types 4. What is printed?", ["44", "8", "An error", "4 4"], 0, "input() returns the string \"4\", and \"4\" + \"4\" is \"44\".",
                code="x = input()\nprint(x + x)"),
            run("Read a number from input and print its double.", "python", [t("input 4", stdin="4"), t("input 21", stdin="21"), t("input -3", stdin="-3")],
                ["8", "42", "-6"], "n = int(input())\nprint(n * 2)", require=[r"input\("],
                hint="Convert the input with int() before multiplying."),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Working with text",
        lesson(
            "f-strings",
            "An f-string puts values straight into text. Put f before the quotes and variables in { }:\n\nname = \"Ada\"\nage = 36\nprint(f\"{name} is {age} years old\")\n\nYou can put expressions inside too: f\"{age + 1}\". Format decimals with :.2f → f\"{3.14159:.2f}\" gives 3.14.",
            mcq("What is printed?", ["Hi Ada", "Hi {name}", "f\"Hi Ada\"", "An error"], 0, "The f prefix makes {name} be replaced.",
                code='name = "Ada"\nprint(f"Hi {name}")'),
            mcq("What is printed?", ["Hi {name}", "Hi Ada", "An error", "Hi name"], 0, "Without the f, braces are just characters.",
                code='name = "Ada"\nprint("Hi {name}")'),
            fill("Show price with exactly 2 decimals.", 'print(f"{price___}")', ":.2f", ":.2f formats a float with 2 decimal places."),
            code("Write an f-string print that shows: Score: followed by the variable score.", [r"print\(\s*f" + Q + r"Score: \{\s*score\s*\}\1\s*\)"],
                 'print(f"Score: {score}")', hint='f"Score: {score}"'),
            run("Read a name and an age (two lines of input) and print: <name> will be <age+1> next year.", "python",
                [t("Ada 36", stdin="Ada\n36"), t("Bo 9", stdin="Bo\n9")], ["Ada will be 37 next year.", "Bo will be 10 next year."],
                'name = input()\nage = int(input())\nprint(f"{name} will be {age + 1} next year.")', require=[r"input\("],
                hint="Remember the full stop at the end."),
        ),
        lesson(
            "Indexing & slicing",
            "Each character in a string has an index, starting at 0:\n\nword = \"Python\"\nword[0]    # 'P'\nword[-1]   # 'n'  (negative counts from the end)\nword[0:3]  # 'Pyt' (from 0 up to, not including, 3)\nword[2:]   # 'thon'\nlen(word)  # 6",
            mcq("What is word[1]?", ["o", "c", "d", "e"], 0, "Indexes start at 0, so [1] is the second character.", code='word = "code"'),
            mcq("What is word[-1]?", ["e", "c", "d", "An error"], 0, "-1 is the last character.", code='word = "code"'),
            mcq("What is word[1:3]?", ["od", "ode", "cod", "co"], 0, "From index 1 up to (not including) 3.", code='word = "code"'),
            fill("Get the length of the string s.", "n = ___(s)", "len"),
            run("Read a word and print its first letter, its last letter, and its length - each on its own line.", "python",
                [t("python", stdin="python"), t("a", stdin="a"), t("hello", stdin="hello")], ["p\nn\n6", "a\na\n1", "h\no\n5"],
                "word = input()\nprint(word[0])\nprint(word[-1])\nprint(len(word))", require=[r"\[\s*0\s*\]", r"\[\s*-1\s*\]", r"len\("]),
        ),
        lesson(
            "String methods",
            "Strings have built-in methods:\n\ns = \"  Hello World  \"\ns.strip()           # 'Hello World'\ns.upper()           # '  HELLO WORLD  '\ns.lower()\ns.replace(\"World\", \"Py\")\n\"a,b,c\".split(\",\")  # ['a', 'b', 'c']\n\"-\".join([\"a\", \"b\"])  # 'a-b'\n\"Hello\".count(\"l\")    # 2\n\nMethods return a NEW string - the original doesn't change.",
            mcq("What is printed?", ["HI", "hi", "Hi", "An error"], 0, ".upper() returns an upper-case copy.", code='print("hi".upper())'),
            mcq("What is printed?", ["['a', 'b', 'c']", "abc", "a b c", "('a', 'b', 'c')"], 0, "split() returns a list.", code='print("a-b-c".split("-"))'),
            fill("Remove the spaces around the text.", 'clean = "  hi  ".___()', "strip"),
            mcq("What is printed?", ["cat", "CAT", "An error", "Cat"], 0, "upper() returns a new string; s itself is unchanged.",
                code='s = "cat"\ns.upper()\nprint(s)'),
            run("Read a sentence and print it in capitals with every space replaced by a dash.", "python",
                [t("hello world", stdin="hello world"), t("learn to code", stdin="learn to code")], ["HELLO-WORLD", "LEARN-TO-CODE"],
                'text = input()\nprint(text.upper().replace(" ", "-"))', require=[r"\.upper\(\)", r"\.replace\("]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Making decisions",
        lesson(
            "Booleans & comparisons",
            "A comparison gives a boolean - True or False:\n\n5 > 3    # True\n5 == 5   # True  (== compares, = assigns!)\n5 != 3   # True  (not equal)\n4 <= 3   # False\n\"a\" == \"A\"  # False (case matters)",
            mcq("What is printed?", ["True", "False", "10", "An error"], 0, "10 is greater than 5.", code="print(10 > 5)"),
            mcq("Which operator checks if two values are equal?", ["==", "=", "===", "!="], 0, "= assigns, == compares."),
            mcq("What is printed?", ["False", "True", "0", "None"], 0, "!= means 'not equal', and 3 equals 3.", code="print(3 != 3)"),
            fill("Check that age is at least 18.", "print(age ___ 18)", ">="),
            run("Read two numbers (one per line) and print True if the first is bigger than the second, otherwise False.", "python",
                [t("9 4", stdin="9\n4"), t("2 7", stdin="2\n7"), t("5 5", stdin="5\n5")], ["True", "False", "False"],
                "a = int(input())\nb = int(input())\nprint(a > b)", require=[r">"], forbid=[r"\bif\b"],
                hint="print(a > b) prints the boolean directly - no if needed."),
        ),
        lesson(
            "if, elif & else",
            "if runs code only when a condition is True. Indentation (4 spaces) shows which lines belong to it:\n\ntemp = 30\nif temp > 25:\n    print(\"Hot\")\nelif temp > 15:\n    print(\"Nice\")\nelse:\n    print(\"Cold\")\n\nPython checks from the top and runs the FIRST branch that's True.",
            mcq("What is printed?", ["Nice", "Hot", "Cold", "Hot and Nice"], 0, "20 > 25 is False, 20 > 15 is True.",
                code='temp = 20\nif temp > 25:\n    print("Hot")\nelif temp > 15:\n    print("Nice")\nelse:\n    print("Cold")'),
            fill("Finish the line so the block runs when x is negative.", "if x < 0___", ":", "Every if/elif/else line ends with a colon."),
            order("Order the program so it prints Pass for a score of 70.", ["score = 70", "if score >= 50:", '    print("Pass")', "else:", '    print("Fail")']),
            mcq("How many branches of an if/elif/else chain can run?", ["Exactly one (at most)", "All the True ones", "Two", "None"], 0,
                "Python stops at the first True branch."),
            run("Read a whole number and print Positive, Negative or Zero.", "python",
                [t("5", stdin="5"), t("-2", stdin="-2"), t("0", stdin="0")], ["Positive", "Negative", "Zero"],
                'n = int(input())\nif n > 0:\n    print("Positive")\nelif n < 0:\n    print("Negative")\nelse:\n    print("Zero")',
                require=[r"\bif\b", r"\belif\b|\belse\b"], hint="Use if / elif / else."),
        ),
        lesson(
            "and, or, not",
            "Combine conditions with and, or, not:\n\nage = 20\nhas_ticket = True\nif age >= 18 and has_ticket:\n    print(\"Enter\")\n\nand  - both must be True\nor   - at least one True\nnot  - flips True/False",
            mcq("What is printed?", ["False", "True", "None", "An error"], 0, "and needs both sides True.", code="print(True and False)"),
            mcq("What is printed?", ["True", "False", "An error", "1"], 0, "or needs at least one True side.", code="print(False or True)"),
            mcq("What is printed?", ["False", "True", "not True", "An error"], 0, "not flips True to False.", code="print(not True)"),
            fill("Check that n is between 1 and 10 (inclusive).", "if n >= 1 ___ n <= 10:", "and"),
            run("Read a year and print Leap if it is a leap year, otherwise Common. (Leap: divisible by 4 and not by 100, or divisible by 400.)",
                "python", [t("2024", stdin="2024"), t("1900", stdin="1900"), t("2000", stdin="2000"), t("2023", stdin="2023")],
                ["Leap", "Common", "Leap", "Common"],
                'y = int(input())\nif (y % 4 == 0 and y % 100 != 0) or y % 400 == 0:\n    print("Leap")\nelse:\n    print("Common")',
                require=[r"\band\b|\bor\b"], hint="Use % to test divisibility, and combine with and / or."),
        ),
    ),
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Loops",
        lesson(
            "while loops",
            "A while loop repeats as long as its condition is True:\n\ncount = 1\nwhile count <= 3:\n    print(count)\n    count = count + 1\n\nPrints 1, 2, 3. Always change something inside the loop, or it runs forever! (count += 1 is short for count = count + 1.)",
            mcq("How many times does this print Hi?", ["3", "2", "4", "Forever"], 0, "i takes the values 0, 1, 2.",
                code='i = 0\nwhile i < 3:\n    print("Hi")\n    i += 1'),
            mcq("What's wrong with this loop?", ["It never ends", "Syntax error", "It never runs", "Nothing"], 0, "n is never changed, so n < 5 stays True.",
                code="n = 0\nwhile n < 5:\n    print(n)"),
            fill("Add 1 to i (short form).", "i ___ 1", "+="),
            order("Order a countdown from 3 to 1.", ["n = 3", "while n > 0:", "    print(n)", "    n -= 1"]),
            run("Read a number n and print a countdown from n to 1, then Liftoff!", "python",
                [t("3", stdin="3"), t("1", stdin="1")], ["3\n2\n1\nLiftoff!", "1\nLiftoff!"],
                'n = int(input())\nwhile n > 0:\n    print(n)\n    n -= 1\nprint("Liftoff!")', require=[r"\bwhile\b|\bfor\b"],
                hint="Loop while n > 0, then print Liftoff! after the loop."),
        ),
        lesson(
            "for loops & range",
            "for repeats once for each item. range() makes a sequence of numbers:\n\nfor i in range(3):       # 0, 1, 2\n    print(i)\n\nrange(1, 6)      # 1..5 (stops BEFORE 6)\nrange(0, 10, 2)  # 0, 2, 4, 6, 8\n\nYou can loop over strings too:\nfor ch in \"hi\":\n    print(ch)",
            mcq("What does range(3) produce?", ["0 1 2", "1 2 3", "0 1 2 3", "3"], 0, "range(n) starts at 0 and stops before n."),
            mcq("What does range(2, 10, 3) produce?", ["2 5 8", "2 5 8 11", "3 6 9", "2 4 6 8"], 0, "Start 2, step 3, stop before 10."),
            fill("Loop over every character of word.", "for ch ___ word:", "in"),
            code("Write a for loop that prints the numbers 1 to 5.", [r"^for\s+\w+\s+in\s+range\(\s*1\s*,\s*6\s*\)\s*:\s*$", r"^\s+print\(\s*\w+\s*\)\s*$"],
                 "for n in range(1, 6):\n    print(n)", hint="range(1, 6) - the stop value isn't included."),
            run("Read n and print the sum of all whole numbers from 1 to n.", "python",
                [t("5", stdin="5"), t("10", stdin="10"), t("1", stdin="1")], ["15", "55", "1"],
                "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)", require=[r"\bfor\b|\bwhile\b"],
                hint="Start total at 0 and add each number in the loop."),
        ),
        lesson(
            "break & continue",
            "break leaves the loop immediately. continue skips to the next round:\n\nfor n in range(1, 10):\n    if n == 5:\n        break      # stop completely\n    if n % 2 == 0:\n        continue   # skip even numbers\n    print(n)       # 1, 3",
            mcq("What does break do?", ["Exits the loop immediately", "Skips one iteration", "Restarts the loop", "Ends the program"], 0),
            mcq("What is printed?", ["1 2", "1 2 3", "1 2 4", "3"], 0, "The loop stops when i reaches 3.",
                code="for i in range(1, 5):\n    if i == 3:\n        break\n    print(i)"),
            mcq("What is printed?", ["1 2 4", "1 2", "3", "1 2 3 4"], 0, "continue skips printing 3.",
                code="for i in range(1, 5):\n    if i == 3:\n        continue\n    print(i)"),
            fill("Skip the rest of this round when n is negative.", "if n < 0:\n    ___", "continue"),
            run("Read numbers one per line until the user types 0. Print the sum of the numbers (not counting the 0).", "python",
                [t("3 4 0", stdin="3\n4\n0"), t("10 -2 5 0", stdin="10\n-2\n5\n0"), t("just 0", stdin="0")], ["7", "13", "0"],
                "total = 0\nwhile True:\n    n = int(input())\n    if n == 0:\n        break\n    total += n\nprint(total)", require=[r"\bbreak\b|while\s+\w+\s*!=\s*0"],
                hint="while True: ... and break when you read 0."),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Lists",
        lesson(
            "Lists",
            "A list stores many values in order, in square brackets:\n\nfruits = [\"apple\", \"banana\", \"cherry\"]\nfruits[0]       # 'apple'\nfruits[-1]      # 'cherry'\nlen(fruits)     # 3\nfruits[1] = \"kiwi\"   # lists can be changed\n\nLists can hold any type, even mixed: [1, \"two\", 3.0].",
            mcq("What is nums[2]?", ["30", "20", "10", "An error"], 0, "Index 2 is the third item.", code="nums = [10, 20, 30]"),
            mcq("What is len([4, 8, 15, 16])?", ["4", "3", "16", "5"], 0),
            fill("Change the first item to 99.", "nums[___] = 99", "0"),
            mcq("What is printed?", ["['a', 'z', 'c']", "['a', 'b', 'c']", "z", "An error"], 0, "Assigning to an index replaces that item.",
                code="letters = ['a', 'b', 'c']\nletters[1] = 'z'\nprint(letters)"),
            run("The list scores is given. Print the first score, the last score, and how many scores there are - each on its own line.", "python",
                [t("Run")], ["70\n88\n5"], "scores = [70, 95, 64, 81, 88]\nprint(scores[0])\nprint(scores[-1])\nprint(len(scores))",
                starter="scores = [70, 95, 64, 81, 88]\n", require=[r"scores\[\s*0\s*\]", r"len\(\s*scores\s*\)"], forbid=[r"print\(\s*70\s*\)", r"print\(\s*88\s*\)"]),
        ),
        lesson(
            "List methods",
            "Useful list methods:\n\nnums = [3, 1, 2]\nnums.append(4)     # [3, 1, 2, 4]\nnums.insert(0, 9)  # [9, 3, 1, 2, 4]\nnums.remove(1)     # removes the value 1\nlast = nums.pop()  # removes and returns the last item\nnums.sort()        # sorts in place\n\nBuilt-ins: sum(nums), max(nums), min(nums), 3 in nums (True/False).",
            mcq("What is printed?", ["[1, 2, 3]", "[1, 2]", "[3, 1, 2]", "3"], 0, "append adds to the end.", code="nums = [1, 2]\nnums.append(3)\nprint(nums)"),
            mcq("What is printed?", ["True", "False", "2", "An error"], 0, "in checks membership.", code="print(2 in [1, 2, 3])"),
            fill("Add \"milk\" to the end of the list.", 'shopping.___("milk")', "append"),
            mcq("What is printed?", ["[1, 2, 5, 9]", "[9, 5, 2, 1]", "[5, 2, 9, 1]", "None"], 0, "sort() orders numbers from smallest to largest.",
                code="nums = [5, 2, 9, 1]\nnums.sort()\nprint(nums)"),
            run("Given the list temps, print the highest temperature, the lowest, and the average rounded to 1 decimal place - each on its own line.",
                "python", [t("Run")], ["31\n18\n24.2"], "temps = [22, 31, 18, 25, 26, 23]\nprint(max(temps))\nprint(min(temps))\nprint(round(sum(temps) / len(temps), 1))",
                starter="temps = [22, 31, 18, 25, 26, 23]\n", require=[r"max\(", r"min\(", r"sum\("], hint="round(value, 1) rounds to 1 decimal place."),
        ),
        lesson(
            "Looping over lists",
            "Loop straight over a list's items:\n\nfor name in [\"Ada\", \"Alan\"]:\n    print(\"Hi \" + name)\n\nA list comprehension builds a new list in one line:\n\nsquares = [n * n for n in range(5)]        # [0, 1, 4, 9, 16]\nevens = [n for n in nums if n % 2 == 0]",
            mcq("What is printed?", ["[2, 4, 6]", "[1, 2, 3]", "[1, 4, 9]", "An error"], 0, "Each n becomes n * 2.", code="print([n * 2 for n in [1, 2, 3]])"),
            mcq("What is printed?", ["[2, 4]", "[1, 3, 5]", "[1, 2, 3, 4, 5]", "[]"], 0, "The if keeps only even numbers.",
                code="print([n for n in [1, 2, 3, 4, 5] if n % 2 == 0])"),
            fill("Loop over every item in the list names.", "for name ___ names:", "in"),
            order("Order the code that adds up the list.", ["total = 0", "for n in [4, 5, 6]:", "    total += n", "print(total)"]),
            run("Read a line of numbers separated by spaces. Print how many of them are even.", "python",
                [t("1 2 3 4", stdin="1 2 3 4"), t("7 9", stdin="7 9"), t("10 20 30 5", stdin="10 20 30 5")], ["2", "0", "3"],
                "nums = [int(x) for x in input().split()]\ncount = 0\nfor n in nums:\n    if n % 2 == 0:\n        count += 1\nprint(count)",
                require=[r"\.split\(", r"\bfor\b"], hint="input().split() gives a list of strings - convert each with int()."),
        ),
    ),
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Dictionaries, tuples & sets",
        lesson(
            "Dictionaries",
            "A dictionary maps keys to values:\n\nages = {\"Ada\": 36, \"Alan\": 41}\nages[\"Ada\"]          # 36\nages[\"Grace\"] = 85   # add or update\n\"Ada\" in ages        # True (checks keys)\nages.get(\"Bob\", 0)   # 0 - a default instead of an error",
            mcq("What is printed?", ["2", "1", "a", "An error"], 0, "The key \"b\" maps to 2.", code='d = {"a": 1, "b": 2}\nprint(d["b"])'),
            mcq("What happens?", ["KeyError", "Prints None", "Prints 0", "Prints z"], 0, "Missing keys raise KeyError - use .get() to avoid it.",
                code='d = {"a": 1}\nprint(d["z"])'),
            fill("Look up key \"x\", giving 0 if it's missing.", 'value = d.___("x", 0)', "get"),
            mcq("Which checks whether \"Ada\" is a key in ages?", ['"Ada" in ages', "ages.has(\"Ada\")", "ages[\"Ada\"] == True", "ages.find(\"Ada\")"], 0),
            run("The dictionary prices is given. Read an item name and print its price, or Not found if it isn't there.", "python",
                [t("apple", stdin="apple"), t("pear", stdin="pear"), t("mango", stdin="mango")], ["1.2", "0.9", "Not found"],
                'prices = {"apple": 1.2, "pear": 0.9, "kiwi": 0.5}\nitem = input()\nif item in prices:\n    print(prices[item])\nelse:\n    print("Not found")',
                starter='prices = {"apple": 1.2, "pear": 0.9, "kiwi": 0.5}\n', require=[r"prices\["]),
        ),
        lesson(
            "Looping over dictionaries",
            "Loop over keys, values, or both:\n\nfor name in ages:               # keys\nfor age in ages.values():       # values\nfor name, age in ages.items():  # pairs\n    print(f\"{name}: {age}\")\n\nCounting pattern:\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1",
            mcq("What does d.items() give you?", ["(key, value) pairs", "Only keys", "Only values", "The length"], 0),
            fill("Loop over names and ages together.", "for name, age in ages.___():", "items"),
            mcq("What is printed?", ["3", "2", "6", "An error"], 0, "sum() adds the values 1 + 2.", code='d = {"a": 1, "b": 2}\nprint(sum(d.values()))'),
            order("Order the word counter.", ["counts = {}", 'for w in ["a", "b", "a"]:', "    counts[w] = counts.get(w, 0) + 1", "print(counts)"]),
            run("Read a sentence and print how many times each word appears, one line per word in the order it first appears, like: the 2",
                "python", [t("the cat the dog", stdin="the cat the dog"), t("a a a", stdin="a a a")], ["the 2\ncat 1\ndog 1", "a 3"],
                "counts = {}\nfor w in input().split():\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in counts.items():\n    print(w, c)",
                require=[r"\{\s*\}|dict\("], hint="Dictionaries remember insertion order - loop over .items() at the end."),
        ),
        lesson(
            "Tuples & sets",
            "A tuple is like a list that can't change: point = (3, 4). Unpack it: x, y = point.\n\nA set stores UNIQUE values with no order:\n\ncolors = {\"red\", \"blue\", \"red\"}   # {'red', 'blue'}\nset([1, 1, 2])                    # {1, 2}\na | b   union   a & b   intersection   a - b   difference",
            mcq("What is printed?", ["3", "4", "2", "An error"], 0, "Sets drop duplicates: {1, 2, 3}.", code="print(len({1, 2, 2, 3, 3}))"),
            mcq("What happens?", ["TypeError", "t becomes (9, 2)", "Nothing", "Prints 9"], 0, "Tuples are immutable.", code="t = (1, 2)\nt[0] = 9"),
            fill("Unpack the tuple into x and y.", "x, y ___ (3, 4)", "="),
            mcq("What is {1, 2, 3} & {2, 3, 4}?", ["{2, 3}", "{1, 2, 3, 4}", "{1, 4}", "{1}"], 0, "& keeps values found in both sets."),
            run("Read two lines of words. Print the words that appear in BOTH lines, sorted alphabetically and separated by spaces (print None if there are none).",
                "python", [t("common words", stdin="red green blue\nblue red yellow"), t("no overlap", stdin="a b\nc d")], ["blue red", "None"],
                'a = set(input().split())\nb = set(input().split())\ncommon = sorted(a & b)\nprint(" ".join(common) if common else "None")',
                require=[r"set\(|\{"], hint="sorted(a & b) gives a sorted list; ' '.join() glues it together."),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Functions & errors",
        lesson(
            "Defining functions",
            "A function is a named, reusable block of code:\n\ndef greet(name):\n    print(f\"Hello, {name}!\")\n\ngreet(\"Ada\")    # Hello, Ada!\ngreet(\"Alan\")   # Hello, Alan!\n\ndef starts it, the parameters go in ( ), and the body is indented.",
            mcq("Which keyword defines a function?", ["def", "function", "func", "define"], 0),
            mcq("What is printed?", ["Hi Bo", "Hi name", "Nothing", "An error"], 0, "The argument \"Bo\" becomes name.",
                code='def hi(name):\n    print("Hi " + name)\n\nhi("Bo")'),
            fill("Finish the function header.", "def square(n)___", ":"),
            order("Order the lines: define the function, then call it.", ["def shout(word):", "    print(word.upper())", 'shout("hey")']),
            run("Write a function stars(n) that prints a line of n stars (*).", "python",
                [t("stars(3)", append="stars(3)"), t("stars(5)", append="stars(5)"), t("stars(1)", append="stars(1)")], ["***", "*****", "*"],
                'def stars(n):\n    print("*" * n)', require=[r"def\s+stars\s*\("], hint='"*" * 3 is "***".'),
        ),
        lesson(
            "Return values & defaults",
            "return sends a value back to whoever called the function:\n\ndef area(w, h):\n    return w * h\n\nsize = area(3, 4)   # 12\n\nParameters can have default values:\n\ndef greet(name, greeting=\"Hello\"):\n    return f\"{greeting}, {name}!\"\n\ngreet(\"Ada\")          # 'Hello, Ada!'\ngreet(\"Ada\", \"Hi\")    # 'Hi, Ada!'",
            mcq("What is printed?", ["10", "None", "5", "An error"], 0, "The returned value is printed.",
                code="def double(x):\n    return x * 2\n\nprint(double(5))"),
            mcq("What is printed?", ["None", "10", "5", "An error"], 0, "Without return, a function returns None.",
                code="def double(x):\n    x * 2\n\nprint(double(5))"),
            fill("Send the result back to the caller.", "def add(a, b):\n    ___ a + b", "return"),
            mcq("What is power(3)?", ["9", "3", "27", "An error"], 0, "exp defaults to 2.", code="def power(base, exp=2):\n    return base ** exp"),
            run("Write a function is_even(n) that RETURNS True if n is even, otherwise False.", "python",
                [t("is_even(4)", append="print(is_even(4))"), t("is_even(7)", append="print(is_even(7))"), t("is_even(0)", append="print(is_even(0))")],
                ["True", "False", "True"], "def is_even(n):\n    return n % 2 == 0", require=[r"def\s+is_even", r"\breturn\b"],
                forbid=[r"print\("], hint="return n % 2 == 0"),
        ),
        lesson(
            "Handling errors",
            "When something goes wrong, Python raises an exception. Catch it with try/except:\n\ntry:\n    n = int(input())\n    print(10 / n)\nexcept ValueError:\n    print(\"That's not a number\")\nexcept ZeroDivisionError:\n    print(\"Can't divide by zero\")\n\nCommon ones: ValueError, ZeroDivisionError, KeyError, IndexError, TypeError.",
            mcq("Which exception does int(\"abc\") raise?", ["ValueError", "TypeError", "KeyError", "ZeroDivisionError"], 0),
            mcq("What is printed?", ["Oops", "0", "An error", "Nothing"], 0, "Dividing by zero raises, so the except block runs.",
                code='try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print("Oops")'),
            fill("Catch the error raised by a missing dictionary key.", "except ___:", "KeyError"),
            order("Order the safe conversion.", ["try:", '    n = int("x")', "except ValueError:", '    n = 0', "print(n)"]),
            run("Read two lines: a and b. Print a divided by b rounded to 2 decimals. If b is 0 print Cannot divide by zero; if either isn't a number print Invalid input.",
                "python", [t("7 / 2", stdin="7\n2"), t("divide by 0", stdin="5\n0"), t("not a number", stdin="five\n2"), t("1 / 3", stdin="1\n3")],
                ["3.5", "Cannot divide by zero", "Invalid input", "0.33"],
                'try:\n    a = float(input())\n    b = float(input())\n    print(round(a / b, 2))\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")\nexcept ValueError:\n    print("Invalid input")',
                require=[r"\btry\s*:", r"\bexcept\b"], hint="Put the risky lines in try and add one except per error type."),
        ),
    ),
    INTERMEDIATE,
    ADVANCED,
    EXPERT,
    EXPERT2,
)
