"""TypeScript - JavaScript with types. Programs are type-checked (strict mode) by the real TypeScript compiler
in the learner's browser, then run; a type error fails the exercise like a wrong answer.

8 units: Beginner (1-4), Intermediate (5-6), Advanced (7-8). Projects are added to units 4, 6 and 8
(see projects_typescript.py). Tests often append `// @ts-expect-error` lines: they pass only if the learner's
types really reject bad calls, so `any` everywhere doesn't work.
"""
from .dsl import code, course, fill, lesson, mcq, order, run, section, t, unit

# appended to a test: the line below MUST be a type error, otherwise the compiler reports the unused directive
REJECTS = "// @ts-expect-error\n"

BEGINNER = section(
    "Beginner",
    # ------------------------------------------------------------------ 1
    unit(
        "Unit 1 · Types basics",
        lesson(
            "Why TypeScript?",
            "TypeScript is JavaScript plus types. You describe what kind of value each variable holds, and the compiler checks your whole program BEFORE it runs:\n\nlet age: number = 30;\nage = \"thirty\";   // error: Type 'string' is not assignable to type 'number'\n\nThe types are erased when TypeScript compiles to JavaScript - they cost nothing at runtime, but catch bugs while you type. In these lessons a type error stops your program from running, just like in a real project.",
            mcq("When does TypeScript find type errors?", ["While the program runs", "Before it runs, when the code is checked/compiled", "Only in production", "Never - types are comments"], 1),
            mcq("What happens to types when TypeScript is compiled to JavaScript?", ["They become runtime checks", "They are removed", "They become comments", "They slow the program down"], 1),
            fill("Annotate the variable as a number.", "let score___ number = 10;", ":"),
            mcq("Which line is a type error?", ["let a: string = 'hi';", "let b: number = 4.5;", "let c: boolean = 'yes';", "let d: number = -1;"], 2),
            run("Declare a const city: string set to \"Paris\" and a let year: number set to 2024. Add 1 to year, then print: Paris 2025", "typescript",
                [t("Run")], ["Paris 2025"], 'const city: string = "Paris";\nlet year: number = 2024;\nyear = year + 1;\nconsole.log(city, year);',
                require=[r"city\s*:\s*string", r"year\s*:\s*number"]),
        ),
        lesson(
            "Primitive types & inference",
            "The basic types are string, number, boolean, null, undefined (and bigint, symbol).\n\nYou often don't need to write them - TypeScript INFERS the type from the value:\n\nlet name = \"Ada\";    // inferred as string\nname = 42;           // error!\n\nAnnotate when there's no initial value, or to document intent:\n\nlet total: number;\ntotal = 0;\n\nany switches checking OFF - avoid it. unknown is the safe 'could be anything'.",
            mcq("What type does TypeScript infer for let x = true?", ["any", "boolean", "true", "unknown"], 1),
            mcq("Which type turns type checking OFF for a value?", ["unknown", "never", "any", "void"], 2),
            mcq("Is this OK?", ["Yes", "No - count was inferred as number"], 1, code="let count = 0;\ncount = \"many\";"),
            fill("Declare a variable that will hold text later.", "let label: ___;", "string"),
            run("Fix the type errors so the program compiles and prints: Ada is 36 (true)", "typescript",
                [t("Run")], ["Ada is 36 (true)"],
                'const person: string = "Ada";\nconst age: number = 36;\nconst active: boolean = true;\nconsole.log(`${person} is ${age} (${active})`);',
                starter='const person: string = "Ada";\nconst age: number = "36";\nconst active: boolean = "true";\nconsole.log(`${person} is ${age} (${active})`);\n',
                forbid=[r"\bany\b"], hint="\"36\" is a string - a number has no quotes."),
        ),
        lesson(
            "Arrays & tuples",
            "Array types: number[] (or Array<number>) - every item must match.\n\nconst scores: number[] = [90, 85];\nscores.push(\"A\");   // error\n\nA tuple has a fixed length and a type per position:\n\nconst point: [number, number] = [3, 4];\nconst entry: [string, number] = [\"Ada\", 36];\nconst [name, age] = entry;   // name: string, age: number",
            mcq("Which is an array of strings?", ["string", "string[]", "[string]", "Array"], 1),
            mcq("What's the type of p?", ["number[]", "[number, number]", "number", "any[]"], 1, code="const p: [number, number] = [1, 2];"),
            fill("An array of booleans.", "const flags: ___[] = [true, false];", "boolean"),
            mcq("Is this OK?", ["Yes", "No - the tuple needs exactly a string then a number"], 1, code="const e: [string, number] = [36, \"Ada\"];"),
            run("Write total(prices: number[]): number returning the sum, and pairs(names: string[], ages: number[]): [string, number][] zipping them together.", "typescript",
                [t("total", append="console.log(total([2.5, 3, 4.5]));"),
                 t("pairs", append='console.log(pairs(["Ada", "Bo"], [36, 7]));'),
                 t("types", append=REJECTS + 'total(["1", "2"]);\nconsole.log("checked");')],
                ["10", "[ [ 'Ada', 36 ], [ 'Bo', 7 ] ]", "checked"],
                "function total(prices: number[]): number {\n  let sum = 0;\n  for (const p of prices) sum += p;\n  return sum;\n}\n\nfunction pairs(names: string[], ages: number[]): [string, number][] {\n  return names.map((n, i) => [n, ages[i]]);\n}",
                forbid=[r"\bany\b"], hint="names.map((n, i) => [n, ages[i]])"),
        ),
    ),
    # ------------------------------------------------------------------ 2
    unit(
        "Unit 2 · Functions",
        lesson(
            "Typed functions",
            "Annotate each parameter, and optionally the return type:\n\nfunction add(a: number, b: number): number {\n  return a + b;\n}\n\nconst greet = (name: string): string => `Hi ${name}`;\n\nCalling with the wrong types - or the wrong NUMBER of arguments - is an error. A function that returns nothing has return type void.",
            mcq("What's wrong with add(1, \"2\")?", ["Nothing", "\"2\" is not a number", "add needs 3 arguments", "add returns a string"], 1),
            mcq("Return type of a function that only prints?", ["null", "undefined", "void", "never"], 2),
            fill("Annotate the return type.", "function double(n: number)___ number {\n  return n * 2;\n}", ":"),
            mcq("Is add(1) OK for function add(a: number, b: number)?", ["Yes, b is undefined", "No - expected 2 arguments", "Yes, b is 0", "Only at runtime"], 1),
            run("Write a function bmi(weightKg: number, heightM: number): number that returns weight / height², rounded to 1 decimal (Math.round(x * 10) / 10).", "typescript",
                [t("70/1.75", append="console.log(bmi(70, 1.75));"), t("90/1.8", append="console.log(bmi(90, 1.8));"),
                 t("types", append=REJECTS + 'bmi("70", 1.75);\nconsole.log("checked");')],
                ["22.9", "27.8", "checked"],
                "function bmi(weightKg: number, heightM: number): number {\n  return Math.round((weightKg / (heightM * heightM)) * 10) / 10;\n}",
                require=[r":\s*number\s*\)\s*:\s*number"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Optional, default & rest parameters",
            "function greet(name: string, greeting?: string) {      // optional: string | undefined\n  return `${greeting ?? \"Hello\"}, ${name}!`;\n}\n\nfunction pad(text: string, width = 10) { ... }           // default value, type inferred\n\nfunction sum(...nums: number[]): number {               // rest: any number of args\n  return nums.reduce((a, b) => a + b, 0);\n}\n\nOptional parameters must come after the required ones.",
            mcq("What is the type of greeting inside greet?", ["string", "string | undefined", "any", "never"], 1),
            mcq("What does sum(1, 2, 3) return with the rest-parameter version?", ["[1, 2, 3]", "6", "1", "An error"], 1),
            fill("Mark the parameter as optional.", "function log(msg: string, level___: string) {}", "?"),
            mcq("Which is NOT allowed?", ["(a: number, b?: number)", "(a?: number, b: number)", "(a = 1, b = 2)", "(...rest: string[])"], 1, "A required parameter can't follow an optional one."),
            run("Write label(name: string, count?: number): string returning 'name' when count is missing, otherwise 'name ×count'. Then average(...nums: number[]): number (0 for no numbers).", "typescript",
                [t("label", append='console.log(label("apple"));\nconsole.log(label("pear", 3));'),
                 t("average", append="console.log(average(2, 4, 9));\nconsole.log(average());"),
                 t("types", append=REJECTS + 'average("1");\nconsole.log("checked");')],
                ["apple\npear ×3", "5\n0", "checked"],
                'function label(name: string, count?: number): string {\n  return count === undefined ? name : `${name} ×${count}`;\n}\n\nfunction average(...nums: number[]): number {\n  if (nums.length === 0) return 0;\n  return nums.reduce((a, b) => a + b, 0) / nums.length;\n}',
                require=[r"count\s*\?\s*:", r"\.\.\.\s*nums"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Function types & callbacks",
            "Functions are values, so they have types too:\n\ntype MathOp = (a: number, b: number) => number;\nconst mul: MathOp = (a, b) => a * b;      // a and b inferred as number\n\nfunction applyTwice(f: (x: number) => number, x: number): number {\n  return f(f(x));\n}\napplyTwice((n) => n + 3, 1);   // 7\n\nCallbacks passed to map/filter get their parameter types inferred from the array.",
            mcq("What does applyTwice((n) => n * 2, 5) return?", ["10", "20", "25", "7"], 1),
            mcq("Which is a function type?", ["(x: number) => string", "function: string", "Function<number>", "() -> string"], 0),
            fill("Type for a callback taking a string and returning nothing.", "type Listener = (msg: string) => ___;", "void"),
            mcq("In [1, 2].map((n) => n * 2), what type is n?", ["any", "number", "unknown", "string"], 1),
            run("Write a type Filter = (n: number) => boolean and a function keep(nums: number[], test: Filter): number[] that returns the numbers passing the test (without using .filter).", "typescript",
                [t("evens", append="console.log(keep([1, 2, 3, 4], (n) => n % 2 === 0));"),
                 t("big", append="console.log(keep([5, 50, 500], (n) => n > 10));"),
                 t("types", append=REJECTS + 'keep([1], (n) => "yes");\nconsole.log("checked");')],
                ["[ 2, 4 ]", "[ 50, 500 ]", "checked"],
                "type Filter = (n: number) => boolean;\n\nfunction keep(nums: number[], test: Filter): number[] {\n  const out: number[] = [];\n  for (const n of nums) if (test(n)) out.push(n);\n  return out;\n}",
                require=[r"type\s+Filter\s*=\s*\(\s*\w+\s*:\s*number\s*\)\s*=>\s*boolean"], forbid=[r"\.filter\(", r"\bany\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 3
    unit(
        "Unit 3 · Objects & interfaces",
        lesson(
            "Object types & interfaces",
            "An interface describes the shape of an object:\n\ninterface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nconst u: User = { id: 1, name: \"Ada\", email: \"ada@example.com\" };\n\nMissing a property, adding an unknown one in an object literal, or using the wrong type is an error. Functions can take and return interfaces.",
            mcq("Is this OK for interface Point { x: number; y: number }?", ["Yes", "No - y is missing"], 1, code="const p: Point = { x: 1 };"),
            mcq("What does an interface produce in the compiled JavaScript?", ["A class", "Nothing - it's erased", "A function", "An object"], 1),
            fill("Declare an interface.", "___ Book {\n  title: string;\n  pages: number;\n}", "interface"),
            mcq("Is this OK for interface Point { x: number; y: number }?", ["Yes", "No - z isn't part of Point"], 1, code="const p: Point = { x: 1, y: 2, z: 3 };"),
            run("Declare interface Product { name: string; price: number; qty: number } and write totalValue(items: Product[]): number (sum of price × qty).", "typescript",
                [t("cart", append='const cart: Product[] = [{ name: "pen", price: 1.5, qty: 4 }, { name: "book", price: 12, qty: 1 }];\nconsole.log(totalValue(cart));'),
                 t("empty", append="console.log(totalValue([]));"),
                 t("shape", append=REJECTS + 'const bad: Product = { name: "x", price: 1 };\nconsole.log("checked");')],
                ["18", "0", "checked"],
                "interface Product {\n  name: string;\n  price: number;\n  qty: number;\n}\n\nfunction totalValue(items: Product[]): number {\n  return items.reduce((sum, p) => sum + p.price * p.qty, 0);\n}",
                require=[r"interface\s+Product"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Optional & readonly properties",
            "interface Profile {\n  readonly id: number;   // can't be changed after creation\n  name: string;\n  bio?: string;          // optional: string | undefined\n}\n\nconst p: Profile = { id: 1, name: \"Ada\" };\np.id = 2;                  // error: id is read-only\nconsole.log(p.bio?.length);   // ?. safely reads possibly-missing values\n\nReadonlyArray<T> (or readonly T[]) is an array you can't push to.",
            mcq("What's the type of p.bio?", ["string", "string | undefined", "undefined", "never"], 1),
            mcq("What does readonly prevent?", ["Reading the property", "Re-assigning the property", "Deleting the object", "Nothing at runtime or compile time"], 1),
            fill("Mark nickname as optional.", "interface Pet {\n  name: string;\n  nickname___: string;\n}", "?"),
            mcq("Is this OK?", ["Yes", "No - readonly arrays have no push"], 1, code="const xs: readonly number[] = [1, 2];\nxs.push(3);"),
            run("Declare interface Contact { readonly id: number; name: string; phone?: string } and write describe(c: Contact): string -> 'Ada (555-0101)' or 'Ada (no phone)'.", "typescript",
                [t("phone", append='console.log(describe({ id: 1, name: "Ada", phone: "555-0101" }));'),
                 t("none", append='console.log(describe({ id: 2, name: "Bo" }));'),
                 t("readonly", append='const c: Contact = { id: 3, name: "Cy" };\n' + REJECTS + "c.id = 4;\nconsole.log(c.name);")],
                ["Ada (555-0101)", "Bo (no phone)", "Cy"],
                "interface Contact {\n  readonly id: number;\n  name: string;\n  phone?: string;\n}\n\nfunction describe(c: Contact): string {\n  return `${c.name} (${c.phone ?? \"no phone\"})`;\n}",
                forbid=[r"\bany\b"]),
        ),
        lesson(
            "Type aliases",
            "type gives a name to ANY type - not just object shapes:\n\ntype ID = number | string;\ntype Point = { x: number; y: number };\ntype Pair<T> = [T, T];\n\nInterfaces can be extended:\n\ninterface Animal { name: string }\ninterface Dog extends Animal { breed: string }\n\nand type aliases can be combined with & (intersection):\n\ntype Timestamped = { createdAt: string };\ntype Post = Point & Timestamped;",
            mcq("Which can describe a union like number | string?", ["Only interface", "Only type", "Both", "Neither"], 1),
            mcq("What does A & B mean?", ["Either A or B", "Must have everything from A AND B", "A minus B", "A compared to B"], 1),
            fill("Extend an interface.", "interface Admin ___ User {\n  level: number;\n}", "extends"),
            mcq("Which keyword creates a type alias?", ["alias", "type", "typedef", "let"], 1),
            run("Create interface Shape { name: string } and interface Rect extends Shape { w: number; h: number }, a type Sized = Rect & { unit: string }, and write info(r: Sized): string -> 'box: 6 cm²'.", "typescript",
                [t("box", append='console.log(info({ name: "box", w: 2, h: 3, unit: "cm" }));'),
                 t("needs unit", append=REJECTS + 'info({ name: "x", w: 1, h: 1 });\nconsole.log("checked");')],
                ["box: 6 cm²", "checked"],
                "interface Shape {\n  name: string;\n}\n\ninterface Rect extends Shape {\n  w: number;\n  h: number;\n}\n\ntype Sized = Rect & { unit: string };\n\nfunction info(r: Sized): string {\n  return `${r.name}: ${r.w * r.h} ${r.unit}²`;\n}",
                require=[r"extends\s+Shape", r"&"], forbid=[r"\bany\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 4
    unit(
        "Unit 4 · Unions & narrowing",
        lesson(
            "Union types",
            "A union means 'one of these types':\n\nlet id: number | string;\nid = 42;      // OK\nid = \"A-42\";  // OK\nid = true;    // error\n\nWith a union you can only use what ALL members support - id.toUpperCase() is an error because numbers don't have it. To use member-specific methods you NARROW first (next lesson).\n\nUnions of literal values are great for options: type Size = \"S\" | \"M\" | \"L\";",
            mcq("Which value is NOT allowed for let v: number | boolean?", ["0", "false", "\"0\"", "3.14"], 2),
            mcq("Why is id.toUpperCase() an error for id: number | string?", ["Strings can't be upper-cased", "number doesn't have toUpperCase", "Unions are read-only", "It isn't"], 1),
            fill("A size can only be one of these.", 'type Size = "S" ___ "M" | "L";', "|"),
            mcq("Is this OK?", ["Yes", "No - \"XL\" isn't one of the allowed sizes"], 1, code='type Size = "S" | "M" | "L";\nconst s: Size = "XL";'),
            run("Define type Unit = \"c\" | \"f\" and write convert(value: number, to: Unit): number - Celsius to Fahrenheit when to is \"f\" (v * 9/5 + 32), Fahrenheit to Celsius when \"c\" ((v - 32) * 5/9). Round to 1 decimal.", "typescript",
                [t("to f", append='console.log(convert(100, "f"));'), t("to c", append='console.log(convert(98.6, "c"));'),
                 t("types", append=REJECTS + 'convert(1, "k");\nconsole.log("checked");')],
                ["212", "37", "checked"],
                'type Unit = "c" | "f";\n\nfunction convert(value: number, to: Unit): number {\n  const result = to === "f" ? (value * 9) / 5 + 32 : ((value - 32) * 5) / 9;\n  return Math.round(result * 10) / 10;\n}',
                require=[r"type\s+Unit\s*=\s*\"c\"\s*\|\s*\"f\"|type\s+Unit\s*=\s*\"f\"\s*\|\s*\"c\""], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Narrowing",
            "Narrowing means checking which member of a union you have; TypeScript follows your checks:\n\nfunction show(id: number | string) {\n  if (typeof id === \"string\") {\n    return id.toUpperCase();   // here id is string\n  }\n  return id.toFixed(2);        // here id is number\n}\n\nOther narrowing checks: === null / undefined, Array.isArray(x), \"prop\" in obj, x instanceof Date.",
            mcq("Inside if (typeof x === \"number\") { ... }, x is…", ["unknown", "number", "the original union", "any"], 1),
            mcq("Which check narrows to an array?", ["typeof x === \"array\"", "Array.isArray(x)", "x is Array", "x.length"], 1, "typeof [] is \"object\"."),
            fill("Narrow away null.", "if (name ___ null) {\n  console.log(name.length);\n}", "!=="),
            mcq("After if (typeof v === \"string\") return; - in the code below it, v: string | number is…", ["string", "number", "string | number", "never"], 1),
            run("Write format(value: string | number | boolean | null): string -> strings in quotes, numbers with 2 decimals, booleans as yes/no, and null as '(empty)'.", "typescript",
                [t("all", append='console.log(format("hi"));\nconsole.log(format(3.14159));\nconsole.log(format(false));\nconsole.log(format(null));'),
                 t("types", append=REJECTS + "format(undefined);\nconsole.log(\"checked\");")],
                ['"hi"\n3.14\nno\n(empty)', "checked"],
                'function format(value: string | number | boolean | null): string {\n  if (value === null) return "(empty)";\n  if (typeof value === "string") return `"${value}"`;\n  if (typeof value === "number") return value.toFixed(2);\n  return value ? "yes" : "no";\n}',
                require=[r"typeof\s+value"], forbid=[r"\bany\b", r"as\s+(string|number|boolean)"]),
        ),
        lesson(
            "Discriminated unions",
            "Give each object in a union a literal 'kind' field, and a switch on it narrows perfectly:\n\ntype Shape =\n  | { kind: \"circle\"; radius: number }\n  | { kind: \"rect\"; w: number; h: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case \"circle\": return Math.PI * s.radius ** 2;\n    case \"rect\":   return s.w * s.h;\n  }\n}\n\nThis is how real apps model states: loading / success / error.",
            mcq("In case \"rect\":, what can you access on s?", ["radius", "w and h", "everything", "nothing"], 1),
            mcq("What's the 'discriminant' in the Shape union?", ["radius", "kind", "Shape", "switch"], 1),
            fill("Switch on the discriminant.", "switch (s.___) {", "kind"),
            mcq("Is this OK?", ["Yes", "No - a circle has no w"], 1, code='const s: Shape = { kind: "circle", w: 2 };'),
            run("Model type Result = { status: \"ok\"; value: number } | { status: \"error\"; message: string } and write show(r: Result): string -> 'OK: 42' or 'Error: bad input'.", "typescript",
                [t("ok", append='console.log(show({ status: "ok", value: 42 }));'), t("error", append='console.log(show({ status: "error", message: "bad input" }));'),
                 t("types", append=REJECTS + 'show({ status: "ok", message: "x" });\nconsole.log("checked");')],
                ["OK: 42", "Error: bad input", "checked"],
                'type Result = { status: "ok"; value: number } | { status: "error"; message: string };\n\nfunction show(r: Result): string {\n  switch (r.status) {\n    case "ok":\n      return `OK: ${r.value}`;\n    case "error":\n      return `Error: ${r.message}`;\n  }\n}',
                require=[r"status\s*:\s*\"ok\"", r"status\s*:\s*\"error\""], forbid=[r"\bany\b"]),
        ),
    ),
)

INTERMEDIATE = section(
    "Intermediate",
    # ------------------------------------------------------------------ 5
    unit(
        "Unit 5 · Classes & enums",
        lesson(
            "Classes with types",
            "class Account {\n  private balance = 0;              // only usable inside the class\n  constructor(public readonly owner: string) {}   // declares + assigns a property\n\n  deposit(amount: number): void {\n    if (amount <= 0) throw new Error(\"Amount must be positive\");\n    this.balance += amount;\n  }\n  get total(): number { return this.balance; }\n}\n\npublic (default), private and protected control access - at compile time.",
            mcq("Where can a private property be used?", ["Anywhere", "Only inside its class", "In subclasses too", "Only in constructors"], 1),
            mcq("What does constructor(public owner: string) do?", ["Nothing special", "Declares AND assigns this.owner", "Makes owner global", "Creates a static property"], 1),
            fill("Hide the field from outside code.", "class Counter {\n  ___ count = 0;\n}", "private"),
            mcq("Is a.balance OK outside the class above?", ["Yes", "No - balance is private"], 1),
            run("Write class Counter with a private count starting at 0, increment(by?: number) (default 1), and a getter value. Outside code must not be able to read count directly.", "typescript",
                [t("count", append="const c = new Counter();\nc.increment();\nc.increment(5);\nconsole.log(c.value);"),
                 t("private", append="const c = new Counter();\n" + REJECTS + "c.count;\nconsole.log(c.value);")],
                ["6", "0"],
                "class Counter {\n  private count = 0;\n\n  increment(by = 1): void {\n    this.count += by;\n  }\n\n  get value(): number {\n    return this.count;\n  }\n}",
                require=[r"private\s+count", r"get\s+value"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Interfaces & abstract classes",
            "A class can promise to fit an interface:\n\ninterface Speaker { speak(): string }\nclass Dog implements Speaker {\n  speak() { return \"Woof\"; }\n}\n\nAn abstract class is a base you can't instantiate; subclasses must fill in its abstract members:\n\nabstract class Shape {\n  abstract area(): number;\n  describe() { return `area ${this.area().toFixed(1)}`; }\n}\nclass Square extends Shape {\n  constructor(private side: number) { super(); }\n  area() { return this.side ** 2; }\n}",
            mcq("What does implements check?", ["Nothing", "That the class has everything the interface requires", "That the class extends another class", "Runtime types"], 1),
            mcq("new Shape() for an abstract class Shape is…", ["Fine", "An error", "Returns null", "Creates a Square"], 1),
            fill("Promise to fit the interface.", "class Cat ___ Speaker {", "implements"),
            mcq("A subclass constructor must call…", ["this()", "super()", "parent()", "base()"], 1),
            run("Write abstract class Employee(name) with abstract pay(): number and a summary() returning 'Ada earns 3000'. Then class Salaried(name, monthly) and class Hourly(name, rate, hours).", "typescript",
                [t("both", append='const staff: Employee[] = [new Salaried("Ada", 3000), new Hourly("Bo", 20, 80)];\nfor (const e of staff) console.log(e.summary());'),
                 t("abstract", append=REJECTS + 'const e = new Employee("x");\nconsole.log("checked");')],
                ["Ada earns 3000\nBo earns 1600", "checked"],
                "abstract class Employee {\n  constructor(public name: string) {}\n\n  abstract pay(): number;\n\n  summary(): string {\n    return `${this.name} earns ${this.pay()}`;\n  }\n}\n\nclass Salaried extends Employee {\n  constructor(name: string, private monthly: number) {\n    super(name);\n  }\n\n  pay(): number {\n    return this.monthly;\n  }\n}\n\nclass Hourly extends Employee {\n  constructor(name: string, private rate: number, private hours: number) {\n    super(name);\n  }\n\n  pay(): number {\n    return this.rate * this.hours;\n  }\n}",
                require=[r"abstract\s+class\s+Employee", r"abstract\s+pay"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Enums & as const",
            "An enum names a set of constants:\n\nenum Direction { Up, Down, Left, Right }      // 0, 1, 2, 3\nenum Status { Active = \"ACTIVE\", Banned = \"BANNED\" }\n\nMany teams prefer a plain object 'as const' plus a union type - no extra runtime code:\n\nconst ROLES = [\"admin\", \"editor\", \"viewer\"] as const;\ntype Role = (typeof ROLES)[number];   // \"admin\" | \"editor\" | \"viewer\"",
            mcq("Default value of the first member of enum Color { Red, Green }?", ["1", "0", "\"Red\"", "undefined"], 1),
            mcq("What does as const do to [\"a\", \"b\"]?", ["Nothing", "Makes it a readonly tuple of the literal types", "Converts it to an enum", "Freezes it at runtime only"], 1),
            fill("Declare an enum.", "___ Level { Low, High }", "enum"),
            mcq("type Role = (typeof ROLES)[number] gives…", ["string", "number", "\"admin\" | \"editor\" | \"viewer\"", "Role[]"], 2),
            run("Create enum Priority { Low = 1, Medium = 2, High = 3 } and write sortTasks(tasks: { title: string; priority: Priority }[]): string[] returning titles, highest priority first.", "typescript",
                [t("sort", append='console.log(sortTasks([{ title: "tidy", priority: Priority.Low }, { title: "fix bug", priority: Priority.High }, { title: "email", priority: Priority.Medium }]));'),
                 t("enum only", append=REJECTS + 'sortTasks([{ title: "x", priority: "high" }]);\nconsole.log(Priority.High, Priority[2]);')],
                ["[ 'fix bug', 'email', 'tidy' ]", "3 Medium"],
                "enum Priority {\n  Low = 1,\n  Medium = 2,\n  High = 3,\n}\n\nfunction sortTasks(tasks: { title: string; priority: Priority }[]): string[] {\n  return [...tasks].sort((a, b) => b.priority - a.priority).map((t) => t.title);\n}",
                require=[r"enum\s+Priority"], forbid=[r"\bany\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 6
    unit(
        "Unit 6 · Generics",
        lesson(
            "Generic functions",
            "Generics are type PARAMETERS - they keep the link between input and output types:\n\nfunction first<T>(items: T[]): T | undefined {\n  return items[0];\n}\n\nconst n = first([1, 2, 3]);       // n: number | undefined\nconst s = first([\"a\", \"b\"]);     // s: string | undefined\n\nWithout generics you'd need any (losing all checking) or one function per type.",
            mcq("What is the type of x?", ["any", "boolean | undefined", "T", "unknown"], 1, code="const x = first([true, false]);"),
            mcq("Why not just use any[] instead of T[]?", ["any is slower", "any loses the link between input and output types", "any isn't allowed", "No reason"], 1),
            fill("Declare a type parameter.", "function wrap___(value: T): T[] {\n  return [value];\n}", "<T>"),
            mcq("How do you call a generic function with an explicit type?", ["first(number)([1])", "first<number>([1])", "first:number([1])", "first[number]([1])"], 1),
            run("Write generic last<T>(items: T[]): T | undefined and pairUp<A, B>(a: A, b: B): [A, B]. The tests also check the types flow through.", "typescript",
                [t("last", append='console.log(last([1, 2, 3]), last<string>([]));'),
                 t("pair", append='const p = pairUp("Ada", 36);\nconst age: number = p[1];\nconsole.log(p, age);'),
                 t("typed", append='const s = last(["a", "b"]);\n' + REJECTS + "const wrong: number = s;\nconsole.log(s);")],
                ["3 undefined", "[ 'Ada', 36 ] 36", "b"],
                "function last<T>(items: T[]): T | undefined {\n  return items[items.length - 1];\n}\n\nfunction pairUp<A, B>(a: A, b: B): [A, B] {\n  return [a, b];\n}",
                require=[r"<\s*T\s*>", r"<\s*A\s*,\s*B\s*>"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Constraints & keyof",
            "Constrain a type parameter with extends:\n\nfunction longest<T extends { length: number }>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}\nlongest(\"hi\", \"hello\");   // OK - strings have length\nlongest(1, 2);             // error\n\nkeyof T is the union of T's property names, so this is fully type-safe:\n\nfunction get<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}",
            mcq("What is keyof { id: number; name: string }?", ["string", "\"id\" | \"name\"", "number | string", "[\"id\", \"name\"]"], 1),
            mcq("Why is longest(1, 2) an error?", ["Too few arguments", "numbers don't have a length property", "1 < 2", "It isn't"], 1),
            fill("Only allow keys of T.", "function pick<T, K ___ keyof T>(obj: T, key: K) {", "extends"),
            mcq("What type does get(user, \"name\") return for user: { name: string }?", ["any", "string", "keyof User", "unknown"], 1),
            run("Write pluck<T, K extends keyof T>(items: T[], key: K): T[K][] that returns that property from every item.", "typescript",
                [t("names", append='const users = [{ id: 1, name: "Ada" }, { id: 2, name: "Bo" }];\nconsole.log(pluck(users, "name"));\nconsole.log(pluck(users, "id"));'),
                 t("safe keys", append='const users = [{ id: 1, name: "Ada" }];\n' + REJECTS + 'pluck(users, "email");\nconst ids: number[] = pluck(users, "id");\nconsole.log(ids);')],
                ["[ 'Ada', 'Bo' ]\n[ 1, 2 ]", "[ 1 ]"],
                "function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {\n  return items.map((item) => item[key]);\n}",
                require=[r"K\s+extends\s+keyof\s+T"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Generic classes",
            "Classes and interfaces can be generic too:\n\nclass Stack<T> {\n  private items: T[] = [];\n  push(item: T): void { this.items.push(item); }\n  pop(): T | undefined { return this.items.pop(); }\n  get size(): number { return this.items.length; }\n}\n\nconst s = new Stack<number>();\ns.push(1);\ns.push(\"two\");   // error\n\nBuilt-ins work the same way: Map<string, number>, Set<string>, Promise<User>.",
            mcq("What does new Stack<string>().pop() return?", ["string", "string | undefined", "T", "any"], 1),
            mcq("Which is a generic built-in type?", ["Math", "Map<K, V>", "JSON", "console"], 1),
            fill("A queue that holds strings.", "const q = new Queue<___>();", "string"),
            mcq("Is this OK?", ["Yes", "No - the map's values must be numbers"], 1, code='const m = new Map<string, number>();\nm.set("a", "1");'),
            run("Write class Queue<T> with enqueue(item: T), dequeue(): T | undefined (first in, first out), peek(): T | undefined and a size getter.", "typescript",
                [t("fifo", append='const q = new Queue<string>();\nq.enqueue("a");\nq.enqueue("b");\nq.enqueue("c");\nconsole.log(q.dequeue(), q.peek(), q.size);'),
                 t("empty", append="const q = new Queue<number>();\nconsole.log(q.dequeue(), q.size);"),
                 t("typed", append="const q = new Queue<number>();\n" + REJECTS + 'q.enqueue("one");\nconsole.log(q.size);')],
                ["a b 2", "undefined 0", "1"],
                "class Queue<T> {\n  private items: T[] = [];\n\n  enqueue(item: T): void {\n    this.items.push(item);\n  }\n\n  dequeue(): T | undefined {\n    return this.items.shift();\n  }\n\n  peek(): T | undefined {\n    return this.items[0];\n  }\n\n  get size(): number {\n    return this.items.length;\n  }\n}",
                require=[r"class\s+Queue\s*<\s*T\s*>"], forbid=[r"\bany\b"]),
        ),
    ),
)

ADVANCED = section(
    "Advanced",
    # ------------------------------------------------------------------ 7
    unit(
        "Unit 7 · Type-level tools",
        lesson(
            "Utility types",
            "TypeScript ships helpers that build new types from existing ones:\n\ninterface User { id: number; name: string; email: string }\n\nPartial<User>          // every property optional (great for updates)\nRequired<T>            // every property required\nReadonly<User>         // every property readonly\nPick<User, \"id\" | \"name\">\nOmit<User, \"email\">\nRecord<string, number> // an object with string keys and number values\nReturnType<typeof fn>  // what a function returns",
            mcq("Which type makes every property optional?", ["Required<T>", "Partial<T>", "Pick<T>", "Record<T>"], 1),
            mcq("Omit<User, \"email\"> has which properties?", ["email only", "id and name", "id, name and email", "none"], 1),
            fill("An object mapping names to scores.", "const scores: ___<string, number> = { ada: 91 };", "Record"),
            mcq("Best type for an 'update' function's changes argument?", ["User", "Partial<User>", "Readonly<User>", "Omit<User, keyof User>"], 1),
            run("With interface User { id: number; name: string; email: string }, write update(user: User, changes: Partial<Omit<User, \"id\">>): User returning a NEW user, and countBy(words: string[]): Record<string, number>.", "typescript",
                [t("update", append='const u: User = { id: 1, name: "Ada", email: "a@x.io" };\nconsole.log(update(u, { name: "Ada L." }));\nconsole.log(u.name);'),
                 t("count", append='console.log(countBy(["a", "b", "a"]));'),
                 t("no id", append='const u: User = { id: 1, name: "Ada", email: "a@x.io" };\n' + REJECTS + "update(u, { id: 2 });\nconsole.log(\"checked\");")],
                ["{ id: 1, name: 'Ada L.', email: 'a@x.io' }\nAda", "{ a: 2, b: 1 }", "checked"],
                "interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nfunction update(user: User, changes: Partial<Omit<User, \"id\">>): User {\n  return { ...user, ...changes };\n}\n\nfunction countBy(words: string[]): Record<string, number> {\n  const out: Record<string, number> = {};\n  for (const w of words) out[w] = (out[w] ?? 0) + 1;\n  return out;\n}",
                require=[r"Partial\s*<\s*Omit", r"Record\s*<\s*string\s*,\s*number\s*>"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "typeof, keyof & indexed access",
            "Derive types from values and other types instead of repeating yourself:\n\nconst config = { host: \"localhost\", port: 8080 };\ntype Config = typeof config;          // { host: string; port: number }\ntype Key = keyof Config;              // \"host\" | \"port\"\ntype Port = Config[\"port\"];           // number\n\nconst COLORS = { red: \"#f00\", blue: \"#00f\" } as const;\ntype ColorName = keyof typeof COLORS;  // \"red\" | \"blue\"",
            mcq("type T = typeof { a: 1, b: \"x\" } as a variable's type is…", ["{ a: number; b: string }", "\"a\" | \"b\"", "object", "any"], 0),
            mcq("Config[\"host\"] for Config = { host: string; port: number } is…", ["\"host\"", "string", "number", "Config"], 1),
            fill("The names of the keys of an object's type.", "type Keys = ___ typeof settings;", "keyof"),
            mcq("Why derive types with typeof instead of writing them again?", ["It's faster at runtime", "They stay in sync with the value automatically", "It's required", "It hides the type"], 1),
            run("Given const PRICES = { coffee: 3, tea: 2.5, cake: 4 } as const, define type Item = keyof typeof PRICES and write bill(order: Item[]): number (the total).", "typescript",
                [t("bill", append='console.log(bill(["coffee", "cake", "tea"]));\nconsole.log(bill([]));'),
                 t("menu only", append=REJECTS + 'bill(["pizza"]);\nconsole.log("checked");')],
                ["9.5\n0", "checked"],
                "const PRICES = { coffee: 3, tea: 2.5, cake: 4 } as const;\n\ntype Item = keyof typeof PRICES;\n\nfunction bill(order: Item[]): number {\n  return order.reduce((sum, item) => sum + PRICES[item], 0);\n}",
                starter="const PRICES = { coffee: 3, tea: 2.5, cake: 4 } as const;\n",
                require=[r"keyof\s+typeof\s+PRICES"], forbid=[r"\bany\b", r"\"coffee\"\s*\|"]),
        ),
        lesson(
            "Mapped & conditional types",
            "Mapped types transform every property of a type:\n\ntype Flags<T> = { [K in keyof T]: boolean };\ntype Optional<T> = { [K in keyof T]?: T[K] };   // this is how Partial works\n\nConditional types choose a type with a condition:\n\ntype IsString<T> = T extends string ? \"yes\" : \"no\";\ntype ElementOf<T> = T extends (infer E)[] ? E : never;\n\nElementOf<number[]> is number. These power libraries' clever types - you'll mostly use them, sometimes write them.",
            mcq("{ [K in keyof T]: boolean } for T = { a: string; b: number } is…", ["{ a: string; b: number }", "{ a: boolean; b: boolean }", "boolean[]", "\"a\" | \"b\""], 1),
            mcq("IsString<42> with the type above is…", ["\"yes\"", "\"no\"", "boolean", "never"], 1),
            fill("Loop over the keys of T.", "type Getters<T> = { [K ___ keyof T]: () => T[K] };", "in"),
            mcq("What does infer do in a conditional type?", ["Runs code", "Captures part of a type into a new type variable", "Imports a type", "Nothing"], 1),
            run("Write type Validators<T> = { [K in keyof T]: (value: T[K]) => boolean } and validate<T>(obj: T, rules: Validators<T>): (keyof T)[] returning the keys that FAIL their rule.", "typescript",
                [t("form", append='const form = { name: "", age: 17, email: "a@x.io" };\nconsole.log(validate(form, { name: (v) => v.length > 0, age: (v) => v >= 18, email: (v) => v.includes("@") }));'),
                 t("typed rules", append='const form = { age: 20 };\n' + REJECTS + 'validate(form, { age: (v) => v.length > 0 });\nconsole.log(validate(form, { age: (v) => v >= 18 }));')],
                ["[ 'name', 'age' ]", "[]"],
                "type Validators<T> = { [K in keyof T]: (value: T[K]) => boolean };\n\nfunction validate<T>(obj: T, rules: Validators<T>): (keyof T)[] {\n  const failed: (keyof T)[] = [];\n  for (const key in rules) {\n    if (!rules[key](obj[key])) failed.push(key);\n  }\n  return failed;\n}",
                require=[r"\[\s*K\s+in\s+keyof\s+T\s*\]"], forbid=[r"\bany\b"]),
        ),
    ),
    # ------------------------------------------------------------------ 8
    unit(
        "Unit 8 · Real-world TypeScript",
        lesson(
            "unknown & type guards",
            "Data from outside (JSON, user input, APIs) has no guaranteed type. Treat it as unknown - you must check it before use:\n\nfunction isUser(x: unknown): x is User {       // a type guard\n  return typeof x === \"object\" && x !== null &&\n         typeof (x as User).name === \"string\";\n}\n\nconst data: unknown = JSON.parse(text);\nif (isUser(data)) console.log(data.name);       // data is User here\n\nunknown is the safe twin of any.",
            mcq("What can you do with a value of type unknown without checking?", ["Anything", "Almost nothing - narrow it first", "Call it", "Read any property"], 1),
            mcq("What does the return type x is User mean?", ["It returns a User", "When it returns true, x is a User", "x becomes a class", "Nothing"], 1),
            fill("Declare a type guard.", "function isNumber(x: unknown): x ___ number {\n  return typeof x === \"number\";\n}", "is"),
            mcq("JSON.parse returns any. What's the safer thing to do?", ["Use it directly", "Assign it to unknown and validate it", "Cast it to the type you hope for", "Ignore types"], 1),
            run("Write interface Point { x: number; y: number }, a type guard isPoint(v: unknown): v is Point, and parsePoints(json: string): Point[] that keeps only the valid points from a JSON array (and returns [] if the JSON isn't an array).", "typescript",
                [t("mixed", append='console.log(parsePoints(\'[{"x":1,"y":2},{"x":"1","y":2},null,{"x":5,"y":-1}]\'));'),
                 t("not array", append='console.log(parsePoints(\'{"x":1,"y":2}\'));')],
                ["[ { x: 1, y: 2 }, { x: 5, y: -1 } ]", "[]"],
                "interface Point {\n  x: number;\n  y: number;\n}\n\nfunction isPoint(v: unknown): v is Point {\n  return typeof v === \"object\" && v !== null && typeof (v as Point).x === \"number\" && typeof (v as Point).y === \"number\";\n}\n\nfunction parsePoints(json: string): Point[] {\n  const data: unknown = JSON.parse(json);\n  if (!Array.isArray(data)) return [];\n  return data.filter(isPoint);\n}",
                require=[r"v\s+is\s+Point", r"unknown"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "Async code with types",
            "async functions return a Promise of their result type:\n\nasync function getUser(id: number): Promise<User> {\n  const res = await api(`/users/${id}`);\n  return res.user;\n}\n\nconst users = await Promise.all([getUser(1), getUser(2)]);   // User[]\n\nIn these lessons wrap async work in an async function main() { ... } and call main() - the runner waits for it.",
            mcq("Return type of async function f(): Promise<number> when awaited?", ["Promise<number>", "number", "void", "any"], 1),
            mcq("What does Promise.all([p1, p2]) give, for p1: Promise<string> and p2: Promise<number>?", ["Promise<[string, number]>", "Promise<string | number>", "[string, number]", "never"], 0),
            fill("Annotate the async function's return type.", "async function load(): ___<string[]> {", "Promise"),
            mcq("Inside an async function, what does await do?", ["Blocks the whole program", "Pauses this function until the promise settles", "Creates a thread", "Nothing"], 1),
            run("Given the fake fetchScore below, write async function totalScore(ids: number[]): Promise<number> that fetches all scores IN PARALLEL (Promise.all) and adds them up.", "typescript",
                [t("total", append="async function main() {\n  console.log(await totalScore([1, 2, 3]));\n  console.log(await totalScore([]));\n}\nmain();"),
                 t("typed", append="async function main() {\n  const n: number = await totalScore([4]);\n  " + REJECTS + "  const s: string = await totalScore([4]);\n  console.log(n);\n}\nmain();")],
                ["60\n0", "40"],
                "function fetchScore(id: number): Promise<number> {\n  return new Promise((resolve) => setTimeout(() => resolve(id * 10), 50));\n}\n\nasync function totalScore(ids: number[]): Promise<number> {\n  const scores = await Promise.all(ids.map(fetchScore));\n  return scores.reduce((a, b) => a + b, 0);\n}",
                starter="function fetchScore(id: number): Promise<number> {\n  return new Promise((resolve) => setTimeout(() => resolve(id * 10), 50));\n}\n",
                require=[r"Promise\.all", r"totalScore\s*\([^)]*\)\s*:\s*Promise\s*<\s*number\s*>"], forbid=[r"\bany\b"]),
        ),
        lesson(
            "never & exhaustive checks",
            "never is the type with no values. Use it to make the compiler prove you handled every case:\n\ntype Event = { type: \"click\" } | { type: \"key\"; key: string };\n\nfunction handle(e: Event): string {\n  switch (e.type) {\n    case \"click\": return \"clicked\";\n    case \"key\":   return `pressed ${e.key}`;\n    default: {\n      const unreachable: never = e;   // error if a case is missing\n      return unreachable;\n    }\n  }\n}\n\nAdd { type: \"scroll\" } to Event later, and TypeScript points at every switch you forgot to update.",
            mcq("Which value has type never?", ["null", "undefined", "No value at all", "0"], 2),
            mcq("Why assign e to a never variable in default?", ["To clear it", "So a forgotten case becomes a compile error", "To log it", "It's required by switch"], 1),
            fill("The type with no possible values.", "const impossible: ___ = value;", "never"),
            mcq("Return type of a function that always throws?", ["void", "never", "undefined", "Error"], 1),
            run("Model type Op = { kind: \"add\"; by: number } | { kind: \"mul\"; by: number } | { kind: \"reset\" } and write apply(value: number, op: Op): number with an exhaustive switch (a never check in default).", "typescript",
                [t("ops", append='let v = 1;\nfor (const op of [{ kind: "add", by: 4 }, { kind: "mul", by: 3 }, { kind: "reset" }, { kind: "add", by: 2 }] as Op[]) {\n  v = apply(v, op);\n  console.log(v);\n}')],
                ["5\n15\n0\n2"],
                'type Op = { kind: "add"; by: number } | { kind: "mul"; by: number } | { kind: "reset" };\n\nfunction apply(value: number, op: Op): number {\n  switch (op.kind) {\n    case "add":\n      return value + op.by;\n    case "mul":\n      return value * op.by;\n    case "reset":\n      return 0;\n    default: {\n      const unreachable: never = op;\n      return unreachable;\n    }\n  }\n}',
                require=[r":\s*never\s*=", r"switch\s*\("], forbid=[r"\bany\b"]),
        ),
    ),
)

COURSE = course(
    "typescript", "TypeScript", "🔷", "JavaScript with types - catch bugs before your code runs.",
    BEGINNER, INTERMEDIATE, ADVANCED,
)
